### ISSUE TITLE
Select for page linking not working

### ISSUE THREAD

**Issue by jesperlundnielsen** [polylang/polylang#1]
Issue:
When I try to link pages together (translations), I don't get the autocomplete box appearing, and console displays some errors.
Result is that I can't link pages together in the Language box.

Versions:
WP: 4.5.1
Polylang 1.9

![image](https://cloud.githubusercontent.com/assets/5707542/14908580/21d03622-0dd9-11e6-8ea4-f8b5eabb6201.png)

**Comment by Chouby** [comment]
This is mot probably caused by a Javascript error in your theme or another plugin.
Please de-activate all your other plugins and switch your theme to Twenty Sixteen and test again.

**Comment by jesperlundnielsen** [comment]
True. Deactivating and reactivating actually solved it. Thanks.
