### ISSUE TITLE
Home page issue

### ISSUE THREAD

**Issue by Benmi093** [polylang/polylang#1013]
Hi !

I have a problem with my home page.

When I switch my home page on the English version is reload on my French version.

I don’t know why ?

Thank you !

The page I need help with: https://massiveimmersive.com/

**Comment by Chouby** [comment]
Usage questions should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
