### ISSUE TITLE
QUESTION : How to assign menu location with WP-CLI?

### ISSUE THREAD

**Issue by gbouteiller** [polylang/polylang#102]
Hello,
First of all, thank you for your great work.
I'm using **WP-CLI** to initialize my projects but I'm stuck with menu location assignments.
I've managed to create one menu per language and so I'd like to assign each menu to the correct location with:
```sh
wp menu location assign my_menu my_location 
```
The problem is that I can't simply assign the translated menus to the same location like :
```sh
wp menu location main_fr main
wp menu location main_en main
```
as the last one will take precedence. And, correct me if I'm wrong, but it appears that there are no locations created for each language by Polylang.
So,  does anyone know an answer to that issue?
Thanks in advance.

**Comment by grappler** [comment]
I think you need a Polylang WP-CLI extension for this. You can try one of these.

https://github.com/dereckson/wp-cli-polylang
https://github.com/diggy/polylang-cli
https://github.com/exozet/wp-cli-polylang

**Comment by gbouteiller** [comment]
Hello @grappler,
I'm currently using https://github.com/diggy/polylang-cli but it doesn't offer this possibility yet. Am I correct @diggy?

**Comment by diggy** [comment]
@gbouteiller Spot on :) Commands to manage nav menus are on my mental roadmap, you're welcome to open issues for features that are currently lacking, or submit a PR if you feel like contributing.

**Comment by gbouteiller** [comment]
Just to mention that @diggy already nailed it. Great job!
