### ISSUE TITLE
Function Composer\Autoload\ClassLoader->findFile takes 1.593177

### ISSUE THREAD

**Issue by wpsumo** [polylang/polylang#1028]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

Timing might variate from site to site depending on complexity and plugins but this function still seems to be on the slower side which hopefully can be improved:

**Function:**
`Composer\Autoload\ClassLoader->findFile`

**Caller:**
`/vendor/composer/ClassLoader.php@321`

**Script:**

```
 /**
     * Finds the path to the file where the class is defined.
     *
     * @param string $class The name of the class
     *
     * @return string|false The path if found, false otherwise
     */
    public function findFile($class)
    {
        // class map lookup
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }
        if ($this->classMapAuthoritative || isset($this->missingClasses[$class])) {
            return false;
        }
        if (null !== $this->apcuPrefix) {
            $file = apcu_fetch($this->apcuPrefix.$class, $hit);
            if ($hit) {
                return $file;
            }
        }

        $file = $this->findFileWithExtension($class, '.php');

        // Search for Hack files if we are running on HHVM
        if (false === $file && defined('HHVM_VERSION')) {
            $file = $this->findFileWithExtension($class, '.hh');
        }

        if (null !== $this->apcuPrefix) {
            apcu_add($this->apcuPrefix.$class, $file);
        }

        if (false === $file) {
            // Remember that this class does not exist.
            $this->missingClasses[$class] = true;
        }

        return $file;
    }
    
```

**Comment by Chouby** [comment]
I don't know what we can do for this.  This method is part of the composer autoloader, widely used in the PHP ecosystem. Moreover it should return after the first `if()` as we use the class map. Searching a string in an array of 122 items should'nt take long.

**Comment by wpsumo** [comment]
In a local installation with local by flywheel it took 1.593177 seconds

**Comment by Chouby** [comment]
I just measured on a local install with an old laptop. All calls take approx 50 ms.
