### ISSUE TITLE
Issues with wordpress playlist shortcodes

### ISSUE THREAD

**Issue by nirbhasa** [polylang/polylang#104]
Inserting the shortcode [playlist ids="1,2,3,4,5"] should load a playlist with those attachment IDs. However, it stops working if the attachments were originally uploaded to a different language post. 

This seems to be because of the 'lang' requirement in get_posts (which is called by wp_get_shortcode in includes/media.php, and it doesn't seem like I can hook into it without hacking wordpress.

Steps to recreate:
1. Create a post in default language, upload audio files and create a playlist - this works
2. Translate this post, and add the same playlist shortcode - the shortcode 'expands' properly in the edit window, but when you save and view the post , the playlist cannot be seen

adding 'lang' => '' in the $args array in line 1969 of media.php fixes the problem, but obviously it would be nice not to have to hack wordpress.

Is there a programattic work around? On the translated post, I get the attachment ids and call do_shortcode programatically - is there something I can do just before i call do_shortcode?

**Comment by nirbhasa** [comment]
I just saw the setting to disable translation of media - this seems to have done the job! Thanks

**Comment by sinankoatata** [comment]
dsf
