### ISSUE TITLE
Polylang + Yoast SEO nofollow, noindex extends to second pages

### ISSUE THREAD

**Issue by mihrich** [polylang/polylang#1046]
Hi guys, so as not to repeat what has already been written, please see the task at the Yoast plugin link 
https://github.com/Yoast/wordpress-seo/issues/18356

The problem is that when indexing of the translation page is disabled, the main page is also disabled for indexing.

Wordpress 5.9.3
Polylang 3.2.2
Yoast SEO 18.8

**Comment by manooweb** [comment]
👋 @mihrich 

I suggest you to override [WordPress SEO configuration](https://github.com/Yoast/wordpress-seo/blob/18.8/wpml-config.xml#L7-L8) by creating a `wp-content/polylang/wpml-config.xml` and writing in this file

 ```xml
<wpml-config>
	<custom-fields>
		<custom-field action="copy_once">_yoast_wpseo_meta-robots-noindex</custom-field>
		<custom-field action="copy_once">_yoast_wpseo_meta-robots-nofollow</custom-field>
	</custom-fields>
</wpml-config>
```

If the file already exist simply merge these two lines

 ```xml
<custom-field action="copy_once">_yoast_wpseo_meta-robots-noindex</custom-field>
<custom-field action="copy_once">_yoast_wpseo_meta-robots-nofollow</custom-field>
```

inside the existing `<custom-fields></custom-fields>` tags.

Best regards 😉

**Comment by mihrich** [comment]
Many thanks to manooweb for helping me figure it out! I'm a little dumb )))
