### ISSUE TITLE
~5k posts lost their language assignment

### ISSUE THREAD

**Issue by gpcola** [polylang/polylang#1053]
I've been using Polylang and Lingotek with great success for over a year and had managed to build up a list of nearly 5k posts over the 16 languages I have configured.

I was using Rankmath for SEO purposes but due to incompatibility with Polylang causing incorrect canonical URLs to be generated, yesterday I switched to SEOPress yesterday. 

When using the data migration feature in SEOPress I ran into Javascript errors, presumably due to a conflict with another plugin and so I _deactivated all plugins_. 

_On reactivation_, I now find that when editing a post, just over half of the languages are now decoupled from the English language version (default language)

<a href="https://i.imgur.com/bLYR47E.jpeg" rel="noopener" target="_blank">https://i.imgur.com/bLYR47E.jpeg</a>

and, weirdly, it would appear that the rest of the languages are linked to each other AND to the English language version!

<a href="https://i.imgur.com/Ix19HMB.jpeg" rel="noopener" target="_blank">https://i.imgur.com/Ix19HMB.jpeg</a>

the association must therefore still exist in some form. Something about is broken, however.

I'm guessing that I might be able to recover this situation with an SQL query of some kind.

Anyone got any ideas on how a query to do that might look?`

**Comment by Chouby** [comment]
Probably you destroyed the association between the posts and language and not the translation groups. The only way I can imagine to destroy such amount of data is by using a database cleaning tool.
Sorry to come late, but unfortunately I cannot help. There is no easy way to restore this with something like an SQL query. The best way in such caseif always to restore a database backup.
