### ISSUE TITLE
REST API Yoast data does not match the locale of the post | Polylang Pro 3.2.4  wp 6.0

### ISSUE THREAD

**Issue by xitex** [polylang/polylang#1059]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set default language as English
2. Create posts in another language (de in my case)
3. go to /wp-json/wp/v2/posts?lang=de

## Expected behavior and actual behavior

When I follow those steps, I see...
yoast data show default locale "en"

I was expecting...
yoast data must show actual locale "de"

**Comment by jdoubleu** [comment]
Might this be related to https://github.com/polylang/polylang/issues/576#issuecomment-745208604?

**Comment by xitex** [comment]
`Might this be related to https://github.com/polylang/polylang/issues/576#issuecomment-745208604?`

I believe not, since I set the default localization for all posts to de.
Even if everything is normally translated from the admin panel, yoast in restapi still displays localization data set by default in wordpress

**Comment by Chrystll** [comment]
As you are using our premium version, could you please contact the [support team](https://polylang.pro/support/) to investigate further your issue? In the goal to reproduce your issue we would need that you describe steps by steps your issue.

**Comment by xitex** [comment]
`As you are using our premium version, could you please contact the [support team](https://polylang.pro/support/) to investigate further your issue? In the goal to reproduce your issue we would need that you describe steps by steps your issue.`
i describe step by step this 3 step
