### ISSUE TITLE
PLL()->curlang is always false in WP Cron

### ISSUE THREAD

**Issue by jpSimkins** [polylang/polylang#1070]
I am currently migrating from WPML to Polylang. 

I have a data import system that runs on CRON since this site has weekly imports of large datasets. It's a true cron running with WP cron disabled. This should not matter but still worth mentioning.

When in cron, I am not able to use `pll_current_language` or `pll_default_language` as these only return `false`. This is not for the API, this is just the state of Polylang during a normal cron event.

While debugging, I noticed that `PLL()->curlang` is always false. This means, I am not able to get the current language or the default language for the site. I have a fail-safe that does:

```php
$currentLanguage = get_bloginfo('language');
self::$_failSafeLang= substr($currentLanguage, 0, 2); // Only need the 2-digit code
```

But this always returns `en` even though the site is default to Spanish in Polylang. Even using `get_locale` returns English instead of Spanish. I am assuming this is just the default WP behavior and it seems Polylang is not doing anything at this time. I have confirmed Polylang loads properly before the script for the import is run.

This is not expected so I wonder why this is the case. I would expect this to load the proper language the site is configured for by Polylang. At minimum, I would expect the `pll_default_language` to return the site's configured default language.

At it's current state, Polyland seems to be useless in a WordPress Cron as it isn't aware of the locale. Is this expected? If so, why?

**Comment by jpSimkins** [comment]
Seems that the language is not really necessary unlike it was for WPML. I can still control the language when ingesting so I will just close this.

**Comment by jpSimkins** [comment]
I am actually having an issue due to language not being able to be used in WP Cron.

Emails are in Spanish for English users. 

I tried using `\PLL()->curlang = \PLL()->model->get_language($lang);` to set the language but it's always false for the languages.

Is there a way to load Polylang so it works for my cron script? Not sure why it wouldn't be loaded. I can see that the plugin is being instantiated but I have no language control at all.

Emails and notices created during cron are always in the site default language. It is not possible to change the language during a WordPress cron event.

**Comment by jpSimkins** [comment]
Ok, so the only way to get cron to obey the language is to use `switch_to_locale`. I use `en` or `es` so this is just a bit of a pain for fixable. Hope this helps others the run into this issue.

**Comment by Buzut** [comment]
Late to the game, but from my experience everything in the WP_CRON and switch_to_locale is erratic, especially if you'll be dealing with multiple languages in the same cron. Like you send emails and switch languages on the fly.
;
Ended up migrating all the language related translations to DB instead of translation files for this use case. This can therefore be edited in the strings feature of Polylang.
