### ISSUE TITLE
Tags links alternates hreflang on front page

### ISSUE THREAD

**Issue by MarcosFurquim** [polylang/polylang#1072]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a  front page with a single page config
2. Configure Poly Langy for 2 or more languages
3. Set multiple languague for front page.
4. Remove  any lang from him
5. Links` alternates hreflang` are mounted for all active langs on polylang and even front page is not bound to all languages

## Expected behavior and actual behavior

Only prints links alternate hreflang for actived to front page

i made an solution with this Fork:
https://github.com/polylang/polylang/pull/1071

See below 👇 

<br class="Apple-interchange-newline">

## Problem
When you have a Front Page configured with an static page, all links  alternate:
like:
```<link rel="alternate" href="http://localhost:8080/pt/" hreflang="pt-PT" />```
 are printed on head HTML,  even it is not bound to all languages
 
<p align="center"> <img  width="auto" height="360px" src="https://user-images.githubusercontent.com/48767108/178686542-ee0d07a6-c13d-4ebb-8ea0-e5a373966528.png">
<br/><i>Columbia and Mexico Lang isnt bound to front page 1/2</i>
</p>

<br><br>

<p align="center"> <img  src="https://user-images.githubusercontent.com/48767108/178686553-1685aa15-1a0b-4e17-8d5e-c86fe34503e2.png">
<br/><i>Columbia and Mexico Lang isnt bound to front page 2/2</i>
</p>

<br><br>

![Captura de Tela 2022-07-13 às 05 18 40](https://user-images.githubusercontent.com/48767108/178686558-d1fad712-c7fe-462a-85c4-e0a4b8cc14e7.png)

<p align="center">
<i>HTML <code>head</code> printed with all languagues actived on Polylang, ignoring the configs of front-page atribuation.</i></p>

<br><br>
# Solution

Checkk, when is a page is front page, if the language has `page_on_front`
```php
// Front page when it is the list of posts
elseif ( is_front_page() && $language->page_on_front) {
    $url = $this->get_home_url( $language );
}
```

**Comment by Chouby** [comment]
A site is expected to have a homepage.
When you are using a static front page, it must be translated in all languages. We used to require these translations in the past. Based on user feedbacks, we now only display notices to inform users that there are missing translations. 
If the page is not translated in one language, then WordPress will display the list of posts. This is however a flawed situation as the WordPress option tells your site is using a static front page and in fact, the page is not present.
To conclude, we expect that a static front page must be translated in all languages and we cannot support a flawed situation when it's not the case.
That said you can do what you want with `hreflang` with the filter `pll_rel_hreflang_attributes`.
