### ISSUE TITLE
Contact email ? Can't renew my licence - VAT problem

### ISSUE THREAD

**Issue by SupportDK** [polylang/polylang#1075]
Hello,

Do you have a contact email where I can send my request ?
I can't renew my licence due to VAT problem : 

See here : 
https://ibb.co/nwDhw3t
https://ibb.co/XyxN3N6

Even when I do not ask for VAT, I have this problem.

I have to renew before 22th of July.

Thanks.

Stéphane Menet
DIGITAL KORNER

**Comment by sebastienserre** [comment]
Hello,

Thank you for contacting us.

As a Polylang Pro customer, could you please contact our helpdesk by filling the form located at https://polylang.pro/support/

Have a nice end of day;

Regards

**Comment by SupportDK** [comment]
Merci !
