### ISSUE TITLE
Still lot of Pass by Reference

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#108]
E.g. `public function __construct( &$links_model )`

Please consider replacing them.

**Comment by Chouby** [comment]
Could you clarify what's wrong in this? My intention was to access the same object from anywhere in the plugin and simplify writing. For example, if I modify `$curlang` anywhere in the plugin, all plugin classes needing to use `$curlang` are informed since they all use a reference to the same object.

**Comment by szepeviktor** [comment]
To be honest I've never seen classes communicating with each other this way.

```php
	public function __construct( &$polylang ) {
		$this->curlang = &$polylang->curlang;
```

I think it is not an implementation but a design issue.

Classes usually inherit from each other.

**Comment by szepeviktor** [comment]
You may postpone this till v3.0.0

**Comment by szepeviktor** [comment]
WordPress plugins usually must use a global. Which is not nice.

https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo-main.php#L260

**Comment by Chouby** [comment]
I learned PHP by myself so don't be surprised that I use exotic ways. I wanted to avoid to use globals and singletons.

**Comment by wujekbogdan** [comment]
> My intention was to access the same object from anywhere in the plugin and simplify writing. For example, if I modify $curlang anywhere in the plugin, all plugin classes needing to use $curlang are informed since they all use a reference to the same object

This looks like a good use case for the [Observer pattern](https://www.wikiwand.com/en/Observer_pattern).

For reference, have a look at the [EventDispatcher Symfony component](https://symfony.com/doc/current/components/event_dispatcher.html)

**Comment by szepeviktor** [comment]
@Chouby Do you plan to clean things up?

**Comment by Chouby** [comment]
It's not a priority. What issue does it cause?

**Comment by Chouby** [comment]
@wujekbogdan
What would be the advantage to use an observer pattern over the `do_action` / `add_action` already implemented in WP?

**Comment by szepeviktor** [comment]
@Chouby Could you remove all of them?
