### ISSUE TITLE
Change editor direction to rtl

### ISSUE THREAD

**Issue by nemo369** [polylang/polylang#1082]
## Prerequisites

- [ x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ x] This bug happens with only Polylang plugin active
- [ x] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a post in RTL language (Hebrew as an example) in an ltr site (English)
2. Open Gutenberg editor
3. The editor and admin direction is set to site default language (in ltr)

## Expected behavior and actual behavior

When I follow those steps, I see The editor and admin direction is set to site default language (in ltr)

I was expecting Gutenberg to be RTL

We can fix it by having an action in init that uses this function:

```
function set_direction($direction)
{
    global $wp_locale, $wp_styles;

    $_user_id = get_current_user_id();

    $direction = get_user_meta($_user_id, 'rtladminbar', true);
    if (false === $direction) {
        $direction = isset($wp_locale->text_direction) ? $wp_locale->text_direction : 'ltr';
    }

    $wp_locale->text_direction = $direction;
    if (!is_a($wp_styles, 'WP_Styles')) {
        $wp_styles = new WP_Styles();
    }
    $wp_styles->text_direction = $direction;
}

```

If someone can guide me to where the best place to add this action I can open a pull request for this

**Comment by Chouby** [comment]
It looks like your code is borrowed to this plugin: https://wordpress.org/plugins/rtl-tester/. So I suggest you to install it to obtain the expected result with this code.

Note that, as far as I know, it's currently not possible to have a different text direction in the block editor and the WordPress interface, as we are able to do in the classic editor.
