### ISSUE TITLE
[FIX] `wpml-config.xml` doesn't work for `mu-plugins`

### ISSUE THREAD

**Issue by jpSimkins** [polylang/polylang#1088]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Use an `mu-plugin` and have a `wpml-config.xml` inside it
2. `wpml-config.xml` does nothing

## Expected behavior and actual behavior

I expected an `mu-plugin` `wpml-config.xml` to be used but it's not.

**Comment by jpSimkins** [comment]
This is the fix to add `mu-plugin` support for `wpml-config.xml`.

File: `wpml-config.php` Line 130, add:
```php
        // Mu-Plugins
        // Search for top level wp-config.xml, not ideal or best practice but these exist.
        if (file_exists($file = WPMU_PLUGIN_DIR . '/wpml-config.xml')) {
            $files[basename(WPMU_PLUGIN_DIR)] = WPMU_PLUGIN_DIR . '/wpml-config.xml';
        }
        // Search for proxy loaded mu-plugins
        foreach (new DirectoryIterator(WPMU_PLUGIN_DIR) as $file_info) {
            if ($file_info->isDot()) continue;
            // Check if a directory (proxy loader method)
            if ($file_info->isDir()) {
                if (file_exists($file = $file_info->getPathname() . '/wpml-config.xml')) {
                    $files[$file_info->getFilename()] = $file;
                }
            }
        }
```

This checks for 2 most common usages of `mu-plugins`:

1. Single PHP file in the mu-plugins directory that is the simple plugin
2. A proxy loader that loads the plugin from a sub-directory in mu-plugins (WordPress recommended way).

The code is pretty straight forward. It first checks the top-level to see if `wpml-config.xml` exists in the `mu-plugins` root. Then it will iterate only the first level to check if it exists in an sub-folder (proxy loader method). 

This covers the most common usage of `mu-plugins` and adds `wpml-config.xml` support.

I cannot figure out how to submit a PR since this seems to only be for the PRO version

**Comment by manooweb** [comment]
Hi @jpSimkins 

For your information, `wpml-config.xml` feature isn't limited to Polylang Pro.
In fact Polylang is the Polylang Pro core and is managed with composer.
This is why you found `wpml-config.php` file in the `polylang-pro/vendor/wpsyntex/polylang/modules/wpml/` folder

`wpml-config.xml` feature is therefore available in Polylang free version.

Thanks for your proposition. We're going to look at it.

**Comment by jpSimkins** [comment]
Ah, sorry about that. I tried to find the file in the free version but I probably should have just used search instead of trying to find it myself. I'm new to Polylang so I'll keep this in mind for future issues.
