### ISSUE TITLE
Polylang string Translation doesn’t work for footer widget

### ISSUE THREAD

**Issue by BenoitAdam94** [polylang/polylang#1095]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Go to polylang
2. Go to String Translation
3. And voilà, no Footer/Widget options !

## Expected behavior and actual behavior

Polylang “string Translation” doesn’t work for footer widget

I think this is a problem that happen since the Footer Widget use the new bloc system (Gutenberg).

Wordpress 6.01 and Polylang last version.

**Comment by Chouby** [comment]
Sorry I don't see what you mean by footer widget. Could you point me at some WordPress documentation or some screenshot forme to understand what string you expect ot appear in the strings translations.

**Comment by BenoitAdam94** [comment]
ok let's do an example :

On this wordpress : 

https://theunchained.net/

Suppose I want to translate "A propos" in another langage.

**Comment by Chouby** [comment]
OK. This looks like the standard WordPress Pages legacy widget. The steps to translate widget titles are explained in our Getting started doc: https://polylang.pro/doc/widgets/

For usage questions, please use the WordPress forum: https://wordpress.org/support/plugin/polylang/

**Comment by BenoitAdam94** [comment]
Nah, I took this one as exemple but I have a Wordpress 6.01 on local with new widget, and I absolutely doesn't have that option...

https://postimg.cc/crym2tPj

**Comment by BenoitAdam94** [comment]
Same for Paragraph block
