### ISSUE TITLE
Problem with choosing package in Hivepress using Polylang

### ISSUE THREAD

**Issue by Michal123456747** [polylang/polylang#1097]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang
2. Add languages to Polylang
3. Install Hivepress 
4. Install Hivepress Paid Listings
5. Add some packages(including free package) 

6. Try to submit listing selecting free package 
---------or--------
6. Fill in listings form
7. Close page on packages form
8. Enter again into .../submit-listing url 
9. Try to select free package
## Expected behavior and actual behavior

When I follow those steps, I see...
Form is refreshing and doesn't submit listing. 

I was expecting...
Form should submit new Listing

**Comment by Chouby** [comment]
I'll be honest with you. Given our high workload, we integrate Polylang only with extremely popular plugins that could benefit to most of our users. Although HivePress may be a great plugin (I don't know it), it's not popular enough to be high in our integration priorities list. 

That said, if HivePress authors are themselves interested in working on the Polylang integration on their side, we will be happy to help them by answering to any question they may have with the Polylang API.
