### ISSUE TITLE
(Custom) post types and (custom) taxonomies don't show in settings when not public

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#11]
When CPT's or CT's are added but not set to public they don't show in the settings tab for polylang.
BUT: they CAN be translated in the admin!

When a tax or post is not public they can still be used for various cases. Even for generating content in the frontend! This just means that the post or tax pages are not accessible directly.

So, I would say the private CPT's and CT's should be in the settings tab to enable/disable translations for them.

**Comment by JoryHogeveen** [comment]
In addition to the post above.
Why not add the builtin posttypes aswell and enable them by default?
I can imagine that you could want to translate posts but not translate the pages (or the other way around)

**Comment by Chouby** [comment]
Yes, non public post types and taxonomies can be translated, but I intentionally remove them from the options to avoid UI bloat and user mistakes.

You can however enable both translation or option using the filters [pll_get_post_types](https://polylang.pro/doc/filter-reference/#pll_get_post_types) and pll_get_taxonomies.

Default post types and taxonomies are also accessible with these filters. In my opinion, it is safe to remove post tags but you may have issues with other (Post is the default post type, the default category introduces tricky issues and the static front page needs to be translated in all languages).

**Comment by JoryHogeveen** [comment]
I understand.
Perhaps a better idea to disable translations of non-public posts and taxes by default and let users enable them manually to prevent confusion?

**Comment by Chouby** [comment]
It's already disabled by default even for public post types / taxonomies.

Just look at WooCommerce. I believe that a lot of users would spend a lot of time to figure out what to do with product_type, shop_webhook, shop_coupon, product_variation... Some of them don't even have a label. And that's only one plugin. Each activated plugin can add several post types / taxonomies. Polylang itself adds one post type and 4 taxonomies which I don't like to see in 3rd party plugins UI... I really believe that the less options, the better it is (and let developers do the right choice once for all).

**Comment by JoryHogeveen** [comment]
Hmm then there is a bug I quess:

- I've added some custom post types
- I didn't enable them for translation since I can't do this in the interface because they are not public
- and I can still add translations for these types.

**Comment by JoryHogeveen** [comment]
Hi Chouby,

No it's not one of those cases.. (I didn't even know about the filter).

Did some tests to be sure and the problem is a little different than I thought.

Actually the CPT's works as you've said but the CT's don't. Sorry for the confusion.

If a CT is non-public the translation functionality is only partially disabled. The flags are showing in the edit-tags.php page, but you can't create an actual translation. When I click on the + icon it seems I can add a translation, but when I do, the new CT doesn't get a language and isn't linked to the original CT.

I think this "bug" is simply resolved by removing the flags from a CT overview when the translations are not enabled.

I have another idea as to where this bug might be coming from.
When I look at the edit-tags.php page I only see the translation options on the original CT's, not on the newly created ones.
Now I remember that I clicked on the button that assignes all content to the default language when firstly configuring Polylang. Maybe this could be the "problem"??

**Comment by JoryHogeveen** [comment]
More on the custom taxonomies:

There is also a bug that when I add a translation with the + icon on the overview screen. This new translation doesn't get assigned to a language. (same behaviour as when the CT isn't enabled for translating)

**Comment by Chouby** [comment]
This works the same for custom post types and taxonomies. Anyway, I am not reproducing the issue.
Are you using a plugin to register your taxonomy? Or do you register it directly in PHP?
Also could you check if your taxonomy appears in the 'polylang' option?

**Comment by JoryHogeveen** [comment]
I'm using Pods for CPT's and CT's.
I'll test this with PHP a.s.a.p. to check if it also happens then.

**Comment by Chouby** [comment]
Do you still experience this issue?

**Comment by gortsilas** [comment]
@Chouby 
Hello, I face the same issue with translating non-public post types used by SportsPress.
Just a suggestion: Is it possible to put all these non public post types and taxonomies hidden under an "Advanced" button so that developers can customize it through the backend?
Thanks!

**Comment by grappler** [comment]
@gortsilas As a developer you can use the filter to add extra custom post types to the checkbox or directly mark them as translatable. https://polylang.pro/doc/filter-reference/#pll_get_post_types

**Comment by Chouby** [comment]
@gortsilas Options (even more "advanced options") tend to increase support requests because users like to click everywhere ;-). There are even 2 or 3 existing options that I may suppress in the future due to the confusion caused.
Thus I prefer to keep the situation as is. The solution proposed by @grappler offers full control to PHP developers. A less advanced but efficient solution is to use a w[pml-config.xml file](https://polylang.pro/doc/the-wpml-config-xml-file/).

**Comment by JoryHogeveen** [comment]
@Chouby Sorry for my late reply. With PHP it worked fine so no problem there. I understand you want to keep it like this. I will think about adding an option to Pods that lets the user hook an object into PLL even if it's not public.

**Comment by Chouby** [comment]
Yes. For posts types registered with Pods, it makes sense to add the option. I did the same for CPTUI integration in Polylang Pro.
