### ISSUE TITLE
Can't assign languages for sub sub page 

### ISSUE THREAD

**Issue by vlad00777** [polylang/polylang#110]
Hi. I am using "duplicate post" and after that i am assign this cloned page with previous page in another language. Its work perfectly, but if i duplicate or create some page in some sub category plugin don't finding my sub sub page in others languages. 
![1489655415578](https://cloud.githubusercontent.com/assets/5796753/23988969/d58388dc-0a30-11e7-8a0f-1ef1dc9bf155.png)
![1489655117708](https://cloud.githubusercontent.com/assets/5796753/23988970/d5849f92-0a30-11e7-89e2-8fe932301690.png)

**Comment by vlad00777** [comment]
I have some solution. 
You can't attach new page to another pages, but you can edit page in other language and attach it's new page. Please fix it in new versions. Polylang - 2.1.2

**Comment by Chrystll** [comment]
Hi
I didn't reproduce your issue with sub sub page. You are maybe facing to a conflict with another plugin (or your theme). Could you test with a default theme as Twenty Sixteen and only Polylang? The other plugins must be deactivated.
