### ISSUE TITLE
After update: Fatal error: Call to undefined function PLL()->languages_page()

### ISSUE THREAD

**Issue by einicher** [polylang/polylang#111]
Wordpress Version 4.7.3
Fatal error: Call to undefined function PLL()->languages_page() in on line Error handler in /var/www/development/xxx/wp-content/plugins/polylang/include/base.php on line 108

Happens when you enter
/wp-admin/admin.php?page=mlang_strings
/wp-admin/admin.php?page=mlang_settings
/wp-admin/admin.php?page=mlang_lingotek
but not on
/wp-admin/admin.php?page=mlang

**Comment by Chouby** [comment]
The function exists: https://github.com/polylang/polylang/blob/2.1.2/settings/settings.php#L246
Could you delete all the files and install the plugin again?

**Comment by einicher** [comment]
downloading the zip and replacing the files with ftp fixed it.
