### ISSUE TITLE
Missing post type archive

### ISSUE THREAD

**Issue by Mte90** [polylang/polylang#112]
In my website I have a post type guest-post but is not possible to show the archive of all the posts.
On my page https://mte90.net/guest-post/ there is not a list so I don't understand where is the problem.

**Comment by Chouby** [comment]
Could it be that the url is lacking the language code. Except for the default language if you choose to "hide the language code in the url for the default language", archives urls must include the language code.

**Comment by Mte90** [comment]
As I can see https://mte90.net/ita/guest-post https://mte90.net/eng/guest-post are not working

**Comment by Chouby** [comment]
Did you create any custom post? Also did you try on a fresh install with only a Twenty theme, Polylang and your custom post type?

**Comment by Mte90** [comment]
I am not sure to have created a new post for that post type after the polylang activation but the post type itself is integrated in the theme (maybe by myself, based on an old version of roots boilerplate).
The code that add the post type is available https://github.com/mte90/mte90-2014/blob/master/lib/custom.php#L150

**Comment by Chouby** [comment]
If you don't have a custom post or if your custom posts don't have language, it is expected that there is nothing found. When you type https://mte90.net/eng/guest-post the query will retrieve English posts in the custom post type 'guest-post' and nothing else. Not also that https://mte90.net/guest-post does not exist anymore (you retrieve all posts with no language or all posts in any language).

**Comment by Mte90** [comment]
The post type has like 90 post on it and I configured the language in all of them, infact in the backend I can see all of them

**Comment by Chouby** [comment]
Could you test your post type on a fresh install with only Polylang?

**Comment by Mte90** [comment]
No I cannot do it, there any other tests that I can do it?

**Comment by Chouby** [comment]
That's the most basic test to do. When you report an issue in a plugin, it's important to test the the issue in the minimal installation. In your case a Twenty theme + Polylang + your registered post type. Otherwise we cannot be sure where the issue is.

**Comment by AF20181** [comment]
Had the same Problem. Solved it by resaving custom posts.
