### ISSUE TITLE
SQL error on languages page

### ISSUE THREAD

**Issue by recalderon** [polylang/polylang#1121]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. PHP 7.3, Mysql 5.7.39, Polylang 3.2.7
2. Access languages page on dashboard or Setup

## Expected behavior and actual behavior

When in the languages page or in the setup i can't add any language. Then i go back to the languages page and there is this error on top of page, it dissapears when i deactivate the polylang plugin:

[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) LIMIT 1' at line 4]
SELECT pdh_term_taxonomy.term_id FROM pdh_term_taxonomy WHERE taxonomy IN ('category','post_tag') AND pdh_term_taxonomy.term_id NOT IN ( SELECT object_id FROM pdh_term_relationships WHERE term_taxonomy_id IN () ) LIMIT 1

From Query Monitor plugin i got this traceback:

PLL_Model->get_terms_with_no_lang()
wp-content/plugins/polylang/include/model.php:704
PLL_Model->get_objects_with_no_lang()
wp-content/plugins/polylang/include/model.php:631
PLL_Settings->notice_objects_with_no_lang()
wp-content/plugins/polylang/settings/settings.php:347
do_action('admin_notices')
wp-includes/plugin.php:476

**Comment by Chouby** [comment]
Thank you for the report.

I wonder about the context of this error. It seems to happen [because there are no languages yet](https://github.com/polylang/polylang/blob/3.2.7/include/model.php#L693). But on the other hand, there seems to be [a default language existing](https://github.com/polylang/polylang/blob/3.2.7/settings/settings.php#L347) on your install.
Could you tell me more how I could reproduce?

**Comment by recalderon** [comment]
Thank you for reaching out... So I don't know how to assist you in reproducing this bug but if you can guide me, I'll be happy to help! Just for record my main problem seems to be adding Spanish ES and English US, cause earlier today I had success adding Afrikaans and Deutsch (just for testing). 
The only thing I can think that could be conflicting (as is a pretty recent clean installation) is that the pages that i've imported came from an installation that had Pollylang installed and were wrote originally in PTBR and later added EN-US and SP-ES translations.

**Comment by Chouby** [comment]
Maybe the issue is in the import. I can imagine that this error will occur if Polylang options are imported but the languages are not. Anyway we will fix this error in the next release.
