### ISSUE TITLE
Attachment parent page is not synced

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#113]
Hi Chouby,

I noticed that when I upload a media file directly to media library (so it is not assigned to any page/post), create translations for this media file and then later assign parent page to one of translations, the assigned parent page is not synced to other translations, despite that I have "Page parent" checked in Synchronization settings.

Cheers,
Česlav

**Comment by Chouby** [comment]
That's true. The page parent synchronization handles only the synchronization of the hierarchy for hierarchical custom post types. It does not handle the synchronization of the parent post of attachements even if it is stored in the same post_parent column.

**Comment by chesio** [comment]
I see, thanks for answering. I'll check how this could be implemented, it would be a great time saver in one of my projects. If I find a working solution, I'll submit a PR.

**Comment by chesio** [comment]
Ok, I'm closing this, I found out that this is impossible to implement in the moment, because there are no hooks in [wp_media_attach_action](https://developer.wordpress.org/reference/functions/wp_media_attach_action/).

**Comment by grappler** [comment]
Actually [`clean_attachment_cache`](https://developer.wordpress.org/reference/hooks/clean_attachment_cache/) could be potentially used.
