### ISSUE TITLE
Special Question: how to deal with development instance

### ISSUE THREAD

**Issue by einicher** [polylang/polylang#114]
Hi,

I have a live and a development version of the same wordpress website using some tricks described here: https://codex.wordpress.org/Running_a_Development_Copy_of_WordPress. Both versions use the same database. That works fine with wordpress alone, but with polylang enabled there are unpredictable redirects between the two instances. Is there a way to overwrite this behavior, like it is possible with `define('WP_HOME', 'http://example.com')`?

regards

**Comment by Chouby** [comment]
The constant [PLL_CACHE_HOME_URL](https://polylang.pro/doc/php-constants/) should help.

**Comment by einicher** [comment]
Thanks!
Tried to put it in wp-config and in functions.php, no effect.
It is always redirecting to the instance where the last post was saved.

**Comment by Chouby** [comment]
Polylang stores the languages ( including the homepage urls ) in a transient `pll_languages_list` to improve the performance. This obviously creates conflicts if there are 2 sites on the same DB. 

`PLL_CACHE_HOME_URL` set to false should avoid using the cached home urls.
There is another constant `PLL_CACHE_LANGUAGES` which, when set to false, completely prevents the transient to be used. 

These constants must be set in wp-config.php. functions.php come too late.

**Comment by einicher** [comment]
Set both constants to false in wp-config.php - no effect, always redirecting to the instance where the last post was saved.

```
define('PLL_CACHE_HOME_URL', false);
define('PLL_CACHE_LANGUAGES', false);
```

**Comment by Chouby** [comment]
Could you find out if the redirect is initiated by Polylang?

There are two redirects in Polylang.

The first is a 302 for the home page: See https://github.com/polylang/polylang/blob/2.1.2/frontend/choose-lang.php#L262. This one uses the cached home url.

The second is a 301 and extends the canonical url functionality of WordPress. See https://github.com/polylang/polylang/blob/2.1.2/frontend/frontend-filters-links.php#L422. As far as I know, this one should no use any cached url (unless another plugin implements such cache).

**Comment by einicher** [comment]
Thank you very much for your help it works now.

The problem was simply that i put the declarations of the constants after the include wp-settings line.
