### ISSUE TITLE
wp.data.select( 'core' ).getEntitiesByKind() is deprecated since version 6.0

### ISSUE THREAD

**Issue by erikjoling** [polylang/polylang#1147]
Using WordPress 6.1RC-5 I saw a deprecation warning in my browser console:

`wp.data.select( 'core' ).getEntitiesByKind() is deprecated since version 6.0. Please use wp.data.select( 'core' ).getEntitiesConfig() instead.`

Checking my code I discovered that Polylang is using `getEntitiesByKind` in a couple of places.

## Steps to reproduce the issue

1. WordPress 6.1 RC-5
2. Latest polylang plugin
3. editing a page using Gutenberg 
4. clicking around triggers it sometimes

**Comment by Chouby** [comment]
We have to live with this kind of warning as long as we support older versions of WordPress.

**Comment by eldaragalarov** [comment]
```
$wp_version = bloginfo('version');
$wp_version = substr('$wp_version', 0, 2);
$wp_version_num = floatval($wp_version);
if($wp_version_num >= 6.0) {
    wp.data.select( 'core' ).getEntitiesConfig()
}
else{
    wp.data.select( 'core' ).getEntitiesByKind()
}
```
