### ISSUE TITLE
Gutenberg Phase 4 and Polylang

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#1152]
Hi @Chouby and other developers.

As I know, WP team is planning to implement their own multilingual support in Wordpress.
Do Polylang will have any feature or guide to help WP users to migrate to WP core multilingual functionality?
How large chances are that WP team will use Polylang as reference implementation for their core implementation?

**Comment by Chouby** [comment]
As far as I know Gutemberg Phase 4 has not started and is probably still not much more than one line in the WordPress roadmap. So at this stage I am unable to answer any of your questions.
For your information, here is a conference on the topic at WCEU 2019: https://wordpress.tv/2019/10/11/pascal-birchler-on-multilingual-wordpress-sites/. It's quite old now, and it does not answer your question, but this is the only time I am aware of a core committer expressing himself on the topic.
