### ISSUE TITLE
Multidomain width domain mapping

### ISSUE THREAD

**Issue by TanguyS** [polylang/polylang#116]
Hello,

When using polylang on multidomain with domain mapping enabled, the site has normally two urls (if redirects can't be enabled, this is my case cause I need one domain for each language. In this case, the redirects tend to go wrong since domain mapping doesn't know where to redirect):
http://site.multisite.com
http://www.site.com

After setting the domain in polylang as www.site.com (and en.site.com, and so on), when going to http://site.multisite.com it doesn't redirect naturally to http://www.site.com.

This is a very specific issue. I'll commit something to patch this issue as soon as I find how to do this.

Thanks,

Tanguy

**Comment by Chouby** [comment]
Hi,

Is your issue specific to one domain mapping plugin? Could you clarify what happens when you write that  "the redirects tend to go go wrong"?

**Comment by TanguyS** [comment]
The plugin is this one:
https://wordpress.org/plugins/wordpress-mu-domain-mapping/

Yes, my problem is really specific since normally, you should go for one primary domain and some secondary domains in the domain mapping plugin. At this point, you can make a redirect from the domain mapping plugin in order to redirect to the primary domain. Since, I have more than one language (and so, more than one primary domain. In fact, I have one for each language), I can't do this redirect easily. So, with more than one primary domain, it seems that it will redirect to the first primary domain it finds (which doesn't fit cause it could be any language).

I didn't find how to bypass this limitation from the domain mapping plugin since it's the language plugin which "knows" which domain (ie english.domain.mu-domain.com) should redirect to (ie again en.final-domain.com).

Maybe, I'm showing just a bit of a lack of WP science here and switching to another mapping plugin could fix things out.

**Comment by Chouby** [comment]
I installed a WordPress with WordPress MU Domain Mapping 0.5.5.1. I tried several combinations of options and it looks like the important thing to avoid redirect issue is to check the option 5, "Disable primary domain check". The issue is that domain.mu-domain.com is no more redirected to final-domain.com. Your intention is to restore this redirect from Polylang. Did I understand correctly?

**Comment by TanguyS** [comment]
Yes, I checked everything since it was long ago. Yes, I did check "Disable primary domain check" and yes it's not redirected. And yes, since I can't have figured out how to tell to MU Mapping which domain should redirect to which language based homepage, I thought it would be better to sort this out from polylang. BTW, I think you understood me perfectly.

**Comment by papoola** [comment]
For people getting `too_many_redirect` issue when using `Wordpress MU Domain Mapping` plugin following hack worked for me:

```php
add_filter( 'redirect_canonical', array( $this, 'redirect_canonical' ), 10, 2 );
function redirect_canonical( $redirect_url, $requested_url ) {
	$redirect_url = str_replace('www.primarydomain.com/siteurl', 'www.siteurl.com', $redirect_url);
	return $redirect_url;
}
```
