### ISSUE TITLE
Content loads on invalid repeated URL instead of returning 404 error page

### ISSUE THREAD

**Issue by ssthormess** [polylang/polylang#1172]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Wordpress and Polylang
2. Enter URL of any post/page repeated two or more times like:
https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/

## Expected behavior and actual behavior

When I follow those steps, I see the content loads with an invalid URL.

I was expecting a 404 error page to return instead of the content.

**Comment by Chouby** [comment]
On your site, I see a 301 redirect from the wrong url https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/ to the right url https://blog.majestic.com/fr/etudes-de-cas-recherche/pourquoi-voler-lidee-de-seth-godin-a-marque-le-coup-denvoi-de-ma-carriere-de-link-building/.
And yes, it looks like this redirect is indeed made by Polylang. But this looks good to me.

**Comment by ssthormess** [comment]
How can I avoid this redirect and just show a 404 error page instead?
