### ISSUE TITLE
Translation link lost after saving media file

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#118]
When trying to add a translation of a media file it works initially, but after changing the title of a translation the link get's lost and the two posts are stored separately.

WP: 4.7.3
PLL: 2.1.2

**Comment by Chrystll** [comment]
Hi Jory

I didn’t reproduce your issue but maybe I missed some steps. Here is my test :

Go to the Media list, choose a Media > add a translation by clicking on the plus sign > update.
Go back to the Media list, edit the just translated Media > modify the title > update.
Result : the link between the translations (pen icon) hasn’t been removed.

Do you reproduce it on a fresh install?

**Comment by JoryHogeveen** [comment]
It wasn't an existing site so I'll try the same on a fresh install a.s.a.p. and let you know!

**Comment by JoryHogeveen** [comment]
Hi @Chrystll 
I also can't reproduce on other sites so it must be something specific to that installation.
I'll close the issue for now.
When I find the problem and it could be Polylang related I'll post it here!
