### ISSUE TITLE
Set default language does not flush cache

### ISSUE THREAD

**Issue by phh** [polylang/polylang#119]
Hi there,

`There are posts, pages, categories or tags without language. You can set them all to the default language.`

It seems like `set_language_in_mass` is doing a direct SQL query instead of using the wp_insert_term which is way faster. But it doesn't take into account that WP is also caching the terms.

Without digging too much into this one it seems like a `wp_cache_flush` "fixes" it - but the best solution would be to clear the correct cache groups.

I dont know if the problem only occurs when using a persistent cache. I'm using wp-redis: https://da.wordpress.org/plugins/wp-redis/

**Comment by Chouby** [comment]
Hi,

That's true. Since terms are not existing before, I did not expect it to be an issue. Could you explain what are the consequences?

**Comment by phh** [comment]
On the list page the flags are added but the icons (plus, edit) are not shown. So it seems like no posts are set to the default language.
