### ISSUE TITLE
Polylang throwing 500 after update to 3.3.1

### ISSUE THREAD

**Issue by mpanonmail** [polylang/polylang#1194]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. updated to polylang version 3.3.1
2. can no longer loginto admin area (wp-admin)
3. I then get notified by wordpress of an critical error, providing me with a login via the "wp recovery mode"
4. I log into wp recovery mode, go to the list of installed plugins

## Expected behavior and actual behavior

When I follow those steps, I see...

within the list of installed plugins, it is statet that the polylang plugin could not be loaded, with this error message:
```
an error of type E_ERROR was caused line 13 of the file /home/vnvoocey/public_html/wp-content/plugins/polylang/modules/lingotek/load.php.
Error: Uncaught Error: Class "PLL_Lingotek" not found in /home/vnvoocey/public_html/wp-content/plugins/polylang/modules/lingotek/load.php:13 Stack trace: #0 /home/vnvoocey/public_html/wp-content/plugins/polylang/include/class-polylang.php(247): require_once() #1 /home/vnvoocey/public_html/wp-includes/class-wp-hook.php(308): Polylang->init('') #2 /home/vnvoocey/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #3 /home/vnvoocey/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /home/vnvoocey/public_html/wp-settings.php(480): do_action('plugins_loaded') #5 /home/vnvoocey/public_html/wp-config.php(104): require_once('/home/vnvoocey/...') #6 /home/vnvoocey/public_html/wp-load.php(50): require_once('/home/vnvoocey/...') #7 /home/vnvoocey/public_html/wp-admin/admin.php(34): require_once('/home/vnvoocey/...') #8 /home/vnvoocey/public_html/wp-admin/plugins.php(10): require_once('/home/vnvoocey/...') #9 {main} thrown
```
(the first line of the error message was translated from german by me)

In the frontend, the plugin also does not function (no language selecotr present anymore)

I was expecting...
polylang 3.3.1 to work without issue

**Comment by Chouby** [comment]
> updated to polylang version 3.3.1

Did you update the plugin using the standard Update link in the Plugins page?

The error occurs in a file that has been removed from 3.3.1. So normally this error is not possible unless this file remains from the previous version, which should not occur as WordPress completely deletes all the plugin files during the standard update process.

I suggest that your re-install properly the plugin and the error should disappear.

**Comment by mpanonmail** [comment]
Thanks for the quick response!
Deleting the plug in an reinstalling it did resolve the issue. The error does not happen anymore and the language selector is back. Was a bit worried that we'd loose configurations, but does not seem so.

Unfortunately, I can't say for sure how the update happened, since multiple people use the admin area. But I'm fairly sure that it was not done via the plugin page, rather I assume someone triggered the update manually from the wordpress admin dashboard. Though it could also have been triggered automatically (though polylang would have been the only plugin we set up for automatic updates then, which feels unlikely).
Sorry for not being more helpful here, I hope we were just unlucky and more people are not affected by this. From my side this can be closed.
