### ISSUE TITLE
Uncaught Error: Class 'PLL_Lingotek' not found

### ISSUE THREAD

**Issue by faremal** [polylang/polylang#1200]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate polylang plugin with version 3.3.1

## Expected behavior and actual behavior

When I follow those steps, I see a white screen of death. The debug logs of Wordpress show the following error :
`PHP Fatal error:  Uncaught Error: Class 'PLL_Lingotek' not found in /home/**/public_html/wp-content/plugins/polylang/modules/lingotek/load.php:13
Stack trace:
#0 /home/**/public_html/wp-content/plugins/polylang/include/class-polylang.php(247): require_once()
#1 /home/**/public_html/wp-includes/class-wp-hook.php(308): Polylang->init('')
#2 /home/**/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /home/**/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/**/public_html/wp-settings.php(480): do_action('plugins_loaded')
#5 /home/**/public_html/wp-config.php(111): require_once('/home/aethongr/...')
#6 /home/**/public_html/wp-load.php(50): require_once('/home/aethongr/...')
#7 /home/**/public_html/wp-admin/admin.php(34): require_once('/home/aethongr/...')
#8 /home/**/public_html/wp-admin/index.php(10): require_once('/home/aethongr/...')
#9 {main}
  thrown in /home/**/public_html/wp-content/plugins/polylang/modules/lingotek/load.php on line 13`

The admin area of Wordpress is unusable when the plugin is active

I was expecting no error to be thrown and the plugin to work.

**Comment by Chouby** [comment]
Please read https://wordpress.org/support/topic/polylang-fatal-error-since-09-01-23/
