### ISSUE TITLE
PHP Warning: Attempt to read property "home_url" on bool in polylang/include/links.php on line 62

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#1206]
PHP Warning: Attempt to read property "home_url" on bool in polylang/include/links.php on line 62

WP 6.1.1
PL 3.3.1
PHP 8.0.26

**Comment by Chouby** [comment]
Could you provide steps to reproduce starting from a fresh install?

**Comment by EldarAgalarov** [comment]
Hi @Chouby 

1. Set some theme.
2. Upload new theme zip archive and replace existing theme version with uploaded one.

**Comment by Chouby** [comment]
Closed by #1207
