### ISSUE TITLE
polylang and post categories list

### ISSUE THREAD

**Issue by lucav90** [polylang/polylang#121]
hi,

if i have polylang enabled on my wordpress website, i don't view all post categories and when i saved new category i dont view it on the list.
if i disabling polylang, i view all correctly.

What is the problem?

Regards,

**Comment by Chouby** [comment]
Hi,

It looks more like a support request than a valid issue. Please clarify the steps to reproduce (I don't even understand if it's on admin or frontend). Please do that on a fresh install with only Twenty Seventeen and Polylang activated.
