### ISSUE TITLE
Custom ACF keys in clones is not working due to $field_key = substr( $field_key, -19 );

### ISSUE THREAD

**Issue by tkorsback** [polylang/polylang#1212]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate ACF and create a field with the type post_object. Create a flexible content field and use the "post_object" field as a clone. It's important to create the fields with PHP and use custom names instead of "field_xxx".
2. When translating to another language the "post_object" field looses the relation.

The reason is that in `acf-auto-translate.php` (`get_field_object`) on line ~164 it uses `substr` with a fixed **-19**. That only works for auto generated keys in ACF (field_xxx) and not for custom keys.

In our case one key is **internal_link_a_internal_link_item** where **internal_link** is the clone field and **a_internal_link_item** is the "post_object" field, -19 is tripping the letter **a** from the key.

In a large project (like ours) with hundreds of fields it's impossible to use the auto generated keys if you want to keep your sanity.

A solution could be to add a filter in `get_field_object` that we can hook into. I think it possible to fix this by extracting the prefixed clone key from the `$field`. Will test this during the weekend.

**Comment by Chrystll** [comment]
Could you please contact me on our [helpdesk](https://polylang.pro/support/)? That will be easiest for me to investigate your issue. I would need that you provide me your json file to reproduce it as well the site health info of your site. It will allow me to know more about your installation and your Polylang settings (I will see if you are translating or not the Field groups). Please don't forget to provide me your license key in your support request. Thank you.
