### ISSUE TITLE
Can't translate project category

### ISSUE THREAD

**Issue by mrfanny** [polylang/polylang#1218]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x ] This bug happens with only Polylang plugin active
- [ x] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open WP admin
2. click on Projects in left menu
3. click on Projects / Tags in left menu
4. There is a problem - can't translate project categories and tags

## Expected behavior and actual behavior

When I follow those steps, I see list of categories / tags without translations

I was expecting translation for project categories and tags. If you open posts or pages categories / tags, there are translations available.

**Comment by Chouby** [comment]
For support questions like this please use the support forum or the support helpdesk if you are using Polylang Pro. You'll need to precise where your projects come from to receive help.

**Comment by mrfanny** [comment]
> For support questions like this please use the support forum or the support helpdesk if you are using Polylang Pro. You'll need to precise where your projects come from to receive help.

It's not a support issue. It's about a missing part of the plugin, which is not a problem I can solve on myself or with the help of support. This problem can only be solved by you with the next update.
