### ISSUE TITLE
issue with OnePress Plus Theme

### ISSUE THREAD

**Issue by AgnesFaid** [polylang/polylang#122]
Polylang : Version 2.1.2
WordPress : Version 4.7.3
Hi,
I'm trying to configure polylang on my website. My theme is OnePress, with pluging OnePress Plus. 
I've 2 issues, certainly linked to the theme.
1-When I want to set my theme appareance, all is bugged, my options are void
2-In the front office, my menu doesn't appear, in french or in english (the 2 languages I want)
Do you know if there's an incompatibility with my theme ?
I'm not a developer unfortunately, hope you could help me :(
Thanks
Agnes

**Comment by Chouby** [comment]
We took the time to test the OnePress theme with Polylang on a fresh install and we did not experience anything unusual. Please use the community supported forum for such support requests.

**Comment by AgnesFaid** [comment]
OK, so, I don't understand why I have bugs.
Anyway, I've decided to install another multilanguage plugin which works well with my theme.
Thanks,
Agnes

**Comment by DanSman** [comment]
He is right. I have the same problem.
Nearly every 'section content' isn't changeable. Maybe you can check it again?

If you add a section content for example for the 'Features content' you can't change it. The string isn't there.
```
<key name='onepress_features_id' />
<key name='onepress_features_title' />
<key name='onepress_features_subtitle' />
<key name='onepress_features_desc' />
<key name='onepress_features_layout' />
<key name='onepress_features_boxes' />
```

Your plugin includes "only"

```
onepress_features_id
onepress_features_desc
onepress_features_layout
```
