### ISSUE TITLE
Can’t get back to principal language

### ISSUE THREAD

**Issue by Luccio333** [polylang/polylang#1220]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ x] This bug happens with only Polylang plugin active
- [ x] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. I checked the menus, everything is ok
2. I checked the page translations and it's ok

## Expected behavior and actual behavior

https://www.dominicaines-du-saint-esprit.fr

Since I’ve made update of the site of my client it do not work well. It’s a french site. If you land on it for the fisrt time it’s loading well on french version. The navigation on the french pages works well. When you select a foreign language, english, german or italian, it load well. But if you want to go back to the french version, it do not work. I made the same updates on a mirror site and it doesn’t have the same problem. The translations links are ok. 

The issue only appears on the home page. The other pages switch correctly to different pages. 

Where do you think the problem comes from ?

thank you for your help !

Luc

**Comment by bardiotmarin** [comment]
I had the same problem a few days ago, my solution was to go to the administration, in the user select the administrator and set the language to its main language.

Then I deactivated and reactivated polylang and the bug was fixed 

Dm si tu a besoin d'aide !

**Comment by Chouby** [comment]
This is indeed most probably a cache issue. Make sure that the browser language detection is deactivated. I also invite you to use a cache plugin officially supporting mutilingual sites (ex: WP Rocket). 

For support questions like this, please use the support forum.
