### ISSUE TITLE
Language switcher return links without pagination

### ISSUE THREAD

**Issue by g-rodigy** [polylang/polylang#1222]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add few languages.
2. Make some post on all languages more than displayed in one page.
3. In setting set the permalinks format arbitrarily: /press/%postname%/
4. Go to archive page 2 or more.

## Expected behavior and actual behavior

The language switcher will be return links with pagination like site.com/en/press/page/2

Actual the language switcher always return links without pagination site.com/en/press

**Comment by g-rodigy** [comment]
Tested on version v3.3.1

**Comment by Chouby** [comment]
This is the desired bahavior. As the translation is optional, we have no warranty that there is the same number of pages in all languages. So the translation of the page 3 doesn't may not exist. That's why we intentionnaly link to the first page. 

If you don't agree with our choice, you can use the filter [`pll_translation_url`](https://polylang.pro/doc/filter-reference/#pll_translation_url) to customize the link according to your needs.

**Comment by g-rodigy** [comment]
In my case always have the same number of pages, so filter `pll_the_language_link `is quite an acceptable solution. I .
Perhaps you can add a parameter for this to plugin settings or a language switcher.

**Comment by g-rodigy** [comment]
Perhaps need to add example of similar code to the documentation, it may be useful to someone.
````php
add_filter('pll_the_language_link', function($url, $slug) {
	if (is_paged() && (is_archive() || is_home())) {
		$page = get_query_var('paged', null);
		$page_url = substr(get_pagenum_link($page), strlen(home_url()));

		return rtrim(pll_home_url($slug), '/') . '/' . ltrim($page_url, '/');
	}

	return $url;
}, 10, 2);
````
