### ISSUE TITLE
WordPress 6.2 beta 2 - Fatal error: Uncaught TypeError: Illegal offset type in isset.

### ISSUE THREAD

**Issue by oldrup** [polylang/polylang#1223]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install WordPress 6.2 beta 2 on existing site using PolyLang
2. Edit a post with a translation
3. Click "Update" (save post)

## Expected behavior and actual behavior

When I follow those steps, I see...

Page crashes with this error:` "Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in /home/sustain2/oldrup.net/wp-includes/class-wp-metadata-lazyloader.php:89 Stack trace: #0 /home/sustain2/oldrup.net/wp-includes/post.php(7843): WP_Metadata_Lazyloader->queue_objects() #1 /home/sustain2/oldrup.net/wp-includes/class-wp-query.php(3532): wp_queue_posts_for_term_meta_lazyload() #2 /home/sustain2/oldrup.net/wp-includes/class-wp-query.php(3787): WP_Query->get_posts() #3 /home/sustain2/oldrup.net/wp-includes/class-wp.php(663): WP_Query->query() #4 /home/sustain2/oldrup.net/wp-includes/class-wp.php(783): WP->query_posts() #5 /home/sustain2/oldrup.net/wp-includes/functions.php(1330): WP->main() #6 /home/sustain2/oldrup.net/wp-admin/includes/post.php(1245): wp() #7 /home/sustain2/oldrup.net/wp-admin/includes/class-wp-posts-list-table.php(165): wp_edit_posts_query() #8 /home/sustain2/oldrup.net/wp-admin/edit.php(235): WP_Posts_List_Table->prepare_items() #9 {main} thrown in /home/sustain2/oldrup.net/wp-includes/class-wp-metadata-lazyloader.php on line 89"`

I was expecting...

No error ;) Listen, I know this is an early beta of WordPress 6.2, so just consider this a heads op :) I'm testing plugin compatibility on https://oldrup.net/polylang-in-english/ with new WordPress versions before updating production-sites.

**Comment by Chouby** [comment]
Thank you for your test and bug report. This helps to know that users are testing Polylang against the future version of WordPress.

On our side we have already detected [a similar issue in the curent stable version of Polylang Pro](https://github.com/polylang/polylang-pro/issues/1590). But the error doesn't appear with the master branch. According to our tests it was fixed by #1154.

Could you check on your side if the master branch (or the 3.3.x branch as I committed #1154 to this branch in preparation for the future version 3.3.2) solves your error too?

**Comment by oldrup** [comment]
> Could you check on your side if the master branch ... solves your error too?

Sure!. Will test and report back within a few days :) Thank you for sharing this plugin with the community ✌

**Comment by oldrup** [comment]
I can't say I'm convinced I did this correctly, but I got this error when trying to activate the plugin downloaded from https://github.com/polylang/polylang

Did I download the wrong package? Polylang-master??

`
Warning: require(/home/sustain2/oldrup.net/wp-content/plugins/polylang-master/vendor/autoload.php): Failed to open stream: No such file or directory in /home/sustain2/oldrup.net/wp-content/plugins/polylang-master/polylang.php on line 70

Fatal error: Uncaught Error: Failed opening required '/home/sustain2/oldrup.net/wp-content/plugins/polylang-master/vendor/autoload.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php')
in /home/sustain2/oldrup.net/wp-content/plugins/polylang-master/polylang.php on line 70

Call stack:

    include_once()
    wp-admin/includes/plugin.php:2314
    plugin_sandbox_scrape()
    wp-admin/plugins.php:192

Query Monitor

Fatal error: Uncaught Error: Failed opening required '/home/sustain2/oldrup.net/wp-content/plugins/polylang-master/vendor/autoload.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/sustain2/oldrup.net/wp-content/plugins/polylang-master/polylang.php:70 Stack trace: #0 /home/sustain2/oldrup.net/wp-admin/includes/plugin.php(2314): include_once() #1 /home/sustain2/oldrup.net/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /home/sustain2/oldrup.net/wp-content/plugins/polylang-master/polylang.php on line 70
`

**Comment by Marianne380** [comment]
Some tests breaks in PHPUnit without the [following fix](https://github.com/polylang/polylang/pull/1154) in `Query_Test` such as : 

- `test_cat()`
- `test_any()`
- `test_language_and_no_post_type_in_query()`
- `test_category_with_post_type_added_late_in_query()`
- `test_or_operator_on_category()`
- `test_or_operator_on_untranslated_tax()`
- `test_or_operator_on_translated_tax()`
- `test_query_several_languages()`
- `test_or_operator_on_category_with_several_languages()`

With the following error : **TypeError : Illegal offset type in isset or empty /wp-includes/class-wp-metadata-lazyloader.php:89**

**Comment by Chouby** [comment]
@oldrup Thank you very much for your attempt. I am sorry I did not explain that you need to build the plugin after download. 

On our side, we did not reproduce with your test steps, but we reproduced the same error in other ways and also, as reported by @Marianne380 by runnings our automated tests with Polylang 3.3.1. So we are confident enough that the development version is already protected against this error. Expect it to be fixed in the future version 3.3.2.  I am keeping this issue open until this release.

**Comment by Chouby** [comment]
This issue should now be fixed in WordPress. See [the report](https://core.trac.wordpress.org/ticket/57150#comment:17) and [the fix](https://core.trac.wordpress.org/ticket/57150#comment:27).
On our side, #1154 will ensure that such errors won't happen again in the future.

**Comment by oldrup** [comment]
Thank you for your feedback. I did not have time to venture into a build process, so I was unable to test the master branch here. Sorry for not getting back to you.

Will test the next version available on WordPress.org once released :)
Bjarne
