### ISSUE TITLE
Home page redirect to SSL not working when Polylang enabled

### ISSUE THREAD

**Issue by matthewblain** [polylang/polylang#1238]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Have a Wordpress blog set up with the default URL with SSL. E.g. https://example.com.
2. Install polylang. I am currently using Version 3.3.2.
3. Use an HTTP (non-SSL) URL to access the site. E.g. http://example.com/ 

curl -I is an easier way to test this than using the browser.

## Expected behavior and actual behavior

Expected: A 302 or 301 redirect to https://example.com. 
Actual: No-redirect. 200 OK and content returned 'insecurely' over HTTP.

Alternate broken path: Try a non-http, non-canonical URL. E.g. http://www.example.com/
Expected: A 302 or 301 redirect to canonical URL including configured scheme, e.g. https://example.com. Actual: Redirect to 'correct' hostname, but no change in scheme. e.g. http://example.com/

Working alternate: using the SSL URL directly (e.g. https://example.com/ in the browser) works as expected, it does not downgrade to HTTP.

Validation: Disable Polylang and the redirects work as 'expected', 

## Further notes

Possibly related: I had changed the canonical hostname from e.g. test.exampl.e.com to example.com, and polylang was redirecting everything non-canonical (e.g. www.example.com) to test.example.com. Something kicked the cache and it no longer does that.

Possibly related: Issue #865 . Looks similar but not the same.

I don't have Polylang confiugred to use the hostname for langauge, but rather path. I have not tried HTTP language headers in my test to see if it impacts anything.

**Comment by Chouby** [comment]
Probably something is misconfigured on your site. I recommend to use the plugin Really Simple SSL which handles the redirect from http to https in .htaccess.
