### ISSUE TITLE
Array to string conversion in class-wp-debug-data.php

### ISSUE THREAD

**Issue by Screenfeed** [polylang/polylang#1241]
When printing the values of the properties of each language in the site health page, the property `PLL_Language::$term_props` triggers a PHP notice because it is an array because the site health supports arrays that are only 1 level deep.

Maybe we could display something like this:
```
term_props
    language/term_id: xxx
    language/term_taxonomy_id: xxx
    language/count: xx
    term_language/term_id: xxx
    term_language/term_taxonomy_id: xxx
    term_language/count: xx
```

**Comment by Chouby** [comment]
We can even reduce and avoid to display "term_props" itself.

**Comment by Screenfeed** [comment]
I think it can be useful, for example to know if all language taxonomies are well registered and have their terms.

**Comment by Chouby** [comment]
I meant output like this :
```
language/term_id: xxx
language/term_taxonomy_id: xxx
language/count: xx
term_language/term_id: xxx
term_language/term_taxonomy_id: xxx
term_language/count: xx
```

**Comment by Screenfeed** [comment]
OK, I see.
