### ISSUE TITLE
Server variables "are required but not set" PHP notices emitted in a CLI environment

### ISSUE THREAD

**Issue by Kadigan** [polylang/polylang#1252]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Load WP from CLI (by including wp-load.php)

Test file contents: `<?php include("./wp-load.php"); ?>`

## Expected behavior and actual behavior

Expected output: no output.

Actual output:

```
Notice: $_SERVER['HTTP_HOST'] or $_SERVER['REQUEST_URI'] are required but not set. in {path to WP}/wp-content/plugins/polylang/include/functions.php on line 87
```

[Referenced issue on wordpress.org, reported a year ago.](https://wordpress.org/support/topic/notice-_serverhttp_host-or-_serverrequest_uri-are-required/)

Wordpress can be loaded from CLI (command-line interface), eg. over SSH, or via `wp-cli`. This allows the user to run WP functions (like post management, updates etc.) without actually rendering the site.

When this happens, plugin code _should not rely_ on any webserver variables to be set, because **the webserver is not actually part of the load chain**.

This can probably be fixed with `if ( php_sapi_name() == "cli" ) { ... }` or something similar.

**Comment by Chouby** [comment]
You reach a point where Polylang needs the current requested url, which is obtained with these superglobals. 

Although it is [recommended to set them for WP CLI](https://make.wordpress.org/cli/handbook/guides/common-issues/#php-notice-undefined-index-on-_server-superglobal), we work around the issue by replacing the current url with the home url if they are not provided. For all other (unknown) usage we intentionnally trigger this error when `WP_DEBUG` is set to true to inform the users the issue and that something may not work as expected. See https://github.com/polylang/polylang/blob/3.3.2/include/functions.php#L71-L91

**Comment by Kadigan** [comment]
So I'm essentially stuck with these and can't do clean file pipes unless I disable Polylang. Got it.
