### ISSUE TITLE
Support for  WP Customize Control

### ISSUE THREAD

**Issue by mattiasghodsian** [polylang/polylang#126]
I just finished coding a template and i cant find a way for PLL to detect all my [wp customize controllers](https://codex.wordpress.org/Theme_Customization_API) to add extra fields for each active language, 

The only way i see for me is to make a loop for each controller and add extra fields for each active language and a function to extract the right values for each controller for the current active language.

Any ideas ?

**Comment by grappler** [comment]
I have done something similar. This is part of my code. I have not tested this snippet.

```php
$languages = [
	'de' => __( 'German', 'text-domain' ),
	'fr' => __( 'French', 'text-domain' ),
	'it' => __( 'Italian', 'text-domain' ),
];
foreach ( $languages as $slug => $name ) {
	$wp_customize->add_section( 'posts_section_' . $slug, array(
		'title'           =>  __( 'Title', 'text-domain' ),
		'panel'           => 'homepage_panel',
	) );
	$wp_customize->add_setting(
		"skbw_home_posts[{$slug}]",
		array(
			'default'           => false,
			'sanitize_callback' => 'absint',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		'home_post_' . $slug,
		array(
			'label'    => __( 'title', 'text-domain' ),
			'section'  => 'posts_section_' . $slug,
			'settings' => "skbw_home_posts[{$slug}]",
		)
	);
} // End foreach().
```

The solution also depends on the data that you are saving and how often it is changed. If you give a bit more info I could give some other suggestions.

**Comment by Chouby** [comment]
Yes that's one way. To set options in all languages directly form the customizer.
Another way would be to keep only one option in the customizer and to enable its translation in the strings translations table, either with a [wpml-config.xml](https://polylang.pro/doc/the-wpml-config-xml-file/) file or better, with [pll_register_string()](https://polylang.pro/doc/function-reference/#pll_register_string), pll__() and the filter [pll_sanitize_string_translation](https://polylang.pro/doc/filter-reference/#pll_sanitize_string_translation) for the sanitization

**Comment by mattiasghodsian** [comment]
Well i know you could do it this way but i wanted to know if there was an easy and better way to do it, here my code.

https://pastebin.com/5Xg8YBr6

**Comment by Chouby** [comment]
The customizer part looks goo to me. The Polylang part could be greatly simplified.
As I see it, you could replace `$ppl_langs` by a call to [pll_languages_list()](https://polylang.pro/doc/function-reference/#pll_languages_list), which return the list of languages slugs.
