### ISSUE TITLE
Polylang has been deactivated because you upgraded from a too old version.  Before upgrading to 3.3.3, please upgrade to 2.9.

### ISSUE THREAD

**Issue by osamax2** [polylang/polylang#1267]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. worked fine 3.3.3
2. add this code : update_option('polylang', array('switch_lang' => 'rtl'));
3. error version in array is null
4. then error Polylang has been deactivated because you upgraded from a too old version.  Before upgrading to 3.3.3, please upgrade to 2.9.

## Expected behavior and actual behavior

When I follow those steps, I see that polylang is deaktive

I was expecting no error and still work my website is down

**Comment by osamax2** [comment]
How do I fix my Polylang now?

I just stopped all upgrade functions to start the plugin.

I need a solution.

**Comment by Chouby** [comment]
The easiest is to restore a database backup
