### ISSUE TITLE
Quick edit does not display categories

### ISSUE THREAD

**Issue by Toshiwoz** [polylang/polylang#127]
![image](https://cloud.githubusercontent.com/assets/21297356/25317195/4be0589a-2839-11e7-97c1-9597eea9fc03.png)

Hi, as you can see from the image the categories are not displayed in the quick edit. Quite annoying, hopefully can be solved pretty quick.

**Comment by grappler** [comment]
Categories are shown in the quick edit. This seems to be an issue with your site.

A few things that I would check for is that the categories are properly assigned to a language. Deactivate all of the other plugins to see if that makes a difference and activate a default theme.

**Comment by Chouby** [comment]
The debug bar shows an error in the screenshot. If this is a javascript error, it could explain that the categories are not shown. They are filtered in javascript.
