### ISSUE TITLE
Duplicate Posts Plugin Compatibility Fatal Error

### ISSUE THREAD

**Issue by vageliskatsiotis** [polylang/polylang#129]
Hi. This error appear in Duplicate Post plugin Settings Page, after activating it. I've had Polylang Free (not Pro) enabled and configured first if that matters. As a result, the option to clone post in wp-admin/edit.php page does not exists.

`Fatal error: Uncaught Error: [] operator not supported for strings in /srv/http/wordpress/wp-content/plugins/polylang/modules/plugins/plugins-compat.php:528 Stack trace: #0 /srv/http/wordpress/wp-includes/class-wp-hook.php(300): PLL_Plugins_Compat->duplicate_post_taxonomies_blacklist('') #1 /srv/http/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array) #2 /srv/http/wordpress/wp-includes/option.php(141): apply_filters('option_duplicat...', '', 'duplicate_post_...') #3 /srv/http/wordpress/wp-content/plugins/duplicate-post/duplicate-post-options.php(296): get_option('duplicate_post_...') #4 /srv/http/wordpress/wp-includes/class-wp-hook.php(298): duplicate_post_options('') #5 /srv/http/wordpress/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /srv/http/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /srv/http/wordpress/wp-admin/admin.php(222): do_action('settings_page_d...') #8 /srv/http/wordpress/wp-admin/options-general.php(10): require_once('/srv/http/wordpress...') #9 {main} thrown in /srv/http/wordpress/wp-content/plugins/polylang/modules/plugins/plugins-compat.php on line 528`

**Comment by Chouby** [comment]
I don't reproduc with Polylang 2.1.3 and Duplicate Post 3.2. It looks like some third party plugin is messing  with the Duplicate Post option 'duplicate_post_taxonomies_blacklist'. The line 528 expects the option to be an array. Just as Duplicate Post does.

**Comment by vageliskatsiotis** [comment]
Ok, I'll look into it and let you know, if you want.

Thank you
