### ISSUE TITLE
Static front page does not work in 3.4.2 with only one language

### ISSUE THREAD

**Issue by zepich** [polylang/polylang#1291]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install the Polylang plugin
2. Add **one** language
3. Add a static front page
4. Configure the static front page in the reading settings
5. Visit the front page

## Expected behavior and actual behavior

When I follow those steps, I see a list of posts on the front page.

I was expecting that I see the static front page.

## Workaround

Everything worked as expected after adding another language and translating the static front page to this new language.

But with only one language added, the static front page does not work.

## Explantion

I have a website where a customer planned to have multiple languages later. To avoid any issues with the URLs later, we added multilanguage with just one language before go-live.

Today, I updated from 3.3.3 to 3.4.2. After the update, the front page was empty since we were using ACF on the front page, and the fields were not available anymore. I investigated the issue and found out that the wrong posts were loaded. After disabling the Polylang plugin, everything worked as expected again.

So I started to investigate the issue in a new WordPress installation and was able to reproduce the issue, as long as there is only one language added to Polylang (or the front page of the second language is not translated).

In my eyes, this is a very rare use case. But if you have an idea how to fix it, it would be great to have a solution for that.

**Comment by Chouby** [comment]
We are indeed aware of this regression which has been reported in the WordPress forum. We are working on it.
