### ISSUE TITLE
Non-default language homepage 301 redirect.

### ISSUE THREAD

**Issue by onesecurity** [polylang/polylang#1294]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. New Language Page Settings: Japanese(Default) and English.
2. Shortly after the update of the English homepage, there was a continuous 301 redirect situation, which currently only appears on the homepage.
![16855432766034](https://github.com/polylang/polylang/assets/61774041/145b4dd6-5cb8-4fd7-91b7-c8ad10fa038a)

## Expected behavior and actual behavior

I was expecting,Accessing non-default language homepages normally should not result in repeated redirections.

**Comment by Chouby** [comment]
I'm not able to reproduce. Please start from a WP 6.2.2 fresh install on which you install only Twenty Twenty One and Polylang 3.4.2. Nothing else. Then describe step by step how to reproduce your issue.

**Comment by Chrystll** [comment]
I am closing this ticket as there has been no response from the sender for four months.
