### ISSUE TITLE
Flags broken after update with WordPress in subfolder

### ISSUE THREAD

**Issue by mklusak** [polylang/polylang#1296]
I have WP installed **in subfolder**, and after update to 3.4.2 my flags are broken - not only custom ones, but event default plugin flag. Image paths are wrong.

Custom flag in /wp-content/polylang has URL:  `https://www.domain.com/subfolder/subfolder/wp-content/polylang/cs_CZ.svg`

Plugin flag: `https://www.domain.com/subfolder/subfolder/wp-content/plugins/polylang/flags/pt.png`

This line of code is the problem: https://github.com/polylang/polylang/blob/cff7e5fe7ae880dfcfb05e2ba58c4f3d2b942853/include/language.php#LL491C7-L491C7

The code `return site_url( set_url_scheme( $flag_url, 'relative' ) );` creates `https://www.domain.com/subfolder/subfolder/wp-content/polylang/cs_CZ.svg` from originally correct URL `https://www.domain.com/subfolder/wp-content/polylang/cs_CZ.svg`

**Comment by Chouby** [comment]
Thanks for the bug report.
For the record, in this context ( WP installed as subfolder ):
```
$flag_url => http://monsite.com/subfolder/wp-content/polylang/en_US.png
set_url_scheme( $flag_url, 'relative' ) => /subfolder/wp-content/polylang/en_US.png
site_url( set_url_scheme( $flag_url, 'relative' ) ) => http://monsite.com/subfolder/subfolder/wp-content/polylang/en_US.png
```
This is quite hard to detect as our language switcher doesn't use this method (we use only the relative url). The full url is provided for the WPML compatibility API or for custom languages switcher using `pll_the_languages()` with the raw option.
