### ISSUE TITLE
Deprecation notice - Deprecated: Class property PLL_Language::$home_url is deprecated

### ISSUE THREAD

**Issue by waleedmumtaz** [polylang/polylang#1298]
### The issue:
The following deprecation notice displays my website:

> Deprecated: Class property PLL_Language::$home_url is deprecated, use PLL_Language::get_home_url() instead. Error handler in /directory/directory/public_html/website-directory/wp-content/plugins/polylang/include/language-deprecated.php on line 253

###  Produced by:
I just updated from Polylang 3.3.3 to 3.4.2 on two of my WordPress websites. The first website did not show this notice, but the second one did. The notice displays at the top of the page, both on the admin dashboard and on the website itself.

### Screenshot:
![image](https://github.com/polylang/polylang/assets/32681782/5821843e-f32d-48c8-af5a-8f729a80b031)

**Comment by Chouby** [comment]
This notice has been added in version 3.4 to warn developpers that important changes have been made in Polylang 3.4 and that we will not support the old way to get the home url in a future version. See also https://polylang.pro/polylang-3-4-eases-the-translation-of-custom-tables/

I invite you to deactivate your plugins one by one until you find which one is responsible for the deprecated notice and contact the author in case he/she doesn't know yet.
