### ISSUE TITLE
cmb2 integration

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#130]
It would be awesome if soemone could give me a direction. I'd like to integrate cmb2 theme options page with polylang strings.

https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

**Comment by Chouby** [comment]
Generally, this can easily be achieved with a [wpml-config.xml](https://polylang.pro/doc/the-wpml-config-xml-file/) file. You can also use the PHP functions pll_register_string() and pll__() for more flexibility (see https://polylang.pro/doc/function-reference) . The filter [pll_sanitize_string_translation](https://polylang.pro/doc/filter-reference/#pll_sanitize_string_translation) is useful to to sanitize inputs.
