### ISSUE TITLE
Navigation menu - selected language <a> tag without link

### ISSUE THREAD

**Issue by Tester11110000** [polylang/polylang#131]
When navivation menu is inserted to the themes naviation area and the selected item does not include link to page.

When cliking this link the page goes to "Undefined" -url and the page is not found.

![kuva](https://cloud.githubusercontent.com/assets/28687320/26034395/ae34288c-38c4-11e7-9904-e75edac1837f.png)

![kuva](https://cloud.githubusercontent.com/assets/28687320/26034438/2c5e674a-38c5-11e7-90e7-5bcb37a45754.png)

![kuva](https://cloud.githubusercontent.com/assets/28687320/26034448/559668e2-38c5-11e7-86f9-fed3327aacff.png)

Theme is Maskitto Light

And the problem code with this theme is this: 

```javascript
<script type="text/javascript">
			jQuery( document ).ready(function( $ ) {
				$('.navbar .dropdown').hover(function() {
				  $(this).find('.dropdown-menu').first().stop(true, true).slideDown(150);
				}, function() {
				  $(this).find('.dropdown-menu').first().stop(true, true).slideUp(105)
				});

				$( '.dropdown-toggle' ).on( 'click', function() {
					window.location.href = $(this).attr( 'href' );
					return false;
				});
			});
</script>
```

So my suggestion would be that there should be some kind of default href in this part as well or possibility to tell the url. For example # or somethig. This would prevent these kind of problems

I fixed the theme using child-theme and overrided custom js generation and no the site works.

**Comment by Chouby** [comment]
I believe that the issue is in your theme.
* Are you able to reproduce the issue in Twenty Seventeen?
* Are you able to reproduce the issue in your theme by manually adding sub-items (for example to your menu item "Coming soon")?
