### ISSUE TITLE
If wordpress url is different from site url, then polylang redirects pages to same url as wordpress url

### ISSUE THREAD

**Issue by Tester11110000** [polylang/polylang#132]
I have installed and developed site under a subdirecotry  domain.com/wp/{lang}

After taking it to production and changing site url to domain.com the pages are still redirected to domain.com/wp/{lang} even if the settings are changed and the .access file and index.php file are changes according to instructions.

**Comment by Chouby** [comment]
That's probably linked to the way you are migrating your database from one site to another site. A lot of people are forgetting to delete transients or to search and replace *all* the occurences of the domain name (including in serialized options). One or the other is needed for Polylang. 

Go  in Languages > settings > URL modifications and re-save changes. This will clear the languages cache (stored in a transient).
