### ISSUE TITLE
current menu item

### ISSUE THREAD

**Issue by gadze** [polylang/polylang#134]
Hi! I'm the guy from wp.org:
https://wordpress.org/support/topic/current-menu-item-14/

Basically what I would like to ask is, that in this file:
\frontend\frontend-nav-menu.php
where the current-menu-item classes are removed:
`$item->classes = array_diff( $item->classes, array( 'current-menu-item' ) );
$r_ids = array_merge( $r_ids, $this->get_ancestors( $item ) );`

the current attribute should be set to false as well:
`$item->current = false;`

because this is used too, to identify which menuitem is active.

**Comment by Chouby** [comment]
Thanks. I will fix that in 2.1.5.

**Comment by pp-awa** [comment]
Now the current attribute is set to false for every menu item.
I can't anymore identify which menu item is active.

**Comment by Chouby** [comment]
@pp-awa Could you clarify? This changes should impact only the language switcher.

**Comment by pp-awa** [comment]
@Chouby I'm using the current attribute to identify which language is selected on the language switcher.
The problem is that the current attribute is set to false for every item of the language switcher.

**Comment by Chouby** [comment]
The goal of this property is to know which menu item is current, not to know which language is current. There was an inconstency with the current language menu item set to current, while the `current-menu-item` was removed.

To know which menu item is for the current language, you can test the class 'current-lang'.
