### ISSUE TITLE
Select for page linking not working

### ISSUE THREAD

**Issue by Bel1haz0r** [polylang/polylang#1356]
I have an issue connecting the already made page. We already have two languages and want to add the third. The autocomplete under the languages box returns nothing. I have checked the ajax response in networking tab in the browser, it is empty. There is no javascript error.

![Untitled](https://github.com/polylang/polylang/assets/16511744/fba319b5-d906-4dfd-842c-779b8915a366)
![Untitled2](https://github.com/polylang/polylang/assets/16511744/c5b6ade1-051b-4fa1-b6ce-61440d34e94a)

**Comment by Chrystll** [comment]
Usage questions should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
