### ISSUE TITLE
Can't differentiate between multiple English locations in Menus -> Manage Locations editor.

### ISSUE THREAD

**Issue by hilyin** [polylang/polylang#1364]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [?] This bug happens with only Polylang plugin active
- [?] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce

- Setup 2 english languages, ex: en and en-gb
- Setup each navigation
- View 'Manage Locations'

## Actual behavior

Observe multiple menu locations with the same name.

ex:

`<Menu Name> English`
`<Menu Name> English`

## Expected behavior

Multiple menu locations with same language should indicate language code to differentiate.

`<Menu Name> English (en)`
`<Menu Name> English (en-gb)`

## Workaround

(Developer Tools) Inspect the select menu and view the actual language code to know which you're editing.

**Comment by Chouby** [comment]
Polylang displays the name how you filled it in the form when you created the language. You saw an issue in the Menus screen, however you have the same issue, for example, in the language Switcher on the frontend. You may have not noticed it if you selected to display flags though. 
Probably you kept prefilled names when you created the languages, however you have the possibility to change them exactly as you did for the language slug. So, what you must do is to differentiate your two languages by editing them and fill the [name](https://polylang.pro/doc/configure-the-languages/#full-name) with the value you want for each language.
