### ISSUE TITLE
Unable to display blogs from one language in another language's page

### ISSUE THREAD

**Issue by anudeepND** [polylang/polylang#1365]
## Prerequisites

- [ x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ x] This bug happens with only Polylang plugin active
- [ x] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install polylang with more than 2 languages.
2. Create same page called "latest articles" in both the language
3. Write few blog posts in only one language
4. Make the posts to display in all the language's page
5 Now instead of displaying the blogs on both the pages, the articles shows up in the page with same language as the blog posts.
6. All the posts section in other language pages will display as "No posts found"

## Expected behavior and actual behavior

When there is a common blog posts with only one language but that needs to be seen in all the pages, it is not possible currently? There is no way to configure the the bog section to exclude it from poly lang

**Comment by Chouby** [comment]
I am sorry but I ma not sure to understand:
2. Do you mean: create one page called "latest articles" and its translations in other languages.
Could you clarify bullets 4 and 5?

**Comment by anudeepND** [comment]
Sorry for the confusion. I want to have a page called "Latest posts" to feature my posts but the posts are written in default language only and not in any other language. However the site pages use multiple languages.

When a user visits the "Latest posts" with the default language, it shows all the posts properly. But when the "Latest posts" page is visited in another language other than the default one, the posts won't be displayed because there are no posts in that language (the posts are written in only one language which is set as default in polylang)

**Comment by Chrystll** [comment]
If you want to display your articles in the default language on your 'Latest articles' page in your secondary language, it is then necessary to translate them into this secondary language as well. In the Pro version of Polylang, [there is a tool available that allows you to do this in bulk.](https://polylang.pro/doc/duplicating-content-in-bulk/)
If you need further clarification about this tool, [please contact our helpdesk.](https://polylang.pro/support/)
