### ISSUE TITLE
Infinite loop after saving permalinks in wordpress settings. (Multisite)

### ISSUE THREAD

**Issue by dmitrizone** [polylang/polylang#1374]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ x] This bug happens with only Polylang plugin active
- [not sure ] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1.  We have setted up polylang settings to "The front page URL contains the language code instead of the page name or page id" 
2. Save permalink settings in default wordpres setup under settings - permalinks and choose for example post name.
3. Got infinity loop on main page, polylang is sending it to /languageslug and than wordpress sending to / 

## Expected behavior and actual behavior

polylang is sending it to /languageslug, no infinite loop. 

Maybe in /include/link-directory.php file, in init function this part should exist as it was in 3.4 : 

add_filter( 'pre_option_rewrite_rules', array( $this, 'prepare_rewrite_rules' ) );

**Comment by Chrystll** [comment]
@dmitrizone I didn't reproduce your issue on my multisite with Polylang 3.5.1 activated on a sub-site having these settings below:
![screenshot-compat local-2023 10 20-14_28_33](https://github.com/polylang/polylang/assets/19824724/5c7e6403-7035-40f6-bd24-bb306af28cb1)

![screenshot-compat local-2023 10 20-14_29_31](https://github.com/polylang/polylang/assets/19824724/7fd5d2d5-1178-43d4-9b2c-46ba62a7e4b7)

![screenshot-compat local-2023 10 20-14_28_33](https://github.com/polylang/polylang/assets/19824724/3f7e2080-2516-48ff-b15c-555c66b80052)

![screenshot-compat local-2023 10 20-14_29_31](https://github.com/polylang/polylang/assets/19824724/44e48c82-9c6f-4dca-b799-af097d871c75)

Could you please let me know if you are using different Polylang settings? If you are using the same Polylang settings could you please check if you still get or not your issue with a basic configuration such Twenty-twenty One (WordPress default theme) + Polylang only. The others plugins *must be* deactivated.

**Comment by Chrystll** [comment]
I am closing this ticket as there has been no response from the sender for one month.
