### ISSUE TITLE
Notice about missing variables $_SERVER[HTTP_HOST] and $_SERVER[REQUEST_URI].

### ISSUE THREAD

**Issue by arielruminski** [polylang/polylang#1379]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Introduction

After disabling the default cron task and enabling the call in task schedule, the plugin returns a message in the logs.
The message is generated by the `pll_get_requested_url` function in the function.php file.

```
PHP Notice: $_SERVER['HTTP_HOST'] or $_SERVER['REQUEST_URI'] are required but not set. in /wp-content/plugins/polylang/include/functions.php on line 98
```

## Steps to reproduce the issue

1. Set the `WP_DEBUG` variable to true in wp-config.php.
2. Set the `DISABLE_WP_CRON` variable to true in wp-config.php.
3. Add running wp-cron.php file in task schedule.

## Possible solution

I suggest adding an additional if to check if a cron task is not running, I checked and it works.

```php
if ( defined( 'DOING_CRON' ) && DOING_CRON ) {
	return get_option( 'home' );
}
```

Full function code:

```php
function pll_get_requested_url() {
	if ( isset( $_SERVER['HTTP_HOST'], $_SERVER['REQUEST_URI'] ) ) {
		return set_url_scheme( esc_url_raw( wp_unslash( 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ) ) );
	}

	/*
	 * In WP CLI context, few developers define superglobals in wp-config.php
	 * as proposed in https://make.wordpress.org/cli/handbook/common-issues/#php-notice-undefined-index-on-_server-superglobal
	 * So let's return the unfiltered home url to avoid a bunch of notices.
	 */
	if ( defined( 'WP_CLI' ) && WP_CLI ) {
		return get_option( 'home' );
	}

	if ( defined( 'DOING_CRON' ) && DOING_CRON ) {
		return get_option( 'home' );
	}

	if ( WP_DEBUG ) {
		// phpcs:ignore WordPress.PHP.DevelopmentFunctions
		trigger_error( '$_SERVER[\'HTTP_HOST\'] or $_SERVER[\'REQUEST_URI\'] are required but not set.' );
	}

	return '';
}
```

**Comment by Chrystll** [comment]
@Chouby I had a quick conversation with @Screenfeed and it's a borderline case. There's this solution: https://github.com/JulioPotier/secupress/blob/bef7c76c4ed45b1f4b7b4ed8f81ace1b964f983d/free/functions/common.php#L872

**Comment by Screenfeed** [comment]
The solution suggested in the original post seams better actually 😅
