### ISSUE TITLE
"lang" parameter in POST body of custom rest api endpoint overrides "lang" in get_posts args

### ISSUE THREAD

**Issue by huda0816** [polylang/polylang#1388]
- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Make custom rest api endpoint and include "lang" parameter in POST body
2. Make this endpoint call get_posts() with a different lang arg e.g. $args['lang'] = "" 
3. Query ignores lang arg

## Expected behavior and actual behavior

I would expect that a manually set lang arg in get_posts would overrule the lang in the POST body. Renaming the lang parameter in post body to "objLang" solved the problem.

**Comment by Chrystll** [comment]
As of my last check, it seems you haven't raised a customer request through our dedicated support for our clients.
Have you managed to resolve the issue on your end? If not, could you provide us your custom code to help replicate your issue and see what goes wrong?

**Comment by huda0816** [comment]
Hi, I am sorry but I do not have time to raise a customer request. I managed to solve it after I renamed the body parameter. Just want to bring the problem to your attention.
