### ISSUE TITLE
Theme customizations not applying with polylang enabled

### ISSUE THREAD

**Issue by jensni-ch** [polylang/polylang#1391]
## Prerequisites

- [x] This is not a usage question.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

I use the following versions: WordPress 6.4.1, PHP 8.2.13, OnePress Theme 2.3.5, Polylang 3.5.2
Since the last update Polylang breaks my OnePress Theme. Lot's of settings in theme customization do not work anymore.

## Expected behavior and actual behavior

Lot's of settings in the theme customization do not work anymore like 'disable animation effect', 'Disable Sticky Header', header 'Background Color' etc.
In customizer preview some of them are working like header 'Background Color', but not all. When I open the site (in a private browser window) the settings are not applied.
As soon as I disable the Polylang plugin, all settings are applied immediately. When I enable the Plugin again, all settings are gone.

Also the 'Hero' section is not loaded anymore when the plugin is enabled.

**Comment by Chouby** [comment]
I quickly tested a dozen of theme settings with the latest version of Polylang, at least settings which are obvious to discover what they do. I did not notice any issue. 
A bug report should include **detailed steps to reproduce** starting from a fresh install, otherwise we are not able to reproduce and thus not able to fix anything.
