### ISSUE TITLE
Gutenberg 17.x causes theme editor translation controls to be inactive

### ISSUE THREAD

**Issue by badg0003** [polylang/polylang#1392]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and enable Gutenberg (needs to be version 17 or newer)
2. Navigate to the theme editor and choose an existing template part
3. Language selector will no longer be available.

## Expected behavior and actual behavior

The theme editor, specifically the editing of patterns, template parts, etc. within a block theme cannot be translated unless the Gutenberg plugin is disabled. See my ticket I opened with them here:
https://github.com/WordPress/gutenberg/issues/56683#issuecomment-1833850677

**Comment by Chouby** [comment]
This should be fixed in Polylang Pro 3.6-beta1 with WordPress 6.5 beta.
Closed by https://github.com/polylang/polylang-pro/pull/2038
