### ISSUE TITLE
Polylang pro 3.1.6 and SEOpress 7.2

### ISSUE THREAD

**Issue by orso081980** [polylang/polylang#1394]
## Prerequisites

- [✅ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [✅ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ✅] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ✅] This bug happens with only Polylang plugin active
- [ ✅] This bug happens with a default WordPress theme active
- [ ✅] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate polylang pro
2. Activate SEOpress
3. try to access the sitemap.xml file

## Expected behavior and actual behavior

Polylang will redirect the sitemaps_xsl.xsl to the default language (ex. EN) so the website won't be able to access the sitemaps.xml
 page

**Comment by orso081980** [comment]
Dear @toineenzo , I really apologize for the misunderstanding. First of all, you're right: my plugin was really out to date. Secondly, the issue is not at all with Polylang but with the last version of SEOpress. In fact, that version of that plugin adds the language subdirectory to the sitemap. That action will brake the sitemap.xml file. I will contact them to properly explain the issue. You can close this ticket. Again, my apologies.

**Comment by toineenzo** [comment]
> Dear @toineenzo , I really apologize for the misunderstanding. First of all, you're right: my plugin was really out to date. Secondly, the issue is not at all with Polylang but with the last version of SEOpress. In fact, that version of that plugin adds the language subdirectory to the sitemap. That action will brake the sitemap.xml file. I will contact them to properly explain the issue. You can close this ticket. Again, my apologies.

No problem mate!

**Comment by Chrystll** [comment]
Thank you @toineenzo, for your advice ❤️
@orso081980 it's important to note that GitHub, while an excellent platform for code collaboration, might not be the suitable place for support inquiries concerning Polylang Pro. For specific and dedicated support related to Polylang Pro, please contact us directly at https://polylang.pro/support/. Thank you.
