### ISSUE TITLE
Language not available through REST API

### ISSUE THREAD

**Issue by MastaBaba** [polylang/polylang#140]
I want to access the posts of my multilingual blog through the WordPress JSON REST API.

However, there is no info available on the language of posts through the API.

Apparently, to achieve this, the Polylang 'language' taxonomy property ‘show_in_rest’ needs to be 'true'. (See https://wordpress.org/support/topic/how-to-know-the-language-of-a-post-through-the-wordpress-rest-api/#post-9210009)

Can this update be included?

**Comment by Chouby** [comment]
I have made a different choice. I prefer not to expose directly the taxonomy which is too low level and not handy to manipulate. I will expose the language and translations array in a similar way as the functions `pll_get_post_language` and `pll_get_post_translations` do. However, this will be included in Polylang Pro 2.2.

If you prefer to work with the taxonomies, WordPress offers you the necessary filter to change `show_in_rest` to `true`.

**Comment by MastaBaba** [comment]
To achieve this yourself, find relevant code here: https://wordpress.org/support/topic/how-to-know-the-language-of-a-post-through-the-wordpress-rest-api/
