### ISSUE TITLE
Polylang bug with tags (inserted wrong tag)!

### ISSUE THREAD

**Issue by ve3** [polylang/polylang#1401]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install fresh new WordPress with permalink custom structure `/%category%/%postname%/` (but I think it is not important).
2. Delete all plugin but install and active only Polylang. Primary language: Thai, secondary: English-US.
3. Delete all posts, pages, tags. Leave uncategorized and uncategorized-en untouch (I think category is not important).
4. Use any theme. In my testing, I use **Twenty Twenty-Four** but any theme is same.
5. Create 2 new tags with these details. 
    First tag name: **`ชื่อเต็ม กทม`** and slug is **`กรุงเทพมหานคร-อมรรัตนโก`**. 
    Second tag name: **`กรุงเทพมหานคร อมรรัตนโกสินทร์`** and slug is **`บางกอก`**.
6. Create new post or edit existing post.
7. Add tag **`กรุงเทพมหานคร อมรรัตนโกสินทร์`** or you may enter **กรุง** to search and it will be found only one (only one which is correct, the tag name **กรุงเทพ...** has only one, the other one is **ชื่อเต็ม กทม**).
8. Update or submit or save that post.
9. View your post on front page you will see that tag name is **INCORRECT**! It will be displayed **ชื่อเต็ม กทม** instead of **กรุงเทพมหานคร อมรรัตนโกสินทร์**.

## Expected behavior and actual behavior
The expected behavior is Polylang should not change my insert tag which is **กรุงเทพมหานคร อมรรัตนโกสินทร์**. 

The actual behavior is Polylang change my tag to be **ชื่อเต็ม กทม**.

However, if I deactivated Polylang, the only WordPress itself is working correctly.

The problem maybe because the slug name is look like other tag name and Polylang catch from that.  
You may say that I have to change it to be completely different but in real project I have tag names **หนังสือaaaa Aaaaa**, **หนังสือaaaa AaaBbbb** (aa, bb is censored) which is not possible to change because it will be unreadable (in my language) and can be duplicated with **เสียงaaa Aaaa**, etc if I remove some part of it.

Tested with Polylang 3.6-dev. WordPress 6.4.2, or 6.5 (dev version)

**Comment by ve3** [comment]
I'm not sure is this the best way to fix but if it work, please forgive me for my PHP style.

```lang-php
	public function force_tags_translation( $post_id, $post_after, $post_before ) {
		$post_before = $post_before->to_array();

		if ( ! empty( $post_before['tags_input'] ) ) {
			// Let's ensure that `PLL_CRUD_Posts::set_object_terms()` will do its job.
			$tagsObjArray = get_terms(
                array(
                    'taxonomy'         => 'post_tag',
                    'name' => $post_before['tags_input'],
                    'lang'             => '',
                )
            );
            $tagsArray = [];
            foreach ($tagsObjArray as $tag) {
                $tagsArray[] = $tag->term_id;
            }
            unset($tagsObjArray);
            wp_set_post_tags( $post_id, $tagsArray );
		}
	}
```
polylang/include/crud-posts.php

I've tested myself but it seems to be fixed. I'm not sure about that because I didn't run any unit test.

**Comment by Chouby** [comment]
Thank you for the detailed report. WordPress mixes your 2 tags because at some point the slug of the first tag is the same as the name of the second tag once passed to `sanitize_title()`. This is partially due to WordPress encoding Thai characters and limiting the total size of the encoded slug to 200 characters. As you proposed, fixing this requires to set post tags with term ids instead of tag names. I used a different approach in #1418 but it should be equivalent.

**Comment by ve3** [comment]
This is fixed. Thanks a lot. 🎉
