### ISSUE TITLE
Cannot translate custom post and taxonomies

### ISSUE THREAD

**Issue by Milanti** [polylang/polylang#1407]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)). 
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. I check the boxes for my custom post (osetin_recipes) and taxonomies (recipe_cuisine) under the settings sections of the polylang plugin so that I can translate them in English
![image](https://github.com/polylang/polylang/assets/155361964/e9580e6c-7f6e-4117-9f1d-d325da30410b)
2. I save my changes
3. Then, all my cuisine pages and recipes disappear from my French website and I do not have the ability to translate them
![image](https://github.com/polylang/polylang/assets/155361964/fb9fd908-4809-46c2-b5ea-365075cb5cd0)

## Expected behaviour and actual behaviour

When I follow those steps, I see...

I was expecting to see the "+" icon just like the category pages and be able to translate my recipes pages and cuisine pages from french to English

**Comment by Chouby** [comment]
1. Although your screenshot is incomplete, my guess is that you activated the admin language filter to show only French content.
2. Between steps 2 and 3, you forgot the required step to assign a language to all your existing content.
=> As your existing recipes have no language and your settings enforce to display the content only in French then it's expected that your recipes don't appear in the list.
