### ISSUE TITLE
custom post type archive doesn't redirect

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#142]
e.g. cpts: "product"  

/en/products works fine  
but  
/products returns 404  

I expect /products -> /en/products

**Comment by Chouby** [comment]
This could work in your case on your site, but not on other sites. For archives, there is no way to know for sure to which Ianguage to redirect.

I suggest that either you hide the language code in the url for the default language. Thus you won't have any redirect. Or you create a specific redirect that will in your specific case.
