### ISSUE TITLE
Update did_action() checks in home_url()

### ISSUE THREAD

**Issue by sybrew** [polylang/polylang#1422]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Expected behavior and actual behavior

`PLL_Frontend_Filters_Links::home_url()` tests a couple of prerequisites before performing. One of them is `did_action( 'template_redirect' )`. 

We need to filter `pll_home_url_white_list` before that action occurs (as early as `parse_request`) for sitemap support and caching the canonical URL. `$this->curlang` already provides the correct language at `parse_request`. 

So, I think removing the `did_action()` checks will be helpful without incurring side effects.

The test remained largely unchanged since [Polylang 0.4](https://plugins.trac.wordpress.org/browser/polylang/tags/0.4/polylang.php#L707) (12 years ago) -- before the plugin's source landed on GitHub. So, I was unable to find a reason this check was added.

**Comment by Chouby** [comment]
Hi!
Sorry this is a very important test. This guarantees that we filter `home_url()` by default for theme templates and not plugins (we would break too many plugins if we filtered `home_url()`.
For your own needs you can whitelist the file or method that calls `home_url()`. See for example how it's done for WP sitemaps:
https://github.com/polylang/polylang/blob/3.6-beta1/modules/sitemaps/abstract-sitemaps.php

**Comment by sybrew** [comment]
The test is fine, but is passed too late. Consider using `parse_request` instead of `template_redirect`.

The whitelist won't have an effect with the current `did_action()` block in place, for it is unreachable.

**Comment by sybrew** [comment]
My [hijack of Polylang](https://github.com/sybrew/the-seo-framework/commit/27f763c95daeef2dfb84b1b427d7886b4429236f) has produced exactly zero negative feedback in the past 4 months. Please reconsider @Chouby.

**Comment by nviitala** [comment]
What if the check could be completely disable by a plugin or by a theme? Eg. add_filter('pll_home_url_check', '__return_false'); 

Plugins/themes could be also use it like:
add_filter('pll_home_url_check', '__return_false'); 
some code...
remove_filter('pll_home_url_check', '__return_true');

**Comment by sybrew** [comment]
24 months later, and the fix still works without any issues. Please reconsider, @Chouby. 
I found a similar issue that should be fixed, as well. Report coming soon.

Briefly: Polylang delays frontend language-sensitive behavior until `template_redirect`, despite already having enough language context earlier. This issue breaks many queries. Fix this, and 80% of the patches can go.
