### ISSUE TITLE
pll_register_string for arrays?

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#143]
`pll_register_string` is handy when translating simple strings.

But how would you deal with an array? e.g. cmb2 repeatable group options.

**Comment by Chouby** [comment]
I don't know cmb2 but I guess that using `pll_register_string` in a foreach loop may be just fine. In Polylang, I also use it in a recursive function to register strings defined in a `wpml-config.xml` file.
See: https://github.com/polylang/polylang/blob/2.1.5/modules/wpml/wpml-config.php#L184-L198

**Comment by sandrodz** [comment]
@Chouby yes, after some consideration, I did exactly that.
<img width="639" alt="screen shot 2017-06-19 at 6 59 48 pm" src="https://user-images.githubusercontent.com/8479569/27291517-7f0a6eb2-5521-11e7-88fe-8043c1dcd702.png">

**Comment by Chouby** [comment]
Yes. Don't forget to test the existence of `pll_register_string` to avoid a fatal error when Polylang is deactivated.

**Comment by sandrodz** [comment]
no need for that, I use composer+mu-plugins so polylang is project dependency.
