### ISSUE TITLE
JS-Error after QuickEdit: Uncaught TypeError: form.classList is undefined

### ISSUE THREAD

**Issue by mcguffin** [polylang/polylang#1435]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Quick edit a post or page.
2. Hit "Update"
3. An `Uncaught TypeError` occurs in the js console

<img width="670" alt="grafik" src="https://github.com/polylang/polylang/assets/402988/4136e8ea-4d72-406d-8c99-53c29987e4db">

## Expected behavior and actual behavior

When I follow those steps, I see an `Uncaught TypeError` in the JS console.

I was able to track down the issue to these lines:
https://github.com/polylang/polylang/blob/17fe4aabca9b4d91f544038ea8c8ed601b3a4958/js/src/post.js#L27-L28

When I `console.log(mutation.addedNodes)` the first node is a text node containing two tabs.
<img width="670" alt="grafik" src="https://github.com/polylang/polylang/assets/402988/316b479e-38e9-4545-9687-470753160a1b">

**Comment by manooweb** [comment]
Hello @mcguffin,

Thanks to report that.

Could you precise which Polylang version that you're using?

**Comment by mcguffin** [comment]
Hi @manooweb,
both v3.5.4 (latest at wporg) and 3.6-beta1 (cloned 1 minute ago from the repo).

**Comment by mcguffin** [comment]
if it's of any help for reproduction, here are my wp-config.php debug settings:
```php
define('WP_DEBUG',true);
define('WP_DEBUG_LOG',true);
define('WP_DEBUG_DISPLAY',false);
define('SAVEQUERIES',true);
define('SCRIPT_DEBUG',true);
define( 'WP_SANDBOX_SCRAPING', true );
```
