### ISSUE TITLE
Frontpage Model

### ISSUE THREAD

**Issue by GeekZebre** [polylang/polylang#1437]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

Wordpress Version : 6.4.3
Polylang Free Version : 3.5.4

When I set a model to my page wich is the front page, this is affect the model to my second language frontpage

The value of the meta_key "_wp_page_template" is modified for all front page.

**Comment by Chouby** [comment]
You most probably activated the page template synchronization in Polylang settings. Please use https://wordpress.org/support/plugin/polylang/ for support questions.
