### ISSUE TITLE
lang switcher on cpts archive redirects to root

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#144]
On normal pages language switcher has correct current page url and seamlessly switches between languages of the current page (if available).

But on cpts language switcher just returns root url. Why is that?

**Comment by Chouby** [comment]
I don't reproduce the issue. Are you sure that you have created content in all your languages. For archives, Polylang checks that there is some content in the other languages. If there is some content, th language switcher will link to the correct archive. If not, it will consider that there is no translation (and usually link ot the home page in the other language). That's to avoid to create links to an empty content.
