### ISSUE TITLE
Yoast SEO post type archive breadcrumb translation

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#1440]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active (and Yoast SEO)
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Use Polylang Pro and translate the post type name for a CPT
2. Use Yoast SEO to display breadcrumbs including the post type archive
3. The CPT archive isn't always showing the correct language

## Solution

This topic has already been active on the Yoast SEO forums and WPML (which has the same issue) has scheduled a fix.
I've provided a solution here: https://github.com/Yoast/wordpress-seo/issues/19739#issuecomment-1971764269

**Comment by Chrystll** [comment]
I don't reproduce this issue. I may have missed a step. Here are the steps I followed:

**Context:**

Yoast SEO 22.3
Polylang Pro 3.6

- URLs modifications setup: directories

**Steps to reproduce:**

1. Translate a Custom Post Type (CPT) into multiple languages:
![step1](https://github.com/polylang/polylang/assets/19824724/8679731b-2004-4977-856a-b600070c915b)

2. Go to Yoast > Settings > Content Types > Books > Additional settings > Breadcrumbs title. Set a title as follows:
![step2](https://github.com/polylang/polylang/assets/19824724/8c8b4e77-dbd9-4f1e-981f-1be58247599c)

3. Go to Languages > Translations, then translate 'bctitle-ptarchive-book' into your desired languages: 
![step3](https://github.com/polylang/polylang/assets/19824724/4067d6b9-3212-43cf-a5bd-f812d12bdf7b)

Note that my 'slug_book' is translated:
![Capture d’écran du 2024-03-21 10-44-34](https://github.com/polylang/polylang/assets/19824724/24fb5632-df1c-4acb-aee9-dd3186d9a4ec)

4. visit an English CPT Book => site-test-1.lndo.site/book/fairy-tale/:
![Capture d’écran du 2024-03-21 10-46-35](https://github.com/polylang/polylang/assets/19824724/28fa42bf-ae1f-4d55-a483-2d33407cb725)
If you click on "test breadcrumbs book ENGLISH" you get site-test-1.lndo.site/book/:

![Capture d’écran du 2024-03-21 10-48-15](https://github.com/polylang/polylang/assets/19824724/a17d8f70-b045-4b2f-a850-d54abecf526e)

5. visit a French CPT Book => site-test-1.lndo.site/fr/livre/conte-de-fees/
![Capture d’écran du 2024-03-21 10-49-21](https://github.com/polylang/polylang/assets/19824724/808eb44d-21f4-42bf-9003-e67492166dc8)
If you click on "test breadcrumbs book FRENCH" you get site-test-1.lndo.site/fr/livre/
![Capture d’écran du 2024-03-21 10-50-27](https://github.com/polylang/polylang/assets/19824724/8f75f401-ca07-4e5f-86e3-c488b3958738)

**Comment by sebastienserre** [comment]
Hello @JoryHogeveen 
As per my tests, Yoast SEO is displaying the Custom Post Type labels thanks to i18n functions.

**Comment by JoryHogeveen** [comment]
I will try again on a fresh sandbox env and make it public once I'm back from holiday in a week.
