### ISSUE TITLE
PHP?

### ISSUE THREAD

**Issue by MROVIC** [polylang/polylang#1447]
Dear @Chrystll,
I just checked last version of Polylang (3.5.4) and this is the report of PHP-compatibility-checker.
Of course the check filter was PHP 8.3.4.
How to solve? Should we fix?
Thank you.

----------------------------------------------------------------
Polylang 3.5.4

PHP 5.6 incompatibilities:

FILE: include/base.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
165 | ERROR | bool return type is not present in PHP version 5.6 or earlier
FILE: include/crud-posts.php
FOUND 4 ERRORS AND 0 WARNINGS AFFECTING 2 LINES
387 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
387 | ERROR | array return type is not present in PHP version 5.6 or earlier
410 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
410 | ERROR | int return type is not present in PHP version 5.6 or earlier
FILE: include/filter-rest-routes.php
FOUND 5 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
56 | ERROR | array return type is not present in PHP version 5.6 or earlier
109 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
123 | ERROR | array return type is not present in PHP version 5.6 or earlier
150 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
150 | ERROR | bool return type is not present in PHP version 5.6 or earlier
FILE: include/functions.php
FOUND 6 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
142 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
142 | ERROR | bool return type is not present in PHP version 5.6 or earlier
158 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
178 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
178 | ERROR | bool return type is not present in PHP version 5.6 or earlier
196 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
FILE: modules/wpml/wpml-config.php
FOUND 6 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
740 | ERROR | bool return type is not present in PHP version 5.6 or earlier
769 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
769 | ERROR | bool return type is not present in PHP version 5.6 or earlier
801 | ERROR | array return type is not present in PHP version 5.6 or earlier
843 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier
843 | ERROR | string return type is not present in PHP version 5.6 or earlier

**Comment by Hug0-Drelon** [comment]
Hi @MROVIC,
Polylang 3.4.5 and above is compatible for PHP > 7.0, just like WordPress since 6.3.
I'm closing this because there is no issue after all.

**Comment by Hug0-Drelon** [comment]
Hi @MROVIC,
Polylang 3.4.5 and above is compatible for PHP > 7.0, just like WordPress since 6.3.
I'm closing this because there is no issue after all.

**Comment by MROVIC** [comment]
but it's needed PHP 8, do you consider in next updates or not?

**Comment by Chouby** [comment]
Please read thoroughly the errors reported. All of them are related to PHP 5.6 which is not supported anymore. As stated by @Hug0-Drelon Polylang is compatible with PHP 7.0 and **all** versions above, including of course PHP 8.3.
