### ISSUE TITLE
images uploaded to one language post are not visible in another

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#145]
Even with all languages selected if I'm editing post in English, images uploaded to other language posts are not visible.

Images rarely need localization, it seems redundant to upload same image.

**Comment by chesio** [comment]
Hi,

I guess you don't need to upload the same image, you just have to add a translation. Or deactivate "languages and translations for media" in plugin settings.

**Comment by Chouby** [comment]
This is indeed the expected result. As suggested by @chesio, if you don't need to translate image titles then deactivate the options in Languages > Settings. Note that the images you already uploaded will keep their language (even if not displayed).

**Comment by mrleemon** [comment]
Just one question. Is it possible to remove the language from images already uploaded after deactivating the "languages and translations for media" setting?

**Comment by JuliusVlad** [comment]
> Just one question. Is it possible to remove the language from images already uploaded after deactivating the "languages and translations for media" setting?

Also faced this problem. How to unlink different uploaded images?
