### ISSUE TITLE
pll_get_post() after switching to another blog.

### ISSUE THREAD

**Issue by loic-parent** [polylang/polylang#1452]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install a WordPress site
2. Configure this site as a network site.
3. Create 2 sites
4. Create a page in the both sites.
6. In one of the sites, try to get the translated id of a page of the other site using `switch_to_blog($blog_id)`and `pll_get_post($page_id)`.

## Expected behavior and actual behavior
I should get the translated id of the page but I get `false`.

----

## Code example
```php
switch_to_blog(1); // 1 = ID of parent site
    $id_of_page_in_parent_site = function_exists('pll_get_post') ? pll_get_post(5) : 5; // Returns false in 3.6 BUT returns 5 in 3.5.4
    echo get_field( 'global_title', $id_of_page_in_parent_site );
restore_current_blog();
```

## Proposition of fix that works for me
I have changed the content of the function set in the file cache.php (vendor/wpsyntex/polylang/include/cache.php:66):
```php
public function set( $key, $data ) {
    // Before:
    // if ( ! doing_action( 'switch_blog' ) ) {
    //  $this->cache[ $this->blog_id ][ $key ] = $data;
    // }
    // return $data;

    // After:
    $this->cache[ $this->blog_id ][ $key ] = $data;
    return $data;
}
```

**Comment by loic-parent** [comment]
Another fix that works is by storing the current language in a variable before the switch_to_blog and adding it in the method pll_get_post:

```php
$current_lang = pll_current_language();
switch_to_blog(1); // 1 = ID of parent site
    $id_of_page_in_parent_site = function_exists('pll_get_post') ? pll_get_post(5, $current_lang) : 5; // if the language is defined, it returns the good id instead of false.
    echo get_field( 'global_title', $id_of_page_in_parent_site );
restore_current_blog();
```

**Comment by Chouby** [comment]
As suggested by #1449, the regression is coming from #1415
