### ISSUE TITLE
Polylang + Nelio Content: Uncaught Error: Object of class WP_Post could not be converted to string

### ISSUE THREAD

**Issue by tribble23** [polylang/polylang#1453]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Wordpres, Polylang, Nelio Content plugin

## Expected behavior and actual behavior

When an post should happen, then wordpress catches an error

WordPress-Version 6.4.3
Aktives Theme: Vantage Child (Version 1.0.0)
Aktuelles Plugin: Polylang (Version 3.6)
PHP-Version 8.2.17
```
Error-Details
==============
An error happend type E_ERROR in line 381 of the file  /var/foobar/domain/wp-content/plugins/polylang/include/filters.php . Error message: Uncaught Error: Object of class WP_Post could not be converted to string in /var/foobar/domain/wp-content/plugins/polylang/include/filters.php:381
Stack trace:
#0 /var/foobar/domain/wp-content/plugins/polylang/include/filters.php(381): array_intersect(Array, Array)
#1 /var/foobar/domain/wp-includes/class-wp-hook.php(324): PLL_Filters->fix_privacy_policy_page_editing(Array, 'edit_post', 10, Array)
#2 /var/foobar/domain/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /var/foobar/domain/wp-includes/capabilities.php(842): apply_filters('map_meta_cap', Array, 'edit_post', 10, Array)
#4 /var/foobar/domain/wp-includes/class-wp-user.php(777): map_meta_cap('edit_post', 10, Object(WP_Post))
#5 /var/foobar/domain/wp-includes/capabilities.php(985): WP_User->has_cap('edit_post', Object(WP_Post))
#6 /var/foobar/domain/wp-includes/capabilities.php(877): user_can(Object(WP_User), 'edit_post', Object(WP_Post))
#7 /var/foobar/domain/wp-content/plugins/nelio-content/admin/views/nelio-content-overview-widget.php(192): current_user_can('edit_post', Object(WP_Post))
#8 [internal function]: Nelio_Content\Admin\Views\Overview_Dashboard_Widget\render_post(Object(WP_Post), 1)
#9 /var/foobar/domain/wp-content/plugins/nelio-content/admin/views/nelio-content-overview-widget.php(81): array_walk(Array, 'Nelio_Content\\A...')
#10 /var/foobar/domain/wp-content/plugins/nelio-content/admin/views/nelio-content-overview-widget.php(48): Nelio_Content\Admin\Views\Overview_Dashboard_Widget\render_posts()
#11 /var/foobar/domain/wp-admin/includes/template.php(1456): Nelio_Content\Admin\Views\Overview_Dashboard_Widget\render_widget('', Array)
#12 /var/foobar/domain/wp-admin/includes/dashboard.php(271): do_meta_boxes(Object(WP_Screen), 'normal', '')
#13 /var/foobar/domain/wp-admin/index.php(204): wp_dashboard()
#14 {main}
  thrown
```

**Comment by Chouby** [comment]
Your plugin is doing something unexpected. This is line `#7` of your stack trace:
`current_user_can('edit_post', Object(WP_Post))`.
This is a misused of the function. The plugin should pass a post ID as second param, not the `WP_Post` object.
See examples in the doc: https://developer.wordpress.org/reference/functions/current_user_can/
and everywhere in the WordPress code: https://github.com/search?q=repo%3AWordPress%2FWordPress%20%22current_user_can(%20%27edit_post%27%22&type=code

Note: Your plugin may work with WordPress without other plugins. This is due to how transforms the post ID to a `WP_Post` to use it. **But** It passes the raw param to the filter `map_meta_cap`, so any plugin using this filter (as Polylang does) iexpecting a post ID and not a `WP_Post` object.
