### ISSUE TITLE
Redirects to a "news" page in only one language (en/news)

### ISSUE THREAD

**Issue by aZilberstein** [polylang/polylang#146]
Hey! 

I'd really appreciate your help with this issue...
At [this site](http://1028602.srl.web.hosting-test.net/) I'm using Polylang to show different posts depending on a chosen locale. But when "Ukr" and "Rus" are chosen and I'm trying to reach the news page ([like this](http://1028602.srl.web.hosting-test.net/news)) it would only redirect to **en/news**. Though the majority of News posts I have are in Russian, it tends to redirect me to "en/news" in any case. This link was added to every locale's menu from the custom "News" taxonomy. I tried disabling the plugin to see if it works fine without it - and it does (redirects me to the _/news_ page where all my posts in all languages are displayed).

Please let me know how can I manage these redirect rules and make it redirect actually depending on the locale chosen. Thanks!

[Check out a video demonstrating the issue + when disabling the plugin](https://www.youtube.com/watch?v=5HOlHKOPlno)

**Comment by grappler** [comment]
The problem seems to be either with the menu item or that there is no news page in Russian.

**Comment by Chouby** [comment]
Yes. You probably used the news pages in your Russian menu. You must use the equivalent Russian page. Please use the [support forum](https://wordpress.org/support/plugin/polylang) for support questions.
