### ISSUE TITLE
[polylang.pro] Sitemap is a 404

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#1462]
https://polylang.pro/sitemap.xml redirects to https://polylang.pro/sitemap_index.xml
but it's a 404

https://polylang.pro/robots.txt announces https://polylang.pro/wp-sitemap.xml
but it loads the Blog page.

**Comment by manooweb** [comment]
Thanks @szepeviktor, that certainly explains why our SEO is bad 😵😁
At the moment a work is in progress on the whole site and this should be fixed, I hope 🤞

**Comment by szepeviktor** [comment]
All right.
I leave you with these.

https://polylang.pro/
accross -> across
https://polylang.pro/privacy-policy/
avertizing -> avertising
licence -> license
https://polylang.pro/downloads/polylang-pro/
orginal -> original

**Comment by szepeviktor** [comment]
@Chouby I would gladly run polylang.pro - my work is cheap and I am a preferenciálist.

1. https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md
