### ISSUE TITLE
After updating website to latest version of wordpress language does not working

### ISSUE THREAD

**Issue by fahadx4** [polylang/polylang#1467]
I update my wordpress website to 6.5.2, polylang is not working i have designed all pages in 2 langauge and assigned languages for each page manually but now after update the langauge are not working only default langauge is working and pages in other langauge is not loading

**Comment by szepeviktor** [comment]
> not

Hello @fahadx4!
Software guys like bug report where you describe what **is** happening/being displayed instead of what is **not** happening.
Just my 2 cents ...

**Comment by Chouby** [comment]
This question looks like a support request rather than a bug report. Please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)
