### ISSUE TITLE
How to change navbar in new version of Wordpress 6.5

### ISSUE THREAD

**Issue by old21** [polylang/polylang#1472]
In the docs i can see information for old menu change page. I work on Gutenberg editor. How to translate a navbar?

**Comment by Chouby** [comment]
The question is not clear and looks like a support request rather than a bug report. Please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)
