### ISSUE TITLE
Sync disabled but some blocks are still synced

### ISSUE THREAD

**Issue by Michael-Schaer** [polylang/polylang#1479]
A bug that affects a very specific set up with [ACF](https://www.advancedcustomfields.com/) only. Couldn't really pin it down but found a quick fix. Here is what is know:

When adding a certain ACF block to the front page, it disrupts the content of the other front pages (the other language versions of the front page). All Polylang synchronizing settings are disabled and usually there is no synchronization happening in between language versions. But as soon as this specific block called "events" is added, the sync function gets somehow called and messes up the other frontpages.

## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

### Setup
ACL, Polylang Pro and [a custom Theme with Timber and Twig](https://github.com/grueneschweiz/2018.gruene.ch)
Wordpress 6.5.3, PHP 8.2
Polylang Settings: Two Languages, one frontpage for each language, all sync options disabled

### reproduce
1. Add some simple blocks in both frontpages
2. Add the "events" block in the top position of one of the frontpages
3. Check the other frontpage and find all blocks messed up, with wrong contents find the events blocks added on top

## Expected behavior and actual behavior
Since all the Sync-Settings are disabled, i was expecting to be able to add any block to the frontpage without it having influence on other pages.

## Quick fix
Comment out the contents of the [copy function](https://github.com/polylang/polylang/blob/08df3eb75eb431d5ab1042ab753244fa1bdf4a36/modules/sync/sync-metas.php#L349). This prevents the bug from happening but also removes all possibilities of syncing pages.

## Expectation
It would be nice if this bug could be prevented in future versions. I'm also happy for any tips on what could cause the sync/copy function being called even tough all sync settings are disabled.

**Comment by Abromeit** [comment]
**+1** 

sounds like the same issue we are facing here. 

- website with 2 languages
- utilizes classic editor
- utilizes acf with sortable fields (think "custom page builder")

creating a new fieldgroup + new field in one language deletes images from the other language's page. for some pages. very hard to debug on our end. the only thing we know as of now is that the issue goes away when disabling polylang pro completely. **but** in contrast the issue persists when just disabling all "sync" features in polylang.

**Comment by Chouby** [comment]
As you are both users of Polylang Pro, please contact [the support helpdesk](https://polylang.pro/support/)). They will help you to debug this.
