### ISSUE TITLE
Is it possible somehow do not translate default post type?

### ISSUE THREAD

**Issue by orest22** [polylang/polylang#148]
Hey, just want to know if it is possible do not translate default post. I don't want to have language slug in my url at all.

For example,  I want to have page `domain.com/blog` as an archive page. And Single blog post with url `domain.com/blog/some-post`.

My default language has a slug as well.

Thanks!

**Comment by Chouby** [comment]
Theoretically, it is possible to use the filter [pll_get_post_types](https://polylang.pro/doc/filter-reference/#pll_get_post_types) to control which post types are translatable and which are not. However posts have particular status in WordPress. This is the default post type. So it is the same in Polylang. Thus, although I never tested, I consider it's unlikely that removing 'post' from the list of translatable post types will work out of the box.

**Comment by orest22** [comment]
Yeah, I'd try and had a problem with the archive link still appends language slug to it. So I've decided to go with custom post type. Thanks.

**Comment by Chouby** [comment]
That will be probably easier like that.
