### ISSUE TITLE
I have a question related to the wp_term_relationships

### ISSUE THREAD

**Issue by lyquocphong** [polylang/polylang#1482]
## Prerequisites

Hi !

I have research about polylang for my wordpress site but I come up with an question regarding how polyland use the table wp_term_relationships. Usually that table is store the relations between post and terms but seem that polylang plugin also use it for keep track of categories and terms (term_language, term_translation) so I wonder what is the technique to prevent id conflict. Because post-id and term-id can have the possiblity that will be the same so in that case, how polylang handle that problem. Example:

category has term-id is 30 and also post has id is 30

- [ x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

**Comment by Chouby** [comment]
Posts and terms use different taxonomies. So yes you can have a post id and a term id which are exactly the same in the column object_id` but the `term_taxonomy_id` will be different. Note that you can register taxonomies for almost anything. BuddyPress for example registers [a taxonomy for users](https://plugins.trac.wordpress.org/browser/buddypress/tags/12.5.0/bp-core/bp-core-taxonomy.php#L27).
