### ISSUE TITLE
Broken URL structure when core WP function home_url() is used in theme (no ending with /)

### ISSUE THREAD

**Issue by jasomdotnet** [polylang/polylang#1483]
You closed the issue #1473 as duplicate of #1478 but it is not a duplicate. Subjected WP installation in issue #1473 is different then in the installation of #1478. I use Polylang plugin frequently so I found two different bugs within 1 month.

Ones again: 

When somebody uses in his theme "superstandard" function `home_url()` Polylang plugin does not add `/` at the end of localization homepage like `https://www.example.com/es` and the Wordpress fires 301 redirect. It should be `https://www.example.com/es/`. 

Try the function `home_url()` by yourself in your dev installation.

**Comment by Chouby** [comment]
- Install a multisite (with sites in folders).
- Create a second site
- Install your "superstandard" theme on the second site.
- Check that the home url is `yourmultisite.com/site2` which is also redirected to `yourmultisite.com/site2/`

You would reproduce the same with a single site installed in a subfolder. The home would be `yoursite.com/subfolder` redirected to `yoursite.com/subfolder/`

We follow the same practice as WP. We add a trailing slash when WP does it and we don't add one when WP does not.
To have a trailing slash, you must use `home_url( '/' )` as WP generally does. See for example https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-content/themes/twentyeleven/header.php#L81
