### ISSUE TITLE
polylang breaks the canonical link in <head>

### ISSUE THREAD

**Issue by AlexisWilke** [polylang/polylang#149]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang
2. Go to a page other than the home page
3. Search for the `<link rel="canonical" ...>`, it shows %pagename% instead of the URL

## Expected behavior and actual behavior

My page shows `<link rel="canonical" href="https://diverserealty.team/%pagename%/" />` when I was expecting the page URL, for example `<link rel="canonical" href="https://diverserealty.team/contact/" />

The problem comes from your caching of the URL when `_get_page_link()` is called. The link CAN CHANGE, it is not immutable because the `get_permalink()` function has a parameter called `$leavename` which at times is `TRUE` and at times it is `FALSE`. When `TRUE`, we get the `%pagename%` and when `FALSE`, we get the full page URL. You do not get that `$leavename` parameter in the filter, so no luck on your end on that one.

Removing the `_get_page_link()` function (shown here) from `wp-content/plugins/polylang/frontend/frontend-filters-links.php` helps for some pages, but not all. I think it still fails for translated pages so you must have another cache somewhere else...

        public function _get_page_link( $link, $post_id ) {
                $cache_key = 'post:' . $post_id;
                if ( false === $_link = $this->cache->get( $cache_key ) ) {
                        $_link = parent::_get_page_link( $link, $post_id );
                        $this->cache->set( $cache_key, $_link );
                }
                return $_link;
        }

For now, my website won't use your plugin since it is way worse to not have any of my canonical than having a few pages translated.

**Comment by AlexisWilke** [comment]
Argh... turning your stuff off creates other problems. So I'm keeping it on and to avoid the canonical problem I am commenting out two lines:

            if ( $this->options['force_lang'] ) {
                    //add_filter( 'post_link', array( $this, 'post_type_link' ), 20, 2 );
                    //add_filter( '_get_page_link', array( $this, '_get_page_link' ), 20, 2 );
            }

That way I have the canonical links working "mostly as expected". The language is missing from links, but that's a small loss. So both of those `add_filter()` calls create the problems. It could also be affecting other links, not just the canonical links.

**Comment by Chouby** [comment]
I understand the issue. However it surprises me. As far as I know, the `$leavename` parameter is used in only one place on admin, to output the sample permalink.  What could be the usecase fro this parameter on frontend?

**Comment by AlexisWilke** [comment]
I'm not sure, when I tracked the calls I could see that the very first call sets `$leavename` to true... either way, if you cache such a value, you're always going to take a chance at returning the wrong value.

**Comment by Chouby** [comment]
Did you identify the conflicting plugin or theme?

**Comment by AlexisWilke** [comment]
There is a basic stack track that shows that the `get_sample_permalink()` function gets called.

    [function] => get_page_link
    [function] => get_permalink
    [function] => get_sample_permalink
    [function] => custom_permalinks_original_page_link
    [function] => custom_permalinks_redirect
    [function] => apply_filters
    [function] => _wp_admin_bar_init
    [function] => twentyseventeen_content_width
    [function] => Array
    [function] => Array
    [function] => custom_permalinks_redirect
    [function] => Array
    [function] => redirect_canonical
    [function] => Array
    [function] => rest_output_link_header
    [function] => wp_shortlink_header
    [function] => wpcf7_cleanup_upload_files
    [function] => wpcf7_cleanup_captcha_files
    [function] => wp_redirect_admin_locations
    [function] => do_action
    [function] => _wp_admin_bar_init
    [function] => twentyseventeen_content_width
    [function] => Array
    [function] => Array
    [function] => custom_permalinks_redirect
    [function] => Array
    [function] => redirect_canonical
    [function] => Array
    [function] => rest_output_link_header
    [function] => wp_shortlink_header
    [function] => wpcf7_cleanup_upload_files
    [function] => wpcf7_cleanup_captcha_files
    [function] => wp_redirect_admin_locations
    [function] => do_action
    [function] => require_once
    [function] => require

The sample link function has these two lines. The first call clearly shows that the $leavename gets set to true.

        # from wp-admin/includes/post.php
        $permalink = get_permalink($post, true);

        // Replace custom post_type Token with generic pagename token for ease of use.
        $permalink = str_replace("%$post->post_type%", '%pagename%', $permalink);

So I'm using the default theme (with different pictures, though) and it looks like that could be the culprit...

Note that does not change much of anything, you still need to completely remove your caching mechanism. Now I suppose you were asking so you can reproduce the problem on your end and see that your fix works... You can just force an early (would need to be first) call to `get_permalink()` with `true` as the second parameter and you should get the problem.

**Comment by Chouby** [comment]
That seems to be a conflict with the plugin 'Custom Permalinks'. There are several other conflicts with this plugin. See: #139

**Comment by AlexisWilke** [comment]
Then you've got a plugin to test with. Great!

The fact is your code is wrong if it caches links, because of that one `$leavename` parameter. If you do not like it, that's a core issue and they would have to fix core... It may be difficult to get them to do that, at least for a while.

On your end, all you have to do is remove all caching capabilities for links. You need to recompute links each time, whatever the cost.

**Comment by Chouby** [comment]
Fixed in e4f2deb29266cef6835af8873b0f8fee1d70b669

**Comment by AlexisWilke** [comment]
Not fixed for me, since you did not remove your caching...

**Comment by Chouby** [comment]
The filter `_get_page_link` does not pass `$leavename`. See https://github.com/WordPress/WordPress/blob/4.8/wp-includes/link-template.php#L378

Since this parameter basically controls whether to replace `%pagename%` in the url or not ( see https://github.com/WordPress/WordPress/blob/4.8/wp-includes/link-template.php#L360-L362 ), it should be equivalent to test `$leavename` or the presence of `%pagename%` in the url. 

I checked for the initial conflict with Custom permalinks and it works for me now.

**Comment by AlexisWilke** [comment]
Okay! I upgraded  to the latest (v2.2.1) and I am here to report that it works as expected. The problem is gone even on pages other than the home with the original version of Polylang.
