### ISSUE TITLE
Polylang translation not saving

### ISSUE THREAD

**Issue by ukrolelo** [polylang/polylang#1499]
## Prerequisites

- [X ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X ] This bug happens with only Polylang plugin active
- [ X] This bug happens with a default WordPress theme active
- [X ] I can reproduce this bug consistently

## Steps to reproduce the issue

1.Update wordpress 6.3.4 to 6.5.4
2.Update Polylang 3.1.4 to Version 3.6.3
3.go to languages translations
4.Try change some translation,click save, it says Translations updated. but it will revert instantly on what it was before

## Expected behavior and actual behavior

Just working like before update... Now 4 languages on 4 domains shows one language... D:

**function.php**
pll_register_string('content_news_more', 'Читати далі','Блог');

**index.php**
?=pll__('Читати далі')?

**Comment by Dave365CH** [comment]
i have the same issue with an link. Its always chaning back to the old one..
