### ISSUE TITLE
Wrong update of _transient_pll_languages_list

### ISSUE THREAD

**Issue by nicolasp9-dev** [polylang/polylang#1509]
## General configuration

Bitnani/wordpress install on kubernetes, the bug occurs with either one or multiple wordpress pods deployed. Only a single common DB is used, the bug have been observed in a non-maintenance mode. The bug seems to occurs with a certain probability, it occurs more often with more pods. It does not seem to occur after a modification is done on a page.

## Expected behavior and actual behavior
After some time, in the DB, the value of _transient_pll_languages_list starts using the local IP of a pod instead of the site URL:
http://172.16.254.235:8080 instead of https://www.property-360.app.

I get:
`
a:2:{i:0;a:22:{s:4:"name";s:2:"EN";s:4:"slug";s:2:"en";s:10:"term_group";i:0;s:7:"term_id";i:13;s:6:"locale";s:5:"en_US";s:6:"is_rtl";i:0;s:3:"w3c";s:5:"en-US";s:8:"facebook";s:5:"en_US";s:8:"home_url";s:27:"http://172.16.254.235:8080/";s:10:"search_url";s:27:"http://172.16.254.235:8080/";s:4:"host";N;s:13:"page_on_front";i:991;s:14:"page_for_posts";i:0;s:9:"flag_code";s:2:"us";s:8:"flag_url";s:67:"http://172.16.254.235:8080/wp-content/plugins/polylang/flags/us.png";s:4:"flag";s:571:"<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAmVBMVEViZsViZMJiYrf9gnL8eWrlYkjgYkjZYkj8/PujwPybvPz4+PetraBEgfo+fvo3efkydfkqcvj8Y2T8UlL8Q0P8MzP9k4Hz8/Lu7u4DdPj9/VrKysI9fPoDc/EAZ7z7IiLHYkjp6ekCcOTk5OIASbfY/v21takAJrT5Dg6sYkjc3Nn94t2RkYD+y8KeYkjs/v7l5fz0dF22YkjWvcOLAAAAgElEQVR4AR2KNULFQBgGZ5J13KGGKvc/Cw1uPe62eb9+Jr1EUBFHSgxxjP2Eca6AfUSfVlUfBvm1Ui1bqafctqMndNkXpb01h5TLx4b6TIXgwOCHfjv+/Pz+5vPRw7txGWT2h6yO0/GaYltIp5PT1dEpLNPL/SdWjYjAAZtvRPgHJX4Xio+DSrkAAAAASUVORK5CYII=" alt="EN" width="16" height="11" style="width: 16px; height: 11px;" />";s:15:"custom_flag_url";s:56:"http://172.16.254.235:8080/wp-content/polylang/en_US.svg";s:11:"custom_flag";s:53:"<img src="/wp-content/polylang/en_US.svg" alt="EN" />";s:6:"active";b:1;s:9:"fallbacks";a:0:{}s:10:"is_default";b:1;s:10:"term_props";a:2:{s:8:"language";a:3:{s:7:"term_id";i:13;s:16:"term_taxonomy_id";i:13;s:5:"count";i:17;}s:13:"term_language";a:3:{s:7:"term_id";i:14;s:16:"term_taxonomy_id";i:14;s:5:"count";i:4;}}}i:1;a:22:{s:4:"name";s:2:"FR";s:4:"slug";s:2:"fr";s:10:"term_group";i:0;s:7:"term_id";i:16;s:6:"locale";s:5:"fr_FR";s:6:"is_rtl";i:0;s:3:"w3c";s:5:"fr-FR";s:8:"facebook";s:5:"fr_FR";s:8:"home_url";s:30:"http://172.16.254.235:8080/fr/";s:10:"search_url";s:30:"http://172.16.254.235:8080/fr/";s:4:"host";N;s:13:"page_on_front";i:2073;s:14:"page_for_posts";i:0;s:9:"flag_code";s:2:"fr";s:8:"flag_url";s:67:"http://172.16.254.235:8080/wp-content/plugins/polylang/flags/fr.png";s:4:"flag";s:467:"<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAbFBMVEVzldTg4ODS0tLxDwDtAwDjAADD0uz39/fy8vL3k4nzgna4yOixwuXu7u7s6+zn5+fyd2rvcGPtZljYAABrjNCpvOHrWkxegsqfs93NAADpUUFRd8THAABBa7wnVbERRKa8vLyxsLCoqKigoKClCvcsAAAAXklEQVR4AS3JxUEAQQAEwZo13Mk/R9w5/7UERJCIGIgj5qfRJZEpPyNfCgJTjMR1eRRnJiExFJz5Mf1PokWr/UztIjRGQ3V486u0HO55m634U6dMcf0RNPfkVCTvKjO16xHA8miowAAAAABJRU5ErkJggg==" alt="FR" width="16" height="11" style="width: 16px; height: 11px;" />";s:15:"custom_flag_url";s:56:"http://172.16.254.235:8080/wp-content/polylang/fr_FR.svg";s:11:"custom_flag";s:53:"<img src="/wp-content/polylang/fr_FR.svg" alt="FR" />";s:6:"active";b:1;s:9:"fallbacks";a:0:{}s:10:"is_default";b:0;s:10:"term_props";a:2:{s:8:"language";a:3:{s:7:"term_id";i:16;s:16:"term_taxonomy_id";i:16;s:5:"count";i:9;}s:13:"term_language";a:3:{s:7:"term_id";i:17;s:16:"term_taxonomy_id";i:17;s:5:"count";i:1;}}}}
`
while I expect:
`
a:2:{i:0;a:22:{s:4:"name";s:2:"EN";s:4:"slug";s:2:"en";s:10:"term_group";i:0;s:7:"term_id";i:13;s:6:"locale";s:5:"en_US";s:6:"is_rtl";i:0;s:3:"w3c";s:5:"en-US";s:8:"facebook";s:5:"en_US";s:8:"home_url";s:27:"https://www.property-360.app/";s:10:"search_url";s:27:"https://www.property-360.app/";s:4:"host";N;s:13:"page_on_front";i:991;s:14:"page_for_posts";i:0;s:9:"flag_code";s:2:"us";s:8:"flag_url";s:67:"https://www.property-360.app/wp-content/plugins/polylang/flags/us.png";s:4:"flag";s:571:"<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAmVBMVEViZsViZMJiYrf9gnL8eWrlYkjgYkjZYkj8/PujwPybvPz4+PetraBEgfo+fvo3efkydfkqcvj8Y2T8UlL8Q0P8MzP9k4Hz8/Lu7u4DdPj9/VrKysI9fPoDc/EAZ7z7IiLHYkjp6ekCcOTk5OIASbfY/v21takAJrT5Dg6sYkjc3Nn94t2RkYD+y8KeYkjs/v7l5fz0dF22YkjWvcOLAAAAgElEQVR4AR2KNULFQBgGZ5J13KGGKvc/Cw1uPe62eb9+Jr1EUBFHSgxxjP2Eca6AfUSfVlUfBvm1Ui1bqafctqMndNkXpb01h5TLx4b6TIXgwOCHfjv+/Pz+5vPRw7txGWT2h6yO0/GaYltIp5PT1dEpLNPL/SdWjYjAAZtvRPgHJX4Xio+DSrkAAAAASUVORK5CYII=" alt="EN" width="16" height="11" style="width: 16px; height: 11px;" />";s:15:"custom_flag_url";s:56:"https://www.property-360.app/wp-content/polylang/en_US.svg";s:11:"custom_flag";s:53:"<img src="/wp-content/polylang/en_US.svg" alt="EN" />";s:6:"active";b:1;s:9:"fallbacks";a:0:{}s:10:"is_default";b:1;s:10:"term_props";a:2:{s:8:"language";a:3:{s:7:"term_id";i:13;s:16:"term_taxonomy_id";i:13;s:5:"count";i:17;}s:13:"term_language";a:3:{s:7:"term_id";i:14;s:16:"term_taxonomy_id";i:14;s:5:"count";i:4;}}}i:1;a:22:{s:4:"name";s:2:"FR";s:4:"slug";s:2:"fr";s:10:"term_group";i:0;s:7:"term_id";i:16;s:6:"locale";s:5:"fr_FR";s:6:"is_rtl";i:0;s:3:"w3c";s:5:"fr-FR";s:8:"facebook";s:5:"fr_FR";s:8:"home_url";s:30:"https://www.property-360.app/fr/";s:10:"search_url";s:30:"https://www.property-360.app/fr/";s:4:"host";N;s:13:"page_on_front";i:2073;s:14:"page_for_posts";i:0;s:9:"flag_code";s:2:"fr";s:8:"flag_url";s:67:"https://www.property-360.app/wp-content/plugins/polylang/flags/fr.png";s:4:"flag";s:467:"<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAbFBMVEVzldTg4ODS0tLxDwDtAwDjAADD0uz39/fy8vL3k4nzgna4yOixwuXu7u7s6+zn5+fyd2rvcGPtZljYAABrjNCpvOHrWkxegsqfs93NAADpUUFRd8THAABBa7wnVbERRKa8vLyxsLCoqKigoKClCvcsAAAAXklEQVR4AS3JxUEAQQAEwZo13Mk/R9w5/7UERJCIGIgj5qfRJZEpPyNfCgJTjMR1eRRnJiExFJz5Mf1PokWr/UztIjRGQ3V486u0HO55m634U6dMcf0RNPfkVCTvKjO16xHA8miowAAAAABJRU5ErkJggg==" alt="FR" width="16" height="11" style="width: 16px; height: 11px;" />";s:15:"custom_flag_url";s:56:"https://www.property-360.app/wp-content/polylang/fr_FR.svg";s:11:"custom_flag";s:53:"<img src="/wp-content/polylang/fr_FR.svg" alt="FR" />";s:6:"active";b:1;s:9:"fallbacks";a:0:{}s:10:"is_default";b:0;s:10:"term_props";a:2:{s:8:"language";a:3:{s:7:"term_id";i:16;s:16:"term_taxonomy_id";i:16;s:5:"count";i:9;}s:13:"term_language";a:3:{s:7:"term_id";i:17;s:16:"term_taxonomy_id";i:17;s:5:"count";i:1;}}}}
`

Is this bug known? Can it be due to issue communicating with the DB during some automated tasks?

**Comment by sabithahmd** [comment]
@nicolasp9-dev This behavior is normal when multiple urls are used to access the same website. When polylang set the transient cache, whatever url is used at that time will be cached. If you are facing any issue due to incorrectly cached urls in the website, you can either

disable the language cache by setting

`define( 'PLL_CACHE_LANGUAGES', false );`

or

disable home url cache only by

`define( 'PLL_CACHE_HOME_URL', false );`

in wp-config

**Comment by nicolasp9-dev** [comment]
Perfect, for now I put that setup into production and it seems that the issue got fixed. Thanks a lot!
