### ISSUE TITLE
WPML constants undefined on backend

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#151]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set user language to en_US (always available)
2. Add sites languages: ignore en_US, use en_GB instead
3. Watch as `pll_language_defined` action is never fired on backend and [WPML constants](https://github.com/polylang/polylang/blob/master/modules/wpml/wpml-compat.php#L52-L70) are undefined

## Expected behavior and actual behavior

Hi Chouby,

I'm not reporting this strictly as an error, just as something to be aware of, because it's not quite easy to track down and you might have another users with the same issue.

I had a problem with one WPML-aware plugin not being able to pick the right language on backend and it turned out that the `get_language()` call [here](https://github.com/polylang/polylang/blob/master/admin/admin-base.php#L278) failed, because I have en_US as user language, but the site has been using en_GB for English. As a result, WPML constants had never been defined [here](https://github.com/polylang/polylang/blob/master/modules/wpml/wpml-compat.php#L27). Happens with Polylang 2.1.5 and WP 4.7.5.

Cheers,
Česlav

**Comment by chesio** [comment]
Btw. maybe it would be helpful to add admin notice with warning that user had a language set that is not set as site language and this can have unexpected consequences.

**Comment by Chouby** [comment]
Hi,

Would it work as you expect if you add this:
```php
add_action( 'pll_no_language_defined', array( $this, 'define_constants' ) );
```
in PLL_WPML_Compat constructor?

**Comment by chesio** [comment]
Hi,

Sorry it took me a while to get back to you.

Yes, this helps! And the `ICL_LANGUAGE_CODE` constant has the value of whatever language is currently set in admin language switcher, which is great. Although I don't really understand how this is possible, when there is no language defined... 😕

**Comment by Chouby** [comment]
Some time ago, 'pll_language_defined' was fired to load the translations files in the user preferred locale. 'pll_no_language_defined' was fired instead if the preferred locale did not match a Polylang language. But now that WordPress takes care of the preferred locale on admin side, the names of the actions are not as meaningful. They are still useful though, so I kept them as they are.
