### ISSUE TITLE
DeepL and glossaries

### ISSUE THREAD

**Issue by RobbeCl** [polylang/polylang#1510]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

Is there an option to use DeepL with DeepL glossaries (https://developers.deepl.com/docs/api-reference/translate)?

**Comment by Chouby** [comment]
The short answer is no. 

The longer answer is that to support this, we need to develop our own interface as from https://developers.deepl.com/docs/api-reference/glossaries
>Glossaries created via the DeepL API are distinct from glossaries created via the DeepL website and DeepL apps. This means API glossaries cannot be used on the website and vice versa.

For such questions, I invite you to contact the support in the future. You'll get a much faster answer. https://polylang.pro/support/
