### ISSUE TITLE
Conflict with AffiliateWP, infinite redirection loop

### ISSUE THREAD

**Issue by hogash** [polylang/polylang#1519]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and use AffiliateWP;
2. Visit the site with www.website.com/ref/999 (where 999 is the affiliate ID). It only happens on the homepage.
3. Causes an infinite redirect loop.

## Expected behavior and actual behavior

From my findings, the problem comes from the `redirect_canonical` method in `PLL_Frontend_Static_Pages` ([link to code](https://github.com/polylang/polylang/blob/6ea50473685c8ff9b29501b36c995021f23b2d6d/frontend/frontend-static-pages.php#L79)), more exactly the `$this->links->get_home_url()` which is returned by `$url`. 

Replacing `$this->links->get_home_url()` with `$redirect_url` solves the problem.

This conflicts with AffiliateWP's filter added on `wp_redirect`from wp-content/plugins/affiliate-wp/includes/class-tracking.php ex:

```
add_filter( 'wp_redirect', array( $this, 'redirect_with_referral_link' ), 100, 2 );


/**
 * Appends the referral variable and value after a redirect.
 *
 * @since 2.3
 *
 * @param string $location The redirect path.
 * @param int    $status   The status code.
 *
 * @return string The path to redirect to.
 */
public function redirect_with_referral_link( $location, $status ) {

	if ( is_admin() ) {
		return $location;
	}

	// Get the referral variable being used in AffiliateWP.
	$referral_var = $this->get_referral_var();

	// Bail early if the location already has the referral var set.
	if ( false !== strpos( $location, '/' . $referral_var . '/' ) ) {
		return $location;
	}

	$path = ! empty( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '';

	if ( false !== strpos( $path,  '/' . $referral_var . '/' ) ) {

		$pieces = explode( '/', str_replace( '?', '/', $path ) );
		$key    = array_search( $referral_var, $pieces );

		$pieces[ $key + 1 ] = strtolower( sanitize_user( $pieces[ $key + 1 ] ) );

		if ( $key ) {

			$key          += 1;
			$affiliate_id = isset( $pieces[ $key ] ) ? $pieces[ $key ] : false;

			// Append the referral variable and value to the URL after the redirect.
			$processed_location =  trailingslashit( strtok( $location, '?' ) );
			$processed_location .= trailingslashit( $referral_var );
			$processed_location .= trailingslashit( $affiliate_id );

			// If the location has a querystring, append that to the URL.
			$querystring_position = strpos( $location, '?' );
			if ( false !== $querystring_position ) {
				$processed_location .= substr( $location, $querystring_position );
			}

			$location = $processed_location;
		}

	} elseif ( isset( $_GET[ $referral_var ] ) ) {

		// Append the referral variable and value to the URL after the redirect.
		$location = add_query_arg( $referral_var, $_GET[ $referral_var ], $location );

	}

	return $location;
}
```

**Comment by Chouby** [comment]
1. I don't know Affiliate WP. What should I do starting from a fresh install to reproduce the issue?
2. There is something I don't understand in your analysis. In the function you are pointing too, we explicitly check that we are on a static front page for the given current language. Do we pass this test on http://www.website.com/ref/999 ?
