### ISSUE TITLE
Get all languages cpt posts on frontend. Search query.

### ISSUE THREAD

**Issue by orest22** [polylang/polylang#152]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create two languages
2. Set option that default language has slug also
3. Use pre_get_posts to `unset($query->query_vars['lang']);` or `$query->set( 'lang', '' );`

## Expected behavior and actual behavior

When I follow those steps, I see:
```SELECT   wp_posts.* FROM wp_posts  INNER JOIN wp_term_relationships AS pll_tr ON pll_tr.object_id = wp_posts.ID WHERE 1=1  AND (((wp_posts.post_title LIKE '%Health%') OR (wp_posts.post_excerpt LIKE '%Health%') OR (wp_posts.post_content LIKE '%Health%')) AND ((wp_posts.post_title LIKE '%Concierge%') OR (wp_posts.post_excerpt LIKE '%Concierge%') OR (wp_posts.post_content LIKE '%Concierge%')))  AND (wp_posts.post_password = '')  AND wp_posts.post_type = 'blog' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'acf-disabled') AND pll_tr.term_taxonomy_id IN ( 2 )  ORDER BY (CASE WHEN wp_posts.post_title LIKE '%Health Concierge%' THEN 1 WHEN wp_posts.post_title LIKE '%Health%' AND wp_posts.post_title LIKE '%Concierge%' THEN 2 WHEN wp_posts.post_title LIKE '%Health%' OR wp_posts.post_title LIKE '%Concierge%' THEN 3 WHEN wp_posts.post_excerpt LIKE '%Health Concierge%' THEN 4 WHEN wp_posts.post_content LIKE '%Health Concierge%' THEN 5 ELSE 6 END), wp_posts.post_date DESC ```

I was expecting:
Query without polylang where clause.

Any suggestions how I can remove it?

**Comment by chesio** [comment]
I seem to have the same problem. I'm trying to get 404 pages in [all languages](https://polylang.wordpress.com/documentation/documentation-for-developers/general/#all):
```php
$query = ['pagename' => '404', 'post_type' => 'page'];
if (function_exists('pll_current_language')) {
    $query['lang'] = '';
}
$posts = get_posts($query);
```

Unfortunately, `$posts` has always only one item, other languages seem to be ignored.

When I activate `SAVE_QUERIES`, I see the following query being executed:
```sql
SELECT ID, post_name, post_parent, post_type FROM maco_wp_posts
INNER JOIN maco_wp_term_relationships AS pll_tr ON pll_tr.object_id = maco_wp_posts.ID AND pll_tr.term_taxonomy_id IN ( 36 )
WHERE post_name IN ('404') AND post_type IN ('page','attachment')
```

Removing the `INNER JOIN [...] pll_tr.term_taxonomy_id IN ( 36 )` part makes the query return desired results.

**Comment by Chouby** [comment]
The step 3 is wrong.
1. Polylang uses the action `parse_query` which is fired before `pre_get_posts` so `$query->set( 'lang', '' );` can't work. 
2. Polylang does not use the 'lang' query var to filter the query but a tax_query, so `unset($query->query_vars['lang']);` is inefficient in `pre_get_posts`

I suggest that you use `$query->set( 'lang', '' );` in a function hooked to `parse_query` with priority 1.
