### ISSUE TITLE
Limit on taxonomies / terms? Term translation not appearing linked to source

### ISSUE THREAD

**Issue by ac23** [polylang/polylang#153]
## Steps to reproduce the issue

1. Attempt to create taxonomy term translation
2. Save
3. Review list (see below)

The above is occurring on the latest pro version & the beta of 2.2

## Expected behavior and actual behavior

I've run into a weird issue where I have one taxonomy where the language variations of each term are not linked. The are added fine, but in the UI they appear as separate items (i.e., viewing english only shows + signs for each as if no translation is created, but if you view a particular language they appear in the list while also showing as not linked to any other items).

I'm using lingotek for some pieces of content, so I thought maybe something got screwed up with this particular taxonomy. So i went ahead and created a new tax, enabled translation for it, set english as the default...and same results. None of the variations appear to stick. I currently have 16 registered taxonomies -- some are loaded with (many) terms, others aren't. This particular one had 8 terms. The (new test) tax had 1 term when I attempted to add the variations.

I'm at a loss for what this could be.

Note that I dumped all the content on a dev server and tried there as well (with this now being the 1st translated tax in this instance) and it worked fine in this scenario as well. This is why I seem to think it has to do with the number of taxonomies(?) as I have no idea what else it could be.

**Comment by Chouby** [comment]
There is no limit neither on the number of registered taxonomies, nor on the number of terms (I hace seen sites with thousands of terms). 

I suggest that you make a test with only Twenty Seventeen + Polylang and you register your taxonomies manually to see if the issue is still there.

**Comment by ac23** [comment]
Hi @Chouby -- seems the issue has resolved and/or disappeared somehow. I couldn't replicate it (even in a dev environment with all the same plugins activated it worked fine). Maybe a specific DB issue of some kind on my end.
