### ISSUE TITLE
ACF page type == front page condition

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#154]
Polylang translates `page_on_front` but only on the frontend.

https://support.advancedcustomfields.com/forums/topic/polylang-location-front-page/

Please advise.

This is my hack, a MU plugin.

```php
class ACF_Page_Type_Polylang {

    // Whether we hooked page_on_front
    private $filtered = false;

    public function __construct() {

        add_filter( 'acf/location/rule_match/page_type', array( $this, 'hook_page_on_front' ) );
    }

    public function hook_page_on_front( $match ) {

        if ( ! $this->filtered ) {
            add_filter( 'option_page_on_front', array( $this, 'translate_page_on_front' ) );
            // Prevent second hooking
            $this->filtered = true;
        }

        return $match;
    }

    public function translate_page_on_front( $value ) {

        if ( function_exists( 'pll_get_post' ) ) {
            $value = pll_get_post( $value );
        }

        return $value;
    }
}

new ACF_Page_Type_Polylang();
```

**Comment by Chouby** [comment]
The functionnality is implemented in Polylang Pro, as part of the integration with ACF Pro. So I don't want to publish the corresponding code here. However I can confirm that I am using the filter `acf/location/rule_match/page_type` too, even if the code is completely different. 

What type of advice were you looking for?

**Comment by szepeviktor** [comment]
> However I can confirm that I am using the filter acf/location/rule_match/page_type too

Thank you. That is all.

Please consider listing plugin integrations on the product page https://polylang.pro/downloads/polylang-pro/
Thanks.
