### ISSUE TITLE
Site Title Block issues

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#1540]
There are few issues with Site Title block:

1. Language slug have no slash at the end;
2. On Gutenberg 19.2 there are no language slug at all.

**Comment by Chouby** [comment]
Hello,
Could please be more precise? I don't understand.

**Comment by EldarAgalarov** [comment]
@Chouby I'm using block theme that uses [Site Title block](https://wordpress.org/documentation/article/site-title-block/) in header area. When I click on the site title, I expect to redirect to home page of the actual language, i.e. to language subdir. This works on WP 6.6, but url have no backslash at the end (normally, all urls in WP ends with backslash). Using Gutenberg plugin 19.2 (newest Gutenberg features that will be merged into WP 6.7) it redirects only to root domain (no redirect to the lang subdir).

Example. URL on click on Site Title block with make title link to home option enabled.

WP 6.6:
Expected: site.com/en/
Actual: site.com/en

Gutenberg 19.2:
Expected: site.com/en/
Actual: site.com

**Comment by Chouby** [comment]
I found out that the issue is coming from WordPress (in fact Gutenberg). I opened an issue and proposed a PR to fix that. See https://github.com/WordPress/gutenberg/issues/65670
