### ISSUE TITLE
Add Language Switcher Block

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#1541]
Please implement Language Switcher Block in Free version of Polylang. This is essential feature that must be available in free version of Polylang.

By fact, Polylang Free is NOT compatible with Wordpress bundle that comes with Block themes. It's impossible to use Polylang Free with any Block theme.

**Comment by Chouby** [comment]
You can use a classic widget. We have even created a plugin for that: https://wordpress.org/plugins/fse-classic/
