### ISSUE TITLE
Translation of Custom Post Type (Footer/Layouts) does not load on the translated site. 

### ISSUE THREAD

**Issue by francofx2** [polylang/polylang#1545]
## Prerequisites

- [ x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x ] This bug happens with only Polylang plugin active
- [x ] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Polylang 3.6.4
2. I have a premium theme enabled, which introduces a Custom Post Type named "Layouts". (**Capture 1**)
3. Go to Wordpress Dashboard sidebar > Languages > Settings > Custom Post types and Taxonomies 
4. Check the "Layouts (cpt_layouts)" checkbox > Save changes. (**Capture 2**)
5. Now the layouts can be translated. I'm translating the Footer Layouts from Italian (id: 1063) to English (/en, id: 17579). (**Capture 3**)
6. Nonetheless, the translations of the this element do not show up when loading the localized version of the website, the italian version persists (when looking at the HTML, I can verify it loads the element wth ID:1603)

## Expected behavior and actual behavior

If I load the english version of the site, I would expect the English version of the footer to load. 

## Outstanding question
Am I missing something when dealing with Custom Post Types and having them to load on a translated website? What do you recommend for troubleshooting this behaviour? Can't test on a base WP theme as it does not have the layout CPT. 

<img width="1426" alt="CAPTURE #1" src="https://github.com/user-attachments/assets/32ef38d3-21df-4fba-bfe2-457ed876c729">
<img width="1178" alt="CAPTURE #2" src="https://github.com/user-attachments/assets/a3aaba0f-c443-4aec-ac4a-a6bd4ba16a7c">
<img width="1504" alt="CAPTURE #3" src="https://github.com/user-attachments/assets/83e9d6f7-a76b-4a24-b9ad-488f00a30f4b">

**Comment by Chouby** [comment]
>I have a premium theme enabled, which introduces a Custom Post Type named "Layouts"

There is no way for us to reproduce this issue with a default theme. So it's more a support issue specific to your setup (compatibility issue) than a bug.
