### ISSUE TITLE
home_url() is not transformed to the current language, and the URL parameter "lang" is not interpreted

### ISSUE THREAD

**Issue by yoancutillas** [polylang/polylang#1549]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x ] This bug happens with only Polylang plugin active
- [x ] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. You can click on the provided URLs
2. To reproduce on dev enriveronment, you can use this code on the backend to display the incorrect URL: `echo add_query_arg( array( 'lang' => 'fr' ), home_url() );`

## Expected behavior and actual behavior

Hello, I am the author of the Booking Activities plugin.
Booking Activities is compatible with WPML, and therefore with Polylang via your WPML compatibility API.

A customer reported a problem to me: 
When generating a URL from the backend with home_url(), it is not transformed according to the current language.
In addition, if you add the `lang` parameter in the URL, the page is displayed in English even if the French URL is correct.

Does not work (not translated): 
- https://closdescoustoulins.com/?action=bapap_booking_pass_pdf_voucher&key=a1a823f19d55ceef57ebb834a5bec5c1&booking_pass_id=22&lang=fr
- https://closdescoustoulins.com/fr/?action=bapap_booking_pass_pdf_voucher&key=a1a823f19d55ceef57ebb834a5bec5c1&booking_pass_id=22&lang=fr 

Works (well translated): 
- https://closdescoustoulins.com/fr/?action=bapap_booking_pass_pdf_voucher&key=a1a823f19d55ceef57ebb834a5bec5c1&booking_pass_id=22 

The customer told me that the URL used to worked correctly in June (she probably updated Polylang, but I can't say from which version).
For my part, I tested with WPML, the three URLs work indeed.

So I thought the "lang" URL parameter being not correctly interpreted would be a Polylang bug, or at least, at a bug at the WPML compatibility API level.

Kind regards, Yoan Cutillas

**Comment by sebastienserre** [comment]
Hello,

Thank you for reaching out to us.
I'm not sure to understand your issue. Trying this little snippet:
```
add_action( 'wp_body_open', 'pll_function_test' );
add_action( 'admin_init', 'pll_function_test' );
function pll_function_test(  ) {
	echo add_query_arg( array( 'lang' => 'fr' ), home_url() );
}
```
And the result on my test website is https://helpdesk-polylang.lndo.site?lang=fr both on admin and front.

Would you please contact me through our official support page at https://polylang.pro/support with this issue in the description to not lose the history?
We'll find how to help you.
