### ISSUE TITLE
No "product" search results

### ISSUE THREAD

**Issue by amrod1** [polylang/polylang#155]
Polylang somehow disables search results of woocommerce products or other special **post_types**.
When I disable Polylang search results come back.

Test theme is twenty seventeen which is using  get_search_form() 

This is a very serious problem since **no search results** returns in an e-commerce website.

**Comment by Chouby** [comment]
I don't reproduce the issue. 

Test made with WooCommerce 3.1.1 + Polylang 2.1.6. Without Polylang for WooCommerce, I activated the translation for products in Languages > Settings > Custom post types and Taxonomies. The search is filtered by the current language as expected.
