### ISSUE TITLE
ACF taxonomy fields not synced

### ISSUE THREAD

**Issue by timhuisman** [polylang/polylang#156]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

0. Install Polylang Pro 2.1.6 (or Polylang Pro 2.2-beta1) and ACF5 Pro 5.5.3
1. Add a non-translatable taxonomy and one or more terms
2. Add a translatable post type
3. Add a ACF taxonomy field to this post type referencing the taxonomy
4. Create a post of this post type and select a term within the taxonomy field
5. Add a translation for this post

## Expected behavior and actual behavior

When I follow those steps, I see...

That the taxonomy field within the translation is empty and the following warning is given: `Warning: Invalid argument supplied for foreach() in <path-to-plugin>/polylang-pro/modules/plugins/acf.php on line 221` (Line 221 in v2.2-beta1 and Line 218 in v2.1.6). An array with terms is expected here to loop through, but instead the `$value` parameter is the same format as the `$field['return_format']` (an id or object). This causes the warnings on the foreach loop.

Furthermore (only tested in v.2.1.6); after adding a quickfix for the situation above we also noticed that the combination translatable post-type and non-translatable taxonomy doesn't work correctly. It always tries to retrieve the term in the language of the post-type, which isn't available in this case.

Both observation cause the taxonomy field to be empty when adding a translation.

I was expecting...

That the code for the syncing of taxonomy fields looks for the type of `$value` it gets and acts based on this: be it an array, id or object. And that is looks whether the taxonomy is translatable (`pll_is_translated_taxonomy`) and returns the translated term or the original term (when not translatable).

**Comment by Chouby** [comment]
Tanks for the bug report. I just released Polylang Pro 2.2 beta2 (available in your account). It should fix this issue as well as several other issues related to the ACF Pro integration. Let me know if it's ok for you now.

**Comment by timhuisman** [comment]
@Chouby The beta2 release indeed fixes the above mentioned issues. Taxonomy fields are now synced correctly. Thank you!

**Comment by Chouby** [comment]
Thanks for your feedback :)
