### ISSUE TITLE
Polylang not copying or translating new ACF flexible layout or repeater

### ISSUE THREAD

**Issue by epigeyre** [polylang/polylang#1572]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. **Install** Polylang Pro and ACF Pro plugins (latest versions)
2. **Configure** Polylang to have at least **two languages** _(in my example English and French)_
3. **Create a page** in the default language _(ex: English)_ and publish it
4. **Create the translation of the page** in another language _(ex: French)_
5. Add a **Flexible Content** or **Repeater** field to the page
6. **Add a Text field** to the previously created Flexible Content or Repeater field
7. **Set the Text field translation option** to _Copy once_ or _Translate_.
8. **Add some content** to the previously created Text field in your default language (ex: English) in the previously created page and save it
9. **Go to your translated page** _(ex: French)_

## Expected behavior and actual behavior

When I follow these steps I can see that 

- If I've set the translation option of the Text field to _Copy once_ **the field is not created** in my Flexible Content or Repeater field.
- If I've set the translation option of the Text field to _Translate_ the field is created in my Flexible Content or Repeater field but **does not contain any value**.

In both cases I would expect Polylang to create the Text field inside my Flexible Content or Repeater field with the text copied (for the first case) or translated (for the second case) **if the field did not exist before** on the page.

## Screenshots
ACF field group settings
![Screenshot 2024-11-14 at 14-43-09 Edit Field Group “Test” ‹ — WordPress](https://github.com/user-attachments/assets/02a7e968-974b-47dc-98bb-3c698c59e8d6)

Page in English
![Screenshot 2024-11-14 at 14-44-10 Edit Page “This is a test page” ‹ — WordPress](https://github.com/user-attachments/assets/89a5b52e-fa87-474a-be7b-675dc2ad48b4)

Page in French
![Screenshot 2024-11-14 at 14-43-56 Edit Page “Il s’agit d’une page de test” ‹ — WordPress](https://github.com/user-attachments/assets/32c3d2c0-59a0-436c-b1d7-3ccd0832e94e)

**Comment by sebastienserre** [comment]
ACF Pro is maintained in Polylang Pro. I will answer on the issue you opened on our Polylang Pro helpdesk.
