### ISSUE TITLE
Feed Rss broken

### ISSUE THREAD

**Issue by Mte90** [polylang/polylang#159]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Go to https://mte90.net/feed
2. 404

Also if you see the html code of https://mte90.net/ where there is the link of feed rss is empty.

## Expected behavior and actual behavior
Get the feed rss for italian (default language)

Any suggestions for the debug?

**Comment by Chouby** [comment]
Your feed urls changed as they need to be filtered by the language.
They are now located at https://mte90.net/en/feed/ and https://mte90.net/it/feed/

**Comment by Mte90** [comment]
Uh okay but why in the html code of the page there is:
```<link href="" rel="alternate" title=" Feed" type="application/rss+xml">```

**Comment by Mte90** [comment]
Also in my configuration I use https://mte90.net/ita/ and not `it` and for en I use `eng`

**Comment by Chouby** [comment]
1. Mayb your theme does not use standard WordPress functions and thus the link cannot be filtered by Polylang. This works with a default theme (or the Meta widget).
2. 'ita' and 'eng' are the slugs of your home pages. The language codes are 'it' and 'en'. Check the Languages list table.
