### ISSUE TITLE
Content duplication issue with "Media and text"-block, when media is set to right

### ISSUE THREAD

**Issue by luuptekman** [polylang/polylang#1597]
**Describe the bug**
When using "media and text"-block **with media on the right setting** and duplicating content into another language, there will be block validation issues.

**To Reproduce**

Preconditions:
-In polylang Media settings will setting is turned on: `Automatically duplicate media in all languages when uploading a new file.`
- You have added a image to media gallery and it's correctly synched between languages.
- You have at least two languages added to Polylang

1. Go to  pages and create a page including "media and text"-block for the main language. Save and publish the page.
2. In "Media and text"-block, set media position on the right and save the page
3. Click on languages-button in page editor
4. In translations-section activate content duplication
5. Click on the plus sign to add translation to secondary language
6. New post is created, but there is block validation errors in the page

Error is related to img-class. In the duplicated content mediaId is correctly set, but img-class still refers to main language version.

```
{"mediaId":654} ==> id of the secondary language media file
<img class="wp-image-653"> ===> id of the main language media file
```

**!!NOTE!! Error will not happen, when image position is on the left.**

**Expected behavior**
Content is duplicated correctly without issues.

**Environment (please complete the following information):**
This error is reproduced in fresh WP-install with Twentytwentyfour/Twentytwentyfive theme and WP 6.7.1. Polylang Pro version 3.6.5.

**Comment by sebastienserre** [comment]
Hello,
Thank you for having opened an issue on our Polylang pro helpdesk.
We'll manage to help you there.

Regards
