### ISSUE TITLE
[feature request] REST API compatibility?

### ISSUE THREAD

**Issue by wujekbogdan** [polylang/polylang#160]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently
- * [x] This is not a bug, but a feature request :)

---

In order to make Polylang work with requests made via REST API, there is an explicit language declaration needed. So a parameter must be added to the GET request and In order to handle this parameter, a little fix must be applied in PHP - a fix that "tells" Polylang what is the desired language. This is the code I use:

``` php
add_action('rest_api_init', function () {
	$defaultLanguage = pll_default_language();
	$languages = pll_languages_list();
	$requestLanguage = filter_input(INPUT_GET, 'lang', FILTER_SANITIZE_STRING);
	$language = in_array($requestLanguage, $languages) ? $requestLanguage : $defaultLanguage;

	PLL()->curlang = PLL()->model->get_language($language);
});
```

And of course, the `lang` GET parameter is added to each REST API request.

---

It would be good to add this feature to Polylang core or at least to mention this issue in Polylang docs.

PS
I'm not sure if  `PLL()->curlang` is a good way of changing the current language, but I wasn't able to find any public method that does such a thing.

**Comment by Chouby** [comment]
The compatibility with the REST API has been added in Polylang Pro 2.2. The support of the 'lang' parameter to filter the query has of course been added, although I used a different way than yours.

**Comment by wujekbogdan** [comment]
@Chouby 
Is it available in the pro version only?

**Comment by Chouby** [comment]
Yes. It's currently only in the Pro version. But if you only need to filter the content in a certain language, what you did is sufficient.

**Comment by wujekbogdan** [comment]
Yeah, I know it's sufficient, I was just curious is it only a pro version feature. I wanted to makes sure that my solution will not conflict with the solution that exists in the plugin's core.

**Comment by alibasheer** [comment]
Thank you @wujekbogdan, your code helped me.
In my use-case, I set a default language in case it is not sent in the GET request and this was my final code:

	function ba_polylang_support_restapi() {
	    $defaultLanguage = pll_default_language();
	    $languages = pll_languages_list();
	    $getRequestLanguage = filter_input(INPUT_GET, 'lang', FILTER_SANITIZE_STRING);
	    $requestLanguage = ($getRequestLanguage)? $getRequestLanguage : 'en' ;
	    $language = in_array($requestLanguage, $languages) ? $requestLanguage : $defaultLanguage;

	    PLL()->curlang = PLL()->model->get_language($language);
	}
	add_action( 'rest_api_init', 'ba_polylang_support_restapi' );

**Comment by fedegonzal** [comment]
it's broken after today update, version 2.3.2

**Comment by anodine-org** [comment]
Working here. Thank you @wujekbogdan !!! I earn so much time thanks to you!!! I was trying to read how work the REST API and how to hack it.
