### ISSUE TITLE
pll_translate_string bug when the asked language is the active one

### ISSUE THREAD

**Issue by shkup** [polylang/polylang#163]
## Prerequisites
1. Latest version of PolyLang.
2. Create a dummy plugin with a function hooked to the initialize event.  
    Like: add_action( 'init', 'myplugin_initalize' );

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a translation entry like 'My String' (pll_register_string) and translate it to some string in Russian. 
    (Using the UI in the backend)
2. Create a dummy plugin with a function hooked to the initialize event.  
    Like: add_action( 'init', 'myplugin_initalize' );
    function myplugin_initalize() {
	$a1 = pll_translate_string('My String', 'ru');
     }
3. In the backend select the target language which is NOT the default language (For instance English is default, Russian is the active language).
4. Call pll_translate_string with the same active language code (ru in our example).
5. You will see that when the active language is the same as the asked language, The default language translation is returned.

## Expected behavior and actual behavior
When I follow those steps, I get the translated string in the default language, English.
I was expecting to get the translated string in Russian.

**Comment by Chouby** [comment]
The function has originally been written to be used on frontend. Do you confirm that your issue is on backend only?

**Comment by shkup** [comment]
Hi.
No. I create menu items on server side and need to translate their captions.
If you remove the first condition in your function (That the required language is the active one) the function works as expected.
Thanks, Yaron.

??? ?? Outlook ???? Android<https://aka.ms/ghei36>

________________________________

**Comment by Chouby** [comment]
I ended up to test (on frontend and backend) and it works as expected for me.
