### ISSUE TITLE
Is there a known way / better way to make a ACF option page multilingual with Polylang?

### ISSUE THREAD

**Issue by Julianoe** [polylang/polylang#168]
I know about  [this plugin](https://github.com/BeAPI/acf-options-for-polylang) but the way it works makes it not very user friendly. When on said option page on "all languages" the options are not displayed but the fields are. 

I wonder if you the creators of Polylang or users know of any use cases with Polylang + ACF options page and the best optimised way to deal with it.

Thanks in advance guys ;)

**Comment by Chouby** [comment]
I know only this plugin and no other. Problaby a future version of our Pro version will integrate the options but this is not the case today (only posts and terms metas have been integrated at this point).
