### ISSUE TITLE
Polylang 2.2 is showing all differents languages posts on my home 

### ISSUE THREAD

**Issue by DamChtlv** [polylang/polylang#171]
Hi,

Don't know why but it is only happening with 2.2 (i did a rollback to 2.1.6 and it works fine).

Like the title says: if i click on any languages (i have "French" set by default and "English" as secondary), the same post written with differents languages is showing twice (French and English) on Home like if i was on "Show all".

I'm using latest stable wordpress version and all extensions are up-to-date (the website in question: "[f-and-k.fr](https://f-and-k.fr)" in case that helps.)

**Comment by Chouby** [comment]
I don't reproduce. Please follow the steps described in the issue template.
