### ISSUE TITLE
redirect_canonical filter is triggered

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#173]
WP v4.6
Polylang v2.2.1

We have domain based languages: http://www.artmedic.eu/ and http://mutoberles.hu/ (main)

When I visit the .eu front page the `redirect_canonical` filter is triggered *3 times* with these values:
`http://www.artmedic.eu/` -> `http://mutoberles.hu/` then it loads correctly.

I have a [WAF](https://github.com/szepeviktor/wordpress-fail2ban) in place which dislikes this.
@Chouby Please advise.

**Comment by Chouby** [comment]
It's what I expect. The function `redirect_canonical()` is called once by WP and [2 times by Polylang](https://github.com/polylang/polylang/blob/2.2.1/frontend/frontend-filters-links.php#L366-L367), before that. I would need only once but was obliged to call it 2 times to work around a WP bug. It may even be called a 4th time by WP in case a redirect is needed.

**Comment by szepeviktor** [comment]
Thank you.

Now I see that redirect-based threat detection should be disabled on sites with Polylang.

**Comment by Chouby** [comment]
Maybe you can validate the redirect to allow only safe hosts: https://github.com/WordPress/WordPress/blob/4.8.1/wp-includes/pluggable.php#L1316. Polylang uses the filter 'allowed_redirect_hosts' to add all domains assigned to languages.

**Comment by szepeviktor** [comment]
Thank you.

My WAF bans hosts by the aggregated number of `redirect_canonical` filter calls: at 6 / 10 minutes.
It is simple: a human runs into a redirection once or twice in the beginning of a visit,
but a bad robot may ask for incorrect thus redirected URL-s many times.
