### ISSUE TITLE
Polylang is not get translation url for term even if hide_if_empty property is set to false

### ISSUE THREAD

**Issue by ChaDmiS** [polylang/polylang#174]
When using the pll_the_languages function, I set the hide_if_empty property to false. It works fine for the list of languages, but it does not work at all for terms.

Moreover, the get_translation_url method in PLL_Frontend_Links class does not take into account the arguments specified in pll_the_languages function

**Comment by Chouby** [comment]
I don't understand the issue. `pll_the_languages` displays a list of languages, not a list of terms.

`PLL_Frontend_Links::get_translation_url()` is here to evaluate the translation url independantly of the options used in `pll_the_languages`. It is used for example to evalueate hreflang attributes.

**Comment by ChaDmiS** [comment]
Let me describe in more detail what I kept in mind. The procedure for reproducing the problem is as follows:
1. Create a taxonomy with register_taxonomy
2. Add the term in 2 languages, for example English and French
3. Terms are without posts
4. Click "View" in the English term
5. Now `pll_the_languages` ​​shows 2 links. The English reference leads to the current page of the term, the second link refers to the home page, instead of leading to the page of French translation of the term

This is due to the fact that the `get_translation_url` method uses the `get_terms` function without the `hide_empty` property is set to true

I think that this behavior of the plugin is incorrect, because `hide_if_empty` property is in the `pll_the_languages` ​​function, and it should be used not only for posts, but also for terms!

**Comment by Chouby** [comment]
`get_translation_url` does not use `get_terms` to evaluate the link of the translated term however I better understand now. 

This is the expected comportment. The goal is never to link to an empty archive. Note  the comment at https://github.com/polylang/polylang/blob/2.2.1/frontend/frontend-links.php#L104. The term count is explicitely checked at next line before evaluating the url.

If you don't like how it works, it's easy to override this with the filter `pll_translation_url`.

**Comment by ChaDmiS** [comment]
Okay, thanks for the help. I override translation URL like this:
```
function wt_pll_translation_url( $url, $lang ) {
    if( !$url && function_exists( 'pll_get_term' ) && function_exists( 'wpcom_vip_get_term_link' ) ) {
        $term_id = pll_get_term( get_queried_object_id(), $lang );
            if( $term_id ) {
                $url = wpcom_vip_get_term_link( $term_id, get_query_var( 'taxonomy' ) );
            }
        }
    
    return $url;
}
add_filter( 'pll_translation_url', 'wt_pll_translation_url', 10, 2 );
```
Maybe someone will come in handy.

Of course, in the future it would like that the behavior can be determined with the help of the property `hide_if_empty` or similar

**Comment by cfaria** [comment]
```
// Allow polylang redirection to existing terms even if there are empty
add_filter( 'pll_hide_archive_translation_url', '__return_false' );
```
