### ISSUE TITLE
Avoid PHP notice in PLL_Admin_Filters_Post::add_meta_boxes()

### ISSUE THREAD

**Issue by ocean90** [polylang/polylang#175]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install [Members](https://wordpress.org/plugins/members/)
2. Go to /wp-admin/users.php?page=role-new

## Expected behavior and actual behavior

When I follow those steps, I see...

`Notice: Trying to get property of non-object in /plugins/polylang-pro/admin/admin-filters-post.php on line 130`

I was expecting...

No PHP notice.

---

Related issue for the Members plugin: https://github.com/justintadlock/members/issues/131

**Comment by Chouby** [comment]
I tend to agree with https://github.com/justintadlock/members/issues/131. Using an action with the same name as in WordPress but in a different context is likely to create conflicts...
