### ISSUE TITLE
Illegal character in authority at index 7 • organization_id is a required parameter

### ISSUE THREAD

**Issue by oncletom** [polylang/polylang#177]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a new user account 
2. Click on Pages
3. Click on the pencil icon to translate a page in a given language
4. A lingoteck error appears
5. When I refresh the page, no translation appears (but browser DevTools show a bunch of errors)

![screen shot 2017-09-10 at 14 32 56](https://user-images.githubusercontent.com/138627/30249198-6ff35112-9637-11e7-8623-481dc0f3541f.png)

![screen shot 2017-09-10 at 14 51 55](https://user-images.githubusercontent.com/138627/30249205-9bffcede-9637-11e7-8a36-99dfee68c9b4.png)

## Expected behavior and actual behavior

When I follow those steps, I see _an error message_.

I was expecting to see a translation page.

The blog name is `Rédacteurs Techniques Sans Frontières` in French. `Technical Writers Without Borders` in English. I suspect the accented characters might be the source of the problem. So far we have been unable to locate the `wpml-config.xml` file so I am unsure if this is the cause of the issue.

cc @LaureVergeron @sculshaw

**Comment by Chouby** [comment]
According to your screenshots, the issue are related to the Lingotek translation plugin, not to Polylang. Please contact the Lingotek support.

**Comment by oncletom** [comment]
Hi @Chouby,

indeed the bug happens on Lingotek side of things but it happens _via_ the Polylang plugin, when clicking on the `pencil` icon of a page or blog post. Which I believe is a feature provided by Polylang, right?

If I remember well what was shown to me, was that Polylang offers different translation third-party services backends, Lingotek being one of them.

I thought the bug was on the Polylang side of things because the plugin forwards the user/link/translation on Lingotek, and possibly with a malformed information.

I am happy to contact Lingotek but I'd like to be sure this issue has not been overlooked.

Thanks for your time 👍
