### ISSUE TITLE
Issue with pll_translate_string() in WP admin

### ISSUE THREAD

**Issue by donacross** [polylang/polylang#178]
Hello Polylang,

Thank you for your great work. Your plugin is gorgeous. I came across an issue today. I thought it could be useful to log it here. I've found a workaround for now so I'm not in the rush for an answer.

Keep up the good work.

Thank you

## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently
- [x] Pro user

### In WordPress admin
```
// Bug : The string is NOT translated using the 'slug'

$lang = pll_get_post_language( $id, 'slug' ); // "fr"
$translation = pll_translate_string( 'Hot', $lang ); // "Hot"


// Workaround : The string IS translated using the 'locale'

$lang = pll_get_post_language( $id, 'locale' ); // "fr_FR"
$translation = pll_translate_string( 'Hot', $lang ); // "Chaud"
```

### In the theme
Everything is working fine with both 'slug' and 'local'.

## My use case

I'm computing a title for a post A based on an post B language when post B is updated.
My code used to work 4 month ago. From my side, it looks like a regression.

**Comment by Chouby** [comment]
Initially, the function was indeed not intented to be used on admin side. That's why you can get unexpected results: when the second parameter is the current language is fallbacks to `pll__()` which does not translate anything as the translations are loaded only on frontend.

**Comment by donacross** [comment]
Okay. Thank you for your answer.
