### ISSUE TITLE
CPT settings does not show the same as the code

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#180]
I have the following code in my plugin.
```php
add_filter( 'pll_get_post_types', function( $post_types, $is_settings ) {
	if ( $is_settings ) {
		// Hides CPT from the list of CPT in Polylang settings.
	} else {
		// Enables language and translation management for CPT.
		$post_types['ph_artist'] = 'ph_artist';
	}
	return $post_types;
}
```

By when I check the custom post type in the settings it shows as if the post type is not translatable.
![image](https://user-images.githubusercontent.com/1785641/31427124-da5e10e2-ae6e-11e7-82cf-7fc9a0bedbb0.png)

Though when I check if it is a translatable function in the code it returns true. 
`wp eval "var_dump(pll_is_translated_post_type('ph_artist'));"`

The custom post type is also ready to be translated. The checkbox is selected but disabled from being changed.

I think it would be good to have something to this effect.
![image](https://user-images.githubusercontent.com/1785641/31486229-67fa0ffc-af3f-11e7-9ca4-0f113339686f.png)

**Comment by Chouby** [comment]
Hi Ulrich,

Here is the way I use the filter:
```php
add_filter( 'pll_get_post_types', function( $post_types, $is_settings ) {
	if ( $is_settings ) {
		$post_types = array_diff( $post_types, array( 'ph_artist' ) );
	} else {
		// Enables language and translation management for CPT.
		$post_types['ph_artist'] = 'ph_artist';
	}
	return $post_types;
}```
That way the checkbox for Artists does not even appear.

**Comment by Chouby** [comment]
That's easy to achieve, even without modifying the current filters.

However, I fear that it generates a lot fo noise. WooCommerce adds 3 post types and 2 taxonomies + an indefinite number of attributes. Bookings adds 3 more post types. The Events Calendar 3 more. I fear that the list of disabled options become huge on a site with several tenths of plugins.

My initial goal when I decided to allow developers to hide their post types and taxonomies from the settings was to hide the complexity of these plugins to the average users. I fear that adding this infomation will rise more questions from the bginners than it will help the advanced users (I am reasonning here as a support person).

**Comment by grappler** [comment]
Sorry for not getting back to you. I read the comment but forgot to reply.

If we are supposed to hide post types that are programmatically defined as translatable then it would be good to mention that in the documentation.

> However, I fear that it generates a lot fo noise. WooCommerce adds 3 post types and 2 taxonomies + an indefinite number of attributes. Bookings adds 3 more post types. The Events Calendar 3 more. 

I understand and agree that non-public post types should not be added to the settings as discussed in #164. I understand that you may want to do things differently when supporting other plugins but I am thinking from more a custom development perspective.

I find it confusing when I have defined a CPT as translatable in the code and the settings it does not show the same setting. Another option would be to automatically hide that CPT as it does me no good to show it in it's current status. Maybe it would be possible to add extra information on why some are disabled as they are enable in the code of a theme or plugin.

I am not saying show all CPT and Taxonomies but if the CPT or Taxonomy is not hidden but enabled in the code it should be displayed as checked with the selection disabled.  

P.s. I would love for Polylang to have an official WP-CLI support/plugin so that I could easily query the list of CPT and Taxonomies that are translated or not.

**Comment by Chouby** [comment]
What do you think of https://github.com/polylang/polylang/tree/issue_180 ?

The intention is demonstrated with the sample code below:
```php
add_filter( 'pll_get_post_types', function( $post_types, $is_settings ) {
	if ( $is_settings ) {
		$post_types = array_diff( $post_types, array( 'hidden' ) );
		$post_types[] = 'added';
	} else {
		$post_types = array_merge( $post_types, array( 'hidden', 'visible' ) );
	}

	return $post_types;
}, 10, 2 );
```
The post post type 'hidden' will be translatable and not shown in the settings. This is the way I handle the post types in my integrations fo WooCommerce.

The post type 'added' is added to the settings but it's up to the user to decide whether to translate it or not (as I do for the field groups in ACF Pro integration).

The 'visible' post type will be translatable and shown as disabled in the settings. Today private post types are not be shown in the settings while public post types are shown in the settings and the checkbow has no effect. As I understand it's what's disturbing.

**Comment by grappler** [comment]
I can confirm that the branch fixes my problem. Here is a screenshot of one of the sites
![image](https://user-images.githubusercontent.com/1785641/34364844-a07beed4-eaab-11e7-8d4f-a7da92906c05.png)

As I was looking at the change, I was wondering if the number of `apply_filter` call could be reduced. I was able to achieve the same result with the following changes. I only made the changes for CPT and not taxonomies.
```diff
index 2f02d1c..63f1bf7 100644
--- settings/settings-cpt.php
+++ settings/settings-cpt.php
@@ -21,17 +21,17 @@ class PLL_Settings_CPT extends PLL_Settings_Module {
            'description' => __( 'Activate the languages and translations management for the custom post types and taxonomies.', 'polylang' ),
        ) );

-       $post_types = get_post_types( array( 'public' => true, '_builtin' => false ) );
+       $public_custom_post_types = get_post_types( array( 'public' => true, '_builtin' => false ) );
        /** This filter is documented in include/model.php */
-       $active = apply_filters( 'pll_get_post_types', $post_types, true );
-
-       $post_types = array_unique( apply_filters( 'pll_get_post_types', array(), false ) );
+       $progamatically_active_post_types = array_unique( apply_filters( 'pll_get_post_types', array(), false ) );
        /** This filter is documented in include/model.php */
-       $disabled = array_intersect( $post_types, apply_filters( 'pll_get_post_types', $post_types, true ) );
+       $settings_post_types = apply_filters( 'pll_get_post_types', $public_custom_post_types, true );
+
+       $disabled_post_types = array_intersect( $progamatically_active_post_types, $settings_post_types );

        $this->post_types = array_merge(
-           array_fill_keys( array_unique( $active ), 'active' ),
-           array_fill_keys( array_unique( $disabled ), 'disabled' )
+           array_fill_keys( array_unique( $settings_post_types ), 'active' ),
+           array_fill_keys( array_unique( $disabled_post_types ), 'disabled' )
        );

        $taxonomies = get_taxonomies( array( 'public' => true, '_builtin' => false ) );
```

**Comment by Chouby** [comment]
This doesn't produce exactly the same result (for non-public programmatically translated post types), but your solution is better. Thanks!
