### ISSUE TITLE
Fatal error: Uncaught Error: [] operator not supported

### ISSUE THREAD

**Issue by jasperrooduijn** [polylang/polylang#181]
I get this error when using Polylang with Duplicate Post plugin. Using WP 4.8.2 and PHP 7.1. I'm using the latest version of Polylang. It get's triggered by this function PLL_Plugins_Compat->duplicate_post_taxonomies_blacklist( ).

Fatal error: Uncaught Error: [] operator not supported for strings in /Users/jasperrooduijn/Sites/invicta/web/app/plugins/polylang-pro/modules/plugins/plugins-compat.php on line 567

**Comment by chesio** [comment]
I guess this is the reason: http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator

**Comment by jasperrooduijn** [comment]
Jep! Any E.T.A for plugin compatiblity with PHP 71? My solution for now was to switch back tot php70 when using Polylang.

**Comment by Chouby** [comment]
Did you test with the latest master branch?

**Comment by jasperrooduijn** [comment]
No! I tested it with the latest stable version -> 2.2.3

**Comment by Chouby** [comment]
You should. That's one of the reason why I added the issue template which, unfortunately, you did not filled in.
T
o answer to your question about the compatbility with PHP 7.1, this PHP version is continuously checked with Travis CI. But approximately 1/3 of the code is not tested. Especially the compatibility with 3rd party plugins is not tested. That's the reason why I originally missed the issue in the code related to Duplicate Posts.

**Comment by jasperrooduijn** [comment]
Okay understood! I will use the template next time.

**Comment by Chouby** [comment]
And does it work with 2.2.4?

**Comment by jasperrooduijn** [comment]
Yeah! It does. Thanks!
