### ISSUE TITLE
Polylang leads to 404 error!!!

### ISSUE THREAD

**Issue by shangdev** [polylang/polylang#182]
I downloaded the Polylang plugin and used her in one of the subdomain sites

In order to test the featured of this plugin, first I added a new language, and then deleted the added language

Then I found that after I set up permalink, in addition to the index page and the custom post type archive page, all other page access will jump to 404 pages

It made me very embarrassing, I checked the nginx configuration and found that it was not caused by nginx; after I suspended the Polylang plugin, the problem was solved; however, when I reactivated Polylang again, the problem appeared again

I thought it might be a bug…-_-

**Comment by shangdev** [comment]
I found a solution to the problem:

`
add_action( 'init', 'flush_rewrite', 99 );
function flush_rewrite()
{
    flush_rewrite_rules();
}
`

So I think the operation should be performed when deleting the last language,
It does not seem to be present?

**Comment by Chouby** [comment]
I suggest that you never do that. See: https://codex.wordpress.org/Function_Reference/flush_rewrite_rules#Usage

Indeed the rewrite rules are flushed when a language is deleted. I suggest that you first check if you can reproduce the issue with a default theme such as Twenty Seventeen and with no other plugin than Polylang. Then you should look for a conflict with your theme or your other plugins.
