### ISSUE TITLE
Translated term attempts to display translated posts of same language eventhough content type is non-translatable

### ISSUE THREAD

**Issue by d9media** [polylang/polylang#183]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Register content type, attach category taxonomy
2. Create new category - default language is English
3. Create new post (custom post type) - no language

## Expected behavior and actual behavior

When I follow those steps, I see nothing. I am expecting to see the post without specific language.

Proposed solution: 

a) Treat custom post types without language as  "language-neutral" -> display posts of any langaugeas on the language-neutral category archive.
b) Introduce selection "language-neutral" for posts (Drupal does the same thing. Very smart!)  or 
c) Allow posts to have multiple languages.

**Comment by Chouby** [comment]
Did you try to filter the query remove the 'lang' query var?
