### ISSUE TITLE
menus are not translated after updating from 2.2.1 to 2.2.4

### ISSUE THREAD

**Issue by jumika** [polylang/polylang#187]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Update to latest version (2.2.4) of polylang

## Expected behavior and actual behavior

When I follow those steps, I see the menu in the default language even after i change language. (page refreshes)

**Comment by jumika** [comment]
I think It's a bug in Timber plugin's Menu class.

**Comment by Chouby** [comment]
See the topic on nthe forum: https://wordpress.org/support/topic/problem-with-more-than-one-menu-at-the-same-time-polylang-and-timber/

**Comment by jumika** [comment]
My workaround was this:

    $menuLocations = get_nav_menu_locations();
    $context['top_menu'] = new TimberMenu($menuLocations['theme_pos_top']);

I would stay away from modifying plugins which i don't own.

**Comment by Chouby** [comment]
Could you try to replace the function `icl_object_id` [here](https://github.com/polylang/polylang/blob/2.2.4/modules/wpml/wpml-legacy-api.php#L171-L175) by this one:
```php
	function icl_object_id( $id, $type = 'post', $return_original_if_missing = false, $lang = false ) {
		$lang = $lang ? $lang : pll_current_language();

		if ( 'nav_menu' === $type ) {
			$theme = get_option( 'stylesheet' );
			foreach( PLL()->options['nav_menus'][ $theme ] as $loc => $menu ) {
				if ( array_search( $id, $menu ) && ! empty( $menu[ $lang ] ) ) {
					$tr_id = $menu[ $lang ];
					break;
				}
			}
		} elseif ( $pll_type = ( 'post' === $type || pll_is_translated_post_type( $type ) ) ? 'post' : ( 'term' === $type || pll_is_translated_taxonomy( $type ) ? 'term' : false ) ) {
			$tr_id = PLL()->model->$pll_type->get_translation( $id, $lang );
		}

		return ! empty( $tr_id ) ? $tr_id : ( $return_original_if_missing ? $id : null );
	}
```

**Comment by jumika** [comment]
The code you posted fixes the issue.

**Comment by Chouby** [comment]
Thanks for your test :)
