### ISSUE TITLE
On admin, PLL()->curlang should equal the language of the current post being edited

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang#19]
The same for the current term being edited.

This should allow to filter posts and terms queries according to the post or term being edited instead of the admin language filter.

**Comment by JoryHogeveen** [comment]
An extra thing I've found in this matter is the new-post and term pages. Here the current language for this object is not confirmed yet and this is available with your parameter "new_lang".
Are you planning to do this aswell?

**Comment by Chouby** [comment]
Yes. If you want to test it, I just created a test branch: https://github.com/polylang/polylang/tree/test_admin_curlang

**Comment by JoryHogeveen** [comment]
Thanks! I'll take a look a.s.a.p.

**Comment by Chouby** [comment]
I deleted the test branch as now it has been merged to master.

**Comment by JoryHogeveen** [comment]
Ok! Did install the update and all seems to work fine, haven't got the time to do more tests though

**Comment by Chouby** [comment]
Just a precision: It's still not in 1.9.3 but should come in 2.0. It may seems to be a minor change but since it closely associated with how posts and terms queries are filtered by language, I am still testing and fixing bugs around this.
