### ISSUE TITLE
Polylang and MU Domain mapping - multisite

### ISSUE THREAD

**Issue by thebrownchair** [polylang/polylang#190]
We recently upgraded to version WP 4.8.2 and also updated Polylang to 2.2.3. We found an issue with this version of Polylang and had to rollback.

We also use WordPress MU Domain Mapping v 0.5.5.1 to map domains to our individual sites with our multi site instance. When this version of Polylang was enabled along with MU Domain Mapping plugin the domain mapping was not working. When viewing the site …..com/site it would not redirect to the mapped domain.

**Comment by Chouby** [comment]
I added compatibility with WordPress Mu Domain Mapping in version 2.2. See https://github.com/polylang/polylang/commit/ed254ec35bd60767bdec37d611c4aafb835d9359

Is the compatibility broken by this specific commit?
What settings are you using in WordPress Mu Domain Mapping?

**Comment by thebrownchair** [comment]
I think this commit did break the compatibility. We rolled back to v. 2.1.5 and the mapping worked again. What was happening when the v.2.2.3 was installed is that you could visit the site with non mapped URL (root URL) and the URL you mapped. It was not auto directing to the mapped URL. We use multi site and map each domain as primary for each site inside the domain mapping.

Let me know if you need more information.

**Comment by Chouby** [comment]
What settings are you using in WordPress Mu Domain Mapping?
