### ISSUE TITLE
Media domains per language

### ISSUE THREAD

**Issue by mvanmeerbeck** [polylang/polylang#191]
Hi,

I know you can change the urls for the frontend in the settings of polylang but when a media is posted and linked to a language, it doesn't use those urls.

Is there a way to add the possibility to define the domains per languages for medias ?
Also, i'm using a plugin to host medias to S3 (https://github.com/humanmade/S3-Uploads but there are plenty) so it would have to be compatible.

In s3-uploads, you have to define a constant which i guess, would be problematic
https://github.com/humanmade/S3-Uploads#url-rewrites

PLL: 2.2.4 pro
Wordpress: 4.8.3

Thanks for your help

**Comment by Chouby** [comment]
This depends on which media you are referring to. When the url is dynamically evaluated then the domain is correct (for example the featured image). However if you add an image inside the post content, WordPress will hardcode the url and thus will use the domain used on admin (the main domain). Fixing that would mean filtering the post content which is not done by Polylang.
