### ISSUE TITLE
Posts are not filtered by language on custom taxonomy page if it shares slug with other languages

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#198]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang Pro 2.2.6
2. Create custom taxonomy for attachment post type
3. Add a term in custom taxonomy with the same slug in multiple languages
4. Open the [`taxonomy-{taxonomy}.php` page](https://developer.wordpress.org/themes/basics/template-hierarchy/#custom-taxonomies) for custom taxonomy

## Expected behavior and actual behavior

When I follow those steps, I see attachments in both languages (ie. language filter does not kick in). Problem started with 2.2.6. Also, the problem only happens if taxonomy term shares slug with other languages - if the slug differs, attachments are filtered correctly.

**Comment by chesio** [comment]
Forgot to mention I'm running WP 4.8.3.

**Comment by chesio** [comment]
Seems the change in `PLL_Frontend_Share_Post_Slug::can_filter()/get_language_for_filter()` is causing the problem, if I revert the code to version 2.2.5 state, the problem is gone.

**Comment by Chouby** [comment]
Could you clarify things about attachments? Is your custom taxonomy registered for the post type 'attachment'? Or is it registered for a custom post type in which you insert attachments in the post content? Also are the attachments sharing the same slug too?

**Comment by chesio** [comment]
By "attachment" I mean post type "attachment". I have two custom taxonomies for attachment post type: media_gallery (hierarchical) and media_tag (flat). The problem occurs with both. As soon as there is a term (ie. a gallery or a tag) with slug shared between languages, attachments listed on `taxonomy-media_gallery.php` or `taxonomy-media_tag.php` page are not filtered by current language.

Attachments themselves share the slug too, but to be honest, this is kind of implicit, isn't it? I'm not aware of any way how to change slug for an attachment after it is being created by WordPress from media filename on upload.

**Comment by Chouby** [comment]
I get a `Nothing Found` page.

The DB query is something like:
```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id) 
LEFT JOIN wp_term_relationships AS tt1
ON (wp_posts.ID = tt1.object_id)
WHERE 1=1 
AND ( wp_term_relationships.term_taxonomy_id IN (2) 
AND tt1.term_taxonomy_id IN (1931) )
AND wp_posts.post_type IN ('post', 'page', 'attachment', 'book')
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_author = 1
AND wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 3
```
which can't return any result due to the required private or publish post_status when the post status of attachments is 'inherit'. How do you make it work on your install?

**Comment by chesio** [comment]
True, I forgot I had to tweak WP_Query to workaround this:
```php
add_filter('pre_get_posts', function (\WP_Query $query) {
    if ($query->is_tax('media_gallery') || $query->is_tax('media_tag')) {
        $query->set('post_status', 'any');
    }
    return $query;
}, 10, 1);
```

**Comment by Chouby** [comment]
I don't reproduce. Could you share the SQL query?

**Comment by chesio** [comment]
I did some more digging and it seems the problem is caused by how I fetch posts in my template: instead of regular `while ( have_posts() ) : the_post();` loop, I fetch them via [`$wp_query->get_posts()`](https://developer.wordpress.org/reference/classes/wp_query/get_posts/) call.

To my surprise, SQL queries are slightly different in both cases. This is the regular (working) query:
```sql
SELECT wp_posts.*
FROM wp_posts
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
LEFT JOIN wp_term_relationships AS tt1
ON (wp_posts.ID = tt1.object_id)
LEFT JOIN wp_posts AS p2
ON (wp_posts.post_parent = p2.ID)
WHERE 1=1
AND ( wp_term_relationships.term_taxonomy_id IN (5)
AND tt1.term_taxonomy_id IN (16,18) )
AND wp_posts.post_type IN ('post', 'page', 'attachment')
AND (((wp_posts.post_status <> 'trash'
AND wp_posts.post_status <> 'auto-draft')
OR (wp_posts.post_status = 'inherit'
AND (p2.post_status <> 'trash'
AND p2.post_status <> 'auto-draft'))))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
```

This is the query when I call `$wp_query->get_posts()`:
```sql
SELECT wp_posts.*
FROM wp_posts
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
LEFT JOIN wp_term_relationships AS tt1
ON (wp_posts.ID = tt1.object_id)
LEFT JOIN wp_posts AS p2
ON (wp_posts.post_parent = p2.ID)
WHERE 1=1
AND ( wp_term_relationships.term_taxonomy_id IN (16,18)
AND tt1.term_taxonomy_id IN (16,18) )
AND wp_posts.post_type = 'attachment'
AND (((wp_posts.post_status <> 'trash'
AND wp_posts.post_status <> 'auto-draft')
OR (wp_posts.post_status = 'inherit'
AND (p2.post_status <> 'trash'
AND p2.post_status <> 'auto-draft'))))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
```

Also in the latter case, the query seems not to be recognized as main query (at least [Query Monitor](https://wordpress.org/plugins/query-monitor/) does not label it as such).

**Comment by chesio** [comment]
Ok, I think you can disregard this issue. I have found that calling `$wp_query->get_posts()` on main query in a template file is a stupid idea, the posts can be simply read from `$wp_query->posts` array... Less DB queries and Polylang works as expected.

Thank you for your time and sorry that I bothered you unnecessarily!
