### ISSUE TITLE
Getting: ( ! ) Notice: Undefined offset: 3 in /plugins/polylang-pro/admin/admin-filters-term.php on line 725

### ISSUE THREAD

**Issue by alexkerber** [polylang/polylang#2]
Call Stack
#	Time	Memory	Function	Location
1	0.0019	450416	{main}( )	.../edit-tags.php:0
2	0.4747	23930336	get_option( )	.../edit-tags.php:355
3	0.4747	23930384	apply_filters( )	.../option.php:136
4	0.4747	23930760	PLL_Admin_Filters_Term->option_default_category( )	.../plugin.php:235

and

( ! ) Notice: Undefined offset: 3 in /plugins/polylang-pro/admin/admin-filters-term.php on line 725
Call Stack
#	Time	Memory	Function	Location
1	0.0019	450416	{main}( )	.../edit-tags.php:0
2	0.4747	23930336	get_option( )	.../edit-tags.php:355
3	0.4747	23930384	apply_filters( )	.../option.php:136
4	0.4747	23930760	PLL_Admin_Filters_Term->option_default_category( )	.../plugin.php:235

With latest WP 4.5.1 and Polylang Pro 1.9.0 when I try to translate categories

**Comment by Chouby** [comment]
Replacing the line 725 by 
`
elseif ( isset( $traces[3]['file'] ) && ( false !== stripos( $traces[3]['file'], 'edit-tags.php' ) || false !== stripos( $traces[3]['file'], 'options-writing.php' ) ) ) {`
should fix the notice.
