### ISSUE TITLE
Insert post of specific language

### ISSUE THREAD

**Issue by b4dnewz** [polylang/polylang#200]
First of all, great plugin, sometimes can be buggy but still great.

I would like to programmatically add posts and bind the translations to them but I'm incurring in a error, basically what I do is:
* get the languages list
* loop language and create 1 post per language
* link the created posts with `pll_save_post_translations`

The pseudo code is this:
```php
// Get all active languages
$languages = pll_languages_list(array(
  'hide_empty' => false
));

// Create the posts than store langs and ids
$postids = [];
foreach ($languages as $lang) {
$postids[$lang] = wp_insert_post(array(
	'post_title' => $title,
	'post_status' => 'publish',
	'post_type' => 'custom'
));
}
// Bind posts with translations
pll_save_post_translations($postids);
```

But i'm facing a problem, every time I call: `wp_insert_post()` it uses the default language for the newly created post so what I obtain is (assuming loop count is 3):

3 posts of default language
1 post per non-default language

![image](https://user-images.githubusercontent.com/29862596/33206917-1eb19600-d10c-11e7-8de5-a30514679f67.png)

My default language is italian and as you can see it was created 3 times.

I see from the documentation that you can query posts per language like:
```
$posts = get_posts( array(
    'post_type' => 'post',
    'lang' => 'fr', // use language slug in the query
    'showposts' => 5,
) );
```

Is possible to specify the language to use inside `wp_insert_post` function? I'm digging in the code but I can't understand which parameter I should use.

**Comment by Chouby** [comment]
You can set the post language with `pll_set_post_language()`. See https://polylang.pro/doc/function-reference/. You must take care to have posts in the correct language when using `pll_save_post_translations()`

**Comment by skanw** [comment]
Hey everyone,

First, thank you for sharing your code and insights, it has been incredibly helpful! I am trying to transfer our posts from WPGlobus to Polylang. I can create posts and set their language with ```pll_set_post_language()```, but I’m struggling to link these translations correctly. Can anyone show me how to correctly link these posts as translations? Any tips or examples would be really helpful! 

```
<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);
get_header();

echo "Test import posts";

// Get all active languages
$languages = pll_languages_list(array('hide_empty' => false));
echo "active languages".print_r($languages);

// Create the posts then store langs and ids
$postids = [];
foreach ($languages as $lang) {
    // Create a new post
    $post_id = wp_insert_post(array(
        'post_title' => "Automatic Import",
        'post_status' => 'publish',
        'post_type' => 'post'
    ));

    // Set the language for the post
    pll_set_post_language($post_id, $lang);

    // Store the post ID with its language
    $postids[$lang] = $post_id;
}

echo "Post Import Success".print_r($postids);
?>
```

I’ve also tried Polylang’s admin-link functions without success.

Thanks!

**Comment by c-orazio** [comment]
Hi,
I am interested to migrate a whole website to polylang. I like this functions, but I wonder if I cannot import directly the data rather than running a php code...
I understand from these exchanges that polylang stores two key informations : 
- the language associated to each post. In wihich field of wp_posts is it stored?
- their is aniformation sayin what is the id to the post in english matching to the post is spanish ofr example, but I do not understand where and how this information is stored? is is in a specific polylang table?
Thanking you for you help.

**Comment by Kovalchik8** [comment]
> Hi, I am interested to migrate a whole website to polylang. I like this functions, but I wonder if I cannot import directly the data rather than running a php code... I understand from these exchanges that polylang stores two key informations :
> 
> * the language associated to each post. In wihich field of wp_posts is it stored?
> * there is somewhere  an iformation saying to polylnag what is the id to the post in english matching to the post is spanish for example, but I do not understand where and how this information is stored? is is in a specific polylang table?
>   Thanking you for you help.

Hi, I made a free plugin compatible with Polylang to export and import any Wordpress posts and terms. If you want set or edit language you can make export first, edit column **polylang:language** with language code in CSV file and make import. Feel free to ask if you need any help since I want to test my tool in different themes.

**Comment by Kovalchik8** [comment]
Hi @dademaru, thanks for your feedback. You are definitely right speaking about serialized data, it's might be tough to edit and the idea to add a common identifier to link all translations is pretty good for those who will edit it within CSV file. 

I'll take note of this for the next version.

**Comment by c-orazio** [comment]
> column **Translation Group**

Hi, 
I understand that the translation group refers to the same content but under different languages. sounds like a good idea.

How do we now wich language correspond to which code with this approach? a:2:{s:2:"en";s:7:"test-en";s:2:"fr";s:7:"test-fr";}

**Comment by dademaru** [comment]
@c-orazio 
Sorry I manually edited the serialized array without modifying the array items count.
`a:2` = array with 2 items (but in my example the items are 3, so it had to be `a:3`).
`s:2` = 2 characters string ('en').
`s:7` = 7 characters string ('test-en').

> is english always 2?

No, the key is the language code, the value is the item slug.
If you unserialize the array you get:
```PHP
array(
	'en' => 'test-en',
	'fr' => 'test-fr',
	'it' => 'test-it',
);
```
This is currently how the translations are linked when importing.

It is not meant to be edited manually in a CSV file, it is too easy to make a typo; that is why I was proposing a unique value that would group and link the different translations.
