### ISSUE TITLE
Feature Proposal: Language filter for Recent Posts Widgets

### ISSUE THREAD

**Issue by MatthiasLohr** [polylang/polylang#203]
## The Problem

For some reason I don't want to translate all posts in my blog and manage them in all languages. Unfortunately, the Recent Posts widget only shows the latest articles in the currently active language. This means that on some pages (in xx language) there are many Recent Posts entries, on other pages (yy language) there are only a few/other Recent Posts entries. This is inconsistent and may be difficult for the user to understand.

## Solution/Suggestion

Add a checkbox to the Recent Posts widget (and possibly other widgets) to specify which languages should be included in the listing. Default is the currently selected language, another option should be "All languages".

I would be happy if you could think about this feature.

Best regards and thanks in advance
Matthias

**Comment by Chouby** [comment]
This seems a bit too specific need to me. And I am not in favor of adding options. There is already an option in Polylang Pro allowing to [display posts in several languages](https://polylang.pro/doc/synchronized-posts/). This would work for the widget recent. 

Otherwise, if you have PHP knowledge, you can use the filter `widget_posts_args` to filter the query according to your needs.

**Comment by MatthiasLohr** [comment]
The feature for displaying posts in several languages is completely different to that what i need. So that doesn't help me. Otherwise buying the pro version would be an option.

So i'll try to implement that on my own.

**Comment by Chouby** [comment]
To act only on he widget, I believe that the filter `widget_posts_args` is exactly what you need.

**Comment by MatthiasLohr** [comment]
Setting that to another language works like a charm.

But is there any chance to prevent polylang from setting the language if no language is set, for example when i want to have no language filter?

**Comment by Chouby** [comment]
You can set the 'lang' paramter to an empty value. See: https://polylang.pro/doc/developpers-how-to/

**Comment by MatthiasLohr** [comment]
Done and working. The result is available here: https://github.com/MatthiasLohr/mlohr-polylang-widgets

Best regards
Matthias
