### ISSUE TITLE
Polylang with Woocommerce triggers ajax request loop when multiple tabs are open

### ISSUE THREAD

**Issue by chrisschrijver** [polylang/polylang#204]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open site with woocommerce in 2 separate tabs
2. (optional) open console
3. Switch language in 1 tab

## Expected behavior and actual behavior

You'll see a "get_refreshed_fragments" woocommerce ajax request looping. It has something to do with this piece of javascript in the "cart-fragments.js" of woocommerce:

`
		$( window ).on( 'storage onstorage', function ( e ) {
			if ( cart_hash_key === e.originalEvent.key && localStorage.getItem( cart_hash_key ) !== sessionStorage.getItem( cart_hash_key ) ) {
				refresh_cart_fragment();
			}
		});
`

When switching language in one of the tabs session storage value gets updated with a new hash with the translated products. This triggers the other tab to refresh the cart as well (hash is change), so it will perform a refresh fragment, which changes the cart hash back to the original one, which triggers the refresh fragments in the second tab, etc, etc ,etc.....a loop.

**Comment by Chouby** [comment]
I reproduce the issue. This is because WooCommerce stores a localized version of the mini-cart. Each page wants to keep the mini-cart in its own language creating an infinite loop. Solving this means that we have to find another way to translate the cart.

**Comment by chrisschrijver** [comment]
Good the hear you were able the reproduce it. It Think it's quite a hard thing to fix. It's not a real critical bug, but it it's something that needs to be fixed. When I think of a solution I will let you know.

**Comment by Chouby** [comment]
That's something I plan to work on during the spring, after the release of WC 3.3.

**Comment by chrisschrijver** [comment]
@Chouby See you closed the issue. Were you able to fix it?

**Comment by Chouby** [comment]
Yes. This will be in Polylang for WooCommerce 0.9.4 to be released very soon.
