### ISSUE TITLE
Extend string translations search to translated strings

### ISSUE THREAD

**Issue by kozekzs** [polylang/polylang#207]
Hi!

The search form not search in translations (see the attached image), but it would be the most important source, because the user will find only through that the necessary translation.

Please extend the search with this! 
Thx!

![screenshot](https://user-images.githubusercontent.com/14937482/34512575-b18b0774-f063-11e7-8440-5b59743df999.jpg)

**Comment by Chouby** [comment]
That's indeed something I have thought to for a long time. But it's more complex to do than the current search among source strings.

**Comment by kozekzs** [comment]
Hi Chouby!

I've modified the code (wp-content\plugins\polylang\settings\table-string.php), I tested it and it works! :) please check it and update the code, thank you very much!

[table-string.zip](https://github.com/polylang/polylang/files/1601114/table-string.zip)

**Comment by Chouby** [comment]
Thanks for your proposal.

**Comment by kozekzs** [comment]
Finally did you do it?

**Comment by grappler** [comment]
@kozekzs Yes, you can see the changes here: https://github.com/polylang/polylang/commit/9d5427415616a8991562d112d95ff3f5d90d8623

**Comment by kozekzs** [comment]
Not work for me... see my screenshot. When I post the form, no record found.
![wp](https://user-images.githubusercontent.com/14937482/51919734-58275880-23e4-11e9-81cd-c262ea3f8be0.jpg)
