### ISSUE TITLE
Tag cloud for taxonomy in post admin gets wrong markup and layout

### ISSUE THREAD

**Issue by bonny** [polylang/polylang#208]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

In admin, when clicking the link "Choose from the most used tags" it fetches the tags via ajax and dispays them. WordPress by default places the markup for the tag cloud (`<ul class='wp-tag-cloud'>`) inside a div with class tagcloud (`<div class="tagcloud-tag">`). 

Polylang however places the markup for the tag cloud inside a `p`-tag and then because a p-tag can not contain an ul-list the browser moves the ul-list to outside the p-tag. And because of this the CSS for the tag cloud is not working because the CSS targets the ul inside the the-tagcloud-class, but now the ul is outside/after the the-tagcloud-class.

## Expected behavior and actual behavior

I expect the tag cloud to look like it usally does, i.e. the tags are placed after each other in a row. See first screenshot.

Instead it displayed all the tags on one line after each other, occuping a lot of screen space. See second screenshot.

## Solution

I believe the solution is to change line 30 in `post.js` from

`r = $( '<p id="tagcloud-' + tax + '" class="the-tagcloud">' + r + '</p>' );`

to

`r = $( '<div id="tagcloud-' + tax + '" class="the-tagcloud">' + r + '</div>' );`

If I make this change the tag cloud looks good again.

## Screenshots

Screenshot 1 - tags are placed correct
<img width="277" alt="polylang tags correct" src="https://user-images.githubusercontent.com/221570/34565773-6b18509a-f15c-11e7-99d2-6ee8ad286efe.png">

Screenshot 2 - tags are placed wrong
<img width="298" alt="polylang tags wrong" src="https://user-images.githubusercontent.com/221570/34565765-66502f74-f15c-11e7-8c28-078790614077.png">

**Comment by Chouby** [comment]
Thanks for your report. This was indeed changed in WP 4.9. See https://core.trac.wordpress.org/ticket/40187
