### ISSUE TITLE
The HTTP host can be invalid when WordPress is used behind a proxy.

### ISSUE THREAD

**Issue by shulard** [polylang/polylang#209]
Hello,

I've just deployed a WordPress instance behind a proxy and I got a problem with the Polylang generated URLs.

The URLs built inside admin bar menu, for example use the `$_SERVER['HTTP_HOST']` variable which can be invalid... In most of the case, I think Polylang can rely on relative URIs instead of absolute one.

## Prerequisites

The WordPress instance must be installed behind a proxy which doesn't override HTTP_HOST variable. We can tell WordPress which is the valid URL to use, Polylang must use it...

## Steps to reproduce the issue

1. Install a WordPress instance ;
2. Configure a proxy which for example, forward https://domain.tld to http://internal.domain.tld:8000 ;
3. Define `WP_HOME` and `WP_SITEURL` with "https://domain.tld" ;
3. In the admin bar, the links used the http://internal.domain.tld:8000 domain.

This is because the HTTP_HOST in the PHP process is the current one and Polylang use it directly.

## Expected behavior and actual behavior

Using relative URIs (in the admin bar) can solve the problem. Maybe there are other places where this need to be fixed.

**Comment by shulard** [comment]
That kind of problem has been discussed in the issues and PR #91 and #92.

**Comment by Chouby** [comment]
WordPress itself uses this variable directly in several places: https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=%24_SERVER%5B%27HTTP_HOST%27%5D&type=
Isn't it an issue?

**Comment by shulard** [comment]
I know that WordPress is using that variable directly in the core. Using that var is not a real problem for me because it's necessary to detect what's the current context.

But the problem with the plugin here is that the behaviour is not the same than the core. Actually only the Polylang generated URLs are invalid. I think that plugins must let that URL detection / construction part directly to the core and it's why I pointed to relative URIs.

I can work on a PR if you want 😊.

It's a tiny edge case since it appears only when the HTTP_HOST server var is not right (maybe only when the website is behind a proxy...).

**Comment by Chouby** [comment]
I agree that using absolute links for the admin bar does not make a lot of sense. And it's easy to fix. 
Do other cases cause issues?

**Comment by shulard** [comment]
At the moment there isn't any other cases for me but I need to make deeper tests to be sure. I'll add notes here if I find some.

**Comment by Chouby** [comment]
OK. I switched to relative urls for the admin bar. I keep this issue open for a couple of weeks in case you find other issues with this variable that can be easily fixed.
