### ISSUE TITLE
Synchronization in Taxonomies

### ISSUE THREAD

**Issue by goldweb** [polylang/polylang#21]
Polylang Version 1.9.2

Checked on fresh wordpress install without any additional plugins.

-     Added two languages, created in them two categories, on top, other sub category.
-     Synchronization in Taxonomies enabled.
-     Added 5 posts into sub category.

Categories structure:
`Cat 1 (0 posts) -> Sub Cat 2 (5 posts)`

**Problem is in:**
When I go into created 'Cat 1' category, when I save it again, then all posts from sub category are assigned to the 'Cat 1'.

**Comment by Chouby** [comment]
Thanks for the bug report. Confirmed.
