### ISSUE TITLE
Doesn't save language cookie with WP Fastest Cache

### ISSUE THREAD

**Issue by beherit** [polylang/polylang#210]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install cache plugin "WP Fastest Cache"
2. Go directly site e.g. through new private tab in Chrome to see cached version
3. There is no new cookie saved with language code. Because of this issue there is a problem with e.g. data getting by wp rest api.

## Expected behavior and actual behavior

I don't know when but previously this bug wasn't exists. I check version from master with fix for such issues but this doesn't work for me.

**Comment by beherit** [comment]
I found where is the problem - "WP Fastest Cache" plugin doesn't require define the WP_CACHE. After adding WP_CACHE to wp-config.php everything works okay.

**Comment by Chouby** [comment]
Indeed I reproduced the issue. I was thinking that all cache plugins were adding the constant WP_CACHE.

**Comment by AmrSubZero** [comment]
```define('WP_CACHE', true);``` to ```wp-config.php``` was the final destination to my 3 hours searching.

Thanks!
