### ISSUE TITLE
WP_Query translating taxonomy IDs when using lang

### ISSUE THREAD

**Issue by GreenManSK** [polylang/polylang#213]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Using get_posts to get translated posts in multiple languages
2. Setting lang parameter to 2 different languages, one of them is actual default language
3. Using tax_query with 1 taxonomy and 2 terms, one is slug in frist language, second is slug in another language

## Expected behavior and actual behavior

When I follow those steps, both taxonomy ID for these 2 terms are translated to default language and only post I get are posts that are in default language.

I was expecting to get post in both language that belongs under these two terms.
I can see in commit [9a51d7fef734e1311eaab556461edc828cd2c5a6](https://github.com/polylang/polylang/commit/9a51d7fef734e1311eaab556461edc828cd2c5a6), that this problem is repaired when using only WP_Term_Query, but not when WP_Query is using WP_Term_Query while getting posts.

**Comment by Chouby** [comment]
To make things clearer, could you share an example of a query demonstrating the issue?

**Comment by GreenManSK** [comment]
```php
$query = [
	'post_type' => 'vacancy',
	'post_status' => 'publish',
	'number_posts' => -1,
	'lang' => 'en,cs',
	'tax_query' => [
		'taxanomy' => 'vacancy_category',
		'field' => 'slug',
		'terms' => ['slug-for-en-category', 'slug-for-cs-category']
	]
];
$posts = new \WP_Query($query);
```
Default language is en. After query is executed, there is used only id for slug-for-en-category, because id for slug-for-cs-category was translated into id for en category

**Comment by Chouby** [comment]
There are several mistakes in your query. Here is a fixed version:
```php
$query = [
	'post_type' => 'vacancy',
	'post_status' => 'publish',
	'numberposts' => -1, // numberposts instead of number_posts.
	'nopaging'    => true, // You need this if you don't want to limit the number of posts as the line above seems to indicate. 
	'lang' => 'en,cs',
	'tax_query' => [ [ // 2 levels of array instead of one.
		'taxonomy' => 'vacancy_category', // taxonomy instead of taxanomy.
		'field' => 'slug',
		'terms' => ['slug-for-en-category', 'slug-for-cs-category']
	] ]
];
$posts = new \WP_Query($query);
```
Once I have fixed all the errors, I get all posts in in both languages and both categories.
