### ISSUE TITLE
Broken Shortcodes in Second Language

### ISSUE THREAD

**Issue by sinankoatata** [polylang/polylang#214]
Hello

I’ ve recently installed polylang plugin to my website and i have a problem about my shortcodes.
If you check my [default homepage](www.ekinmakina.com) you will see that there is images of my products under “Geniş Ürün Yelpazesi”.

But in the [English version](http://www.ekinmakina.com/en
) of my home page which shares the same content with default homepage wont show these images under “Wide Product Range” for following shortcode;

[recent_works columns=”4″ amount=”4″ animate=””]

Is there something i am missing? Why do you think my theme’s recent works shortcode wont work in homepage/en page?

http://www.ekinmakina.com
http://www.ekinmakina.com/en

Thanks a lot!

**Comment by Chouby** [comment]
I don't know this shortcode [recent_works]. Your issue does not looks like a bug but more like a compatibility issue with your theme or a 3rd party plugin. I invite you to contact the support of the provider of this shortcode. You can also try to ask the question on the Polylang support forum, but I suggest that you provide more details in your support request to identify the conflict source.
