### ISSUE TITLE
Archives in non default languages for not translated post types are 404

### ISSUE THREAD

**Issue by certainlyakey** [polylang/polylang#215]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x]  This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

Basically, there might be two sub-issues here.

1. I'm looking for an option to have the UI of archive pages for non translated post types localised, while keeping the post listing there. Instead archive pages in this case are 404'd altogether unless URL slug for the default language is set to be displayed. 
2. The slugged version of an archive page for a non translated CPT always gives 404. See below. 

## Steps to reproduce the issue

1. Create a custom post type with `has_archive`, `public` set to `true`
2. Make sure it's not set as a translated post type
3. Make sure that in _URL modifications_ section of Polylang settings, _Hide URL language information for default language_ checkbox is checked
5. Go the archive page of this post type in a non default language, at `/<language-slug>/<post-type-slug>`. A 404 page should appear. 
6. Or go to `/<post-type-slug>` (without the language slug). The archive page in default language will appear (both UI and post list).

The other options set are _The language is set from the directory name in pretty permalinks_ and _Remove /language/ in pretty permalinks_. They don't seem to affect the issue much.

## Expected behavior and actual behavior

When I follow those steps, I see either the 404 page or an archive page in the default page.

I was expecting to see an archive page for the post type, with the same non translated posts list, and UI in the non default (current) language.

So, for example, what i see with a CPT called _Services_ and Italian language as a second language in _twentyseventeen_ theme (with _Hide URL language information for default language_ checked): 

- `/services` shows English UI, services posts list;
- `/it/services` shows English UI, **404**;
- additionally, `/en/services` is also 404.

What is expected:

- `/services` shows English UI, services posts list;
- `/it/services` shows Italian UI, services posts list.

If I uncheck _Hide URL language information for default language_ checkbox, the services archive in secondary language becomes accessible but at `/services` URL instead of `/it/services`. It's probably more consistent to have it under `/it/` directory, but that's a separate issue.

Tested this on a custom theme on my local and on the stock twentyseventeen.

Thanks!

**Comment by Chouby** [comment]
This is the expected result. When you decide not to translate a post type, it means that Polylang takes no action for this post type. So the urls are not modified and the theme is loaded in the default language. To obtain what you expect, you need to make your post type translatable and duplicate the content from one language to the other. Polylang Pro has a feature to synchronize posts across languages.
