### ISSUE TITLE
Custom root rewrite rules stopped working after upgrade to 2.3

### ISSUE THREAD

**Issue by lewebsimple** [polylang/polylang#216]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

Add the following to your theme's function.php:
```php
// Add 'action' to query_vars
add_filter( 'query_vars', 'testing_query_vars' );
function testing_query_vars( $query_vars ) {
	$query_vars[] = 'action';

	return $query_vars;
}

// Add custom root rewrite rules
add_filter( 'root_rewrite_rules', 'testing_root_rewrite_rules' );
function testing_root_rewrite_rules( $rules ) {
	$actions              = array();
	$rules['^testing/?$'] = 'index.php?action=testing';

	return $rules;
}

// Custom template include for testing action
add_filter( 'template_include', 'testing_template_include' );
function testing_template_include( $template ) {
	$action = get_query_var( 'action' );

	if ( ! empty( $action ) && $action_template = locate_template( "$action.php" ) ) {
		return $action_template;
	}

	return $template;
}
```

Then create a dummy template file named "testing.php" inside your theme directory, flush your rewrite rules and visit `/testing`

## Expected behavior and actual behavior

When I follow those steps, I get redirected to the front page when trying to access '/testing' instead of seeing the dummy template.

Deactivating Polylang Pro 2.3 and flushing the rewrite rules fixes the problem and the `/testing` rewrite works normally. It also works if I downgrade to polylang-pro version 2.2.8 so it's definitely caused by the update to 2.3 (tried the pro and free version, both have this problem).

This might break a lot of plugins and/or themes that rely on root rewrite rules!

Thanks for such a wonderful plugin!

**Comment by Chrystll** [comment]
Bug introduced by the commit: 56fa5c3b9dc89d3143621c55ec537120cf548186

**Comment by Chouby** [comment]
Could you check if it works for you with the master branch?
