### ISSUE TITLE
Fatal error: Class 'PLL_Jetpack' not found in \wp-content\plugins\polylang\modules\plugins\plugins-compat.php on line 41

### ISSUE THREAD

**Issue by RaduPoe** [polylang/polylang#217]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate JetPack version 5.7.1
2. Try to activate Polylang 2.3
3. Error is raised

## Expected behavior and actual behavior
Error not to be raised.

When I follow those steps, I see...

( ! ) Fatal error: Class 'PLL_Jetpack' not found in C:\Work\www\it_brainiacs\itb-www\wp-content\plugins\polylang\modules\plugins\plugins-compat.php on line 41
Call Stack
`#	Time	Memory	Function	Location
1	0.0010	432712	{main}( )	...\plugins.php:0
2	0.8912	69301560	plugin_sandbox_scrape( )	...\plugins.php:172
3	0.8916	69319104	include( 'C:\Work\www\it_brainiacs\itb-www\wp-content\plugins\polylang\polylang.php' )	...\plugin.php:1897
4	0.8921	69368592	require_once( 'C:\Work\www\it_brainiacs\itb-www\wp-content\plugins\polylang\include\class-polylang.php' )	...\polylang.php:70
5	0.8921	69368896	Polylang->__construct( )	...\class-polylang.php:231
6	0.8964	69566128	PLL_Plugins_Compat::instance( )	...\class-polylang.php:53
7	0.8964	69566400	PLL_Plugins_Compat->__construct( )	...\plugins-compat.php:68

![image](https://user-images.githubusercontent.com/388393/35634144-403116e6-06ab-11e8-8d32-61751ad78a46.png)

I was expecting...
No error, the Polylang plugin to start succesfully

**Comment by Chouby** [comment]
I don't reproduce. Could you check if there is a file jetpack.php in /polylang/modules/plugins as in this repo? https://github.com/polylang/polylang/tree/2.3/modules/plugins

**Comment by RaduPoe** [comment]
Indeed, the modules/plugins didn't contain the jetpack.php.
Thank you for the hint, reinstalling the Polylang fixed this  - now the file is there.
