### ISSUE TITLE
PHP Notice on saving posts

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#218]
When I save a post I am getting the following PHP Notice while using Polylang Pro 2.3.
`PHP Notice:  Trying to get property of non-object in wp-includes/class-wp-query.php on line 3728/3730/3732`

I traced `is_page()`  being called from `PLL_Frontend_Static_Pages->pll_check_canonical_url()`.

```
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, PLL_Frontend_Filters_Links->check_canonical_url, apply_filters('pll_check_canonical_url'), WP_Hook->apply_filters, PLL_Frontend_Static_Pages->pll_check_canonical_url, is_page, WP_Query->is_page
```

Related core ticket https://core.trac.wordpress.org/ticket/29660

**Comment by Chouby** [comment]
Did this error appear in 2.3? This function is using `is_page()` for ages.
Are you saving your post on front? The file should not be loaded on backend.

**Comment by Chouby** [comment]
@grappler Are you able to provide me steps to reproduce the issue?

**Comment by grappler** [comment]
Sorry, it has taken so long for me to look at this. I think the error happens when saving a post with https://wordpress.org/plugins/varnish-http-purge/ activated. I am yet not fully sure why but try to continue to dig.

**Comment by Chouby** [comment]
Closing this for now. Feel free to comment if you encounter this error again.
