### ISSUE TITLE
Disable auto translation of tax query if main query has a 'lang' parameter

### ISSUE THREAD

**Issue by ocean90** [polylang/polylang#223]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Have a post type only in the default language available.
2. Have a taxonomy which is available in multiple languages and assigned to the above post type.
3. Query for the post type and include all term IDs in the `tax_query`

Code snippet:
```php
$args = [
	'post_type'      => 'my-post-type'
	'post_status'    => 'publish',
	'posts_per_page' => -1,
	'order'          => 'ASC',
	'lang'           => '',
];

$field = get_query_var( 'my-query-var' );
if ( ! empty( $field ) ) {
	// Include terms of all languages.
	$translations = pll_get_term_translations( $field );
	if ( is_array( $translations ) && count( $translations ) ) {
		$field = array_values( $translations );
	}

	$tax_query[] = [
		'taxonomy' => 'my-taxonomy',
		'field'    => 'term_id',
		'terms'    => $field,
	];
}

$args['tax_query'] = $tax_query;

$query = new WP_Query( $args );
```

## Expected behavior and actual behavior

When I follow those steps, I get no results if the current language is not the default language.

I was expecting results even if the current language doesn't match the language of the post type.

The cause for this is `PLL_Frontend_Auto_Translate::get_terms_args()` kicking in. Although there is a check for the `lang` argument since 9a51d7fef734e1311eaab556461edc828cd2c5a6, it seems like it doesn't inherit the value from the "main" query. 

I also tried setting the `lang` argument like in

```
$tax_query[] = [
	'taxonomy' => 'my-taxonomy',
	'field'    => 'term_id',
	'terms'    => $field,
	'lang'     => '',
];
```

but it doesn't get passed to the underlying term query.

Current workaround:

```
// Don't auto-translate term IDs.
if ( function_exists( 'PLL' ) && isset( PLL()->auto_translate ) ) {
	remove_filter( 'get_terms_args', array( PLL()->auto_translate, 'get_terms_args' ), 10 );
}

$query = new WP_Query( $args );

// Restore auto-translate filters.
if ( function_exists( 'PLL' ) && isset( PLL()->auto_translate ) ) {
	add_filter( 'get_terms_args', array( PLL()->auto_translate, 'get_terms_args' ), 10, 2 );
}
```

**Comment by Chouby** [comment]
It looks like this is another side effect of the issue that I attempted to describe in https://core.trac.wordpress.org/ticket/42104.

Since WP 4.9, `[transform_query()](https://github.com/WordPress/WordPress/blob/aaf99e691391cfceb004d848450dbbf3344b1bee/wp-includes/class-wp-tax-query.php#L597)` uses `WP_Term_Query`. The issue is that terms queries must be filtered in most cases, but not when called by `transform_query()`, and I have currently no way to properly distinguish this case.

My proposal for https://core.trac.wordpress.org/ticket/42104 may not be the best choice. Allowing to filter the terms query args in `transform_query()` may be a better solution.

**Comment by Chouby** [comment]
I'll do the same as you suggest to workaround. The filter will be removed in a function hooked to `parse_query` and added back in another function hooked to `posts_selection`.
