### ISSUE TITLE
JS error when Gutenberg plugin is active

### ISSUE THREAD

**Issue by theleemon** [polylang/polylang#225]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and activate the Gutenberg plugin ( https://wordpress.org/plugins/gutenberg/ )
2. Install and activate the Polylang plugin
3. Add or edit a post with the Gutenberg editor

## Expected behavior and actual behavior

When I follow those steps, I see...

```
Uncaught TypeError: wp.utils.WordCounter is not a constructor
    at load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,wp-ajax-response,suggest,jquery-color,wp-lists,jquery-ui-positi&load[]=on,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,tags-suggest,tags-box,post,media-editor,media-audiovideo,mce-view,imgareaselect&load[]=,image-edit,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,quicktags,wplink,thickbox,media-upload,&load[]=sack,wp-pointer&ver=4.9.4:290
(anonymous) @ load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,wp-ajax-response,suggest,jquery-color,wp-lists,jquery-ui-positi&load[]=on,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,tags-suggest,tags-box,post,media-editor,media-audiovideo,mce-view,imgareaselect&load[]=,image-edit,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,quicktags,wplink,thickbox,media-upload,&load[]=sack,wp-pointer&ver=4.9.4:290

```

I was expecting...

No JS errors

----

I know that Gutenberg is under active development right now, but considering that it will be merged into core in the near future I wanted to let you know about a possible conflict between both plugins.

**Comment by manooweb** [comment]
I corrected this issue by loading our Polylang js script in the header. It is now avalaible in our master branch and will be available in our next release
