### ISSUE TITLE
Polylang + Domain Mapping failing with languages as subdirectories on multisite installation (subdomain type)

### ISSUE THREAD

**Issue by Julianoe** [polylang/polylang#226]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Wordpress installation as a Network of sites (multisite)
2. Wordpress Multisite set as subdomains. I have site1.multisite.com and site2.multisite.com
3. Using the [WordPress MU Domain Mapping](https://wordpress.org/plugins/wordpress-mu-domain-mapping/) with the following configuration:
![Mu domain Mapping](https://i.imgur.com/ckiY9R3.png)
I use this plugin to map the domains to redirect domains from the multisite to different domains from clients.

4. Polylang is set to use subfolders architecture and other configuration looks like this
![](https://i.imgur.com/XMt7qLE.png)

5. In the end here is a visual representation of the architecture.
![](https://i.imgur.com/ZCXOW4O.png)

## Expected behavior and actual behavior

Once the install is configured like this there is obviously an incompatibility between the two modes of remapping urls of Polylang and Mu Domain Mapping. 

The same installation without the multilingual aspect of it (site1.multisite.com on my example) is working like a charm. Urls are redirected properly to the client1site.com.

Once Polylang is activated and configured as presented (**i tried different configuration but i need the subfolder type of infrastructure**) the urls are not redirect anymore, although the mapped domain is accessible also. 

I've seen multiple threads over the past months covering this issue without a clear answer and not with **the subdomain multisite to multilingual subfolder** type of configuration. Is this a known issue. Have you tried it?

Thanks for the answer and/or testimony from other users that are trying to achieve the same type of **multilingual multisite Wordpress installation with Polylang and Wordpress MU Domain Mapping**.

**Comment by Chouby** [comment]
Could you clarify what does not work? I have a multisite running Mu Domain Mapping and Polylang and I don't see any obvious issue.

**Comment by Julianoe** [comment]
Hi @Chouby thanks for taking up my issue.

As you can read on my chart i expect my multisite installation to redirect site3.multiste.com/fr to pro.client2site.com/fr.
That is not currently the case.

In fact when i visit the site3.multiste.com it does not redirect traffic. pro.client2site.com works also. But having to sites standing at the same time for the same content is obvioulsy an issue.

 As i wrote in my issue traffic is redirected correctly on the same Network on subsite that has not Polylang activated, leading me to think it is due to incompatibility.

Does you multisite/MU Domain Mapping/Polylang config has subdirectory type redirection set for the different languages?

I will try to run more config tests to check if i can be even more precise.

**Comment by Chouby** [comment]
I got it. Thanks.

**Comment by Julianoe** [comment]
I updated our production site with the latest Polylang update that added the fix and it worked like a charm. Thanks a lot !
