### ISSUE TITLE
Problems with subcategories

### ISSUE THREAD

**Issue by Infolu** [polylang/polylang#227]
Hello, I am facing what I believe to be a problem, when I have enabled the plugin, I can not reach my existing subcategories, I can only see category.

However if I create a new subcategory this happens to be leveraged in front of my template, ie the plugin is not mapping existing subcategories to new ones only.

Anyone else going through this?

**Comment by Chouby** [comment]
I don't understand your issue. If you believe there is a bug, please provide clear steps to reproduce.

**Comment by Infolu** [comment]
Hi, I'll try to describe the problem.

Taxonomies created before plugin installation are no longer displayed or found returning error 404, only categories created after plugin activation are found.

When the previously created categories should be displayed in the default language,

Now if I enter edit category and click refresh category the same happens to be found, so for those who have a number of categories registered it is tricky to enter each category just to update.

**Comment by Chouby** [comment]
Please read https://polylang.pro/doc/i-activated-the-plugin-and-my-categories-are-not-displayed-anymore/
and https://polylang.pro/doc/assign-a-language-to-an-existing-content/
For any other issue like this, please use the support forum. GitHub is to report bugs. Thanks.
