### ISSUE TITLE
Problem with add_rewrite_rule

### ISSUE THREAD

**Issue by malevski** [polylang/polylang#228]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add multiple languages and pages
2. Add custom add_rewrite_rule to create a "virtual page" - for example: add_rewrite_rule( 'test.html', 'index.php?page_id=123', 'top' ); - linking to *not default* language
3. Visit URL example.com/test.html - showing navigation on the default language
4. print(pll_current_language()); - It's pointing to the default language

## Expected behavior and actual behavior

When I follow those steps, I see the default navigation, just the content of the page is correct.

I was expecting to see the navigation translated as well.

**Comment by Chouby** [comment]
If you chose to set the language from the url in Polylang settings, the obtained result is expected as you don't add the language in the url. For such support questions, please use the support forum.
