### ISSUE TITLE
The number of posts of a post type are wrong when a languague is selected

### ISSUE THREAD

**Issue by 7studio** [polylang/polylang#231]
```
WordPress version: 4.9.4
Plugin version: Polylang Pro 2.3.2
```
Hi,

I run into an issue with Polylang when a list of items is displayed while a specific language is selected.

All number of posts for a post type in the list of views available are wrong.
It's the amount of all languagues which are displayed and not just the selected language (e.g. ; screenshot below)
![bug-polylang-wp-count-posts](https://user-images.githubusercontent.com/835430/37195423-099083da-2373-11e8-9c19-8b65e524338d.png)

It seems that the problem comes from the function `wp_count_posts` there [wp-includes/post.php#L2321-L2389](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L2321-L2389).

I don't know if using the filter `wp_count_posts` is the best solution but I haven't found anything else.
I'm sorry but I haven't enough time to investigate more and submit a PR.

**Comment by chesio** [comment]
Hi, this is known issue, see #133 ;-)

**Comment by Chouby** [comment]
This is probabl not easy to solve. Note that on a fresh install, you will have the same issue when you filter the posts by category.
