### ISSUE TITLE
Static page not served in multidomain case

### ISSUE THREAD

**Issue by facehu** [polylang/polylang#232]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Setup 2 languages with different domain names! "langa.test.com", "langb.test.com"
2. Create a page in both languages and connect them with polylang "Home langA", "Home langB"
2. Set one of them as static frontpage "Home langA"
3. Now langa.test.com servs "Home langA" just fine
4. langb.test.com instead of serving "Home langB" redirects to langa.test.com 

## Expected behavior and actual behavior

langa.test.com servs "Home langA", but langb.test.com instead of serving "Home langB" redirects to langa.test.com.

**Comment by Chouby** [comment]
I followed the steps and this works for me. Either you are facing a conflict with your theme or you did not configured correctly your domains or your redirect is cached in the browser.

**Comment by facehu** [comment]
Thank you for your answer! I tried with a default theme, and it worked just fine. In my case it is an issue with the enfold theme, but there is a solution:
"You only need to set frontpage in Settings > Reading and not in Enfold theme options."
see: https://kriesi.at/support/topic/polylang-support/
