### ISSUE TITLE
Categories and tags not filtered on Gutenberg

### ISSUE THREAD

**Issue by theleemon** [polylang/polylang#235]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Gutenberg plugin
2. Add some languages in Polylang
3. Add some categories or tags and translate them
4. Edit a post and take a look at the categories/tags box in the editor sidebar

## Expected behavior and actual behavior

When I follow those steps, I see ALL categories/tags in ALL registered languages in Polylang in the editor sidebar

I was expecting to see just the categories or tags in the language of the current post in the editor sidebar

To get the terms, Gutenberg makes use of the REST API:

https://github.com/WordPress/gutenberg/blob/41f7feba0717f7ce62e14bcb9bfb8e221f55efbd/editor/components/post-taxonomies/hierarchical-term-selector.js#L170

https://github.com/WordPress/gutenberg/blob/41f7feba0717f7ce62e14bcb9bfb8e221f55efbd/editor/components/post-taxonomies/flat-term-selector.js#L83

As support for the REST API in Polylang is just available in the Pro version, this is an issue that will affect all the Free version users when Gutenberg lands on core sooner or later.

**Comment by manooweb** [comment]
Thanks. We saw that too.
This feature is also broken in Polylang Pro and does not yet use Rest API. We are working on it.

**Comment by Chouby** [comment]
See also: https://github.com/WordPress/gutenberg/issues/5655

**Comment by Chouby** [comment]
I am closin this in favor of https://github.com/polylang/polylang-gutenberg/issues/2

**Comment by edpittol** [comment]
@Chouby I was check this link and I noticed that the project `polylang/polylang-gutenberg` no longer exists.

I'm with the latest version of Polylang and WordPress installed and I see all registered categories and tags instead see just the post language related.

**Comment by manooweb** [comment]
Hi @edpittol,

polylang/polylang-gutenberg no longer exists because we integrated the full compatibility with Gutenberg in Polylang Pro 2.6 version in June 2019 with a metabox full rewritten in ReactJS 
Why Polylang Pro only ? Because only Polylang Pro has a compatibility with the WordPress REST API which doesn't exist in Polylang Free version.

It explains why you have this issue.

Sorry but if you want to absolutely have this feature you have to upgrade to Polylang Pro.

Regards
