### ISSUE TITLE
Polylang 2.3 prevents caching of homepage when browser language detection is active

### ISSUE THREAD

**Issue by Tabrisrp** [polylang/polylang#236]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

Hi,

I'm Remy, lead developer of WP Rocket.

Not so much an issue but a get in touch to find a better solution for everyone :)

Since @chouby told me about this before, I believe the change of using `DONOTCACHEPAGE` on the homepage to prevent caching, is to allow the cookie storing the language to be set when this option is active.

I have an alternate solution to offer, since in WP Rocket you can set a mandatory cookie, which means a cookie that is required to be set before the plugin serves the cache.

Here is a basic example on how that works

```
function wp_rocket_mandatory_cookie_verify( $cookies ) {
	$cookies[] = 'cookie';

	return $cookies;
}
add_filter( 'rocket_cache_mandatory_cookies', 'wp_rocket_mandatory_cookie_verify' );
```

So with that in place, the first time a visitor comes to a website with Polylang and language detection, they receive an uncached page, and Polylang cookie is set. For the subsequent pages, they will receive the cached pages as long as the cookie is set in the browser.

This solution would solve the issue for you, and for us since we have customers opening tickets asking why their homepage is not cached.

If you don't see any issue with that, I'll implement the compatibility in WP Rocket, and you'll be able to remove the `DONOTCACHEPAGE` in Polylang.

Cheers

**Comment by Chouby** [comment]
Hi Rémy,

The browser language detection is indeed not compatible with a cached home page. I had often to ask users to disable the cache on the home page to make the option work. I finally ended up to do it automatically with the constant `DONOTCACHEPAGE` as it seems to be honored by most cache plugins. Unfortunately I was not aware of your solution which is way much better.

Do you know if other cache plugins have the same method? Otherwise I would have to remove the constant only for WP Rocket.

It is better to add the filter in WP Rocket or in Polylang?

**Comment by Tabrisrp** [comment]
I don't know if other caching plugins have this kind of cookie compatibility feature, so it's safer to remove it only for WP Rocket at first.

It's better if I integrate the compatibility code in WP Rocket, as we'll be able to update the WPR config file directly when we detect polylang activation or a change in polylang settings related to that.

I'll work on it and let you know when it's ready!

**Comment by Chouby** [comment]
Can we coordinate ourselves to, more or less, synchronize the modifications?

**Comment by Tabrisrp** [comment]
Hi @Chouby,

We finally got around to include the changes in a minor version. We plan to release it Tuesday next week (version 3.0.5).

Will this work for you to make the change in Polylang too?

**Comment by Chouby** [comment]
Hi Rémy,

Is it ok to replace https://github.com/polylang/polylang/blob/2.3.6/modules/plugins/cache-compat.php by

```php
if ( ! defined ( 'WP_ROCKET_VERSION' ) || version_compare( WP_ROCKET_VERSION, '3.0.5', '<' ) ) {
	add_action( 'wp', array( $this, 'do_not_cache_site_home' ) );
}```

I guess that I still need to set the cookie in Javascript when WP Rocket is present. Am I right?

I can do this in version 2.3.7 next week.

**Comment by Tabrisrp** [comment]
Yes that will work.

I would always favour setting the cookie in JS for maximum compatibility, even though with the changes we made it should also work with a cookie-set in PHP, as PHP will always be executed for the visitor until the cookie is set.

**Comment by KZeni** [comment]
As a W3 Total Cache user,

I would love to see "Detect browser language" be renamed to "Detect browser language (PHP Based)" which then doesn't cache the homepage in certain circumstances.

Meanwhile, it'd be great to see "Detect browser language (JavaScript Based)" added as an alternative where there's client-side JS that detects the visitor's browser language and then redirects accordingly. That would then never interrupt any server-side caching (while then keeping the server-side option for those that want that greater certainty of the redirect happening with the potential performance drawback from that not being seen as an issue & then having a much more performant option for the homepage's initial page load that is potentially not as reliable [while plenty fine for most.])
