### ISSUE TITLE
'pll_the_language_args' is not honored for menus

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang#237]
1. in Appearance > Menus, choose to display a language switcher as dropdown.
2. Add the filter:
```php
add_filter( 'pll_the_languages_args', function( $args ) {
	$args['display_names_as']  = 'slug';
	return $args;
} ); 
```
The parent menu item still displays the language name while one can expect to see the language code. The child menu items are ok.

NB: It is also not possible to filter the 'dropdown' option, neither for menus, nor for widgets.

**Comment by stratboy** [comment]
To follow up the past mails:

- I found out that there are several args that do not work via pll_the_languages_args, not monly that one. 

- Also pll_the_languages filters doesn't work at all.

These apply only when the lang menu is created via admin.
I'm currently using the Uncode theme (https://undsgn.com/uncode/), but I don't think the problems comes from the theme.

- Also, there are important inconsistencies in how the dropdow menu gets written when created via admin (in this case is nested UL lists) VS when instantiated via pll_the_languages (in this case is a SELECT element). I suggest to use lists all the way, for easier styling, or, to add a new 'type' option (select vs list).

**Comment by Chouby** [comment]
The filter `pll_the_languages` is for the widget only (or the `pll_the_languages` template tag if you don't use the `raw` option) otherwise it is not passed.

The "dropdown" option has been added due to a high demand among users but is indeed not a `<select>`. Think to it as menu item + sub menu items. The way it is displayed is totally dependent on the theme. The goal is that it fits correctly in most themes.

**Comment by strarsis** [comment]
+1, `pll_the_languages` is also not used for the menu switcher.
It would be nice if there is a filter for it so I can adjust the flags as in the widget.
