### ISSUE TITLE
`remove_accents()` does not work in `de_DE`

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#24]
[`remove_accents()`](https://developer.wordpress.org/reference/functions/remove_accents/) converts letters like ö, ä, ü to oe, ae, ue. for `de_DE` languages.

Currently this does not work unless the site language is set to `de_DE` in the general settings.

**Comment by Chouby** [comment]
This function is problematic in a multilingual context.
Let's take: chr(195).chr(132)
It must be converted to 'A' in the general case and to 'Ae' in German. That means that we have to be sure of the language of the current content being edited. And that's not always obvious.
For posts and terms, solving #19 may help. For other types of content, we can't be sure.

Moreover, the function has no filter. That means that we have to filter sanitize_title and sanitize_user and redo the complete work, possibly wrongly done by WP.

**Comment by grappler** [comment]
For me it would be sufficient for it work with posts and terms. I am currently using the filter `sanitize_title` so I have a working solution at the moment for the site.
