### ISSUE TITLE
Conflicts Plugin PayPalPlus 

### ISSUE THREAD

**Issue by ingofrost** [polylang/polylang#241]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install: woocommerce, paypalplus, polylang (with language attribute in url)
2. Buy a product, use payment system (you are redirected to paypal)

## Expected behavior and actual behavior

3. After you finish the payment, you except to be redirected to the
shop, BUT these two things happen:
- Polylang v2.3.3 
-- Redirect falils (404 Page)
--In your browser you see the URL [TLD]/wc-api/paypal_plus/?paym[...]
--If you change it by hand to [TLD]/de/wc-api/paypal_plus/?paym[...]
the expected "thanks for your payment" Page from Woocommerce is loaded.

- Polylang v2.3.4 
- You are somehow redirected to another payment method on paypal
without any error message..

**Comment by Chouby** [comment]
The compatibility with WooCommerce or WooCommerce extensions is not handled in Polylang but in specific addons.
