### ISSUE TITLE
PHP constants

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#242]
Does Polylang also initialize PHP constants like `LC_MONETARY`?
Some functions like [`money-format`](http://php.net/manual/en/function.money-format.php) use these constants for formatted money output.
Does Polylang provide localization functions for money/currency formatting?

**Comment by Chouby** [comment]
No it doesn't. WordPress does not use this constant or this function. I don't know for all e-commerce plugins, but as far as I know WooCommerce doesn't either (and implements its own currency formatting).
