### ISSUE TITLE
acf taxonomy fields overwrite other languages

### ISSUE THREAD

**Issue by elnicknamio** [polylang/polylang#244]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. install wordpress 4.9.5, polylang 2.3.4 and acf pro 5.6.10
2. add a second language
3. add acf taxonomy fields to a custom post type
4. translate the acf field group for polylang
5. set taxonomy field content in both languages
6. taxonomy fields override each other in the other language

**Comment by Chouby** [comment]
Most probably you activated the sychronization of custom fields.

**Comment by merelyigor** [comment]
Were you able to solve this problem? I just ran into the same problem and am looking for solutions

**Comment by merelyigor** [comment]
https://monosnap.com/file/ExfqJ1hWpZXcoRVxmVCpfMy79I73Nb
https://monosnap.com/file/54Ovb6SZFYr8zQZZajFeKQxNYSFHX9
