### ISSUE TITLE
Translated Pages in Blank with Yoast SEO 7.0 7.1

### ISSUE THREAD

**Issue by techprimeweb** [polylang/polylang#245]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1.  WIth Yoast SEO 6.3.1; Polylang traslated pages works fine 
2.  When updating to Yoast SEO 7.0 or 7.1 the translated pages are in blank with missing content
3.  Roll back Yoast SEO to 6.3.1 and all pages working as should.

I contacted Yoast SEO support and was advice to contact your support.

**Comment by Chouby** [comment]
I don't reproduce any issue with Yoast SEO. 
* Could you detail the steps to reproduce the issue?
* Could you provide any error message obtained with WP_DEBUG set to true in wp-config.php?
* Could you test with the latest versions of the 2 plugins (Yoast SEO is now 7.2 and use the latest version of Polylang).
* Could you test with a default theme (Twenty Seventeen) and no other plugins activated?
