### ISSUE TITLE
PLL_COOKIE', false not working with W3 Total Cache plugin

### ISSUE THREAD

**Issue by petrhasalik** [polylang/polylang#248]
## Prerequisites
- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open the website
2. Check the dev console
3. See that Polylang cookie is being saved

## Expected behavior and actual behavior
Polylang cookie should not be saved

define( 'PLL_COOKIE', false); does not work
pll-config.php in the ‘/wp-content/polylang/’ directory  does not work

How can I archieve so that Polylang will not save any cookies? There is not such option in the plugin config. 

I only have 2 websites = 2 domains and I want to switch between them (incl. subpages) using language flag icons, so there is absolutely no need to save cookies. I need it to be fully compliant with GDPR.

Thanks.

**Comment by Chouby** [comment]
I am using pll-config.php every day. I just checked the constant `PLL_COOKIE` and it works for me. Check that you spelled correctly the directory and file names. Check your file permissions to. Otherwise yo can use the file wp-config.php to set the constant.

**Comment by Chouby** [comment]
It's possible that there is an issue with cache plugins as the cookie is then not set the same way (js instead of php). I'll look into this.

**Comment by Chouby** [comment]
Could you test with the master branch?

**Comment by petrhasalik** [comment]
Thanks Chouby, it seems to be working now. Are you going to add this fix into the next update?
