### ISSUE TITLE
Deleted post meta with last update

### ISSUE THREAD

**Issue by jiappo** [polylang/polylang#251]
I don't understand why, but i had a weird problem with last update (v. 2.3.4) of the library:

loading (it's not a typo error, it's appen when i loading an admin page... ) the admin page for manipulate custom post type, some post_meta were lost; the first time the value of field was shown but deleted from database (to notice: not all of the post_meta were lost).
An example of post meta name that incur in error is "sezione_titolo".

I verified that restoring the changes to the file admin-base.php everything works correctly.

line 118: 'post'  => array( array( 'post', 'media', 'async-upload', 'edit' ), array( 'jquery', 'wp-ajax-response', 'post', 'jquery-ui-autocomplete' ), 0, 1 )

**Comment by Chouby** [comment]
Could you explain step by step how to reproduce the issue?
