### ISSUE TITLE
PLL_Admin class should be used in CLI context

### ISSUE THREAD

**Issue by swissspidy** [polylang/polylang#255]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Run a command using WP-CLI.
2. Notice that `PLL()` returns an instance of `PLL_Settings`.
3. Notice that both `PLL_ADMIN` and `PLL_SETTINGS` are `true` when using WP-CLI.

## Expected behavior and actual behavior

I was expecting `PLL()` to return an instance of `PLL_Admin` after #185.

However, due to the `elseif` later on, `PLL_Settings` is used nonetheless:

https://github.com/polylang/polylang/blob/d44cdfd0b50caf5b0b5b0a8fbbfba77171add829/include/class-polylang.php#L179-L188

I feel like `PLL_Settings` should be `false` in CLI context. If you want to to modify posts, e.g. by creating media translations, one needs the models available in the `PLL_Admin` class.

I might be wrong though, so feedback welcome :-)

**Comment by swissspidy** [comment]
It looks like this has some implications for the Polylang Pro plugin as well.

The `Polylang_Pro` class runs this:

```php
if ( ! $polylang instanceof PLL_Frontend && $polylang->options['media_support'] ) {
	$polylang->advanced_media = new PLL_Admin_Advanced_Media( $polylang );
}
```

The `PLL_Admin_Advanced_Media` class in turn accesses `&$polylang->filters_media`. Only the `PLL_Admin` class has that property, not the `PLL_Settings` class.

The `instanceof` check should be changed to make sure it's a `PLL_Admin` object.

**Comment by Chouby** [comment]
I re-read the code and don't see how `PLL_SETTINGS` could be true, with only Polylang. Are you using https://github.com/diggy/polylang-cli ? This plugin does set `PLL_SETTINGS` to true.

**Comment by swissspidy** [comment]
D'oh 🤦‍♀️ I installed that package a while ago but haven't used it at all. But since it defines `PLL_SETTINGS` directly, it affected my own command as well..

**Comment by swissspidy** [comment]
Changing `! $polylang instanceof PLL_Frontend` to `$polylang instanceof PLL_Admin` might still be good though.

**Comment by Chouby** [comment]
You are right. There is no reason to have this property for PLL_Settings. The same for duplicate and sync_post. I will change this. Thanks.
