### ISSUE TITLE
Single cpt posts where translation is deactivated give 404

### ISSUE THREAD

**Issue by rinusvandam** [polylang/polylang#264]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang and activate languages
2. Register a custom post type
3. Disable translation for custom post type (through settings)
4. Create a new post (in custom post type)
5. On the front end you will see the post on an archive page
6. Clicking the post on the archive page (to single page) will show 404

## Expected behavior and actual behavior

The problem: single cpt posts where translation is deactivated give 404.

A workaround:
1. Enable translation for the custom post type
2. Set a language for the post (because there i none set)
3. Disable translation for the custom post type
4. Single post is working on the front end

It seems that when disabling the translation for a specific post type the posts are not working on the front end. You have to set a language for each posts to get them working.

**Comment by Chouby** [comment]
This works as expected on my test install. You probably forgot to refresh the rewrite rules after you registered your custom post type, which is something you must do whether Polylang is activated or not.
