### ISSUE TITLE
Categories pages return 404 if I choose permalink URL

### ISSUE THREAD

**Issue by macnux** [polylang/polylang#267]
- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. From URL modifications setting, select:  **The language is set from the directory name in pretty permalinks** then save.
2. Now try to browse any **translated category**, it will **return 404**. like http://localhost/es/cat1
3. If you choose:  **The language is set from content**, it will **work without problems.** http://localhost/category/

This image shows the options i'm talking about in the control panel.
https://imgur.com/a/C0AUdK6

Something I noticed while debugging the code:
When choosing: **The language is set from content**
The sent query is:
```
SELECT SQL_CALC_FOUND_ROWS  lg_posts.ID FROM lg_posts  LEFT JOIN lg_term_relationships ON (lg_posts.ID = lg_term_relationships.object_id)  LEFT JOIN lg_term_relationships AS tt1 ON (lg_posts.ID = tt1.object_id) WHERE 1=1  AND ( 
  lg_term_relationships.term_taxonomy_id IN (6) 
  AND 
  tt1.term_taxonomy_id IN (12)
) AND lg_posts.post_type = 'post' AND (lg_posts.post_status = 'publish') GROUP BY lg_posts.ID ORDER BY lg_posts.post_date DESC LIMIT 0, 10
```
Which return result ofcourse.

And when chosing: **The language is set from the directory name in pretty permalinks**
The sent query is:
```
SELECT   lg_posts.* FROM lg_posts  WHERE 1=1  AND lg_posts.post_name = 'administracion-del-servidor' AND lg_posts.post_type = 'post'  ORDER BY lg_posts.post_date DESC
```

Which return nothing, It's really weried!! It checks the post_name with the category name!!!! This is the error come from.

Regards,

**Comment by Chouby** [comment]
It works as expected for me. Did you make your test with only WordPress + Twenty Seventeen + Polylang?

**Comment by macnux** [comment]
I got it.
The plugin called AMP for WP (Accelerated Mobile Pages) cause that error.
I hope I can find alternative one without conflicts.

Thanks for the hints.
