### ISSUE TITLE
404  Not found in permalinks

### ISSUE THREAD

**Issue by Arbildo** [polylang/polylang#275]
Hello, i just installed polylang, everithing looks good, but i got a issue.

I had the next permalink structure /tours/<<name-tour>>
It is a commerce Product

I try to open a tour page and i get 404 not found error.

I can see every page, even /tours/.

But i can't see  /tours/<<name-tour>>

Am I missing something?

Thanks

**Comment by Chouby** [comment]
For support, please use the WordPress community support forum. Note also that Polylang needs an addon to work with WooCommerce.
