### ISSUE TITLE
help needed after self migrating to wordpress+polylang

### ISSUE THREAD

**Issue by eliazu** [polylang/polylang#276]
hello,
i would really appreciate your help.

i used to have a website written in drupal,
and i made a migration by myself with sql insert queries.
the website was multilingual of course.
when i looked into the wp_terms, wp_term_relationships, and wp_term_taxonomy, i figured out all the connection needed, but not the data of the "pll_*******" value in the wp_terms table.

from what i understand, its a serialized value of the description field of `wp_term_taxonomy` where the taxonomy is "post_translations".

my situation is that:

1. new posts works great.
2 . if im in edit mode of a post i can see the migrated values of the translation, but its get affected only if i click the"update" button, which make the "pll_*******" serialized value to be created in the  wp_terms table.

my problem is that i have thousands of posts i need to fix that for them and i cant find any way to do that.
i tried making a script that will go all over the posts and update them,
but it worked very slowly and stopped after 20 posts.

`

      $query = new WP_Query( array(
    'post_type' => 'post',
    'order' => 'ASC',
    'posts_per_page' => '10000',
    'post_status' => 'publish',
    //'orderby' => 'publish_date',
    'order' => 'ASC',
    'paged' => '1',
    'nopaging' => false
) );

foreach ($query->posts as $post) {
        echo $post->post_name . '<br />';
          $post_to_update = array();
          $post_to_update['ID'] = $post->ID;
          wp_update_post($post_to_update);
          $update_count+=1;
	  
      }
`

any idea?
can you help me understand how can i use your functions in the script so all my missing  wp_terms will be created?

thank you!

**Comment by Chouby** [comment]
You can let Polylang create the translations groups properly with `pll_save_post_translations`. But if you are looking for a fast method, you may use direct SQL queries. You can inspire yourself from what has been done for the migration from WPML. See https://github.com/polylang/wpml-to-polylang/blob/0.2.4/wpml-to-polylang.php#L351-L404. You may need to tweak your PHP memory limit and MySQL buffer size.

**Comment by neoswf** [comment]
Hey guys, I reflected about this matter and I found out that my problem was probably caused by bad maintenance of the sql's tables. Hope thats the case. Ill take out a backup from the dungeons and try to solve my problem by using the proper WP methods. 
Thank you guys for all the good will and assistance.
