### ISSUE TITLE
Misconfigured title attribut in the language switcher leads to displaying code on MouseOver

### ISSUE THREAD

**Issue by felix7718** [polylang/polylang#277]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issne latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue (tested browsers: Firefox + Chrome)

1. Install WP + Polylang
2. Use a language switcher in a menu
3. Hover with the mouse over the name of the currently selected language (or in the dropdown as well)

## Expected behavior and actual behavior
Hi there,
If u do the steps in order to reproduce the issue you will see an image similar to this one:
![polylang - current title](https://user-images.githubusercontent.com/40953162/42420332-8d34d4b0-82c4-11e8-827c-fa3800583b78.png)

The whole code of the base64 encoded image is displayed. This should be altered in my opinion as I expected simply the display of "Deutsch" in this case. When hovering over the flag "Deutsch" is displayed already so I really don't know why the title attribut contains the same code which is used inside the <a> element. I changed the title attribute in the browser inspector and achieved to resolve the issue while keeping the same visual appearance:
![polylang - enhanced title](https://user-images.githubusercontent.com/40953162/42420345-c04a3476-82c4-11e8-80e5-0e82ea2437d1.png)

I hope I haven't overseen any reason for the current state of the title attribut and would suggest to tag this issue as enhancement :) 

Best regards, Felix

**Comment by Chouby** [comment]
Unfortunately there is nothing I can do in Polylang. The issue is in your theme which uselessly and wrongly duplicates the item content in the title attribute. As the item includes an image, this leads to the ugly result you are seeing. Even if the item contains only text, there is absolutely no need to duplicate it in the title attribute. Either you don't display the flags or you ask the theme author to fix this issue.
