### ISSUE TITLE
Custom flag images (theme/location/discovery)

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#279]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

[According to the Polylang docs](https://polylang.pro/doc/can-i-use-my-own-flags-for-the-language-switcher/), it is possible to let it use custom flag images. 
This involves copying the custom images to a WordPress-specific folder.

Is it also possible to place these custom flag images in a theme and let Polylang discover them?
This would be much better because this aspect is actually one that could/should 
be controlled by the theme.

Regardless of location for the flag images: Can also SVG image files (*.svg) be used as custom flag images?

**Comment by Chouby** [comment]
The possibility to add custom flags in the `wp-content/polylang` directory had been added for the end users using themes which are not specifically commpatible with Polylang. I expect that a theme author who is willing to use custom flags will most probably design a custom language switcher and thus doesn't specifically need that these flags are known to Polylang.

Only jpg and png flags are currently supported by the language switcher provided by Polylang. But there is of course no limitation for a custom language switcher. 

Related: #62

**Comment by strarsis** [comment]
Please note that Polylang caches the language selector markup, if custom flags have been added and/or a filter as `pll_custom_flag` used, the transients and cache should be flushed, so the new flags and filters are applied to the markup:
````
wp transient delete --all && wp cache flush
````
