### ISSUE TITLE
Documentation pll_get_post and pll_get_term not correct

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#28]
The doc says it should return `null` if no translation could be found, but it returns `false` instead

**Comment by Chouby** [comment]
You are right. It returns `null` only when you don't use the language argument and the the current language has not been defined yet. Maybe I should use `false` in that case too, to simplify.

To be honest, I used such returned values `false`, `null` in a bit inconsistent way at the beginning of Polylang's life. I tried to fix and simplify that but such inconsistencies may still remain.

**Comment by JoryHogeveen** [comment]
Ah ok, no problem! We've found this issue with the Pods compat for Polylang, just wanted to let you know :)

**Comment by Chouby** [comment]
I believe that there is something to fix as we can have both false or null which is undocumented.

**Comment by JoryHogeveen** [comment]
Oh yeah sorry, forgot the issue list is also a kind of task-list
