### ISSUE TITLE
pll_get_flag filter isn't used (for language switcher/on frontend)

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#280]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add a Polylang Language switcher widget to a theme sidebar.
2. Add a filter handler for the `pll_get_flag` filter (e.g. to theme or active plugin).
3. Load the frontend page (width sidebar that contains the language switcher), 
notice that the filter handler is not called.

## Expected behavior and actual behavior
The filter handler for filter `pll_get_flag` should be called and its output used for the flag HTML (markup).

```php
function theme_flags($flag) {
    return 'test';
}
add_filter('pll_get_flag', 'theme_flags', 10, 1);
````
(You can also add a debug log/print, exit or debugger breakpoint, 
in either case the filter hander cannot change the markup of the flags.)

Related issue: https://github.com/polylang/polylang/issues/279

**Comment by Chouby** [comment]
It works for me. All langages data are cached in a transient. You must refresh the transient for your changes to take effect. You can do ithis for example by resaving your url modifications in Languages > Settings.

**Comment by strarsis** [comment]
@Chouby: Thanks! This explains the behaviour. Is there a way to clear exactly these transients when the theme is activated?

**Comment by Chouby** [comment]
You can directly call `delete_transient( 'pll_languages_list' );`

**Comment by oligoform** [comment]
even if i do it like @Chouby said: "You can do ithis for example by resaving your url modifications in Languages > Settings." the `pll_get_flag` doesn't work for me.
i want to use .svg instead of the small inline png.
My code:
```
function olg_get_flag( $html, $slug ) {
  $html = '<img src="' . get_stylesheet_directory_uri() . '/flags/' . $slug . '.svg" />';
  return $html;
}
add_filter( 'pll_get_flag', 'olg_get_flag', 10, 2 );
```

**Comment by strarsis** [comment]
@oligoform: This may be helpful for you as a workaround: https://github.com/polylang/polylang/issues/279
