### ISSUE TITLE
Copy featured image

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#282]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. With media translation disabled, set a featured image for a post in particular locale.
2. Go to different locale translation for the same post, notice that the featured image is not used there.

## Expected behavior and actual behavior

Featured image is also applied to all other locales for same post.
No different ("translated") featured image should be used among locales for same post, 
it should be just set once by user and then apply too other locales as well.

Is it possible to set copy for featured images in `wpml-config.xml`?

Edit: Apparently it is possible with `wpml-config.xml`:
```xml
<wpml-config>
    <custom-fields>
        <custom-field action="copy">thumbnail_id</custom-field>
        <custom-field action="copy">_thumbnail_id</custom-field>
    </custom-fields>
</wpml-config>

````

**Comment by Chouby** [comment]
It works for me. Here is the code which adds the meta key `_thumbnail_id` to the metas to copy: https://github.com/polylang/polylang/blob/2.3.8/modules/sync/sync-post-metas.php#L54-L58

Your wpml-config.xml doesn't only copy the meta but synchronize them (each time you save a post, the trnslations are updated). For `_thumbnail_id`, there is an option in Languages > Settings > Synchronization to obtain the same result.
