### ISSUE TITLE
Displaying both current language and non-translatable CPT items

### ISSUE THREAD

**Issue by mgibbs189** [polylang/polylang#283]
## Prerequisites

- [x] This is not a usage question.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

Hey @Chouby 

I'm the author of FacetWP and we've been running into an issue with our [Polylang integration](https://github.com/facetwp/facetwp-polylang/).

## Setup

`cpt_1` -- translations enabled
`cpt_2` -- transations disabled

```php
$query = array(
    'post_type' => array( 'cpt_1', 'cpt_2' ),
    'posts_per_page' => 10,
    'lang' => 'fr'
);
```

## Issue

The above query will only return French items from `cpt_1`.

We'd had several customers wanting that query to return French `cpt_1` items *and* any `cpt_2` items (since `cpt_2` has translations disabled).

Does Polylang support such a "fallback"?

Thanks, and nice work w/ Polylang.

**Comment by Chouby** [comment]
As far as I know, this is not possible. Here the 'lang' parameter is a taxonomy. And as far as I know, WP_Query doesn't allow to apply the tax_query only to post types registered in the taxonomy and not to others. The only way I see to achieve this, would be to have 2 different WP_Query, one on translated post types and the other on untranslated post types.

**Comment by mgibbs189** [comment]
Okay, thanks for the clarification @Chouby
