### ISSUE TITLE
Languages dispalyed as Classified-Categories of a Classified-Theme in WordPress 4.9.8

### ISSUE THREAD

**Issue by Vongsi** [polylang/polylang#284]
Dear All

When I tried to use Polylang plugin to create multi languages on one of my WordPress (Using Classified-Theme) website, but after activated the plugin and setup new languages these languages be come displayed as the Classifieds Categories

Please see details below

## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Latest WordPress
![image](https://user-images.githubusercontent.com/1546091/43677351-ccb70024-982a-11e8-8ca1-b40723ab4f2c.png)

2. Install the Classified Theme

3. Install Polylang
![image](https://user-images.githubusercontent.com/1546091/43677356-e8786d16-982a-11e8-83be-60eef98e0bef.png)

4. Active and setup/created two new languages
![image](https://user-images.githubusercontent.com/1546091/43677384-3c16c29c-982b-11e8-8041-0237733432ed.png)

Below is the screenshot showing that Languages is displayed as Categories of a WordPress Classified Theme

![image](https://user-images.githubusercontent.com/1546091/43677325-6c5b4d02-982a-11e8-965a-b4a65cde7d85.png)

Please note that when deactivated Polylang plugin the site/theme is working correctly.

![image](https://user-images.githubusercontent.com/1546091/43677441-266ad9d2-982c-11e8-9229-5712955cff9a.png)

![image](https://user-images.githubusercontent.com/1546091/43677484-d4d18c6e-982c-11e8-8274-81ee1696d57c.png)

## Expected behavior and actual behavior

When I follow those steps, the site should still showing its categories instead of showing languages as its categories

![image](https://user-images.githubusercontent.com/1546091/43677484-d4d18c6e-982c-11e8-8274-81ee1696d57c.png)

Thanks and appreciate for your help

**Comment by Chouby** [comment]
This is an issue with the themes displaying private taxonomies. Please ask support to your theme authors and ask them how to display only public taxonomies. The language is a private taxonomy which is not meant to be displayed by the theme. As you can see in https://github.com/polylang/polylang/blob/2.3.8/include/translated-object.php#L24, Polylang taxonomies are registered with the paramter `'public' => false`.
