### ISSUE TITLE
external code for wordpress

### ISSUE THREAD

**Issue by crippledpedal** [polylang/polylang#285]
hello,
firstly this plugin works very well. but I want something very different. immediately speaking.

this is my website: http://www.starhair.mezbilisim.site/en/home/
I added the red spot to the header.php file myself. http://prntscr.com/kf9suk , http://prntscr.com/kf9u3j
actually what i want is very simple. I want to be able to translate the word "example" there. for example; I want you to write "예" here for korean. I want you to write "مثال" here for arabic.

I can edit it here with a function that I need to write. http://prntscr.com/kf9x8t

please come back to me about the subject. very important to me.

**Comment by Chouby** [comment]
The functions to use the strings translations are `pll__` and `pll_register_string`.
In the future, please use the support forum for support questions like this. Please use GitHub only to report bugs.
