### ISSUE TITLE
Disable redirection for search engines?

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#288]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Have a multilingual page, e.g. the front page, using Polylang plugin.
2. Let this site/page be indexed by google.
3. Notice that in a Google SERP (search result page) including this site as result, 
the summary text is shown in English albeit the default site language is different (for the plain TLD).

## Expected behavior and actual behavior

Search engines (e.g. Google) should not be redirected, 
the user searches with keywords in a particular language and then finds the pages that 
contains them but with English text, this may confuse or deter the user navigating to that page.
Apparently the Google Bot either announces its preference for English language or 
it is assumed by Polylang as kind of a default/fallback language.

@Chouby: Can I selectively disable this by filter so bots are not affected by this?

**Comment by Chouby** [comment]
The summary is in English because Google acts as an English visitor. So if your site redirects according to the browser preferred language, then it's expected that Google is redirected to English.

If you don't want any redirect of the homepage you must hide the language code for the default language and deativate the browser preferred language detection.

**Comment by strarsis** [comment]
@Chouby: This redirection feature is really nice! I want it just disabled for visiting robots.

**Comment by Chouby** [comment]
This where the redirect occurs: https://github.com/polylang/polylang/blob/2.3.9/frontend/choose-lang.php#L263-L267. There is a filter that you can use to disable the redirect, based on any condition you want.

**Comment by strarsis** [comment]
I have probably made a mistake anyway, setting the wrong SEO description (Yoast)...
