### ISSUE TITLE
wpml-config.xml override order

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#292]
In what order are `wpml-config.xml` files of plugins applied? Can the order be influenced?

I want to override a [specific setting](https://github.com/NateWr/food-and-drink-menu/blob/master/wpml-config.xml#L10) in a `wpml-config.xml` of a plugin 
using a `wpml-config.xml` of a site-specific plugin, but the setting is ignored.

It works on another site with another named site-specific plugin, 
is the order affected by the name/ID of plugin?

**Comment by Chouby** [comment]
Here is the code showing the order in which files are loaded: https://github.com/polylang/polylang/blob/2.3.10/modules/wpml/wpml-config.php#L47-L71
So yes, plugins loaded first are overwritten by plugins loaded late.

Please use Github to report bugs or possibly for feature requests. For support questions, please use the support forum. Thanks.

**Comment by Chouby** [comment]
I never met such use case. What's yours?
For your own usage, you can already override what's done in a plugin by your child theme or a `wpml-config.xml` located in `wp-content/polylang`

**Comment by strarsis** [comment]
@Chouby: The issue is that a specific plugin already uses a `wpml-config.xml` on 
its own which I want to override with a `wpml-config.xml` in a separate / site plugin.

**Comment by Chouby** [comment]
Which part of the `wpml-config.xml` do you want to override? Maybe you can achieve the same result with filters 'pll_copy_post_metas', 'pll_get_post_types', 'pll_get_taxonomies' with priorities > 10.

**Comment by strarsis** [comment]
@Chouby: The [Food and Drink Menu plugin](https://github.com/NateWr/food-and-drink-menu) uses `copy` action for the column fields. 
Each post translation has its own post ID, hence using the same post IDs across 
translations results in empty post list because the posts don't belong to 
the language the menu is then translated for (and filtered out by Polylang).

This issue can be fixed by replacing the `copy` with `translate` action 
(https://github.com/NateWr/food-and-drink-menu/blob/master/wpml-config.xml#L10-11):
```xml
    <custom-field action="copy">fdm_menu_column_one</custom-field>
    <custom-field action="copy">fdm_menu_column_two</custom-field>
````

```xml
    <custom-field action="translate">fdm_menu_column_one</custom-field>
    <custom-field action="translate">fdm_menu_column_two</custom-field>
````

Related issue: https://github.com/NateWr/food-and-drink-menu/issues/50

**Comment by strarsis** [comment]
@Chouby: Would the `pll_translate_post_meta` filter be used for 
basically emulating the `action="translate"` in the `wpml-config.xml`?
