### ISSUE TITLE
Pro: Tribe Events compatibility - PHP Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#293]
**This is a Pro issue**

## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Bug

`PHP Warning: Invalid argument supplied for foreach() in /wp-content/plugins/polylang-pro/modules/share-slug/share-post-slug.php on line 191

So far I only found this warning when viewing events post types from [The Events Calendar](https://nl.wordpress.org/plugins/the-events-calendar/)
Also note that this site runs on PHP 7.0.31

The warning arises on a foreach loop there you loop through the tax queries.

## Possible solutions

- I _think_ a simple `(array)` cast would be sufficient to solve this issue.
- Or, you could add an `is_array()` validation on the line above. (`if ( isset( $qv['tax_query'] ) && is_array( $qv['tax_query'] ) ) {`)

**Comment by Chrystll** [comment]
Hello Jory,
Could you please give me the steps to reproduce your issue? Do you use the last version of The Event Calendar: 4.6.23? Or another?

**Comment by JoryHogeveen** [comment]
Hello @Chrystll,
Yes I use the latest version.
No idea on the steps to reproduce at the moment as these warnings simply showed in the error logs.
In any case it would be good to verify the type of variable in the `tax_query` key before looping though it as louping can only be done with arrays.

**Comment by Chouby** [comment]
@JoryHogeveen The `tax_query` parameter should always be an array https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters. So this warning may hide a bug somewhere. I already experienced such case in another part of the code (reported on wordpress.org), unfortunately also without knowing more on the causes. I'll fix that in the next version.

**Comment by JoryHogeveen** [comment]
@Chouby 

> The tax_query parameter should always be an array. So this warning may hide a bug somewhere.

Totally agree, I just thought I'd mention this since these parameters are widely used by many developers and not verified by WP itself during filters etc. So unfortunately it's inevitable that the variable type can't be trusted.
I see you've closed this through a private commit, thanks!
