### ISSUE TITLE
get_the_permalink returns non-canonical URLs

### ISSUE THREAD

**Issue by jcracknell** [polylang/polylang#295]
Calling `get_the_permalink` under a non-canonical request URL does not return the canonical URL. `redirect_canonical`'s functionality is broken by extension, which is supposed to redirect requests to non-canonical URLs.

You can observe this behavior using a request to a URL which is non-canonical, but resolvable e.g. `http://my.site/a%20slug/` vs `http://my.site/a-slug/`.

`wp_get_canonical_url` still works as expected.

**Comment by Chouby** [comment]
On a fresh install with only Twenty Seventeen and no plugins with only one post `http://my.site/a-slug/`, `http://my.site/a%20slug/` is 404. `get_the_permalink` returns false. I don't see any different behavior with Polylang.
