### ISSUE TITLE
Is it possible to create posts in other languages via API?

### ISSUE THREAD

**Issue by gelsas** [polylang/polylang#296]
Hello,

Is it possible to create posts in other languages via API?

What I mean is, that I am grabbing content from a database in different languages and I want to use Polylang as my multi language solution. Is it possible to create the posts in all the languages needed via API ?

**Comment by grappler** [comment]
I am not sure which API you are referring to

You can use WordPress functions insert the post into WordPress and including the necessary information regarding the language.

I have previously written code that creates posts from a Drupal Database dump.

You could use `wp_insert_post ()`, `pll_set_post_language()` & `pll_save_post_translations()`. For taxonomies there are also related functions.

**Comment by Chouby** [comment]
@gelsas See https://polylang.pro/doc-category/developers/ for more details.
Also please use GitHub to report bugs. For support questions, please use the support forum, or the helpdesk if you are using Polylang Pro.
