### ISSUE TITLE
There are two problems in our German blog page 

### ISSUE THREAD

**Issue by millertiga** [polylang/polylang#297]
Dear Mr. Frédéric Demarle
Thank you for developing and updating Polylang. We are developers of a website and have some trouble with Polylang.
Our WordPress site uses free version of Polylang. We have English version blog site and German version blog site. And there are two problems in our German blog page (https://reolink.com/de/blog/).

1.The screenshot below is our German blog page. Click the editor name “NICOLA” that is underlined, and it should go to the page where all Nicola’s blogs are listed (https://reolink.com/de/author/sybil/ ). But now it turns out "404 Not Found" page.
![image](https://user-images.githubusercontent.com/21698240/45668935-01b22f80-bb51-11e8-9285-390ad8c84c29.png)

2.Also German blog page. At the end of the blog, click the work “Wissen” marked by red arrow, it should go to the “Wissen” category page (https://reolink.com/de/category/uncategorized/ ), but now it turns out "404 Not Found". 
![image](https://user-images.githubusercontent.com/21698240/45668956-1393d280-bb51-11e8-81e3-ad93541904fb.png)

The two problems exist only in German blog page. English blog page in our site runs perfectly. We want to know if there are any ways to fix it? We would appreciate it if you can give us some advices. Looking forward to your early reply.

                                                                 Sincerely,
                                                                 Miller Lee

**Comment by Chouby** [comment]
Please use GitHub only to report bugs. For support questions, please use the community supported forum.
