### ISSUE TITLE
Deactivated languages appear in XML sitemaps - 404 crawl errors!

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#30]
I'm having a problem with Yoast SEO (and probably other XML sitemap generators) and deactivated languages because they still show in the sitemaps.
Google Search Console reports these as crawl-errors since these pages aren't available when not logged in.

I'd say this feature should use a filter for compatibility to prevent these languages from apearing in the sitemaps.

**Comment by JoryHogeveen** [comment]
Another (quick fix) solution would be to redirect all calls to a post of a deactivated language to the default homepage or corresponding language.

IMO this is a major bug for SEO!

**Comment by Chouby** [comment]
Yes it most probably occurs with all sitemap generator. I am not sure how a filter in Polylang could help.

I would rather believe that removing the inactive urls has to be done in the sitemap plugin, or using filters of the sitemap plugin if there are enough. Which means a different compatibility code for each sitemap plugin.

Redirect to home would be easy (and not dependent on a sitemap plugin) but I wonder if from SEO point of view, it would not be even worse (tons of different links pointing to the same page?)

**Comment by JoryHogeveen** [comment]
Maybe a wild idea... set a post status other that publish for all posts from disabled languages that behaves the same as the publish status for logged-in users viewing the frond end. Maybe even with a filter of some kind.
I dont think xml plugins should hande a feature related to a pro version of a translation plugin.

About the redirect fallback, 302 should be fine I suppose.

**Comment by Chouby** [comment]
Your idea with the post status would work for posts but not for terms.

I had not a true redirection in mind. Maybe there are already some plugins which redirect all 404 to the homepage.

It's up to plugins authors to decide which 3rd party plugins they want to support. It may be easier for a free plugin author to support other free plugins but a lot are supporting paid plugins (such as WPML) too. You will see more compatibility code for WPML than for Polylang, even in free plugins ;-)

For example, the compatibility between Yoast SEO and WPML is handled partly in WPML and partly in Yoast SEO.

Polylang uses the wpml-config.xml included in Yoast SEO and I added compatibility code to correctly handle sitemaps an fix other issues. I will have to dig again in Yoast SEO code to see if I can fix this issue.

**Comment by JoryHogeveen** [comment]
Good point, didn't thought about terms yet.

It's easy to redirect all 404 results to the homepage, but I would think in this case you only want the 404's of a disabled language redirected.

More compat for WPML is not so strange since they are in the field for quite some time now but I get your point :-).

Anyhow
I checked the compat code. It looks like you remove the language filter on line 244-249 in plugins-compat.php when not using multiple domains so the query searches for all languages.
Maybe simply extend this function to check for disabled languages, and if they are found, adjust the filter accordingly.
Not sure if this filter accepts a list of enabled languages instead of just one language though..

**Comment by Chouby** [comment]
Yes for terms, this is the way to go. You can pass a comma separated list of language slugs to `get_terms()`. For posts, I had to use Yoast SEO filters (the same already used for subdomains and multiple domains) as the plugin uses its own SQL queries.

**Comment by JoryHogeveen** [comment]
Looks good, thanks!
