### ISSUE TITLE
Assigning a parent category breaking the hierarchy of translated category

### ISSUE THREAD

**Issue by lambasoft** [polylang/polylang#300]
Hey,

In your latest update (2.3.11) you said that you fixed ” Assigning a parent category breaking the hierarchy of translated category”, but unfortunately its still causing a problem for me.

If I update or assign a parent category to an English category, it breaks the hierarchy of the Arabic category.

The only workaround is assigning the parent category from database manually.

Can you please check it up.

Thanks a lot!

**Comment by Chouby** [comment]
Hello,

Thanks for reporting. I confirm. We missed something.

**Comment by Chouby** [comment]
Hum. I wrote too fast. According to my tests, the master branch is indeed still buggy but the stable version 2.3.11 is working for me. Here are the steps I use to test:
1. Create Child EN
2. Translate Child EN to Child AR.
3. Create Parent EN
4. Assign Parent EN as parent of Child EN
5. Tranlate Parent EN to Parent AR
6. Assign Parent AR as parent of Child AR.
=> In 2.4-dev (master), this breaks the hierarchy between Parent EN and Child EN. In 2.3.11, it works as expected.

If you are still experiencing an issue with the version 2.3.11, could you provide the detailed steps to reproduce?

**Comment by lambasoft** [comment]
@Chouby Sorry for keeping you in the dark, but I see you fixed it!

Thanks a lot mate, after applying the commit it's working great!

**Comment by Hamsterkacke** [comment]
Hey!

Can we reopen this or should i add a new issue? The fix worked for me too, but only if i have a direct parent child relationship. If we go one level down, it doesnt work anymore. Simple example:

Parent DE
 Child DE
  Child-Child DE

Now, when i assign the translation for Child-Child DE in the other language, the DE Translation gets pushed up one level. So it now Child-Child is the Child of Parent DE. So your fix only seem to work for one level of "childness". Can you confirm?

**Comment by eliazu** [comment]
i can confirm that the relationship is really messed up even if its one level and even with version 2.4.1 of today.

**Comment by Chrystll** [comment]
@Hamsterkacke
I just re-tested on my side and I don't reproduce your issue with Polylang 2.4.1. Do you also reproduce your issue by creating new translated categories ? Or does the issue occur only with existing categories?

**Comment by Hamsterkacke** [comment]
I am not quite sure about this. My client added new children categories, i suppose. But the parent categories where already there.

**Comment by Chrystll** [comment]
Could you please give me the specific steps to reproduce your issue? You can show me them thanks to a video or some detailed screenshots. If you provide me some screenshots, please don't remove the left admin menu as the admin tool bar (top bar). I would need to see also the "Count" column on the Categories list.

**Comment by eliazu** [comment]
oh god, it was my redis cache that gave me the wrong results.
sorry.
thank you
