### ISSUE TITLE
Domain mapping and directory’s

### ISSUE THREAD

**Issue by vipii** [polylang/polylang#302]
Is it possible to have domain mapping and also directory mapping?

In my case my client has 6 languages
1) Dutch for Belgium
2) French for Belgium
3) French for France
4) Dutch for The Netherlands
5) English for United Kingdom
6) German for Germany

I want to do the following:
1) www.domain.be
2) www.domain.be/fr/
3) www.domain.fr
4) www.domain.nl
5) www.domain.co.uk
6) www.domain.de

Can this be done? And how? :-)

**Comment by vipii** [comment]
Any news on this?

**Comment by Chouby** [comment]
This is not possible. Directories and domains work in a totally different way.

Please use GitHub only to report bugs and use the wordpress.org for support questions (I answered to this one many times).
