### ISSUE TITLE
WP-Sweep compatibility

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#303]
Anyone using WP-Sweep?

See how not to sweep Polylang's taxonomies: https://github.com/lesterchan/wp-sweep/issues/40#issuecomment-429035041

**Comment by Chouby** [comment]
It's already there since version 2.0. See https://github.com/polylang/polylang/blob/2.3.11/modules/plugins/plugins-compat.php#L45
The filter was created for Polylang.

**Comment by szepeviktor** [comment]
@Chouby Thanks.
Good to know.

**Comment by JennJe** [comment]
If you're using Polylang, can you use WP-Sweep to clean up revisions, deleted posts and comments?
