### ISSUE TITLE
Updating a page breaks polylang URL settings in multisite (WPMU)

### ISSUE THREAD

**Issue by antonvh** [polylang/polylang#305]
## Prerequisites
- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set URL settings to this:
<img width="1085" alt="screen shot 2018-10-18 at 13 41 24" src="https://user-images.githubusercontent.com/355996/47152243-6d1c2800-d2dc-11e8-826b-d77d449273e9.png">

2. Settings work perfectly after switching language. Nice! Great feature!
<img width="455" alt="screen shot 2018-10-18 at 13 41 38" src="https://user-images.githubusercontent.com/355996/47152281-8e7d1400-d2dc-11e8-87eb-48bb888156c3.png">
<img width="391" alt="screen shot 2018-10-18 at 13 41 46" src="https://user-images.githubusercontent.com/355996/47152288-9341c800-d2dc-11e8-9cbf-c4195e86f47b.png">

3. But... as soon as I edit and publish one of the front pages, the setting breaks:
<img width="288" alt="screen shot 2018-10-18 at 13 43 16" src="https://user-images.githubusercontent.com/355996/47160976-5fbd6880-d2f1-11e8-9b2c-c8bbbb3444c9.png">

<img width="470" alt="screen shot 2018-10-18 at 13 50 29" src="https://user-images.githubusercontent.com/355996/47152384-d56b0980-d2dc-11e8-8aa9-871244ab0e46.png">
The language switch redirects to the main domain, instead of the domain alias.

## Expected behavior and actual behavior

4. When I change the URL setting to 'language is set from domain names', save and back to 'language is set from content' my URLS look great again. Until I edit a front page. Then it all breaks.

**Comment by antonvh** [comment]
I'm using Mercator for setting the domain aliases, by the way. Works great on all single language websites.

**Comment by Chouby** [comment]
Does it work without Mercator and no other plugins?
Does it work with WordPress MU Domain Mapping?

**Comment by antonvh** [comment]
Disabling Mercator, all plugins and Wordpress MU Domain Mapping works. But that's no surprise as this reverts to the broken folder urls from point 3 in my bug report above by default.

From there on enabling Wordpress MU Domain Mapping makes matters much worse than using Mercator: at this point the polylang language homepage of the subsite redirects to the homepage of the master domain.

In my case: https://agilegroei.nl/en/ redirects to https://vanhoucke.nl/wordpress/en/ this is not just an ugly url, it's the wrong page altogether!

**Comment by antonvh** [comment]
I think I found a stable solution. The problem lies in the fact that if you update site settings with WP Multisite under Network Admin > Sites, that _these settings do not take effect until you republish your homepage_

With this combination of settings my multilanguage multisite setup works for having multiple languages under each domain alias.

Under Network Admin > Sites > Edit site I entered:
Info tab > Site URL: https://maindomain/wordpress/subsitename/
Settings tab > Site URL: https://maindomain/wordpress/subsitename/
Settings tab > Site Home: https://subsitename.com/
Aliases tab > Add and activate aliases for subsitename.com and www.subsitename.com

_Now republish the homepages_

Clear all cookies in your browser.

Configure Polylang as in my first screenshot in this issue.

Voila. Workses!

**Comment by Chouby** [comment]
> The problem lies in the fact that if you update site settings with WP Multisite under Network Admin > Sites, that these settings do not take effect until you republish your homepage

Understood! An action done in the network settings is not known by Polylang. As home pages urls are cached in a transient, you need to reset the cache after the change in the settings. It's what you did by re-publishing the home page. This should also work by re-saving the URL modifications in Polylang settings.
