### ISSUE TITLE
Wrong slug for page 

### ISSUE THREAD

**Issue by Giacomo92** [polylang/polylang#306]
Hi everyone,
I created two page with the same title one in Italian and one in English.
I have noticed that the slug is incorrect, infact it contains the "-{post-id}" at the end.

Page in Italian (My default language)
![schermata 2018-10-19 alle 15 58 00](https://user-images.githubusercontent.com/11694429/47222937-4cc19b80-d3b8-11e8-9a66-67291742a811.png)
Page in English with id in the slug
![schermata 2018-10-19 alle 15 58 10](https://user-images.githubusercontent.com/11694429/47222938-4cc19b80-d3b8-11e8-92ee-1d315db2c8c5.png)

How I can fix this slug?

**Comment by Chouby** [comment]
The answer to your questio is in the FAQ: https://polylang.pro/doc/can-posts-or-terms-share-the-same-url-slug-across-translations/. This feature is available in Polylang Pro.
