### ISSUE TITLE
Add custom label for the Language Switcher menu item

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#307]
**Currently**
![image](https://user-images.githubusercontent.com/1785641/47223588-ec335e00-d3b9-11e8-95be-ddaae5376e5f.png)

**With custom code**
![image](https://user-images.githubusercontent.com/1785641/47223778-5815c680-d3ba-11e8-86ad-64d2b7aaf670.png)

Instead of the label stating "Custom Link" we can change the label with the following code.
```php
add_filter( 'wp_setup_nav_menu_item', function( $menu_item ) {
	if ( $menu_item->url === '#pll_switcher' ) {
		$menu_item->type_label = __( 'Language Switcher', 'polylang' );
	}
	return $menu_item;
} );
```

I was not sure where best place the code so that is why I sharing the code in the issue.

**Comment by Chouby** [comment]
It looks good under Appearance > Menus. But it doesn't look so good in the customizer. 
![customizer_language_switcher](https://user-images.githubusercontent.com/3238583/51635979-5b3fc600-1f58-11e9-8a33-8b64e49fd767.png)
I propose to use "Languages" instead of "Language switcher". What do you think?

**Comment by grappler** [comment]
This is how it would look like in German.
![image](https://user-images.githubusercontent.com/1785641/51639208-a1008c80-1f60-11e9-965d-067d69189d7f.png)

I would propose to change the menu title to "Languages" instead of the grey label. So something like this:
![image](https://user-images.githubusercontent.com/1785641/51639328-ef159000-1f60-11e9-977b-8dc26bfa5922.png)
