### ISSUE TITLE
pll_get_term() returns random term in case of missing translation instead of false

### ISSUE THREAD

**Issue by krishaamer** [polylang/polylang#308]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [ ] [Didn't check] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. call pll_get_term() on a custom taxonomy term_id
2. in case of non-existing translation a random term in the other language is returned
3. implemented a workaround using pll_get_term_translations() which returns only existing terms

**Comment by Chouby** [comment]
I don't reproduce. For me the function returns `false` as expected. The value returned by this function should be decided in https://github.com/polylang/polylang/blob/2.4/include/translated-object.php#L210 where `false` is returned if no translation is found. Did you test with a default theme and no other plugins activated?
