### ISSUE TITLE
Non standard port urls are redirected to standard port

### ISSUE THREAD

**Issue by sidewaysdesign** [polylang/polylang#31]
An initial tag search result page returns fine with Polylang active, but when clicking on a pagination link, the port is trimmed from the URL, causing link failure.

Deactivating Polylang restores working pagination links. 

For example, the pagination link is:
http://127.0.0.1/wordpress/tag/artists-performers/page/2/

when it should be:
http://127.0.0.1:8081/wordpress/tag/artists-performers/page/2/

After much troubleshooting, I found what seems to be a fix, on line 360 of frontend-filters-links.php.

Original:
$redirect_url = ( ! $redirect_url = redirect_canonical( $requested_url, false ) ) ? $requested_url : $redirect_url;

As I understand it, the ternary operator in the line tries to compare $redirect_url and redirect_canonical, but up to that point in the function, $redirect_url is undefined, so any comparison would be expected to fail. Changing $redirect_url to $requested_url in the ternary operator seems to fix things.

Revised:
$redirect_url = ( ! $requested_url = redirect_canonical( $requested_url, false ) ) ? $requested_url : $redirect_url;

Does this fix make any sense, or might it cause problems under other circumstances? If the original line is indeed correct, is there a hook I can use to repair the URL specifically for my site?

Any insight would be appreciated.

Note: I am presently developing on a local server, and do not know if this behaviour would occur on a live server, but I have seen other threads with similar search pagination problems. I have tested with the latest build in GitHub without success.

**Comment by Chouby** [comment]
You could read the original code like this:
```
$redirect_url = redirect_canonical( $requested_url, false );
if ( ! $redirect_url ) {
  $redirect_url = $requested_url;
}
```
I don't believe there is any issue in it.

To clear on your bug report, your problem is that the port 8081 is removed from the url. Am I right?

For the filter you are looking for, 
`add_filter( 'pll_check_canonical_url', '__return_false' );`
should remove the redirection.

**Comment by sidewaysdesign** [comment]
Thank you for the quick reply.

I tried the revised code above. Unfortunately, it does the same thing: the port is still removed from the URL.

However, the filter bypass works, so to get the site working the plugin will not need to be modified. I'll keep an eye on whether the bypasses causes its own issues.

**Comment by Chouby** [comment]
Did you add custom code to make WordPress working on port 8081? Such as this one:
`remove_filter('template_redirect','redirect_canonical');`
As far as I understood (I never tested an install on another port than the default one), the canonical redirection mechanism of WordPress should redirect you to the standard port. And you need to disable the canonical redirection (the remove_filter above). Returning false with the 'pll_check_canonical_url' disables the canonical redirection mechanism of Polylang.
