### ISSUE TITLE
Synchronization not work in Polylang Pro

### ISSUE THREAD

**Issue by phamquangbaoplus** [polylang/polylang#313]
## Prerequisites

- Wordpress 5.0-RC1-43945
- Polylang Pro 2.4.1

## Steps to reproduce the issue

1. Add new post in Vietnamese, set categories, tags, featured image and publish
2. Add english version for this post. 

## Expected behavior and actual behavior

When I follow those steps, I see tags, categories, featured image is not sync. Only Custom fields is sync able.

**Comment by Chouby** [comment]
I confirm. This is a know issue with WP 5.0 (it should still work with WP 4.9.8 + Gutenberg). Polylang 2.4.x is not compatible with WP 5.0. We will soon release a beta version of Polylang 2.5 which will be compatible and will fix this issue. The final release will depend on the WP 5.0 release date which is not announced yet.
