### ISSUE TITLE
Multisite static pages with Polylang, is this an issue?

### ISSUE THREAD

**Issue by rraallvv** [polylang/polylang#315]
I installed Polylang on a multisite setup, no issues here, but when I create two front pages that will function as static pages and select the option **Static Page** from **Settings > Reading Settings**, my base address always redirects to the secondary language. The primary language is set to be located at the base address without the language two letters code, and as the default language on Polylang settings:

Something like this:

With static pages disabled:

```
              I visit                    I get
Language 1    https://example.com        https://example.com
Language 2    https://example.com/xx/    https://example.com/xx/
```

No surprise here, but with static pages enabled:

```
              I visit                    I get
Language 1    https://example.com        https://example.com/xx/
Language 2    https://example.com/xx/    https://example.com/xx/
```

So there is no way I can get to the front page of Language 1

Wordpress 5.0
Polylang 2.5

**Comment by Chrystll** [comment]
Sorry I don't understand your bug report. For a bug report, I need that you answer to all questions you removed from the issue template and also exact steps to reproduce the issue illustrating by screenshots. To well understand the context of your screenshots, please don't remove the left admin menu as well the admin tool bar (top bar).
If I don't reproduce the issue, thus we can't fix it. If this is not a bug report but a support request, please use the community supported forum and close this issue.

**Comment by rraallvv** [comment]
Thanks for looking into this. It seems the issue was solved by wiping the browser cache.
