### ISSUE TITLE
unregister_widget('WP_Widget_Calendar') not work with Polylang

### ISSUE THREAD

**Issue by yarovikov** [polylang/polylang#316]
Hi all.

I use WP 5.0 and Polylang 2.5 with my custom theme.

I have simple function 'unregister_default_wp_widgets' via unregister_widget.

but with Polylang the calendar is displayed in the admin panel.

how can i fix it?

thanks!

<img width="667" alt="screenshot 2018-12-11 at 20 50 44" src="https://user-images.githubusercontent.com/30932012/49819565-d7a28f00-fd86-11e8-9de2-7308ce95ddee.png">

**Comment by Chouby** [comment]
It is already unregistered by Polylang. Because the Widget calendar provided by WordPress is not filterable, Polylang comes with its own calendar widget. See https://github.com/polylang/polylang/blob/2.5/include/base.php#L43-L48
