### ISSUE TITLE
Google Search Console errors: International Targeting | Language > 'zh' - no return tags

### ISSUE THREAD

**Issue by physixfan** [polylang/polylang#317]
Starting from Dec 7, 2018, Google Search Console says I got an increasing number of this error: "International Targeting | Language > 'zh' - no return tags. URLs for your site and alternate URLs in 'zh' that do not have return tags." See screenshot:

<img width="1397" alt="screen shot 2018-12-11 at 21 28 39" src="https://user-images.githubusercontent.com/4311261/49848817-c4de8900-fd8b-11e8-9a6f-70baa04007b2.png">

Is it a serious problem? Or should we just ignore it?

BTW, I did not make any relevant change at all on our site during this time period.

**Comment by Chouby** [comment]
Please read the FAQ: https://polylang.pro/doc/google-reports-error-about-hreflang-attributes/
