### ISSUE TITLE
OEmbed does not work on translated front-page

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#318]
https://olm.hu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Folm.hu%2Fen%2F -> 404 (please load it once as our [firewall](https://github.com/szepeviktor/wordpress-fail2ban/blob/master/mu-plugin/wp-fail2ban-mu-instant.php#L131) will block you)

https://olm.hu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Folm.hu%2Fen%2Fimpressum%2F -> OK!

@Chouby Please advise.

v2.5

**Comment by Chouby** [comment]
I confirm. We did not work at all on embeds

**Comment by szepeviktor** [comment]
Thank you.
