### ISSUE TITLE
Published date synchronization problems with new drafts.

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#32]
When adding a new draft the "published date" doesn't get correctly synchronized.

**Comment by Chouby** [comment]
The date should be synchronized when publishing the post. The chosen date is the last entered.

**Comment by JoryHogeveen** [comment]
That's what I thought but this doesn't work well anymore. The new post overwrites the old one so if I have a post set on 2016-05-05 and I create a translation on 2016-06-06 the new published date gets set on 2016-06-06 instead of 2016-05-05 of the original post.

**Comment by Chouby** [comment]
Yes, it's what I meant. The date is synchronized on the last one you enter, not the original post.

If you attempt to copy the date from the original post in the new draft, WordPress will change the date when you hit the publish button.

**Comment by JoryHogeveen** [comment]
Ah ok, I thought it was the other way around ^^
I'll create my own sync then!

**Comment by grappler** [comment]
@JoryHogeveen I would be interested in seeing the code for that. A simple fix that I found was to bulk edit the posts without making any changes. I aslso thought about using wp-cli to run just `wp posts update 123`

**Comment by JoryHogeveen** [comment]
This looks like it works just fine.
It only works for new drafts and sets the original post date in the post-edit screen for a new draft.
Setting post date to sync is not needed, it works standalone

```php
// Set priority to 9 so this function gets run first
add_action( 'pll_save_post', 'sync_original_post_date', 9, 3 );
function sync_original_post_date( $post_id, $post, $translations ) {
	global $wpdb;
	// from_post is only set for new drafts
	if ( isset( $_GET['from_post'] ) ) {
		$original = get_post( (int) $_GET['from_post'] );
		if ( is_object( $original ) ) {
			$wpdb->update( $wpdb->posts, array( 
				'post_date' => $original->post_date, 
				'post_date_gmt' => $original->post_date_gmt 
			), array( 'ID' => $post_id ) );
		}
	}
}
```

**Comment by Chouby** [comment]
Reopening this for 2.1.

Up to now I did not find a good solution as either it was not possible to manually change the date or WP overwrote what I did before. Your solution just works as expected. Combined with some other fix I already have to avoid displayin "Publish Immediately" in the Publish metabox, it should be OK.
