### ISSUE TITLE
Missing language labels in screen options for posts

### ISSUE THREAD

**Issue by raaaahman** [polylang/polylang#324]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Got to *Posts > All posts*
2. Click the *screen options* tab

## Expected behavior and actual behavior

Two checkboxes are unlabelled, these are checkboxes for my lnaguages (en_US and fr_FR).

I was expecting to see the languages names or flags.

**Comment by Chouby** [comment]
I don't reproduce. See the screenshot.
![screenshot-options](https://user-images.githubusercontent.com/3238583/50761495-d3c13a00-126a-11e9-8f3a-a5305b6e4c4d.png)
Only titles (not flags) should appear as for 2 years WordPress strips all tags. See: https://github.com/WordPress/WordPress/blob/5.0.2/wp-admin/includes/class-wp-screen.php#L1102

**Comment by Chouby** [comment]
Feel free to reopen if you reproduce.
