### ISSUE TITLE
Confused plus icon

### ISSUE THREAD

**Issue by Jntz** [polylang/polylang#325]
Is it possible to change plus icon? It used example in page list page. I'm finnish person and it look like very similar to our flag that I always wondered why finnish flag is there where you can add new language. Just realised that it have to be plus! Maybe also title attribute would be nice too "Add new language" or something like that.

Demonstration image: https://i.ibb.co/0XB441Z/finnish-flag.png

**Comment by Chouby** [comment]
It's indeed possible to change the plus icon to something different via a CSS rule. See the current rule used by Polylang https://github.com/polylang/polylang/blob/2.5/css/admin.css#L270-L272 and https://github.com/polylang/polylang/blob/2.5/css/admin.css#L278-L281.

That said, adding as title attraibute the same text already available for screen readers may be a good idea.

**Comment by Jntz** [comment]
Thanks to reply. I will do that css changes.

**Comment by edwinhuish** [comment]
@Jntz  Could you please share your code? I need it also.
