### ISSUE TITLE
[Urgent] Can’t set multi shop pages in Woocommerce

### ISSUE THREAD

**Issue by thehung2224** [polylang/polylang#329]
Hi,

Please find attached 3 screenshots of the back-end.

Example 1 shows we are in working in the English language and choose shop page in that language. http://prntscr.com/mbcuo2

After saving we went in to the VietNamese language choose another page as shop page this time in VietNamese and saved the settings. http://prntscr.com/mbcuwl

Then if you go back into the English language settings again you see what we show in example 3. That the settings are reset to default and you need to select a page again. http://prntscr.com/mbcv19

Regards,

**Comment by Chouby** [comment]
Polylang is not compatible with WooCommerce. You need a separate addon to make the 2 plugins work together. See the [FAQ](https://wordpress.org/plugins/polylang/#is%20polylang%20compatible%20with%20woocommerce%3F) in the plugin description. Please use GitHub issues to report bugs. And use the support forum to get help.
