### ISSUE TITLE
Share slugs not working correctly for CPT's and main blog page

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#33]
It works just fine for default pages but I have two issues since the last update:

Main posts page (in my case: `/blog/`)
It's no problem to add the correct slug, but on the front-end this doesn't work ( `/en/blog/` gets redirected to `/blog/` ).

CPT (in my case `/product/*`).
All default language products are working: `/product/*` 
But products in other languages don't (404): `/en/product/*`

I am trying to find the problem but so far no luck. Disabling plugins is not helping.

**Comment by JoryHogeveen** [comment]
Not sure why, but it looks like a action order problem.
You hook into the parse_query action, but when I check the query_vars at this point I see a 404 result, not the parameters you use (`pagename` & `name`).
It looks like this action is run to late.

**Comment by JoryHogeveen** [comment]
First issue (`/blob/` vs `/en/blog/`) can be fixed by setting the action priority to 1
`add_action( 'parse_query', array( &$this, 'parse_query' ), 1 );`

**Comment by JoryHogeveen** [comment]
CPT problem was with some kind of cache error... no idea where it came from or how it went wrong but a full removal of all transients and a re-save of the permalinks page did the trick.

**Comment by grappler** [comment]
The same blog slug will be fixed in the next update. When I reported the issue by email it was already fixed. You can ask @Chouby for version 1.9.3.1 which fixed it. I don't think the code is here because it is the pro version.

**Comment by Chouby** [comment]
Yes, the bug was reported just after the release of the version 1.9.3 and It's already fixed in the dev version. And you found the fix yourself.

**Comment by JoryHogeveen** [comment]
Ok perfect, thanks!
