### ISSUE TITLE
Using Jetpack's Featured Content Module Results in Errors

### ISSUE THREAD

**Issue by druesome** [polylang/polylang#330]
Recently a bug was corrected in Jetpack that previously disallowed pages to become tagged as Featured Content in a Gutenberg-enabled Calypso interface.  Some themes, such as [Venture](https://wordpress.com/theme/venture/) and [Dara](https://wordpress.com/theme/dara/), need this to be able to feature pages in the post slider.

The bug was reported here: https://github.com/Automattic/wp-calypso/issues/28975

And was resolved here: https://github.com/Automattic/jetpack/pull/10985

With the current version of Polylang installed and activated on a wesite, using the Featured Content feature in the Customizer results in a 500 error in both wp-admin and front end.  The error looks like:

`PHP Fatal error:  Uncaught Error: Call to undefined function PLL() in /srv/htdocs/wp-content/plugins/polylang/modules/plugins/featured-content.php:124`

To resolve this temporarily we'd need to delete the `featured-content` option from the `wp_options` table and ask the user to refrain from using the Featured Content module.

To fix this, Polylang devs need to apply the same fix mentioned in the pull request to their plugin's copy of Featured Content in `/modules/plugins/featured-content.php`

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install/Activate Dara theme
2. Install/Activate Polylang
3. Visit Customizer > Featured Content, check or uncheck any of the check boxes, or add a tag.
4. Click Publish

## Expected behavior and actual behavior

When I follow those steps, I see...

Site throwing 500 errors.

I was expecting...

Site to load normally.

Thanks in advance!

**Comment by Chouby** [comment]
The themes you are mentioning are available on wordpress.com. Is there a public version of a theme using this Jetpack feature that we could use to test on self-hosted WorPress?

**Comment by RafaelFunchal** [comment]
Hi, @Chouby!

It is possible to download Dara from the [WordPress.com theme page](https://wordpress.com/theme/dara) by clicking on Download here:

<img width="754" alt="download-dara" src="https://user-images.githubusercontent.com/1847217/52878381-9bebc300-3143-11e9-8bdc-abee8f533093.png">

**Comment by Chouby** [comment]
Thanks. I did not noticed that.

**Comment by Chouby** [comment]
I have tested the featured content with pages and posts using WP 5.1 + Jetpack 7.0.1 + Dara 1.2.6 + Polylang 2.5.2 and could not reproduce ant fatal error. Is this still an issue? If yes, could you provide me the steps to reproduce it?

**Comment by crunnells** [comment]
Hey @Chouby, I was able to reproduce the bug pretty reliably:

1. Create a fresh WP install (you can use jurassic.ninja)
2. Search for the Dara theme and install + activate it
3. Search for and install the Jetpack plugin. Activate the plugin _and then connect it_ by clicking the "Set Up Jetpack" button and selecting a free plan. You don't need to activate any features after the plan is selected.
4. Return to the site. Create a couple of posts with a `featured` tag.
5. Go to *Customizer > Featured Content* and add the `featured` tag then publish.
6. Install the Polylang plugin and activate it.
7. See the error on the home page:

> Fatal error: Uncaught Error: Call to undefined function PLL() in /public/wp-content/plugins/polylang/modules/plugins/featured-content.php:124 Stack trace: #0 /public/wp-includes/class-wp-hook.php(288): PLL_Featured_Content->option_featured_content(Array) #1 /public/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /public/wp-includes/option.php(152): apply_filters('option_featured...', Array, 'featured-conten...') #3 /public/wp-content/plugins/jetpack/modules/theme-tools/featured-content.php(590): get_option('featured-conten...') #4 /public/wp-content/plugins/jetpack/modules/theme-tools/featured-content.php(145): Featured_Content::get_setting('hide-tag') #5 /public/wp-includes/class-wp-hook.php(286): Featured_Content::wp_ in /apps/user1cd06595/public/wp-content/plugins/polylang/modules/plugins/featured-content.php on line 124

**Comment by Chouby** [comment]
Thank you @crunnells. Now I understand why I did not reproduced. In fact the fatal error occurs when no languages have been defined yet. And I did not test this case...
