### ISSUE TITLE
Media translation issue

### ISSUE THREAD

**Issue by mrleemon** [polylang/polylang#333]
Even though I have the "Languages and translations for media" setting not active I see different files in the media library when selecting different languages or the “Show all languages” option in the language filter in the top admin bar.
Is this by design? Shouldn't ALL uploaded files be shown regardless the selected option in the language filter when the "Languages and translations for media" setting is off?

**Comment by mrleemon** [comment]
I see that even when the "Languages and translations for media" setting is off, a call to `pll_is_translated_post_type('attachment')` returns true.

**Comment by mrleemon** [comment]
It seems that the culprit is the `$this->options['post_types']` array found in the `get_translated_post_types()` function in the `model.php` file.

If I print the contents of the `$post_types` var before the `array_merge(...)` call, I get:

```
Array
(
    [post] => post
    [page] => page
    [wp_block] => wp_block
)
```

After the `array_merge(...)` call, the content of the var is:

```
Array
(
    [post] => post
    [page] => page
    [wp_block] => wp_block
    [attachment] => attachment
    [slider] => slider
)
```

Which is weird. I thought that language support would be added in the `if ( ! empty( $this->options['media_support'] ) ) { ... }` snippet of code that can be found before.

**Comment by mrleemon** [comment]
I found out that this issue just happens in one of my sites. This is an old site that has seen many versions of Polylang. Was language support for media saved in the `options['post_types']` array in old versions of the plugin? Maybe this is a remnant of an old version.

**Comment by Chouby** [comment]
> Was language support for media saved in the `options['post_types']` array in old versions of the plugin?
Not as far as I remember. The media translation was initially added in Polylang 0.9 and controlled by a constant `PLL_MEDIA_SUPPORT`. The option 'media_support' was then added in 1.0. There is still some visible trace of this change in https://github.com/polylang/polylang-pro/blob/2.5.1/install/upgrade.php#L124

**Comment by mrleemon** [comment]
I'll close this issue because I fixed it once and for all removing the 'attachment' post type from the Polylang options in the database via phpMyAdmin.
