### ISSUE TITLE
Filter `pll_custom_flag` not working

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#336]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

I added this code through the `pll_custom_flag` filter. Even when adding a simple `die;` within the callback nothing happens:

```php
add_filter( 'pll_custom_flag', 'custom_plugin_polylang_flags', 20, 2 );
function custom_plugin_polylang_flags( $flag, $locale ) {

	die; // This gets never run...

	if ( file_exists( CUSTOM_FLAG_DIR ) ) {
		if ( ! is_array( $flag ) ) {
			$flag = array();
		}
		$flag['url']    = CUSTOM_FLAG_URL ;
	}
	return $flag;
}
```

Any thoughts?

**Comment by JoryHogeveen** [comment]
To follow up on this. It seems the language cache is preventing this. Is there anything to do about that without adding the constant?

**Comment by Chouby** [comment]
There is no button because the cache is automatically cleared when needed (for example when the settings are modified), except, of course, when the modifications are done from the outside.. 

To clear the cache manually, you can go to Languages > Settings > URL modifications and just resave your settings. See also https://polylang.pro/doc/can-i-use-my-own-flags-for-the-language-switcher/

I will modify the doc of the filter to include this information.

**Comment by JoryHogeveen** [comment]
Hi @Chouby, I actually tried that but it didn't trigger a reset.

**Comment by Chouby** [comment]
Strange. It should be done here: https://github.com/polylang/polylang/blob/2.5.2/settings/settings-module.php#L166

**Comment by miniMAC** [comment]
Hello! I've tried to apply the filter in **_pll_custom_flag_**, but not work.

I'm follow this guide [https://polylang.pro/doc/filter-reference/#pll_custom_flag](https://polylang.pro/doc/filter-reference/#pll_custom_flag)

**Comment by TorinAsakura** [comment]
> Hello! I've tried to apply the filter in **_pll_custom_flag_**, but not work.
> 
> I'm follow this guide https://polylang.pro/doc/filter-reference/#pll_custom_flag

me 2

**Comment by vHeemstra** [comment]
Same here: not working

**Comment by JoryHogeveen** [comment]
@Chouby Please re-open this issue, as you can see, more users can confirm this isn't working.

**Comment by Chouby** [comment]
I re-tested with custom SVG flags and it is working for me.

**Comment by vHeemstra** [comment]
Putting the SVG files in one of the subfolders as described works for me too, but the filters (both `pll_custom_flag` and `pll_flag`) are not fired/called/run. Even with several times re-saving settings of the PLL Language page as prescribed.

**Comment by Jehu** [comment]
Same Problem here!
