### ISSUE TITLE
Translated posts show in overview, but trying to open them results in page not found error

### ISSUE THREAD

**Issue by eir3apps** [polylang/polylang#337]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1.  Set WP Permalinks: /%category%/%postname%/ 
2.  Set Polylang URL settings: The language is set from content
3. Translate a post from the primary to a secondary language

## Expected behavior and actual behavior

When I follow those steps, I see... 

The translated post is correctly displayed in the list of posts, but clicking on it shows an error (Oops! That page can’t be found.) instead of opening the post.

I was expecting...

The post to be opened.

See the problem here: https://lektira.mk/en/

**Comment by Chrystll** [comment]
I don't reproduce your issue on my side. It seems that you get a conflict with another 3rd. Could you please confirm that reproduce the bug with only Polylang activated and  a default WordPress theme? If yes, please give the exact steps to reproduce it.

**Comment by eir3apps** [comment]
Yes, I confirm that the problem persists with only the Polylang plug-in activated, and with the default WP theme. 

My URL settings are: WP Permalinks: /%category%/%postname%/
Polylang URL settings: The language is set from content (The problem also occurs if I select: The language is set from the directory name in pretty permalinks)

Steps to reproduce the problem: 
translate a post (not a page) from the primary language (in my case Macedonian) to the secondary language (in my case English). Save the translation. 

Trying to access the translated post ends up with an error no matter how I try to access it. 

You can see the problem on the page I pointed: https://lektira.mk/en/

Could you please give me a hint how are the permalink settings applied by the plugin, which portion of the code should I look into? I suspect it is a minor flaw and I'd like to try to find it.

**Comment by Chouby** [comment]
The problem is that you are using a category 'author'. This slug is reserved by WordPress for author archives. The problem would occur on all WordPress installn with or without Polylang. You mus not used reserved words as category if you want to use /%category%/%postname%/ as permalink structure.
