### ISSUE TITLE
admin-post.php (admin_post_ actions) localisation

### ISSUE THREAD

**Issue by sandrodz** [polylang/polylang#339]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Enable polylang
2. Use `admin_post_` actions
3. Add localized string in the function hooked to `admin_post_` action, e.g. `__()`
4. Add any of the polylang helper functions, e.g.` pll_current_language()`

## Expected behavior and actual behavior

Expected behaviour is for admin-post.php calls to work properly within the polylang language framework. Similar to how admin-ajax.php works. 

Currently there is no way to localize `admin_post_` calls.

To make `__()` work, I did the following, passing POST variable to admin-post.php submissions and setting locale manually.

<img width="723" alt="Screen Shot 2019-03-11 at 3 18 37 PM" src="https://user-images.githubusercontent.com/8479569/54120374-f7426580-4410-11e9-8b07-5037db94d8cb.png">

I think plugin should handle this automatically as wpml does.

**Comment by manooweb** [comment]
Hello @sandrodz 
Thank you for your issue.

Could you explain a little bit more what you exactly want to do ?

Is your purpose to use admin-post.php in a frontend context ? In our opinion it is dangerous to translate strings in the backend in an another language than the one defined in the user profile.

Thank you

**Comment by stefanfisk** [comment]
I am also running into issues related to not having localisation enabled in `admin-post.php`. I use `admin-post.php` for handling front end form submits, which then redirect back to the appropriate page. As far as I know, this is a normal and common pattern in WordPress. `admin-post.php` does not even require that a use is signed in, as one can just use `admin_post_nopriv_${action}`.

**Comment by smrt21** [comment]
I was having the same issue, but fixed by passing the locale as $_POST variable from my form as suggested by @sandrodz
Thank you!

I fully agree with @stefanfisk

Maybe it is time to fix this issue, because I was looking for a fix 2 days now
