### ISSUE TITLE
Language switcher - home page link instead of post type archive link

### ISSUE THREAD

**Issue by wujekbogdan** [polylang/polylang#34]
On archive pages, when there are no posts in the given language, then the language switcher returns the links to the home page instead of post type archive links.

**Example:**

- There's a product post type
- There are 2 languages defined: EN and ES
- There are some posts of a product type in the EN language but no posts in the ES language
- We are on the /en/product/ page
- For the EN language the language switcher shows the correct url (/en/product/)
- For the ES language the language switcher shows the ES home page URL

IMO it's a bug. Even when there's no post in a given language then the language switcher should still return a link to the post type archive (or it should be configurable in the plugin's options).

So in the given example the language switcher should show the /es/product/ URL instead of the home url.

**Comment by Chouby** [comment]
This is intentional. If there are no posts, `/es/product/` will be 404. Polylang includes a mechanism never to link to a 404 page in the language switcher.

You can always change that with the filter [pll_translation_url](https://polylang.pro/doc/filter-reference/#pll_translation_url).

**Comment by wujekbogdan** [comment]
> This is intentional. If there are no posts, /es/product/ will be 404. 

It's not true. WordPress doesn't redirect to a 404 template when there are no posts. In such case `have_posts()` method returns `false`, `posts_found` is set to `0` but `is_404` is `false` and there's no redirection. Thanks to this we're able to display an info like "No posts found".

I would expect Polylang to act the same way as WordPress acts in such kind of situation. So IMO even if it's intentional it looks like a bug.

I understand that some users might need a redirection in such case, but IMO it should be optional. 

> You can always change that with the filter pll_translation_url.
Thanks.

**Comment by Chouby** [comment]
Yes you are right. Calling "no post found" a 404 was incorrect. Did the filter `pll_translation_url` fit your needs?

**Comment by wujekbogdan** [comment]
Yes, I was able to make a workaround using `pll_translation_url`.

**Comment by aprinciple** [comment]
Make this the default, since this is not entirely correct behavior; I came across something similar to custom taxonomies when I was navigating through taxonomy terms. If posts are not tied to a taxonomy term, they are thrown to the main page.
