### ISSUE TITLE
add_rewrite_endpoint is prepended with the language code

### ISSUE THREAD

**Issue by ziodave** [polylang/polylang#344]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add a custom rewrite endpoint, e.g. `add_rewrite_endpoint( 'example-endpoint', EP_ROOT );`.
2. With Polylang disabled, try to access the end-point at /example-endpoint: it works.
3. With Polylang enabled (and the configuration below), try to access the end-point at /example-endpoint: not found.

![image](https://user-images.githubusercontent.com/11438/54681822-a1a34280-4b0d-11e9-9687-0fafa41729a2.png)

## Expected behavior and actual behavior

The expected behavior is for the end-point to always be accessible at /example-endpoint also after the installation of Polylang since the end-point isn't content-related.

The actual behavior is that Polylang moves the end-point to a subfolder.

**Comment by Chouby** [comment]
I am not sure how I could fix that from Polylang. By adding the `EP_ROOT`, you are telling that your endpoint belongs to the the root rewrite rules group, which is filtered by Polylang with the filter `root_rewrite_rules`. 

However, on your side, you should be able to stop Polylang filtering the specific rule that added by using the filter `pll_modify_rewrite_rule`. See: https://github.com/polylang/polylang/blob/2.5.2/include/links-directory.php#L210-L220
