### ISSUE TITLE
Can't use pll_current_language() if the language is defined by the content is selected

### ISSUE THREAD

**Issue by edirpedro** [polylang/polylang#345]
The function `pll_current_language()` returns false if the option "the language is defined by the content" is selected at the URL settings.

I tried to set the language manually using the query `?lang=en` and getting the `pll_language` cookie to identify the language across the pages. But the cookie is not trustworthy because Polylang changes it after the `functions.php` is processed, resulting in getting old values when switching between languages.

I'm trying to use a single page for all languages, because I have a bunch of pages that just need .mo translations, there is no content for the templates. This should be less complex than duplicate every page and mount every menu for those pages. But it's not working because I can't get the current language correctly.

This is the code to identify the language, working at functions.php file.

```php
$lang = isset($_COOKIE['pll_language']) ? $_COOKIE['pll_language'] : false;
$lang = isset($_GET['lang']) ? $_GET['lang'] : $lang;
define( 'LANG', in_array( $lang, pll_languages_list() ) ? $lang : pll_default_language() );
```

**Comment by Chouby** [comment]
You are using the function too soon. When the language is defined by the content, the currrent language is not available before the action `wp` has been fired. See https://polylang.pro/doc/developpers-how-to/#language-load
