### ISSUE TITLE
WP suggested class file names

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#347]
Please consider class file names like `class-pll-admin-block-editor.php`

See WPCS

**Comment by Chouby** [comment]
We will probably never fix that. If some day, we mass rename the files, this will most probably to use a PSR autoloader (which will possible when we will drop the compatibility of PHP 5.2) and I believe that this requires touse the smae name for the file and the class, without prefix.

**Comment by szepeviktor** [comment]
@Chouby Today is the dropping of ancient PHP versions!! Read https://wordpress.org/news/2019/04/minimum-php-version-update/
