### ISSUE TITLE
Translations doesn't attach

### ISSUE THREAD

**Issue by stelasido** [polylang/polylang#353]
Hi, I have read all the issues here.
In the settings I have two languages. When I create a page and then click on the '+' button for creating a page for other language, both are saved and when I try to attach them, in the input I am writing the page for other language (selecting from autocomplete), then press update, nothing happen, page are still not attached. To attach the pages I need to upload/download to Lingotech, then I have attached translation page, but in the language menu (not admin area, page in the front-end) the links aren't correct - the link for the current language goes to '/' and the link for the second language goes to '/en/' or root of the site. I can't understand, is this plugin works ?

**Comment by stelasido** [comment]
And, if I asssociate a page with another translation page (the only way is uploading/downloading) I can't re-associate it with another page .

**Comment by Chrystll** [comment]
I don't reproduce your issue. You should look for a conflict by deactivating everything, then by activating one by one the 3rd other party until to reproduce your issue.
