### ISSUE TITLE
Multisite installation: Content Editor shows no updated post, alert reports more recent backup

### ISSUE THREAD

**Issue by stilografico** [polylang/polylang#355]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Translate an article (post/page/cpt)
2. Edit the translation
3. Save it o r Publish it

## Expected behavior and actual behavior
Once I save a draft or publish a post the content editor is showing a previous version without last changes. The version is showed up is actually the local-storage one.
Database has the right data saved in, when I edit the post in a new browser session I see the right data.
Nevertheless this issue occurs https://github.com/polylang/polylang/issues/353
Maybe they could be related.

Version in use Polylang Pro 2.5.2

**Comment by Chrystll** [comment]
Could you please confirm that this issue occurs with only Twenty Nineteen and Polylang? The other plugins must be deactivated. 

If you reproduce this issue with only Twenty Nineteen and Polylang then I would need that you give me the exact steps to reproduce it on my environment. You can also provide me some screenshot to describe your steps.

**Comment by stilografico** [comment]
Sorry, it appeared to be a problem related to hosting bad configured memcached.
