### ISSUE TITLE
DropDown authors on add/edit articles

### ISSUE THREAD

**Issue by kcirtap86** [polylang/polylang#358]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create new article;
2. Select English language;
3. On the authors dropdown compare only 4 of 4 authors user with wrong name;
4. Select Italian language;
5. On the authors dropdown compare only 2 of 4 authors user

Thanks for your support, best regards

Patrick

**Comment by Chrystll** [comment]
1. By dropdown authors, do you means this one:?

![screenshot-localhost-2019 06 03-15-21-57](https://user-images.githubusercontent.com/19824724/58804980-6a740600-8613-11e9-884c-78f5d0a08839.png)

2. Could you please describe your issue thanks to some screenshot?
3. Does the issue happens with only Twenty Nineteen (default WordPress theme) + Polylang? The other plugins must be deactivated.
