### ISSUE TITLE
Language not switching to default language

### ISSUE THREAD

**Issue by ShamanFromSiberia** [polylang/polylang#360]
There is one topic reported on the issue from 2017, but I couldn't find any solution yet. Having doubts there's one published...

Description of the issue: many users report that the home page of y website is shown only in secondary language and they can't switch to the primary language. But other pages are shown in correct primary language. Clearing the browser's cache helps, but briefly. After some time the issue is back. Firstly couldn't reproduce the issue and therefore couldn't look at it closely. But  now it's happened for me everywhere: on mobile, on laptop... I use the latests versions of WP and the plugin. The latest versions of web browsers. I can't trace the origin of the issue for there's no possibility to stop my website working. I've seen some reports on the same problem but didn't find any information how people fix it. Could you help, please?

**Comment by Chouby** [comment]
I don't reproduce this on my test site.

If you believe that you found a bug, please fill correctly our form with special attention to the steps to reproduce the issue.

As is, I am closing as support request.
