### ISSUE TITLE
Polylang breaks TinyMCE of PODS custom fields

### ISSUE THREAD

**Issue by phrench** [polylang/polylang#361]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install the PODS plugin
2. Create a custom post type
3. Add a custom field of the type WYSIWYG (Visual Editor) to the custom post type
4. Add a new entry (of the custom post type)
5. TinyMCE field cannot be access with the mouse cursor. (= actual behavior)
6. Disable Polylang plugin
7. TinyMCE field can now be accessed with the mouse cursor. (= expected behavior)

**Comment by phrench** [comment]
Also noticed that collapsing some metaboxes from plugins such as SEOPress doesn't work anymore. But this is only when editing a custom post type. When editing a normal blog post, collapsing the very same metabox works.

Thus looks like some conflict of Polylang with custom post types or the PODS plugin.

**Comment by Chouby** [comment]
Do you confirm that this is the same issue as https://github.com/pods-framework/pods/issues/5365 and fixd by the PR #369?

**Comment by phrench** [comment]
Confirmed, it's the same issue and fixed by the PR.

When applying the change the issue is gone and the UI works as expected.

**Comment by Chouby** [comment]
Closed by #369
