### ISSUE TITLE
Jetpack Portfolio support

### ISSUE THREAD

**Issue by ghost** [polylang/polylang#362]
Hello,

Polylang does not work with Jetpack Portfolio. Hope its support can be added later. Thank you very much.

Best regards,
Deyu Zhou

**Comment by Chrystll** [comment]
Hello,
Could you please describe your issue step by step with screenshots to well understand it? It will allow me to reproduce it on my side.

**Comment by rita-web-maker** [comment]
Hello!
I guess I have the same issue - Jetpack has a functionality for creating Portfolio posts.
These Portfolio items look like Posts/Pages, but it is not possible to add languages to these Portfolio items.

Is there a way to do that?

Thanks/
Rita
