### ISSUE TITLE
Disable Polylang only for specified widget

### ISSUE THREAD

**Issue by Yuribtr** [polylang/polylang#363]
Hello and thanks for great plugin!
Here is my request for improvement.

If site has posts on 2+ languages, we can switch between languages without problems. At sidebar widgets “Recent posts” we'll see only posts that belongs to choosen language.

Unfortunately now it is NOT possible to see "mixed" feed, that contains posts from all languages at once. So we need a way how to say Polylang to NOT filter posts by language at specified widget. This is also might be useful at Calendar widget. And it would be nice if we 'll be able to show links to posts with non-active language using different styling.

**Comment by Chouby** [comment]
This request is too specific as most users want to display the feeds in only one language and there is no plan to make this optionnal. If you absolutely need this feature, I suggest that you get in touch with a developer who will be able to remove the relevant Polylang filters.
