### ISSUE TITLE
Undo Polylang, Extract a specific language's content and pull them out completely?

### ISSUE THREAD

**Issue by EugeneRider1** [polylang/polylang#364]
Hey there developers,

Is it possible to remove Polylang however extract all the content of a specific language?

I run EN and CN both on my blog but now due to many technical issues, albeit Polylang has been very helpful, I have to remove this plugin and set up a new site with the content I pull from Polylang.

Thank you

**Comment by Chouby** [comment]
Please use GitHub issues to report bugs only. For support requests, please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/))
