### ISSUE TITLE
Language switch on get_users() and get_blogs_of_user()

### ISSUE THREAD

**Issue by repli2dev** [polylang/polylang#365]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

0. Multisite
1. Create multiple blogs.
2. Have a user with access to all the blogs (use `get_blogs_of_user()`)
3. Open administration menu

Alternatively

0. Multisite
1. On site A `get_user()` users from blog B.

Tested on PHP 7.1, 7.2, 7.3 with Xdebug 2.6.2, 2.7.0, 2.7.2 and without xdebug. OPCache enabled.

## Expected behavior and actual behavior

Performance degradation, this degradation is of two extents:

1. On production the page loads inconsistencly between 2-8 seconds (per 100 users). Xdebug is disabled (not even loaded).
2. In local development with enabled Xdebug the loads is about 5-8 seconds (per 100 users), however in profiling this can get fairy easy over 2 minutes.

The debugging showed that `get_users` instantiate each user in WP_User object which switches to and from given blog... Which leads to switching and therefore loading language catalogue from db on each switch! The `get_blogs_of_user()` is invoked when rendering admin menu list of blogs, switching language on each row of `get_blogs_of_user` result.

This makes page with Polylang highly unusable. Is this a bug, or this is architectural inevitability?

**Comment by repli2dev** [comment]
Also this problem affects `get_admin_url` and `get_site_url` especially when called in in cycle (needed for adding shortcuts into admin submenu to other blogs).

**Comment by Chouby** [comment]
I don't quite understand how to reproduce the issue. Should I have many blogs for 1 user? Or many users for 1 blog?

**Comment by repli2dev** [comment]
@Chouby Number of users is not relevant here. The number of blogs (sites) is the key for reproducing the issue (in our case around 60).

**Comment by Chouby** [comment]
Once I have created 60 sites, what should I do to reproduce? Is Polylang networked activated? Or is activated per site? Could you provide detailed steps?

**Comment by repli2dev** [comment]
Polylang is not network activated, it is activated only in one site in which I am when this issue occurs.

Reproduction on everypage which has the WP admin bar inside the site with enabled polylang.

**Comment by Chouby** [comment]
I setup a multisite and created 60 sites with WP-CLI. I networked activated Query Monitor, I activated Polylang (current dev version) on one site, created 2 languages, navigated on various admin pages on this site and did not notice any slow page. 

Example of measurement made with Query Monitor (average on 10 requests) on the posts list table (with 1 post in each language):
Without Polylang: 0.65s
With Polylang: 0.78s

**Comment by repli2dev** [comment]
@Chouby Thanks for your effort! This issues seems to be harder to reproduce than I originally though, sorry for that... it still happens in our instances and probably is somehow connected to number of translated strings.

The xdebug and really fast local computer makes it hard to catch, so here are some experiments from our production.

Current state:
![Snímek obrazovky 2019-06-17 v 9 48 39](https://user-images.githubusercontent.com/475549/59587342-5802cd80-90e5-11e9-8dba-76af4a36154e.png)

When I go to `get_blogs_of_user` in `user.php` and replace `$_sites = get_sites( $args );` with `$_sites = [];`
![Snímek obrazovky 2019-06-17 v 9 48 50](https://user-images.githubusercontent.com/475549/59587417-884a6c00-90e5-11e9-92b9-f62243b73040.png)

The numbers of the first holds steadily between 4-8 seconds, and the second between 1.5 to 2 seconds. It is the same page with just this one update. My debugging therefore went to `WP_Site` and its `__get` which calls `get_details` which switches the blog and there falls down to `frontend.php` `switch_blog` method. I have attempted to short-circuit this function and the results are the same and goes up when remove this short-circuit.

From that I am quite sure that the problem really exists and is related to the translation switching.

**Comment by Chouby** [comment]
It's curious that `PLL_Frontend::switch_blog()` is called on admin side, as it should be called only on frontend, while `PLL_Base::switch_blog()` should be called on admin side. In any case, these methods start to check that the plugin is active on the new site. If it's not, nothing should be done apart this active plugins check. See https://github.com/polylang/polylang/blob/2.6-rc1/include/base.php#L112-L114

In my opinion, the slowest part is loading the strings translations https://github.com/polylang/polylang/blob/2.6-rc1/frontend/frontend.php#L214 and this happens only one frontend for sites where Polylang active (only one in your case if I well understood). I don't see how it can double the page load time.

**Comment by repli2dev** [comment]
@Chouby you are right with the `PLL_Frontend` and `PLL_Base`, the `PLL_Base::switch_blog` is used (I have probable get puzzled but the IDE) on each item inside the `get_sites()` call, though the `load_strings_translations` method is called only once, which seems to be as you say. So this doesn't explain the double the page load time.

The weirdest thing is that today I was not able to reproduce the first method in any way.
The second way (via `get_users()` of B users on blog A) the `PLL_Frontend::switch_blog` is still triggered (after the explonation this makes sense) and potentially harmful as it does `$this->load_strings_translations();` for each user in the result. However there is workaround for that in the form of `'fields' => ['ID']` when full `WP_User` object is not needed.

So there is probably no big issue, or I am not able to reproduce it. Anyway I suggest to close the issue at least for now.

Thanks for your cooperation (as during the debugging we managed to discovered few other problems with performance!)
