### ISSUE TITLE
pll_e() and pll__() not working

### ISSUE THREAD

**Issue by miryamfv** [polylang/polylang#367]
I am having this same issue they describe on the link. I registered new string literals on my functions.php and attempting to retrieve them on the them with either of those functions is just not working. Any ideas?

https://wordpress.org/support/topic/pll_e-and-pll__-echoing-the-name-of-my-custom-strings-and-not-the-content/
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

**Comment by Chouby** [comment]
`pll__` and `pll_e` are correctly working for me. We continuously use them in Polylang and addons without any issue. 

If you believe that you found a bug, please fill correctly our form with special attention to the steps to reproduce the issue.

As is, I am closing as support request.
