### ISSUE TITLE
Best way to import

### ISSUE THREAD

**Issue by Colir** [polylang/polylang#370]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Export Content from a WP with Polylang using built-in tool "Wp Import / Export"
2. Import the content via the generated .xml file with buit-in tool "Wp Import / Export"

## Expected behavior and actual behavior

All post / CPT kept there language assignement,
but the translation relationship are lost...

Are we obligated to use WP import All plugin ?
Is someone know a native workaround ?

thank you

**Comment by Chouby** [comment]
Languages and translations are exported only when you export All content. That's an unfortunate limitation of the WP Exporter. Please use the support forum for questions and use GitHub only to report bugs.
