### ISSUE TITLE
WooCommerce notice is shown in English on non-English product when language is set from content

### ISSUE THREAD

**Issue by koskinenaa** [polylang/polylang#376]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and activate Polylang from wordpress.org plugin repository
2. Install and activate WooCommerce from wordpress.org plugin repository
3. Add product with WooCommerce
4. Add two languages, non-English as primary/default and English as secondary
5. Set untranslated content to default language
6. Set Settings > URL modifications to "The language is set from content"
7. Navigate to the product page and click Add to cart, the page reloads and "added to cart" notice is shown above the product.

## Expected behavior and actual behavior

When I follow those steps, the "added to cart" WooCommerce notice is shown in English while everything else on the product page is in the non-English default language.

I was expecting that the notice text would also be shown in the non-English default language.

I've tested this on two different WP installs. This happens on both default theme (twentynineteen) and non-default theme.

The notice is translated when Settings > URL modifications is set to "The language is set from the directory name in pretty permalinks".

Here's a screenshot showing the behaviour,
![woocommerce notice](https://user-images.githubusercontent.com/28140251/60101260-1bc61180-9764-11e9-9f78-b97e0f80682c.png)

## Questions

Is this unexpected (at least to me) behaviour actually expected and I've just missed some small print on the documentation / user guides? Have I misunderstood the setting? Or is this a bug? 

Is it possible to circumvent this with some filter (or action)? If so, which one?

**Comment by Chouby** [comment]
You check that the issue occurs with only Polylang active and then write about WooCommerce. Polylang needs an addon to work with WooCommerce. If you are using such addon, please report the issue to the relevant support. If you are using our Premium adddon, Polylang for WooCommerce, please contact our helpdesk: https://polylang.pro/support/. This is the best way to get fast support.
