### ISSUE TITLE
Tag saved in wrong language

### ISSUE THREAD

**Issue by ndr-thitinan** [polylang/polylang#377]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Have the tag with the different name, different slug

Example: different name and different slug

– JP
    – name: パソコン
    – slug: computer

– EN
    – name: Computer
    – slug: computer-en

2. Save using パソコン tag, or save using Computer tag.

## Expected behavior and actual behavior

When I follow those steps, I see...
Post will be saved with slug computer-en for tag パソコン, and opposite for Computer.

I was expecting...
Post will be saved with slug with the right language tag.

**Comment by Chouby** [comment]
Sorry I don't quite understnad what I should do to reproduce the issue. I have created the 2 tags. What should I do after that? Could you test with the default theme and no other plugins activated?

**Comment by ndr-thitinan** [comment]
Tested, and it didn't occur. So Ill mark as close then.
