### ISSUE TITLE
if I have more than one dropdown on the same page events just work on the first select 

### ISSUE THREAD

**Issue by rehamwael** [polylang/polylang#380]
hello thanks for amazing plugin , Im asking I import` <?php pll_the_languages( array( 'dropdown' => 1) ); ?>` in my header and footer the event just bind on the first select and not worked on footer , how can I change the ID ?

**Comment by Chouby** [comment]
By changing the value of the paremeter 'dropdown'. Please use the support forum for questions and use GitHub only to report bugs.
