### ISSUE TITLE
Confuse in update strings translations which created by icl_register_string

### ISSUE THREAD

**Issue by edwinhuish** [polylang/polylang#381]
## Prerequisites

Wordpress 5.2.2
Polylang 2.6

## Steps to reproduce the issue

1. Register 2 or more groups strings of different plugin by icl_register_string, like below:

```
// First
icl_register_string('First Plugin', 'First String Name 1', $first_string_1);
icl_register_string('First Plugin', 'First String Name 2', $first_string_2);
icl_register_string('First Plugin', 'First String Name 3', $first_string_3);
icl_register_string('First Plugin', 'First String Name 4', $first_string_4);
icl_register_string('First Plugin', 'First String Name 5', $first_string_5);
icl_register_string('First Plugin', 'First String Name 6', $first_string_6);
icl_register_string('First Plugin', 'First String Name 7', $first_string_7);

// Second
icl_register_string('Second Plugin', 'Second String Name 1', $second_string_1);
icl_register_string('Second Plugin', 'Second String Name 2', $second_string_2);
icl_register_string('Second Plugin', 'Second String Name 3', $second_string_3);
icl_register_string('Second Plugin', 'Second String Name 4', $second_string_4);
icl_register_string('Second Plugin', 'Second String Name 5', $second_string_5);
```

2. Change the second groups Strings translations, and update them.

## Expected behavior and actual behavior

The value change in second group, updated in first group. It means, if you change the 'Second String Name 2',  after update, 'Second String Name 2' still in same value, but 'First String Name 2' changed.

It seems the group name didn't work??

**Comment by Chouby** [comment]
Sorry I don't understand. Could you clarify?

**Comment by edwinhuish** [comment]
I have 2 plugin, both register string with WPML function ``` icl_register_string ```. As picture GIF below, when I CHANGE the **WhatsApp** Chat and after SAVE, the string update to another plugin **Cookie Notice** which in the same place.

![select](https://user-images.githubusercontent.com/5207925/60675635-6572d280-9eaf-11e9-94d5-9d1beb98fcd0.gif)

**Comment by Chouby** [comment]
Where can I find this plugin?

**Comment by edwinhuish** [comment]
For the Cookie Notice, search in wordpress plugin **Cookie Notice for GDPR**, and for **WhatsApp Chat**, it modified by myself, the core code as below:

```
function regTrans()
{
    global $qlwapp;

    //User
    icl_register_string('WhatsApp Chat','User Message', $qlwapp['user']['message']);
    //Button
    icl_register_string('WhatsApp Chat','Button Text', $qlwapp['button']['text']);
    icl_register_string('WhatsApp Chat','Button Phone', $qlwapp['button']['phone']);
    //Box
    icl_register_string('WhatsApp Chat','Box Header', $qlwapp['box']['header']);
    icl_register_string('WhatsApp Chat','Box Footer', $qlwapp['box']['footer']);
    //Chat
    icl_register_string('WhatsApp Chat','Chat Response', $qlwapp['chat']['response']);
    //Contacts
    foreach ($qlwapp['contacts'] as $key => $contact) {
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Avatar', $contact['avatar']);
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Phone', $contact['phone']);
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Firstname', $contact['firstname']);
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Lastname', $contact['lastname']);
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Label', $contact['label']);
        icl_register_string('WhatsApp Chat','Contacts['.$key.'] Message', $contact['message']);
    }
}
```

**Comment by Chrystll** [comment]
I didn't reproduce your issue with the 2 mentioned plugins. Do you reproduce your issue when removing the custom code from WhatsApp Chat?

**Comment by edwinhuish** [comment]
WhatsApp Chat plugin in the wordpress never user any WPML function, so that's the reason that you didn't reproduce same issue as mine.

Please use any plugin with icl_register_string function and ***Cookie Notice for GDPR*** ,
