### ISSUE TITLE
404 return with failed payment with Polylang Pro - Different Permalink structure

### ISSUE THREAD

**Issue by Marienernl** [polylang/polylang#384]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set permalink structure to anything other than standard.
2. Have the Mollie Payment plugin installed and obviously run Woocommerce and Polylang for Woocommerce.
3. Go to checkout, select a payment option and cancel the payment.

## Expected behavior and actual behavior

We were having issues with Mollie and Polylang Pro, as soon as a customer decided to return to the website, either because of a failed payment, or perhaps he or she changed their minds, then it would summon a 404 error.

It triggers the following url return
https://url-of-website.com/en/wc-api/mollie_return/?order_id=3883&key=wc_order_BluaBOeYUzwm7

When you remove the /en or for instance /nl in that url then it redirects perfectly to the failed payment screen from Woocommerce. So what we did was we tried the 2.6 beta 2 on our live site and that works flawlessly. 

We saw that there was a new version of Polylang Pro available, 2.6.1 and unfortunately it still has the same 404 issues as the previous version.

How, why and when will this be fixed like in the beta?

The problems dissapears when we set the stock Permalink structure in Wordpress. But the thing is, we want /%category%/%postname%/ instead of the standard permalink structure.

**Comment by Chouby** [comment]
This issue is handled by the support team.

**Comment by Marienernl** [comment]
Nobody knows whats going on with this issue. Fingers being pointed to eachother. Issue still present with every single plugin needed being up to date. This is extremely frustrating, our site is live. We are running on some old Beta...
