### ISSUE TITLE
Breaking changes Polylang 2.6 and upward with Elementor + Polylang Connect

### ISSUE THREAD

**Issue by madbradj** [polylang/polylang#399]
Polylang versions 2.5 & 2.5.2 work well with Elementor + Elementor Pro, if you want to use the template system of Elementor you need to install Polylang Connect for Elementor. 

After updating Polylang to 2.6 and any newer version, we can no longer see the translated templates in Elementor. Only the original language template. I expect to see the translated language template available. 

There are 2 scenarios where you can see this problem:

1: Any new site built with the latest Polylang versions and Elementor +Pro.

1: Any old site built with Polylang V2.5.2 and downwards will have no problem provided that they do not edit in Elementor. The site will remain working with the latest Polylang BUT cannot be edited once they have upgraded to Polylang V2.6 upwards.

**Comment by Chrystll** [comment]
I don't reproduce your issue after updating Polylang 2.5.2 to 2.6. Do you reproduce it on a fresh install? If yes, could you please give me the  the steps to reproduce the issue. You can also add some screenshots to illustrate your steps. To well understand the context of your screenshots please don't remove anything.
