### ISSUE TITLE
Relational issues with ACF Pro

### ISSUE THREAD

**Issue by alexkerber** [polylang/polylang#40]
Relationship or Post Objects doesn't work. Trying to have a relationship flexible content wrapper that needs to be translated and have different content for example Swedish and English.
When I update the Swedish version with a post that doesn't exist in english it creates an empty field. And with save takes a random post.

Tried **Polylang Fix Relationships** (https://github.com/mcguffin/polylang-fix-relationships) and I really don't want to go back to WPML just for this.

Using latest Advanced Custom Fields PRO (5.4.1) and Polylang Pro (2.0.2) with an Custom Post Types.

Any ideas?

**Comment by Chouby** [comment]
I have noticed that Polylang Pro stores integers as integers when ACF Pro stores them as strings. Not sure if this is related to your issue. Could you please contact us at https://polylang.pro/support/ an give details to reproduce the issue?

**Comment by alexkerber** [comment]
Ok just sent an email about this issue. Thanks!

**Comment by alexkerber** [comment]
Fixed with help from @Chouby. This will be with the new 2.0.3. Thanks!
