### ISSUE TITLE
WP Job manager - Job Data translations not translating

### ISSUE THREAD

**Issue by AshleyBale** [polylang/polylang#403]
There appears to be a compatibility issue. Since the latest updates. 

This is only affecting 'featured jobs' listings on WP job manager.
We can only add 'job data' in one language. When saving it only retains the last saved content and replicates this across the translated and original site language.

**Comment by Chrystll** [comment]
We don't know WP Job Manager. The compatibility with Polylang is handled on the WP Job Manager side. If you noticed that a Poylang update breaks their compatibility then please fill correctly our form with special attention to the steps to reproduce the issue. Please add screenshots to illustrate your steps. To well understand the context of your screenshots please don't remove anything.
 
Important: Please specify which Polylang version was working as expected with WP Job Manager. And which Polylang version has triggered your issue.
