### ISSUE TITLE
Polylang not working with ACF plugin when Synchronization Custom Field is ON

### ISSUE THREAD

**Issue by dieupxse** [polylang/polylang#407]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install polylang and ACF. Create any custom field using ACF. Go to Polylang Setting -> Synchronization -> Check Custom fields (Turn it on)
2. Create Two language. After that, create page or port with custom filed. 
3. Save post with two language

## Expected behavior and actual behavior

When I follow those steps, I see the custom field was override by latest content updated. It's mean all language will have the same content depend on the last update.

I was expecting save custom field by each language.

**Comment by bjorn-ali-goransson** [comment]
Are you saying that the same custom field values in ACF fields are shown for both translations of a page?

**Comment by Chouby** [comment]
I am not sure why you activated the synchronization of the custom fields, but having the same value in all languages is *exactly* the purpose of this option.
