### ISSUE TITLE
Custom post type translations can't be enabled if public == false

### ISSUE THREAD

**Issue by andrejcremoznik** [polylang/polylang#410]
## Prerequisites

- [x] This is not a usage question
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Register custom post type by setting public false;
   ```
   register_post_type('mycpt', [
     'public'      => false,
     'show_ui'     => true,
     'has_archive' => false,
     'rewrite'     => false
   ]);
   ```
2. Open Dashboard > Languages > Settings
3. *Custom post types and Taxonomies* is disabled

## Expected behavior and actual behavior

I didn't actually look at Polylang's code, but I assume it's looking at the `public` property of the CPT. It should be using the `show_ui` property.

Changing CPT to `'public' => true` enables translation.

**Comment by Chouby** [comment]
This is the intended behavior. https://github.com/polylang/polylang/blob/3919f8a5c5c2c393a430919892569af458781581/settings/settings-cpt.php#L28

If the post type is not public, then this is a good signal for 3rd party plugins not to interact with it. And a good way to avoid conflicts. So we won't change this default behavior.

I don't know why you want your post type no to be public, but you can perfectly decide to translate your post type with the `pll_get_post_types` filter or the wpml-config.xml file.

**Comment by andrejcremoznik** [comment]
> I don't know why you want your post type no to be public

I'm creating content I only use on specific templates and not via standard archives. Post meta is not appropriate for my use case, I need the full functionality of the `post` entity because I need to be able to custom `WP_query` it. And that CPT needs to be translatable.

No matter what you think about `public` I believe that `show_ui` supersedes it. `show_ui` will literally make the CPT visible in the dashboard so why shouldn't it be exposed in polylang's settings.

Like you said, I can easily work around it if I'm in charge of the entire codebase but if I'm distributing a plugin I need to know about this unexpected behavior.

**Comment by Chouby** [comment]
It means that we don''t have the same interpretation of the meaning of `public => false`. For me it means "Don't touch". So the default behavior of Polylang is not to interact non public post types and not to allow non-developers to allow such interaction. The same way, I expect that 3rd party developers don't mess with non public post types and taxonomies internally used by Polylang.

If you are distributing a plugin, then the wpml-config.xml file is certainly the best way to go, as the configuration will be interpreted by both WPML and Polylang. See: https://polylang.pro/doc/the-wpml-config-xml-file/. If, for some reason, you need a finer control, then you can use the `pll_get_post_types` filter.
