### ISSUE TITLE
[Feature request] Backend language selection

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#412]
Polylang already adds a languae picker to backend, but it only filters the posts.
It would be nice if Polylang can also be used to select the language in backend.
In many cases, the backend users want different languages in the backend.
It wouldn't make sense to use the existing language picker from Polylang as it acts on the posts as a filter, the user may want to use a different backend language.
It would be great if a backend language setting could be added to the user settings to be used in backend when the user is logged in.

**Comment by chesio** [comment]
Have you tried it actually?

On sites with Polylang, I can go to user settings and pick any of the languages I have configured in Polylang as user backend language.

Btw. I believe this feature is provided by WordPress core and you can select from all languages (language packs) that you have installed. Polylang just makes it easier to use as it installs the languages for you when you configure them.

**Comment by strarsis** [comment]
Yes, I noticed there is a language selection also for the user. 
Preferred Languages plugin replaces it, too, with a priority list.
