### ISSUE TITLE
get_terms() ignores 'lang' atttribute

### ISSUE THREAD

**Issue by aurovrata** [polylang/polylang#418]
Getting all terms from a translated taxonomy for a given language was [previously fixed](https://wordpress.org/support/topic/get_terms-ignores-lang/), but is now broken again in v2.5+

```
get_terms(array(
  'taxonomy'=>'custom-category',
  'lang' => 'en'
));
```

returns all the terms in the taxonomy in all languages

**Comment by Chouby** [comment]
I don't reproduce. You are probaby calling the function too soon.

On frontend, the filter is setup as soon as the language is defined: https://github.com/polylang/polylang/blob/2.6.5/frontend/frontend.php#L117

On backend, the filter is set in a method hooked to `wp_loaded`: https://github.com/polylang/polylang/blob/2.6.5/admin/admin.php#L128

Although the code structure has changed wehen we introduced `PLL_CRUD_Terms`, I don't remember having changed this behavior.

**Comment by aurovrata** [comment]
nothing changed in my code.  The plugin works just fine in v2.3.x but is broken in the latest version.

I am using this to retrieve translated terms in a custom REST request

**Comment by Chouby** [comment]
In REST requests, the filter is setup as soon as the plugins are loaded. See: https://github.com/polylang/polylang/blob/2.6.5/include/rest-request.php#L45
I tested `get_terms()` in a rest request `/wp-json/wp/v2/posts` in a function hooked to `init`, just after the taxonomy is registered and it works for me with the current version 2.6.5.

**Comment by aurovrata** [comment]
apologies, I just tested it with v2.6.5 again and its indeed working as expected.  My mistake.
