### ISSUE TITLE
Big flag in mobile device

### ISSUE THREAD

**Issue by Georgeals** [polylang/polylang#419]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## actual behavior

 I see Big flag in mobile device. screenshot: http://joxi.ru/xAebnW9TR3478r
I fix issues when add "style="width: auto;"" in to the file language.php line 214

**Comment by Chouby** [comment]
Which default theme are you using?
