### ISSUE TITLE
PLL() not defined when no languages added (compat issue)

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#427]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- ~~This bug happens with only Polylang plugin active~~
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

When using Loco Translate somehow the CPAC addon (included in Polylang Pro) results in a fatal error since PLL() isn't loaded if there are no languages:
https://github.com/polylang/polylang/blob/master/include/class-polylang.php#L244

While this is an occurrence with Loco Translate and Admin Columns I think more combinations might cause issues.

1. Enable Polylang, Admin Columns and Loco Translate.
2. Do not add languages
3. Try to modify a language file with Loco Translate

## Expected behavior and actual behavior

In my case I'm using a multisite structure where the main site has multiple languages and the second site only has one.
I want to fetch posts from the main site filtered by one language but in order to do that I need Polylang enabled.
With Polylang enabled but no languages added to the second site it causes some weird issues because the PLL API isn't loaded:
https://github.com/polylang/polylang/blob/master/include/class-polylang.php#L238-L276

I think it would be good to have the API available at all times, even if the main class isn't loaded.

**Comment by Chouby** [comment]
That's definitely a bug in our compatibility with Admin Columns. 

Because in a few cases we need to start executing code very early, before `plugins_loaded` is fired, the `PLL_Plugins_Compat` is instanciated before we can check that languages have been defined, but this means that we must tak care in our code to do the necessary checks. It's not done here.
