### ISSUE TITLE
pll_get_post_types filter caches too early

### ISSUE THREAD

**Issue by alpipego** [polylang/polylang#429]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Filter `pll_get_post_types` on `after_setup_theme` with the default priority of 10; i.e.

```php

add_action('after_setup_theme', function() {
    // do something that my post type needs after the theme has been setup
    $postType = thing();

    add_filter('pll_get_post_types', function($postTypes) use ($postType) {
        $postTypes[$postType] = $postType;
        
        return $postType;
    });
});
```

## Expected behavior and actual behavior

When I follow those steps, the post type does not show up as translatable, because the post types get cached as soon as `after_setup_theme` has been fired in:

https://github.com/polylang/polylang/blob/a4bc5e9f200b3c16d278df14aef91297dacb1c59/include/model.php#L243-L247

I was expecting that at least up until the point I'm required to register my custom post types – which IMO is `init` and that's also when WordPress registers the built-in post types – I'm able to add (or remove) a post type from polylang's translatable "list".

## Possible solution
I think the caching of the post types shouldn't occur before (or on) init but on any action after that. `register_sidebar` seems to be the first action after `init` (according to https://codex.wordpress.org/Plugin_API/Action_Reference); `wp_loaded` looks to be the most semantically sound to me:

```php
$post_types = apply_filters( 'pll_get_post_types', $post_types, false );

if ( did_action( 'wp_loaded' ) ) {
    $this->cache->set( 'post_types', $post_types );
}
```
I'll gladly provide the PR for this.

**Comment by Chouby** [comment]
The result is cached so early because the method is called very often. The cache is setup late enough to allow plugins *and* themes to add their filter, so there is no need to wait more. As stated in the filter inline doc https://github.com/polylang/polylang/blob/2.6.8/include/model.php#L234-L235, you can can add the filter in a function hooked to `plugins_loaded` (for plugins) or directly in the functions.php, without waiting for `after_setup_theme` to fire (for themes).

**Comment by alpipego** [comment]
I read the comment in the code, but I still think this is wrong. CPTs must be registered on `init` but PLL sets up the cache before that. Too bad to see this marked as `wontfix`.
