### ISSUE TITLE
 Wrong shortlink and dns-prefetch  link with multidomain setting

### ISSUE THREAD

**Issue by Overflow992** [polylang/polylang#434]
Hi, i have a website with dedicated domain name for every translation section, i have notice that in html source some link have the default domain link, like:

`<link rel='shortlink' href='' />`

my original domain is Domain.com

the other domain are Domain.es, Domain.fr, Domain.de for rispective language.

When visit a page of french domain like Domain.fr/page-name-fr/ in html source code i see that the tag: rel='shortlink' not have the FR slug but the COM, like this

`<link rel=’shortlink’ href=’http://Domain.com/?p=1272' />`

so, it’s use the english domain instead of french domain.

This also happens for the <link rel='' 'dns-prefetch'> tags

can you check if this happens to you too?

**Comment by Chouby** [comment]
If you are seeing the main domain in dns-prefetch, that's not a bug. In some rare cases, plugins could use the main domain to enqueue scripts or styles. If that's the case, WordPress detects it and add the domain to dns-prefetch. That's rather a good thing for performance.

**Comment by Overflow992** [comment]
> 
> 
> If you are seeing the main domain in dns-prefetch, that's not a bug. In some rare cases, plugins could use the main domain to enqueue scripts or styles. If that's the case, WordPress detects it and add the domain to dns-prefetch. That's rather a good thing for performance.

ok but why do some plugins load styles and js with the main domain while others with the correct domain?

instead for the Tag rel = ’shortlink’, did you take a look? in that case there should be the correct domain from an SEO perspective.
