### ISSUE TITLE
Sync event (TEC) metas properties

### ISSUE THREAD

**Issue by yuniers** [polylang/polylang#439]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create an event (English) and add some properties like start and end date.
2. Add translation (Spanish) of previous event created. Save it. 
3. Modify values of English event.

## Expected behavior and actual behavior

Event properties are not sync and two events (English and Spanish) have different values.

## My proposal

This issue is a feature request.

Add a new file whit a class `PLL_TEC` to support this feature and track meta name to sync.
https://github.com/polylang/polylang/blob/03ae15280bccebe1738594909632839a5bd0e9ca/modules/plugins/plugins-compat.php#L99

I created my custom PLL_TEC class and work!.

**Comment by yuniers** [comment]
My custom class

```php
<?php


class PLL_TEC
{
    private $metas;

    public function __construct()
    {
        $this->metas = array(
            '_EventAllDay',
            '_EventTimezone',
            '_EventStartDate',
            '_EventEndDate',
            '_EventStartDateUTC',
            '_EventEndDateUTC',
            '_EventShowMap',
            '_EventShowMapLink',
            '_EventURL',
            '_EventCost',
            '_EventCostDescription',
            '_EventCurrencySymbol',
            '_EventCurrencyPosition',
            '_EventDateTimeSeparator',
            '_EventTimeRangeSeparator',
            '_EventOrganizerID',
            '_EventVenueID'
        );
    }

    /**
     * Initializes filters and actions.
     *
     * @since 2.6
     */
    public function init()
    {
        add_filter('pll_copy_post_metas', array($this, 'copy_post_metas'));
        add_filter('pll_translate_post_meta', array($this, 'translate_post_meta'), 10, 3);
    }

    /**
     * Synchronizes event metas from 'plugins/the-events-calendar/src/Tribe/Editor/Meta.php'
     *
     * @param array $metas List of event fields names.
     * @return array
     * @since 2.6
     *
     */
    public function copy_post_metas($metas)
    {
        return array_merge($metas, $this->metas);
    }

    /**
     * Translate the primary term during the synchronization process
     *
     * @param int $value Meta value.
     * @param string $key Meta key.
     * @param string $lang Language of target.
     * @return int
     * @since 2.3.3
     *
     */
    public function translate_post_meta($value, $key, $lang)
    {
        return $value;
    }

}

```

**Comment by manooweb** [comment]
Sorry but we already develop a compatibility - espacially to synchronize metas - with The Event Calendar plugin free version in our Polylang **Pro** version.

We didn't plan to put it in our free version plugin. Sorry.

You can put your code in you own plugin and hooked it on 'plugins_loaded' hook to be sure not to lose your code each time Polylang is updated.

In addition: 
- don't use 'PLL_' prefix for all of your class or function names to have no issue with Polylang.
- in your plugin hook your class instanciation on 'pll_init' to be sure Polylang is well loaded before.
