### ISSUE TITLE
Switching language for subcategory

### ISSUE THREAD

**Issue by baltazor5000** [polylang/polylang#44]
Hello. I have PHP 7.0.11 , Wordpress 4.6.1 and Polylang 2.0.5 (and I try polylang from github, master branch). 

I add subcategory and can not switching language with help pll_the_languages function. 
Link leads to the home page.

- Permalinks: "Post name"
- Link to a sub-category for the current language is correct, for other languages is not correct and leads to the main page.
- Subcategory linked through the appropriate fields in the admin panel.

P.S. When I do var_dump inside function pll_the_languages: 
`var_dump(PLL()->links);`

I see empty field:
`["translation_url:ru"]=>string(0) ""`
inside PLL_Cache object

**Comment by Chouby** [comment]
Hi!

We are unable to reproduce on a fresh install + Polylang. Maybe a conflict with your theme or another plugin?

**Comment by baltazor5000** [comment]
Hi. I have default theme and only one plugin - Polylang. Now I know that the problem was due to the fact that in the category of no news and in the code I found this filter.

**Comment by Chouby** [comment]
Exact. It is intentional that the language switcher doesn't link to an empty content.
