### ISSUE TITLE
After polylang activated , search results in my website won't show custom post type posts.

### ISSUE THREAD

**Issue by yoshikawa-wise** [polylang/polylang#441]
My wordpress based website installed polylang. 
After that , the search results in my website won't show custom post type posts, which shows only post type 'post' .
When I deactivated polylang , the search results can show custom post type posts again properly.

Does polylang alter query of search in wordpress?
How should I fix this problem?

**Comment by sebastienserre** [comment]
Hello,

Did you check your CPT in "Languages -> Settings -> Custom post types and Taxonomies"
![kzac9ay](https://user-images.githubusercontent.com/3902621/74664132-6d148c80-519d-11ea-9275-3e0f3b005d99.png)
