### ISSUE TITLE
New The Events Calendar 5.0 partially breaks compatibility

### ISSUE THREAD

**Issue by SirLouen** [polylang/polylang#446]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install both Polylang and The Events Calendar
2. Go to any view in certain language different than English
3. Press the button to switch the view. For example, go to List view and then from List view, switch to Month view. 

## Expected behavior and actual behavior

When I follow those steps, the translation system breaks. The fact is that the URL is something like this: https://example.com/(en%7Cit)/events/month/ 

After clicking the month view (for example) the slug switches to a non-rewrited version with parameters like: ?post_type=tribe_events&eventDisplay=list
(always goes to "list)

I was expecting that when clicking on "Month" it goes to "Month" with right slug for the language (for example in Italian, https://example.com/it/eventi/mese/)

**Comment by marmotgary** [comment]
Is there a planned fix for this on the roadmap by any chance? Unfortunately right now the plugin is unusable on multi-lang sites using polylang..

**Comment by simondowdles** [comment]
Bumping this as it's an issue on a build I am involved with too.

**Comment by villeveikkoilen** [comment]
I seem to have similar problems. Switching calendar view (List, Month, Day) doesn't work at all in frontend, in any language. After deactivating Polylang, calendar view switching works normally in default language.

- Polylang Pro 2.8.4
- The Events Calendar 5.2.1.1
- The Events Calendar Pro 5.1.6
- WordPress 5.5.3

**Comment by marcusjwilson** [comment]
Bump : This still seems to be an issue with the new interface in Events Calendar. Switching from List to Month view doesn't work with Polylang enabled.
