### ISSUE TITLE
Caching issue with Memcached (SiteGround hosting)

### ISSUE THREAD

**Issue by JMonvoisin** [polylang/polylang#449]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active **(except SG Optimizer, this issue being a compatibility one)**
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. You need a WordPress hosted on SiteGround servers.
2. Install SiteGround exclusive plugin/service [SG Optimizer](https://wordpress.org/plugins/sg-cachepress/).
3. Check that Memcached option is enabled in SG Optimizer plugin admin AND in your SiteGround cPanel (or Site Tools for recent customers) SuperCacher feature.
4. Back in WordPress admin, try to edit any post (title, content, etc.).
5. Save your changes and reload the page => your changes are not displayed.
5b. If you disable or flush Memcached, your changes are now displayed.

## Expected behavior and actual behavior

This issue prevents normal usage or WordPress admin, since you can't save posts changes or many other changes in admin, like Activate/Deactivate a plugin.
The changes seems to be saved in DB but are not displayed as long as Memcached is active or not flushed.
This issue happens with only Polylang and SG Optimizer enabled.

SiteGround seems to be aware of the issue and recommends contacting Polylang staff to address the issue:
https://wordpress.org/support/topic/issue-with-polylang-5/
https://wordpress.org/support/topic/problem-with-cache-when-editing-posts/

For your information, SiteGround did work with WPML to fix similar issues (see SG Optimizer plugin changelog v5.0.10, v4.0.2, v4.0.0.).

I'm willing to provide any information I can to help address this issue..
thanks

**Comment by solosik** [comment]
I'm also interested in solving this issue

**Comment by addedlovely** [comment]
Just to add, looks like WPML checks for the following option:
`siteground_optimizer_enable_memcached`

In the SG Optimizer plugin [page](https://wordpress.org/plugins/sg-cachepress/) - there's the following function to clear the cache for that URL:
```
if (function_exists('sg_cachepress_purge_cache')) {
    sg_cachepress_purge_cache('https://yoursite.com/pluginpage');
}
```

**Comment by JMonvoisin** [comment]
> In the SG Optimizer plugin [page](https://wordpress.org/plugins/sg-cachepress/) - there's the following function to clear the cache for that URL:
> 
> ```
> if (function_exists('sg_cachepress_purge_cache')) {
>     sg_cachepress_purge_cache('https://yoursite.com/pluginpage');
> }
> ```
Please note that the cache purge does not only purges Memcached but also the dynamic pages cache and static files cache (= meaning it might be a expansive option to purge too often...)

**Comment by addedlovely** [comment]
Looks like the SiteGround plugin hooks on save, so not sure if / why that's not running anyway:
`add_action( 'save_post', array( $this, 'purge_all_post_cache' ) );`

Also looks like their own internal memcache purge function just calls `wp_cache_flush` anyway!
```
public static function flush_memcache() {
	return wp_cache_flush();
}
```

**Comment by addedlovely** [comment]
Sorry to spam the issue! Seems hooking into `pll_save_post` and clearing the cache does work. But not sure if thats an optimal solution. Be great to get baked in support as SiteGround is very prevalent as a host.

```
// Clear SG cache on save 
add_action('pll_save_post', 'addedlovely_purge_cache', 1000);

function addedlovely_purge_cache() {
	wp_cache_flush();
	error_log( 'pll_save_post  wp_cache_flush');
}
```

**Comment by Stoyan0v** [comment]
We've added purge functionality for Polylang in Sg Optimizer 5.5.2.

Would it be possible to test if everything is working now?

**Comment by addedlovely** [comment]
@Stoyan0v thanks! Have updated and enabled Memcache, looks good thus far - but will report back with any issues.

**Comment by JMonvoisin** [comment]
idem
Thank you for making this happen.

I'm not very used to this, but as OP, I think I am supposed to close the issue.
Feel free to reopen if needed.
