### ISSUE TITLE
Support RTL content in LTR admin langauge

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#45]
I am working on a site where the admin is in English but we have content in Arabic.

With the following code I was able to change the content direction in TinyMCE if the post language was RTL.

``` php
function prefix_tinymce_settings( $mceInit, $editor_id ) {

    if ( ! function_exists( 'PLL' ) ) {
        return $mceInit;
    }

    $curlang = PLL()->curlang;
    if ( $curlang->is_rtl ) {
        $mceInit['directionality'] = 'rtl';
    }

    return $mceInit;
}
add_filter( 'tiny_mce_before_init', 'prefix_tinymce_settings', 10, 2 );

function prefix_admin_body_class( $classes ) {
    if ( ! function_exists( 'PLL' ) ) {
        return $classes;
    }

    $curlang = PLL()->curlang;
    if ( $curlang->is_rtl ) {
        // Right: Add a leading space and a trailing space.
        $classes .= ' polylang-rtl ';
    }

    return $classes;
}
add_filter( 'admin_body_class', 'prefix_admin_body_class' );
```

The reason for adding a new admin body class is so that we can change the direction of the title and any other fields.

``` css
.polylang-rtl #titlewrap {
    direction: rtl;
}
```

Here is a screenshot how it would look like.

![image](https://cloud.githubusercontent.com/assets/1785641/18979821/588fb77e-8709-11e6-8fa9-026f85b2d7cd.png)

**Comment by Chouby** [comment]
That's a nice feature!

Is there any particular reason why your target only the title input field and not all text input fields?

**Comment by grappler** [comment]
> Is there any particular reason why your target only the title input field and not all text input fields?

No reason. I just did not think so far. We would just need to whitelist a few fields like the translation fields which contain ltr text.

**Comment by swissspidy** [comment]
Related WordPress core ticket: https://core.trac.wordpress.org/ticket/40194

**Comment by Chouby** [comment]
Thanks @swissspidy for the WP ticket. I subscribed :)

**Comment by Chouby** [comment]
See also https://core.trac.wordpress.org/ticket/40715 for the 'lang' attribute.
