### ISSUE TITLE
Add compatibility with XML Sitemaps

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#451]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang and XML Sitemaps feature plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and activate XML Sitemaps feature plugin (I used [master](https://github.com/GoogleChromeLabs/wp-sitemaps) from GitHub, but there is also [version](https://wordpress.org/plugins/core-sitemaps/) in WP Plugins Directory)
2. Open the sitemap.xml (sitemap index) - observe sitemap contents reflecting current front-end language only
3. Go to post or page sitemap (actual sitemap) - observe sitemap contents reflecting current front-end language only

## Expected behavior and actual behavior

I would expect the sitemap to reflect (include) content from all active languages.

## Footnote

Here's the [feature proposal post](https://make.wordpress.org/core/2019/06/12/xml-sitemaps-feature-project-proposal/) and here's a recent [follow-up post](https://make.wordpress.org/core/2020/01/27/feature-plugin-xml-sitemaps/) - I have no idea what current timing for inclusion in core is, whether it's expected to land in 5.4 (I doubt), but it might be good idea to get in touch with folks behind the initiative early in development cycle.

**Comment by manooweb** [comment]
Hello @chesio,

We are already following this project that is has started and we are attentive to it.
WordPress 5.4 is already in RC1 and this feature plugin project won't be integrated to it.

Regards
