### ISSUE TITLE
get_uploaded_header_images() doesn't work on translated pages

### ISSUE THREAD

**Issue by nnnswordfish** [polylang/polylang#455]
Hi,

This function https://developer.wordpress.org/reference/functions/get_uploaded_header_images/ does NOT work on translated pages while it works well with non-translated pages, it returns an empty array. This is a WordPress core function and it does NOT work...

To reproduce the issue:

1. Install Twenty Seventeen theme from wp.org
2. Navigate to Appearance > Customize > Header Media and upload 3 images
3. `var_dump(get_uploaded_header_images()); ` on untranslated page (you will get array of 3 images) 
4. Now dump it on the translated page (URL should include ?lang=de for example), and now you will get an empty array.

P.S. This function returns all uploaded header images, please see a screenshot - https://imgur.com/VFZNfGg

Kind Regards, Duke

**Comment by sebastienserre** [comment]
Hello @nnnswordfish,
I can't reproduce your bug.
Where did you add your var_dump?
I've added mine on top of single.php and the function is working on both translated and untranslated page

**Comment by nnnswordfish** [comment]
Thanks, @sebastienserre in "header.php" it does not work.

**Comment by sebastienserre** [comment]
Sorry but even in "header.php" it's working:
![Capture-20200303154755-1816x240](https://user-images.githubusercontent.com/3902621/75787086-7ccbcd80-5d66-11ea-9186-820db1b191ca.png)
in source page because the var_dump is hidden by the image.
