### ISSUE TITLE
[Gutenberg] Gutenberg reusable blocks filtered incorrectly

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#462]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and activate Polylang plugin.
2. Set up the Polylang plugin to have at least 2 site languages.
3. Ensure that a particular language is selected in Polylang filter in the admin above (as it is often the case when working with a particular/primary site language).
4. Open a page/post in Gutenberg editor.
5. Create a block and make that block a reusable block.
6. Open the block inserter again, select the Manage Reusable Blocks link at the bottom of the list.
7. On the Gutenberg Reusable Blocks page the just created usable block is not listed, the list is empty although the filter links incorrectly show a count (>0).
Only when the Polylang language filter in admin bar is set to display all languages, the Gutenberg Reusable block appears in the list. This is incorrect behaviour because that Gutenberg block got a language assigned, namely the same under which it was created previously and which staid selected as the filtered language.

## Expected behavior and actual behavior
Gutenberg Reusable Blocks that belong to the filtered language should be listed as expected with other posts.

**Comment by manooweb** [comment]
Hello @strarsis,
It seems this issue is a duplicate of #437 
The issue happens because resuable block has no languages assigned when it is created from another block editor (post, page, custom post, reusable block ...).

We corrected this wrong behaviour and the fix will come in a future release soon.

Because of the need of a full compatibility with the REST API, note that the fix is only available in our PRO release.

Regards

**Comment by strarsis** [comment]
Yes, this is a duplicate.
