### ISSUE TITLE
Translation on month in caption of calendar widget fails

### ISSUE THREAD

**Issue by viegelinsch** [polylang/polylang#464]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate Calendar Widget
2. caption of wp-calendar (month) doesn't get translated
3. Disable PolyLang and the caption is translated 

## Expected behavior and actual behavior

When I follow those steps, I see the caption (month) of the calendar widget translated with PolyLang activated.

Something with fetching the translation of the month broken but I cannot get my head around, what it is.

Any advice - except of "deactivate PolyLang" welcome!

**Comment by raaaahman** [comment]
I am unable to reproduce this issue on a clean WordPress install with Polylang Pro and Twenty Twenty.

Please ask for support either in the [community forums](https://wordpress.org/support/plugin/polylang) or through our [helpdesk](https://polylang.pro/support/) if you're a customer of Polylang Pro.
