### ISSUE TITLE
add_submenu_page slug part is translated

### ISSUE THREAD

**Issue by Ciantic** [polylang/polylang#465]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

admin-base.php
```php
        $hooks = [];
		foreach ( $tabs as $tab => $title ) {
			$page = 'lang' === $tab ? 'mlang' : "mlang_$tab";
			if ( empty( $parent ) ) {
				$parent = $page;
				$parent_hook = add_menu_page( $title, __( 'Languages', 'polylang' ), 'manage_options', $page, null, 'dashicons-translation' );
			}

            
			$hooks[] = add_submenu_page( $parent, $title, $title, 'manage_options', $page, array( $this, 'languages_page' ) );
		}
        var_dump($parent_hook);
        var_dump($hooks);
        exit;
```

```
string(19) "toplevel_page_mlang"
array(4) {
  [0]=>
  string(19) "toplevel_page_mlang"
  [1]=>
  string(25) "kielet_page_mlang_strings"
  [2]=>
  string(26) "kielet_page_mlang_settings"
  [3]=>
  string(26) "kielet_page_mlang_lingotek"
}
```

Notice **kielet**_page_mlang_strings, for some reason that part is translated. Is that intentional, or does it bug somehow for just me?

I have admin user as Finnish, I think it takes it from there somehow.

Why this is a problem is because the code uses the english version of the slug here:

[settings.php line 43](https://github.com/polylang/polylang/blob/master/settings/settings.php#L43)
```php
add_action( 'load-languages_page_mlang_strings', array( $this, 'load_page_strings' ) );
```

(And one would think that load hook would be most performant position to register the strings, but it's useless because the hook is not consitently named)

## Expected behavior and actual behavior

I would expect it to always remain `languages_page_mlang_strings`

**Comment by Chouby** [comment]
This is a very old WordPress issue: https://core.trac.wordpress.org/ticket/18857.
That means that we indeed need to use a localized hook :/
I need to fix that.

**Comment by Chouby** [comment]
See #466. I found a rather hacky solution which prevents to use a localized hook.

**Comment by Ciantic** [comment]
Yea, I actually don't care how it's fixed. But one way would be to store the string from this call: 
```
$STORE_THIS_VALUE = add_submenu_page( $parent, $title, $title, 'manage_options', $page, array( $this, 'languages_page' ) );
```

that `$STORE_THIS_VALUE` contains the right string always, even if WP team fixes something.

**Comment by Chouby** [comment]
That was my first idea. But that would require bigger changes to the plugin because the hooks are often added before the call to `add_submenu_page()`.
