### ISSUE TITLE
Trying to access array offset on value of type null on line https://github.com/polylang/polylang/blob/master/settings/settings-browser.php#L42

### ISSUE THREAD

**Issue by ironland** [polylang/polylang#467]
## Prerequisites

- [x] This is not a usage question
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] I can reproduce this bug consistently
- [ ] This bug happens with a default WordPress theme active

## Steps to reproduce the issue

1. Activate Polylang
2. Deactivate Browser lang module

## Expected behavior and actual behavior

When I follow those steps, I see an error telling that `Trying to access array offset on value of type null` on line https://github.com/polylang/polylang/blob/master/settings/settings-browser.php#L42 

I was expecting that there would be an empty check of the possible null index for example like this:

```
		$active = $this->options['force_lang'] ?? 0;
		return ( 3 > $active ) || class_exists( 'PLL_Xdata_Domain', true );
```

**Comment by ironland** [comment]
For some reason the class seems to exist even though the module is deactivated.

**Comment by raaaahman** [comment]
I can't reproduce with Polylang version 2.6.10 and WordPress 5.3.2 / 5.4. Please try to update.

If you are still having this issue. Could you provide us some more details by:
- sending a WordPress Site Health report.
- sending a database dump / export
