### ISSUE TITLE
Sticky filter is showing posts for all languages when a specific language is selected

### ISSUE THREAD

**Issue by bartczyz** [polylang/polylang#469]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add at least two languages in Polylang.
2. Add a bunch of Sticky posts for both languages.
3. When you use the "Sticky" filter for one language sticky posts for all languages are shown:
<img width="1374" alt="Screenshot 2020-03-16 at 09 10 04" src="https://user-images.githubusercontent.com/1191500/76736399-04520d00-6767-11ea-9074-606fbc3baeef.png">

## Expected behavior and actual behavior

When using "Sticky" filter for one language posts for all languages are shown. I expect that only posts for selected language will be visible.

Tested on WordPress 5.3.2 and Polylang PRO 2.6.10.

**Comment by raaaahman** [comment]
Bug confirmed.

Although it doesn't happen if you select the _sticky_ filter first, **then** select a language filter.

**Comment by Chouby** [comment]
This is related to https://github.com/polylang/polylang-pro/issues/434. I proposed to review that for 2.8.
