### ISSUE TITLE
Setting a static front page in customizer fails silently if translations are not added 

### ISSUE THREAD

**Issue by k1sul1** [polylang/polylang#47]
When trying to set a static front page via customizer before adding translations to said front page, it will fail silently without any errors => quite confusing even for a seasoned developer. 

Trying to set the static front page from `Settings -> Reading` before adding translations also fails, but it displays a helpful error message: 

![the error](http://i.imgur.com/24ebILl.png) 

https://developer.wordpress.org/themes/advanced-topics/customizer-api/#setting-validation

**Comment by Chouby** [comment]
Yes I am aware of this issue. The validation API was introduced only recently and I have to look how o take profit of this.
