### ISSUE TITLE
Polylang language switcher menu item: Showing only active language

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#470]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

@manooweb, @Chouby:

1. Set up Polylang on a site to use two languages (here English and German).
Set one of the language as primary language, apply language to all posts as default.
2. Add the Polylang language switcher menu item to a WordPress menu.
Set the language switcher up to not show the active language.
3. Open a page/post on frontend that has been translated for the other non-primary language.
4. Notice that the language switcher shows only the primary, active language, no other languages, which is the opposite to its set up behavour.

## Expected behavior and actual behavior
The language switcher menu items should show only the other, non-active language.

**Comment by raaaahman** [comment]
Please don't tag our team members when posting an issue, the available developers will take a look when they have time.

I've been using Polylang with a configuration for the Language Switcher similar to the one you describe, and I didn't experienced this bug: https://devindetails.com/

Could you provide us more details about your settings? The following will be needed:
- A WordPress Site Health report 
- A database dump of your website (you can exclude the `wp_users` table for protecting your users' privacy, but all the other tables will be needed
- Screenshots from your selected _Languages > Settings_ (except for your license keys, of course), don't forget to unfold the _URL modifications_ and _Synchronization_ sections!

Thank you for your report.
