### ISSUE TITLE
Link two post language manually

### ISSUE THREAD

**Issue by KristenGarnier** [polylang/polylang#48]
Hi, I am currently developing a plugin for multiposting on multisite wordpress.

I wanted the plugin to work with polylang, it works well when it comes to setting the right language, but i can't find a way to connect to its other translations ( when i post from a blog to the others, otherwise on the same site, it works ).

Do you have any idea how I can set manually the link between translations of the same post ? 

Thank's by advance ! :)

**Comment by KristenGarnier** [comment]
I found a solution to this. 

You just have to create a wp_insert_term like this, with a different description: 

``` php
wp_insert_term($group = uniqid('pll_'), 'post_translations', array('description' => serialize(['fr' => 453, 'en' => 455])));
```

And then you set this term to your concerned posts or custom post : 

``` php
wp_set_object_terms( $postId, yourTerm, 'post_translations');
```


And here you are, your post are linked properly in you back end !

**Comment by grappler** [comment]
Actually there a special functions that do that for you. See https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/

**Comment by Chouby** [comment]
Yes. Please prefer using pll_save_post_translations(). Just in case the translations are saved differently in the future. Also all API functions are in https://github.com/polylang/polylang/blob/master/include/api.php

**Comment by KristenGarnier** [comment]
Thanks for the fast answer, i should have read the documentation better ! 
Thanks all for taking the time to answer my obvious questions !

Have a nice day :)

**Comment by b4dnewz** [comment]
where does that function `pll_save_post_translations()` take the postid from? 
I would like to add link to translation for an existing post inside a loop.

**Comment by grappler** [comment]
@b4dnewz I would use `pll_the_languages( array('post_id'=> get_the_ID()));`. https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/
