### ISSUE TITLE
Opengraph integration broken by Yoast SEO 14.0

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang#487]
Yoast SEO 14.0 will completely change how opengraph tags are generated. This will break our integration which won't be executed anymore (the action `wpseo_opengraph` is completely removed).
I questionned the Yoast team on the way to integrate with the new version. See https://github.com/Yoast/wordpress-seo/issues/14698

We can keep the current integration for a while for backward compatility with Yoast SEO < 14.0.

However, I will remove phpunit tests to avoid them failing as tests are already running against Yoast SEO 14.0-RC1.

**Comment by herregroen** [comment]
The `wpseo_opengraph` action should have been deprecated and was removed by accident.

https://github.com/Yoast/wordpress-seo/commit/18fc4ff67689ce81f0254813541dd3cfb28f2a9f adds it back as a deprecated action.

Please see my reply in https://github.com/Yoast/wordpress-seo/issues/14698#issuecomment-608445977 on the suggested replacement.

**Comment by oguilleux** [comment]
Hi there, any news regarding this matter ? Yoast 14.0 came out today.
