### ISSUE TITLE
After updating to 2.7 lang is forced for custom post type API endpoints

### ISSUE THREAD

**Issue by bartczyz** [polylang/polylang#493]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] I can reproduce this bug consistently

## Problem

After updating to **Polylang PRO 2.7** the plugin stopped respecting "Custom post types and Taxonomies" settings. For example, if the setting for our custom post type was un-checked in **2.6.10** then the call would return the response, even tho the lang parameter was specified in the call:
![image](https://user-images.githubusercontent.com/1191500/78672156-8e157600-78e0-11ea-84ce-1e664211d07e.png)

And when I changed the setting and checked that I would like the custom post type to be translatable:
![image](https://user-images.githubusercontent.com/1191500/78672301-c026d800-78e0-11ea-9535-a8a1e7dc35b4.png)

Then the call is not returning anything as expected, since the content was not translated or added to any language:
![image](https://user-images.githubusercontent.com/1191500/78672419-e77da500-78e0-11ea-9115-eea4ee6ec262.png)

But after updating to **Polylang PRO 2.7** this option is ignored completely. And when I do API call after I unchecked the box, I get no content in return:

![image](https://user-images.githubusercontent.com/1191500/78672692-49d6a580-78e1-11ea-8732-59eca50a3e52.png)

~~Also, why when I'm using **"Show all languages"** to add content, only content for the default language is shown (Media Library, Latest Posts widget etc.)? This should show content for all languages. This is confusing, especially to the editors that don't know which language is a default one.~~

**Comment by Chrystll** [comment]
Regarding your REST API issue it seems that it has been introduced by this commit "Set query vars lang value with the REST API lang parameter" https://github.com/polylang/polylang-pro/commit/bc77510ed2f13ea5b3dee05526312253550c7704. We are investigating it. Regarding your issue second issue about the "Show all languages" filte, could you please open a ticket on our [helpdesk](https://polylang.pro/support/)?  I would need that you show me your issue thanks to a video so that I understand exactly what is happening.
