### ISSUE TITLE
Bug? Posts count on admin page is off

### ISSUE THREAD

**Issue by vHeemstra** [polylang/polylang#496]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. After activating the plugin, add a default language and create some pages in that language
2. Add a second language and create some translations for existing pages. (Some published, some private.)
3. Have a look at the Posts column on the admin page Languages

## Expected behavior and actual behavior

The counts should match the number of pages/posts/etc in that language.

## What actually happens

They're off. :)

## Possible fix?

After quite some time browsing through the source codes, I found what seems to be a fix for this, but I'm not sure if this is correct.

Inside the `PLL_Translated_Object` constructor, I add:

`$args['update_count_callback'] = '_update_generic_term_count';`

before the:

`register_taxonomy( $this->tax_language, $this->object_type, $args );`

Now, if I then force `wp_update_term_count()` for both `language` and `term_language` taxonomies using the proper IDs from my two languages, the counts are higher for both and are correct.

## However...

When I edit one of the translated pages, the count of that language is reset to 0 like before.

## Question

Is this a bug or is the count actually counting something different then what I expect?

**Comment by Chouby** [comment]
I don't have any issue with the posts count in the languages list table. At least all my languages display a non-null value. When no `update_count_callback` argument is provided to the taxonomy, WordPress is supposed to use `_update_post_term_count` for taxonomies registered for post types ( for instance 'language', what is displayed in the Posts column ) and `_update_generic_term_count` for other taxonomies ( for instance  'term_language', not displayed to the user ). See https://github.com/WordPress/WordPress/blob/5.4/wp-includes/taxonomy.php#L3153-L3159 . This is the intended behavior. Have you published pages in the language displaying 0?

**Comment by vHeemstra** [comment]
Hi @Chouby, thank you for the quick response.

When the count is at 0 for the second language (although there are 2 private-published page transaltions), if I change one to non-private published, the count stays 0.

After doing my 'possible fix', when the count is correct (with 2 translated page set to 'private'), if I change one to 'publish', the count for that language goes one down from what it was.

Really strange..

Or are the 'private' pages and/or 'draft' not counted?

**Comment by Chouby** [comment]
As you can see the posts with 'publish' status are counted: https://github.com/WordPress/WordPress/blob/5.4/wp-includes/taxonomy.php#L3723
If you need a different behavior, you could use your own `update_count_callback` using the filter `register_taxonomy_args`

**Comment by vHeemstra** [comment]
Ah, yes, I should’ve read it better.. 

However, even we I set them to ‘publish’, they are still not counted. I’ll see if any plugin is interfering.

**Comment by vHeemstra** [comment]
After reset the plugin's source code, and forcing the re-counts, the numbers seem to be correct again.

There is still a problem that once the count is off, there's no clean way to force recalculation of these. (And maybe it's a nice feature to see the counts for Draft and Private as well?)

Anyway, thanks for your replies and tip for the right filter to use. If I get the suggested functionality to work, I'll post it here.

**Comment by Chouby** [comment]
As you have noticed, we are using a native WordPress count callback, the same used for categories and tags. WordPresst should re-aevaluated this count each time you publish a post. I guess that this count is meant to count only *public* posts.
