### ISSUE TITLE
Cannot disable custom post type "Beaver Themer Layouts" in Polylang

### ISSUE THREAD

**Issue by Bobolinos** [polylang/polylang#498]
Hi,

I cannot disable the custom post type "Beaver Themer Layouts" in the Polylang settings. The checkbox is disabled. Is this a bug? It cannot be unchecked.

**Comment by Bobolinos** [comment]
Does someone know why a custom post type would appear for translation but is forced check and cannot be turend off?

**Comment by Chouby** [comment]
When a 3rd party plugin developper registers a post type and tells Polylang that this post type must be translatable, we disable the option to avoid any wrong usage from the users. If you are a developper yourself, you can override this original choice with the filter `pll_get_post_types`.

GitHub issues should be used only to report bugs. For such usage questions, please use the wp.org forum.
