### ISSUE TITLE
Incorrect url for the translated homepages

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang#503]
Since Yoast SEO 14.0, presenters do not output the correct url on the translated homepage. 

The canonical outputed is:
`<link rel="canonical" href="http://example.org/">`
instead of:
`<link rel="canonical" href="http://example.org/en/">`

The og:url outputed is:
`<meta property="og:url" content="http://example.org/">`
instead of
`<meta property="og:url" content="http://example.org/en/">`

The case of json schema is a bit more complex as it mixes correct urls and incorrect urls:
```json
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "http://example.org/en/#website",
      "url": "http://example.org/en/",
      "name": "Test WP",
      "description": "Just another WordPress site",
      "potentialAction": [
        {
          "@type": "SearchAction",
          "target": "http://example.org/en/?s={search_term_string}",
          "query-input": "required name=search_term_string"
        }
      ],
      "inLanguage": "en-US"
    },
    {
      "@type": "ImageObject",
      "@id": "http://example.org/#primaryimage",
      "inLanguage": "en-US",
      "url": "http://example.org/wp-content/uploads/2020/01/img_3149_campanula_cenisia.jpg",
      "width": 900,
      "height": 600
    },
    {
      "@type": "WebPage",
      "@id": "http://example.org/#webpage",
      "url": "http://example.org/",
      "name": "Page : Home - Test WP",
      "isPartOf": {
        "@id": "http://example.org/en/#website"
      },
      "primaryImageOfPage": {
        "@id": "http://example.org/#primaryimage"
      },
      "datePublished": "2020-02-07T14:18:41+00:00",
      "dateModified": "2020-02-07T15:38:29+00:00",
      "inLanguage": "en-US",
      "potentialAction": [
        {
          "@type": "ReadAction",
          "target": [
            "http://example.org/"
          ]
        }
      ]
    }
  ]
}
```
It seems to be due to a Yoast SEO regression which doesn't honor the home_url filter anymore. Indeeed, as a quick test, I replaced the code of `Canonical_Presenter::get()` by:
```php
public function get() {
		return \WPSEO_Utils::home_url();
}
```
And in this case, the canonical url is correctly outputed because the `home_url` filter is correctly honored. The regression was reported to Yoast in https://github.com/Yoast/wordpress-seo/issues/14994

### How can we reproduce this behavior?
1. Setup Yoast SEO 14.0.2-rc1 and Polylang 2.7.2
2. Add 2 languages (the first one will be the default language)
3. Create a post in the second language.
4. Visit the homepage in the second (non-default language) and check the html source code.

**Comment by papazetis** [comment]
The same happens on archives of custom post types.
Is there any fix on that?
Single ones work well

**Comment by webgrafia** [comment]
Same problem, it work only if i reset indexable tables with yoast test plugin, but it appear again randomly the wrong url and I need to clear it every day to let it work
