### ISSUE TITLE
Polylang & Charitable incompatibility

### ISSUE THREAD

**Issue by ericnicolaas** [polylang/polylang#507]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Polylang, Theme and plugin translation for Polyang, and Charitable
2. In Languages > String translations, translate "First name" and "Last name" in Charitable to a new language. 
3. Create a campaign in Charitable (Charitable > Add Campaign).
4. View campaign, then click on Donate. 

## Expected behavior and actual behavior

On the donation form, the "First name" and "Last name" fields are not using the Polylang translations. 

For an example, see https://sandbox.wpcharitable.com/yetanothernewone/faire-un-don/. There is a French & English version of this page. The French version should show "Prénom" instead of "First name". Other translations are loaded correctly. 

I was expecting to see "Prénom" instead of "First name".

## More details

I have been digging into this issue for quite a while since our customer encountered it. I think I have found the issue, but I'm not sure how to resolve it. 

Currently, we set up the fields that are eventually used in the donation form during the `plugins_loaded` hook. After reading https://github.com/polylang/polylang/issues/39, I see that this is too early. My reading of WP core is that a hook like `after_setup_theme` or `init` should be late enough, so I am testing with that. 

However, even when using `init` with a low priority, Polylang translations still aren't loading. Looking at `PLL_Choose_Lang_Content`, it seems like you're only loading the language at the `wp` hook. 

Is there a suggested way for dealing with this incompatibility? I imagine you have probably run into this issue with other plugins before, so just wanted to see if you have any suggestions.

**Comment by Chouby** [comment]
I tested your plugin. For me it works as expected, except when I select the Polylang option "The language is set from the content".

Usually Polylang defines the language in a function hooked to `plugins_loaded` with priority 1. Then it lets WordPress, the theme and plugins load their translations as usual.

However, when "the language is set from the content", we need to wait for the result of the main query to know which language to load. In this case, Polylang captures all calls to `load_textdomain()` to collect all translations files that need to be loaded and uses this information to load the correct translation files in a function hooked to `wp`, after the main query.

As the output starts later, this should work in theory. The caveat is that it's perfectly possible to store translated strings in variable before they are outputed. Then some themes or plugins are not compatible with this option. 

WP itself stores translated srings in variables for post type and taxonomy labels. But as I know where these translations are stored, the labels are translated in the correct language once the language is known.

For me, you did things correctly. And this is this Polylang option which creates this kind of incompatibility as, unless you know Polylang well, there is no reason to expect that the translations files are loaded so late.

If you want to be compatible with this option, you would need to wait for the action `wp` to start using translatiion functions.  

If I replace:
`add_action( 'plugins_loaded', array( $this, 'donation_fields' ), 100 );`
by
`add_action( 'wp', array( $this, 'donation_fields' ) );`
then the fields are correctly translated. But I am not sure if there are side effects or not.

**Comment by ericnicolaas** [comment]
Thanks @Chouby — that was a very detailed and helpful explanation! 

In our next release I'm adding some Polylang compatibility code which runs on the `wp` hook and checks if the language is pulled from the content, then loops over all the translatable strings that are otherwise not translated. Seems to work quite nicely and avoids changing things for anyone other than Polylang users with that particular option set.
