### ISSUE TITLE
Display the flags on post list 

### ISSUE THREAD

**Issue by sebastienserre** [polylang/polylang#515]
This idea come from @webaxones on [Helpscout](https://secure.helpscout.net/conversation/1112039236/9759) (private)
The main idea is to replace the tick with the language flag:
![polylang](https://user-images.githubusercontent.com/3902621/83501014-cfc93400-a4bf-11ea-980d-75bac0963a21.jpg)
For history, this issue was previously opened on Polylang Pro. https://github.com/polylang/polylang-pro/issues/528

**Comment by sebastienserre** [comment]
@chouby previous comment:
```
It looks indeed more readable. Two cases require a specific attention:

    When the user as not edit access to the post, there is no link. Note that currently we change the color of the tick icon to make things more visual.
    It's possible to have no flags for the languages. In such case, we usuallly display the language code. We have to decide if we should display the language code in this case too. Note that here we could keep changing the color when there is no link.

```
@manooweb Previous comment:
```
Exactly! I think a lot of flags are the same in grayscale (3 colors with vertical or horizontal lines).
And I'm not sure about the compatibily (cross browser) of this kind of CSS function. I also think flag are too small to be distinguishable enough in grayscale.

Because I work on this issue #526 a language could have no flag. So don't forget to replace the flag by the languge code in this case. As the customer suggest and I started to implement we can use a abbr tag which has a title attribute where we can put the language name for displaying a hint.

I'm working on all polylang to make it more consistent everywhere.
```

**Comment by webaxones** [comment]
In fact I think that a user who can't edit post will see black pens next to the flag so he won't even think of clicking on it. #mentalpowa :D

**Comment by sebastienserre** [comment]
If the flag doesn't exist, the language slug is displayed
![7R22kSK](https://user-images.githubusercontent.com/3902621/83647510-4431cf00-a5b5-11ea-9ff1-11dfc08cc2e2.png)

**Comment by Chouby** [comment]
@webaxones Currently, when a user cannot edit a translation, there is no icon at all (we don't grey the pen icon). It's also possible that we are allowed to edit a post but not its translations. This occurs for example for authors. 

In the screenshot below (made with the current version 2.7.3), I am an author. I did not write the original English post and the French translation, but I am the author of the German translation. Thus I can only edit the German post. 
![author-posts-list](https://user-images.githubusercontent.com/3238583/83763384-ecf53280-a678-11ea-8c44-6a9cc68b0ca0.png)

**Comment by Chouby** [comment]
I now remember we had this issue: #325. This could be even more confusing with this proposal. Could you check?
