### ISSUE TITLE
Cannot save string translations

### ISSUE THREAD

**Issue by ve3** [polylang/polylang#52]
My permalink is `/%category%/%postname%/`
(The language is set from the directory name in pretty permalinks)
(Remove /language/ in pretty permalinks)
(Hide URL language information for default language)

My front page is non static.

Link to my site is http://wimutti.org/ and http://wimutti.org/en/

I tried to disabled plugins but not working.

I tried to translated strings and click on **Save Changes** but nothing saved.

**Comment by Chouby** [comment]
This issue has been reported a few times on the support forum, but I never could reproduce it and thus I don't know where to look for.

Users running their site with WP_DEBUG set to true reported an unserialize error, which make me think that data are corrupted by some third party plugin either when writing the strings in DB (or when reading them).

**Comment by ve3** [comment]
My fix:

Open WordPress admin dashboard
Go to Settings > Languages
Edit any languages that have problem (in my case it is English).
From first select box, select the same language (in my case it is English US)
Save

Go to string translations and translate something and then save.
Now it works.
