### ISSUE TITLE
Filter `pll_custom_flag` changes ALL my flags

### ISSUE THREAD

**Issue by carlosarnote** [polylang/polylang#521]
I added this code through the pll_custom_flag filter:

add_filter( 'pll_custom_flag', 'pll_custom_flag', 10, 2 );
function pll_custom_flag( $flag, $pt ) {
    $flag['url']    = "localhost/wordpress/wp-content/plugins/polylang/pt_BR.svg";
    $flag['width']  = 32;
    $flag['height'] = 32;
    return $flag;
}

What happens is that it changes both of my flags, as you can see here:
![polylang issue 2](https://user-images.githubusercontent.com/66733489/84271561-9ff2df80-ab02-11ea-9f70-3bbe5e582e7d.png)

I would like to know how to properly code this filter to set my custom flags to each language, since I tryed to repeat the code in the bottom with my en_US locale and code to distinguish the languages flags and it's cracked wordpress.

Here is my dashboard:
![polylang issue 1](https://user-images.githubusercontent.com/66733489/84271559-9f5a4900-ab02-11ea-9561-897d233e1932.png)

Can you guys help me? Thanks.

**Comment by chesio** [comment]
The second parameter passed to the `pll_custom_flag` function is language code so make use of it accordingly, see: https://polylang.pro/doc/filter-reference/#pll_custom_flag

Btw. GitHub issues are meant for real issues (bugs, feature requests etc.), not for support. You can get support [here](https://polylang.pro/support/) (if you have purchased Polylang Pro) or [here](https://wordpress.org/support/plugin/polylang/) (if you are using free version).
