### ISSUE TITLE
Polylang lang_choice dropdown widget displays without Label - non-accessible form control

### ISSUE THREAD

**Issue by Twintails** [polylang/polylang#53]
ref: [(http://webaim.org/techniques/forms/controls#select)]

**Line 44-46 on include/widget-languages.php**
```
	if ( $title ) {
				echo $args['before_title'] . $title . $args['after_title'];
			}
```

**Suggestion without theme fallback:**

```
if ( $title ) {
  echo $instance['dropdown'] ? '<label for="lang_choice_'.$args['widget_id'].'">' . $title : $args['before_title'] . $title;
  echo $instance['dropdown'] ? '</label>' : $args['after_title'];
}
```

**Suggestion with Theme Fallback:**

      if ( $title ) {
        echo $instance['dropdown'] ? '<label  for="lang_choice_'.$args['widget_id'].'">' . $args['before_title'] . $title : $args['before_title'] . $title;
        echo $instance['dropdown'] ? $args['after_title'] . '</label>' : $args['after_title'];
      }

This way them devs could still wrap the title from the $before_title and $after_title hooks, with 
```
<sapn class="visuallyhidden">Widget Title</span> or <h2>Widget Title</h2>
```
I couldn't determine where the 'lang_choice_' portion of the select(dropdown) id comes from. perhaps someone more familiar with the code could look into integrating this?

**Comment by Chouby** [comment]
Thanks for reporting this issue.

The code was initially inspired by the core widgets archives and categories. But I missed the accessibility improvement done in WP 4.2 (https://core.trac.wordpress.org/ticket/18650).

I'd like however to keep the consistency with the core widgets and thus use the same code. See https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/widgets/class-wp-widget-archives.php#L59

Thus I propose:
`
if ( $instance['dropdown'] ) {
	if ( $title ) {
		echo '<label class="screen-reader-text" for="' . esc_attr( 'lang_choice_' . $instance['dropdown'] ) . '">' . $title . '</label>';
	}
	echo $list;
} else {
	echo "<ul>\n" . $list . "</ul>\n";
}
`

**Comment by Twintails** [comment]
Excellent! 
It may need to be able to wrap the title still from the theme register_sidebar's before_title and after_title. 

```
echo $args['before_title'] . '<label class="screen-reader-text" for="' . esc_attr( 'lang_choice_' . $instance['dropdown'] ) . '">' . $title . '</label>' . $args['after_title'];

```
This would allow Block Level elements such as `<h2>` or further inline elements like `<span>` to surround the widget title if needed by the theme sidebar for consistency.
