### ISSUE TITLE
Broken Uncategorized category

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#541]
I have Uncategorized category which I renamed into another name. After upgrading to 2.7.4 this category is broken now. All translations (EN and RU) of this category is available on EN side and not available on RU side (even RU trasnation of this category). How to fix it? I can’t change language of this category in category settings, language selection combobox is disabled/inactive.

**Comment by Chrystll** [comment]
I don't reproduce your issue on my side. Could you please describe your issue step by step with screenshots to well understand it?

**Comment by EldarAgalarov** [comment]
I have many categories one of them is original Uncategorized category which is impossible to delete. So I just renamed it and continue to use. I have two languages EN and RU on site and previously all was fine. Now two (EN and RU) translations of Uncategorized is available only for EN language and looks like they are different categories with EN translations. And none of them when switching to RU language. Polylang have option to set language of the category in category settings, but exactly for Uncategorized it's disabled/inactive.

**Comment by EldarAgalarov** [comment]
Found that language cannot set only for default category for posts in WP Settings. Workaround is following: set as default category any other category, change language of desired default category and set in as default.

**Comment by Tofandel** [comment]
I'm having the same issue, to reproduce, just try to create translations for the "Uncategorized" category and try to assign them, it never updates
