### ISSUE TITLE
pll_language coockie warning messege

### ISSUE THREAD

**Issue by AmitT** [polylang/polylang#542]
While using Firefox I get this warning:

`Cookie “pll_language” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. install Polylang Pro
2. Open Firefox
3. Open the Developer tools & Go to your site.

**Comment by Chrystll** [comment]
I don't reproduce your warning message. As you are using Polylang Pro, I would need that you contact us [here](https://polylang.pro/support/) to give us further informations to reproduce your issue. Thank you.

**Comment by Chrystll** [comment]
Thank you for the link to your site I see your warning now. There are 2 ways to set a cookie, one in http and one in js (when having a cache plugin). This warning happens with the cookie set in js. Until now we were not aware that the browser sent a warning in this case so thank you for the report. We will fix it.

**Comment by MROVIC** [comment]
Dear @Chrystll,
I just checked last version of Polylang (3.5.4) and this is the report of PHP-compatibility-checker.
How to solve? Should the user fix by himself?
Thank you.

Polylang 3.5.4

PHP 5.6 incompatibilities:

FILE: include/base.php
-----------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
-----------------------------------------------------------------------------
 165 | ERROR | bool return type is not present in PHP version 5.6 or earlier 
-----------------------------------------------------------------------------

FILE: include/crud-posts.php
--------------------------------------------------------------------------------------
FOUND 4 ERRORS AND 0 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------------
 387 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 387 | ERROR | array return type is not present in PHP version 5.6 or earlier         
 410 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 410 | ERROR | int return type is not present in PHP version 5.6 or earlier           
--------------------------------------------------------------------------------------

FILE: include/filter-rest-routes.php
--------------------------------------------------------------------------------------
FOUND 5 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
--------------------------------------------------------------------------------------
  56 | ERROR | array return type is not present in PHP version 5.6 or earlier         
 109 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 123 | ERROR | array return type is not present in PHP version 5.6 or earlier         
 150 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 150 | ERROR | bool return type is not present in PHP version 5.6 or earlier          
--------------------------------------------------------------------------------------

FILE: include/functions.php
--------------------------------------------------------------------------------------
FOUND 6 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
--------------------------------------------------------------------------------------
 142 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 142 | ERROR | bool return type is not present in PHP version 5.6 or earlier          
 158 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 178 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 178 | ERROR | bool return type is not present in PHP version 5.6 or earlier          
 196 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
--------------------------------------------------------------------------------------

FILE: modules/wpml/wpml-config.php
--------------------------------------------------------------------------------------
FOUND 6 ERRORS AND 0 WARNINGS AFFECTING 4 LINES
--------------------------------------------------------------------------------------
 740 | ERROR | bool return type is not present in PHP version 5.6 or earlier          
 769 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 769 | ERROR | bool return type is not present in PHP version 5.6 or earlier          
 801 | ERROR | array return type is not present in PHP version 5.6 or earlier         
 843 | ERROR | 'string' type declaration is not present in PHP version 5.6 or earlier 
 843 | ERROR | string return type is not present in PHP version 5.6 or earlier        
--------------------------------------------------------------------------------------
