### ISSUE TITLE
Showing only one language on both front and back after updating to 2.7.4 ( 2020-06-29)

### ISSUE THREAD

**Issue by miryamfv** [polylang/polylang#555]
## Prerequisites

- [x ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Upgrade to 2.7.4

## Expected behavior and actual behavior

When I follow those steps, I see...

Navigate to post list or front you will see in my case (28) published but only 15 on the list, no pagination
Downgrading to another version takes the issue away

I was expecting...

**Comment by raaaahman** [comment]
Hello,

reading at what you describe here, I have no way of telling if this is a Polylang internal error or just an issue regarding of your particular environment: the other plugins you use, your theme and/or child theme, the version of your WordPress website, etc.

(Also, verify you have not [filtered your posts by language](https://polylang.pro/wp-content/uploads/2015/11/pages-list-table-and-filter-language-1-2.png))

Note that Polylang 2.8 have been released, try with this version isntead.

You should try to [contact our support desk](https://polylang.pro/support/) first. Any screenshot, database export and site health report you can provide them will help.

Thank you for your understanding.

**Comment by miryamfv** [comment]
thanks for your response

**Comment by raaaahman** [comment]
You're welcome.
