### ISSUE TITLE
Saving ACF Repeater that uses on conent type error

### ISSUE THREAD

**Issue by rajankapila** [polylang/polylang#565]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a ACF with repeater that uses a content type
2. save or try to edit page with this acf content
3.

## Expected behavior and actual behavior`

When I follow those steps, I see...

Fatal error:  Uncaught Error: Cannot use object of type WP_Post as array in wp-content/plugins/polylang-pro/modules/plugins/acf-sync-metas.php:132
Stack trace:
#0 /wp-content/plugins/polylang-pro/modules/plugins/acf-sync-metas.php(146): PLL_ACF_Sync_Metas->get_translations(Array, 'components_1_lo...', Array, Array)
#1/wp-content/plugins/polylang-pro/modules/plugins/acf-sync-metas.php(196): PLL_ACF_Sync_Metas->get_translations(Array, 'components', Array, Array)
#2/wp-includes/class-wp-hook.php(289): PLL_ACF_Sync_Metas->copy_metas(Array, true, 172, 9393)
#3 /Users/rajankapila/websites/netskope_stagin/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#4 /wp-content/plugins/polylang-pro/modules/sync/sync-post-metas.php(68): apply_filters('pll_copy_post_m...', Array, true, 172, 9393, 'fr')
#5 /User in /wp-content/plugins/polylang-pro/modules/plugins/acf-sync-metas.php on line 132

I was expecting...
to save my content.

**Comment by Chouby** [comment]
For Polylang Pro customers, we prefer using our ticketing system. You will receive a faster support. Could you please contact the support team? https://polylang.pro/support/. Thanks.

**Comment by rajankapila** [comment]
Here is our acf json file.

It happens when saving a company_logos item.

Here is the error again.

Uncaught Error: Cannot use object of type WP_Post as array in
/wp-content/plugins/polylang-pro/integrations/acf/acf-sync-metas.php:130\nStack
trace:\n#0 /wp-content/plugins/polylang-pro/integrations/acf/acf-sync-metas.php(144):
PLL_ACF_Sync_Metas->get_translations(Array, 'components_1_lo...',
Array, Array)\n#1
/wp-content/plugins/polylang-pro/integrations/acf/acf-sync-metas.php(194):
PLL_ACF_Sync_Metas->get_translations(Array, 'components', Array,
Array)\n#2 /wp-includes/class-wp-hook.php(289):
PLL_ACF_Sync_Metas->copy_metas(Array, true, 172, 9393)\n#3
/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)\n#4
/wp-content/plugins/polylang-pro/vendor/wpsyntex/polylang/modules/sync/sync-post-metas.php(71):
apply_filters('pll_copy_post_m...', Array, true, 172, 9393, 'fr')\n#5
/wp-content/plugins/polyl in
/wp-content/plugins/polylang-pro/integrations/acf/acf-sync-metas.php
on line 130, referer:
https://www.netskope.com/wp-admin/edit.php?s=customer&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&paged=1&action2=-1

**Comment by rajankapila** [comment]
Hi,

Any follow up on this?

cheers,
raj.

**Comment by Chouby** [comment]
Please contact the support team. GitHub is not the right place for us to offer a good follow-up of your issue. And please export your ACF fields in a .json file and forward it to the support team.
