### ISSUE TITLE
pll_current_language in REST API returns `false`

### ISSUE THREAD

**Issue by simplenotezy** [polylang/polylang#576]
Also described here: https://github.com/polylang/polylang/issues/501

How can I fetch the current language in the API?

**Comment by Chrystll** [comment]
By default, REST API requests don't include any language so no current language is defined. With Polylang Pro we have added a new field 'lang' to some endpoints such as /wp/v2/posts to allow filtering the response by a language. The support of the REST API is only available in Polylang Pro and not in Polylang.
If you are using Polylang Pro and need some help, please contact our helpdesk: https://polylang.pro/support/.
