### ISSUE TITLE
get_home_url returns default domain regardless of language

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#58]
Issue for #55

We have defined different subdomains per language.

`get_home_url()` always returns the URL of the default site.

This affects `get_rest_url()` in WP core and `The_Neverending_Home_Page::ajax_url()` from jetpack.

As I was looking at the source code of the page I saw that the `<link rel="next" href="http://magazine.example.ch/page/2/" />` is linking to the default language URL.

I think we should change the URL at the source instead of having to change the URL for every plugin.

**Comment by Chouby** [comment]
In fact `get_home_url()` is complex to filter. In some cases, we need to filter it and in other cases we need to keep as is. By default, it is filtered only when called from the theme. For all other cases, I use a system of whitelist.

I am not familiar with the REST API. What are the cases where `get_rest_url()` must be filtered?

I will investigate the issue with Jetpack.

**Comment by grappler** [comment]
The `get_rest_url()` is used in https://github.com/WP-API/WP-API/blob/develop/extras.php#L30 which is now also being used in WP 4.7 https://github.com/WordPress/WordPress/blob/master/wp-includes/script-loader.php#L508.

This is only a problem when you are using different domains. I expect this will affect any plugin that are using AJAX.

For Jetpack the issue is the error
`XMLHttpRequest cannot load https://rivista.example.ch/?infinity=scrolling. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://magazine.example.ch' is therefore not allowed access.`

For the rest API the error is:
`XMLHttpRequest cannot load https://magazin.example.ch/wp-json/wp/v2/. Request header field X-WP-Nonce is not allowed by Access-Control-Allow-Headers in preflight response.`
