### ISSUE TITLE
Wrong post object data in ACF options page

### ISSUE THREAD

**Issue by oguilleux** [polylang/polylang#581]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create two languages
2. Use default language
3. Create ACF options page with a post object field
4. Go to the ACF options page
5. Add a post object in the field
6. Save
7. Switch to second language
8. See that the post object field data is now different

## Expected behavior and actual behavior

Actual behavior
Since ACF options page are not translated, when the steps above are reproduced we should have the same data in every language. In a post object select field, the posts are filtered with current language thus when we switch language the data saved is not the same as default language.

Expected behavior
In options page, don't filter the post object by current language, leave default language filter OR when we save the data, keep data saved in other languages.

**Comment by Chrystll** [comment]
Polylang is not handling ACF's Option Pages. However it exists an integration built by the Be API Agency to handle the compatibility, see: https://github.com/BeAPI/acf-options-for-polylang
Maybe that you can give it a try to see if that can meet your needs.
