### ISSUE TITLE
Search results not displayed (404)

### ISSUE THREAD

**Issue by bsuccar** [polylang/polylang#59]
I'm using X-theme with cornerstone and ubermenu. The search results do not display (404) until I deactivate Polylang.  Please Have a look: http://bimexcellence.org/

**Comment by Chouby** [comment]
The problem is not in the X theme which I tested and works correctly.

When a search form does not work it's due to the search form not passed passed through filter 'get_search_form'. See: https://polylang.pro/always-use-get_search_form-to-create-search-forms/

**Comment by ahmed4x42010** [comment]
i have the same problem with myhome theme and this is code in searchform.php 


<form role="search" method="get" id="searchform" class="searchform" action="<?php echo esc_url( home_url( '/' ) ); ?>">
	<label class="screen-reader-text" for="s"><?php esc_html_e( 'Search for:', 'myhome' ); ?></label>
	<input placeholder="<?php echo esc_attr( My_Home_Theme()->settings->get( 'search-placeholder' ) ); ?>"
	       value="<?php echo esc_attr( get_search_query() ); ?>" name="s" id="s" type="text" />
</form>

**Comment by ahmed4x42010** [comment]
<form role="search" method="get" id="searchform" class="searchform" action="<?php echo esc_url( home_url( '/' ) ); ?>">
	<label class="screen-reader-text" for="s"><?php esc_html_e( 'Search for:', 'myhome' ); ?></label>
	<input placeholder="<?php echo esc_attr( My_Home_Theme()->settings->get( 'search-placeholder' ) ); ?>"
	       value="<?php echo esc_attr( get_search_query() ); ?>" name="s" id="s" type="text" />
</form>

**Comment by ahmed4x42010** [comment]
`<form role="search" method="get" id="searchform" class="searchform" action="<?php echo esc_url( home_url( '/' ) ); ?>">
	<label class="screen-reader-text" for="s"><?php esc_html_e( 'Search for:', 'myhome' ); ?></label>
	<input placeholder="<?php echo esc_attr( My_Home_Theme()->settings->get( 'search-placeholder' ) ); ?>"
	       value="<?php echo esc_attr( get_search_query() ); ?>" name="s" id="s" type="text" />
</form>`
