### ISSUE TITLE
Site Logo URL translation bug

### ISSUE THREAD

**Issue by theleemon** [polylang/polylang#6]
I'm using the new Site Logo feature introduced in WP 4.5 in a couple of sites with Polylang and the Site Logo URL in every language points to the home page in the default language. Apparently, Polylang is not filtering it taking the current language into account.

This is the WP function I'm using to display the Site Logo:
https://developer.wordpress.org/reference/functions/the_custom_logo/

**Comment by Chouby** [comment]
Hi,

I confirm the issue. I missed this feature :(

**Comment by theleemon** [comment]
I've installed the latest 1.9.2 version of the plugin and the bug is still present.

**Comment by Chouby** [comment]
Yes I committed that to master branch, not 1.9.x

**Comment by theleemon** [comment]
Is this going to be fixed in the 1.9.x branch?
Thanks

**Comment by GipsyBeggar** [comment]
The issue is still present
