### ISSUE TITLE
Polylang 2.0.8 - Uncaught TypeError: Cannot read property 'indexOf' of undefined in post.js

### ISSUE THREAD

**Issue by decarvalhoaa** [polylang/polylang#60]
The new release 2.0.8 release and in particular this [change](https://github.com/polylang/polylang/commit/335e82a92e62b11682f7501e77be39c18611e6c2) in js/post.js is blocking savings Product Attributes in WooCommerce.

The javascript error is Uncaught TypeError: Cannot read property 'indexOf' of undefined in post.js. I think options.data is not defined and creates this error.

How to reproduce:

1. in Admin > Products edit a product
2. Add a new Attribute to the Product in the Product Data metabox
3. Click Save attributes button

See [screenshot](https://1drv.ms/i/s!Apzufnt_aOHHmFj-2PsEpkzlwJQM).

**Comment by Chouby** [comment]
A similar error has been reported on the WordPress forum. I should have have fixed it in https://github.com/polylang/polylang/commit/7a1bcaa05d400b428b3465bf64e582aacf54836f

**Comment by decarvalhoaa** [comment]
Great! That should solve it. But since from 2.0.7 you only added `|| -1 !== options.data.indexOf( 'action=ajax-tag-search' )` to the first test, I was wondering why not just

`
if ( ( -1 !== options.url.indexOf( 'action=ajax-tag-search' ) || ( 'undefined' !== typeof options.data && -1 !== options.data.indexOf( 'action=ajax-tag-search' ) ) ) && ( ( lang = $( '.post_lang_choice' ).val() ) || ( lang = $( ':input[name="inline_lang_choice"]' ).val() ) ) ) {
  			options.data = 'lang=' + lang + '&' + options.data;
  		}
  	});
`

This way, the test ` -1 !== options.url.indexOf( 'action=ajax-tag-search' )` is still done like in 2.0.7.

Closing this issue....

**Comment by Chouby** [comment]
That was indeed another possibility. Since `options.data ` is defined for the two ajax requests I have to filter, both are equal.
