### ISSUE TITLE
Polylang doesn't flush object cache for sticky posts

### ISSUE THREAD

**Issue by ckoerner** [polylang/polylang#601]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Setup WordPress and install and configure Polylang. 
2. Enable Memcache on your site.
3. Make a published post "sticky".
4. Validate that site is cached.
5. "Unsticky" the post.
6. Make a different published post "sticky".
7. The first published post appears sticky and the second does not.
8. Scratch your head in confusion. 
9. Disable Polylang and the correct sticky post appears.

## Expected behavior and actual behavior

The expected behavior is that the new sticky post will be the post that appears, and not the previously stickied post. 

I am using Polylang on a site hosted by WordPress VIP Go. Here is a description of how their object cache works. 

https://wpvip.com/documentation/vip-go/caching-on-vip-go/#object-cache

In working with one of the support engineers, they described the issue as thus, 

"It looks like there is a caching issue here, but in particular with the object cache (Memcached).

The sticky posts are saved in a WordPress option. When this is looked up, Polylang intercepts.
Polylang then does its own lookup to find the corresponding posts for other languages, and it caches those results separately from the original option.

Here's where this is happening:
https://github.com/wpcomvip/wikimedia-blog-wikimedia-org/blob/develop/plugins/polylang/frontend/frontend-filters.php#L85

The problem is that the cache that Polylang set doesn't have any built-in expiration or updates. So regardless of the value of the sticky posts option in the database, it is replaced with an unchanging cached value. (It might expire eventually and be refreshed, but there's no telling when. )

Polylang likely needs to add a bit of code to flush their sticky posts cache when sticky posts are changed."

For a work-around solution, site admins can clear the sticky_posts cache on command using wp-cli.

`wp cache delete sticky_posts options`

I'm enjoying using Polylang and VIP together. While I have a work-around I can use for now, I wanted to make you aware of  the issue.

**Comment by Chouby** [comment]
Yes. Obviously I missed something.

**Comment by Chouby** [comment]
@ckoerner, If you are interested to test the patch before we release it in 2.8.4, here is the patch: #610
