### ISSUE TITLE
Deprecated: _get_path_to_translation is deprecated since version 5.6.0!

### ISSUE THREAD

**Issue by oldrup** [polylang/polylang#627]
Hey... When using Polylang with the WordPress 5.6 beta 3, and debug info on, I receive those warnings:

`Deprecated: _get_path_to_translation is deprecated since version 5.6.0! Use WP_Textdomain_Registry instead. in /home/oldrupdk/oldrup.net/wp-includes/functions.php on line 4840

Deprecated: _get_path_to_translation_from_lang_dir is deprecated since version 5.6.0! Use WP_Textdomain_Registry instead. in /home/oldrupdk/oldrup.net/wp-includes/functions.php on line 4840`

Issue experienced on my testsite at https://oldrup.net/plugin/polylang/

Polylang currently not enabled due to the site wide error message.

Please let me know if there is anything I can do to troubleshoot this issue further, or if there is a fix I can test.

Kind regards
Bjarne

**Comment by manooweb** [comment]
Hello @oldrup,

Thank you for the ping 😉

We already have taken this in account in this PR https://github.com/polylang/polylang/pull/607
Our future beta release of our next major version will come soon.

Regards
