### ISSUE TITLE
use_balanceTags and String Translation issues

### ISSUE THREAD

**Issue by theleemon** [polylang/polylang#63]
If the `use_balanceTags` option in WordPress is active, the `wp_insert_post` call in the `export_to_db` function in the `mo.php` file "fixes" malformed HTML content in text widgets and other translatable fields and thus causes the `unserialize` call in the `import_from_db` function from the same file to throw an "Error at offset..." notice and, consequently, makes the String Translation module in Polylang to malfunction.

**Comment by Chouby** [comment]
I did not know about this option. I just discovered that it has been removed in WP 4.3 (although kept for older WP installs). Now I can at last reproduce the issue. A huge thanks for your investigations!
I will look at the best way to fix this.

**Comment by theleemon** [comment]
The UI for configuring the option has been removed, but if you access:

`www.domain.com/wp-admin/options.php`

the option is still there and it's taken into account by functions such as:

https://developer.wordpress.org/reference/functions/balancetags/

It's not deprecated. In many of the sites I develop I set this to true because many of my clients have a tendency of pasting malformed HTML code from Word docs which then screws the layout up.

**Comment by theleemon** [comment]
Nice solution! Instead of using the post content to store the translations you used a post meta field.
