### ISSUE TITLE
Menus Not Displaying on Category and Tag Archive Pages

### ISSUE THREAD

**Issue by dylanfitz** [polylang/polylang#64]
I have Polylang Pro enabled with subdomains. For some reason, this setting is preventing any menu from showing up on category and tag archive pages. Menus do display properly on custom taxonomy archive pages, and everywhere else on the site. @wgallop99

http://es.familydoctor.social-driver.com/categor%C3%ADa/salud-de-la-familia/

**Comment by Chouby** [comment]
This is not something I am able to reproduce on my test site.  So it probably comes from a conflict somewhere. If you are a customer of Polylang Pro, could you please contact us at https://polylang.pro/support/ ? You will get a much more efficient and faster support.

**Comment by dylanfitz** [comment]
Thanks! I reached out with the link you sent, and am waiting for a reply. I wanted to follow-up and say that I did some poking around the code and discovered that If I remove line 139 from https://github.com/polylang/polylang/blob/master/frontend/frontend.php, this corrects the issue.
