### ISSUE TITLE
Error 404 when translating a custom message type

### ISSUE THREAD

**Issue by Mekhet** [polylang/polylang#652]
Hello there! I use the Avada theme, it has a built-in FAQ message type. when translating this type of message and opening the page, a 404 error appears. What could be the problem?

I also checked the file wpml-config.xml and additionally specified the type of messages to display in the filter, but this did not help.

![2020-12-03 19 53 45 sprutio beget com 3b64bb2f8f84](https://user-images.githubusercontent.com/22636577/101026722-755d7d00-35a1-11eb-9b66-bf9e1d237589.png)
![2020-12-03 19 53 28 sprutio beget com 8b7db83774f3](https://user-images.githubusercontent.com/22636577/101026726-768eaa00-35a1-11eb-9151-b749f88dd5c0.png)

**Comment by Chrystll** [comment]
If you are using Polylang Pro please contact our helpdesk: https://polylang.pro/support/. This is the best way to get fast support. Thanks.
Github is used to report bugs or possibly for feature requests.
