### ISSUE TITLE
Notice: Undefined property: PLL_Cache_Compat::$options  wp-content/plugins/polylang/integrations/cache/cache-compat.php on line 38

### ISSUE THREAD

**Issue by bahaa-almahamid** [polylang/polylang#658]
https://github.com/polylang/polylang/blob/1af6f5ecd88a357576ba0191ddab2392e66637c4/integrations/cache/cache-compat.php#L38

Fix  -> 				$samesite = ( 3 === PLL()->options['force_lang'] ) ? 'None' : 'Lax';

**Comment by manooweb** [comment]
Good catch 👍
Many thanks @bahaa-almahamid
