### ISSUE TITLE
Conflict with Divi theme

### ISSUE THREAD

**Issue by JonWallsten** [polylang/polylang#67]
When I'm trying to import a Divi layout file I got an error in post.min.js.

In the ajaxPrefilter method t.data.indexOf is undefined. So I guess you need to add a check to make sure _t.data_ is a string.

**Comment by Chouby** [comment]
Are you using Polylang 2.0.9?

**Comment by JonWallsten** [comment]
Sorry, forgot to include that. Yes. Latest polylang. Latest Divi.

**Comment by Chouby** [comment]
Could you give me the steps to reproduce? 
I tried editing a page then:
Use the Divi Builder > Load from library > Load Contact Us (predefined layout) > Update the page
and cannot reproduce any error.

**Comment by JonWallsten** [comment]
On this page:
https://www.elegantthemes.com/gallery/divi/documentation/library-import/

Scroll to the bottom where you'll find "Exporting Individual Divi Layouts" and "Importing Individual Divi Layouts".

**Comment by Chouby** [comment]
Thanks. I could reproduce.

**Comment by JonWallsten** [comment]
Perfect! Thanks for looking into it. Really appreciate it.
