### ISSUE TITLE
Images not showing in galleries/carousels

### ISSUE THREAD

**Issue by gassim3** [polylang/polylang#679]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install and customize polylang plugin
2. Use wordpress theme Uncode by undesgn 
3. Update all plugins and themes in its latests versions

## Expected behavior and actual behavior

When I follow those steps, images used in media galleries/carousels stop working

Thanks,
George

**Comment by Chrystll** [comment]
You are probably hitting this case https://wordpress.org/support/topic/polylang-elementor-3/#post-13338352 where 2 solutions are mentioned. 

Please use GitHub only to report bugs or possibly for feature requests. Github is not a support forum. Please use the support forum for questions but please note that the support of Premium themes/plugins such as the theme Uncode by undesgn is not allowed on this forum.
