### ISSUE TITLE
Does not work with nice search module from Soil

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#68]
Hi,

If I translate search slug via Strings translations panel, I'll get a "Too many redirects" error when I activate [nice search](https://github.com/roots/soil/blob/master/modules/nice-search.php) module from Soil plugin.

I found out that the problem stems from fact that the module code checks if `$wp_rewrite->search_base` is in the `$_SERVER['REQUEST_URI']` and if not than it redirects to search URL, but apparently Polylang doesn't manipulate `$wp_rewrite->search_base` variable, so this if-condition leads to infinite redirect loop:
<pre>
  $search_base = $wp_rewrite->search_base;
  
  if (is_search() && !is_admin() && strpos($_SERVER['REQUEST_URI'], "/{$search_base}/") === false && strpos($_SERVER['REQUEST_URI'], '&') === false) {
    wp_redirect(get_search_link());
    exit();
  }
</pre>

To be honest, I don't know, if this would be better solved on Polylang side or Soil side. I'm posting an issue here as I think that maybe `$wp_rewrite->search_base` could be set according to language, but I'm not an expert on URL rewriting in WP...

Cheers,
Česlav

**Comment by Chouby** [comment]
This must be fixed in Polylang. Could you test if this fixes the issue?
```php
add_action( 'setup_theme', 'pll_setup_theme', 1 );

function pll_setup_theme() {
	global $wp_rewrite;

	if ( isset( PLL()->slugs_model->translated_slugs['search'] ) ) {
		$wp_rewrite->search_base = PLL()->slugs_model->translated_slugs['search']['translations'][ PLL()->curlang->slug ];
	}
}
```

**Comment by chesio** [comment]
Hi @Chouby,

Thanks for the hint. I had to modify your snippet a bit, but the following works:

```php
add_action( 'wp_loaded', 'pll_setup_theme' );

function pll_setup_theme() {
	global $wp_rewrite;
    
	if ( isset( PLL()->translate_slugs->slugs_model->translated_slugs['search'] ) ) {
		$wp_rewrite->search_base = PLL()->translate_slugs->slugs_model->translated_slugs['search']['translations'][ PLL()->curlang->slug ];
	}
}
```
Note: `translated_slugs` array have not been yet initialized when `after_setup_theme` action runs.

**Comment by Chouby** [comment]
That's exact. The array is available after all custom post types and taxonomies are expected to be registered. Consider that this will be included in version 2.1. I will use `wp_loaded` with priority 20.

**Comment by chesio** [comment]
Ok, I'll leave the snippet in my functions.php until 2.1 ships. Thanks for prompt reply!

**Comment by chesio** [comment]
Just a short follow-up: I get PHP notices whenever I switch admin to "All languages" (presumably because of `PLL()->curlang` being not an object), so I guess this snippet should be executed on front-end only.
