### ISSUE TITLE
Filter for customization of style for span element within the anchor tags for language switcher.

### ISSUE THREAD

**Issue by coderkoala** [polylang/polylang#699]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

Not an issue, more of a dev feature request.

## Expected behavior and actual behavior
As a developer, I'd appreciate if the span element within the anchor tags were able to be customized, or rather, the entire element structure could have a filter applied so I can override the structure as well as the info.

When I follow those steps, I see...

No reproduction needed.
```wp-content\plugins\polylang\include\walker-list.php:32``` to be specific.

**Comment by Chouby** [comment]
It lloks to me that this filter https://github.com/polylang/polylang/blob/2.9.1/include/switcher.php#L186-L194 is what you are looking for. It's alos possible to develop a custom language switcher using the output of `pll_the_languages()` with the `raw` argument. See: https://polylang.pro/doc/function-reference/#pll_the_languages
