### ISSUE TITLE
No widgets show when admin set to show all laguages

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#70]
Most likely caused by https://github.com/polylang/polylang/issues/54

When the backend is set to "show all languages" no widgets are shown in the sidebar.

This may be a separate issue. The customizer uses the same language setting as the backend. This causes an issue when editing the site in French when the backend setting is set to English. There is no widget in the customizer but the French widget is being loaded on the front end.

**Comment by Chouby** [comment]
Sorry I don't understand the issue. Could you give more details to reproduce?

**Comment by grappler** [comment]
Here the setting in the admin bar is set to all languages and no widgets are shown
![image](https://cloud.githubusercontent.com/assets/1785641/20970421/86b95e66-bc5b-11e6-9c1d-000d7bf4b006.png)

Here the language is changed to German where we have added a widget to only show on the German site.
![image](https://cloud.githubusercontent.com/assets/1785641/20970455/b42ae496-bc5b-11e6-9814-f5346edaa3a0.png)

**Comment by Chouby** [comment]
Thanks. It's what I tested this morning. But since I did not reproduce the issue, I wanted to be sure. What strange is that filters are normally active only on the frontend. See https://github.com/polylang/polylang/blob/master/frontend/frontend-filters.php
Could you check for a conflict?

**Comment by grappler** [comment]
Closing as it is was an issue on my part.

**Comment by kurt-unleashed** [comment]
Can you share what the issue was? I'm facing the same issue currently but can't seem to find a solution :(

**Comment by grappler** [comment]
@kurt-unleashed Sorry, I can't remember what the issue was, as it was 6.5 years ago. It could have been a couple of things, something specific to the environment or some custom code that I had written.

I suppose I would try testing it in other environments. Another idea would be to remove and add the widget again.

**Comment by kurt-unleashed** [comment]
I understand. Thanks for your quick response anyway 👍 
Back to the debug-mobile for me :)
