### ISSUE TITLE
Post preview and oembed provider issue using subdomains

### ISSUE THREAD

**Issue by snotrman** [polylang/polylang#702]
- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

site: ru.mainampasauli.news and mainampasauli.news respectively

1. Ubuntu 20.04 + nginx + mysql 8 + latest woordpress + permalinks + subdomain + polylang with subdomain option + cloudflare dns proxy
1.2. Open WP dashboard at domain.com -> add new post for the language your subdomain.domain.com is at -> *write something* in the post -> preview -> open in new tab
1.3. You are taken to subdomain.domain.com/p=2342, where in turn you are greeted with a WP 404 page not found. The preview has been generated at domain.com/p=2342. You are able to access the preview, by typing the domain.com/p=2342 manually.

2. Ubuntu 20.04 + nginx + mysql 8 + latest woordpress + permalinks + subdomain + polylang with subdomain option
2.2. Open WP dashboard at domain.com -> add new post for the language your subdomain.domain.com is at 
2.3. Paste a link of subdomain.domain.com/any-post-link-url-encoded-transliteration
2.3. The woordpress link generator can't process the link of the subdomain.domain.com/any-post-link-url-encoded-transliteration and receive a metainfo about the post

## Expected behavior and actual behavior

1. Post preview link takes to subdomain.domain.com instead of domain.com, where the link is generated. So the expected behavior would be redirecting to domain.com/p=3223 instead of subdomain.domain.com/p=3223 
2. for the oembed link to open a modal showing the usual picture and metainfo about the post from the subdomain.domain.com site as well.

Any guidance would be very appriciated.

I didn't find anything related to this issue nor on stackoverflow, nor on woordpress, nor here among issues. 
I have searched through all the posts in all the places you list on this github readme, also.

## What you have already tried to solve your issue

1. Preview link
1.1. unsuccessful nginx, .htaccess and php header rewrites
1.2. nginx proxy for subdomain.domain.com to domain.com
1.3. expanding server_name directive with the subdomain.domain.com in a nginx server block
1.4. unsuccessful attempts at finding of the url creator/initiator function in wp-admin, wp-includes and wp-content folders. All of them returned domain.com, so I don't know where and how the redirect link is chosen.
1.5. serving subdomain.domain.com and domain.com in seperate nginx server blocks
1.6. in wp dashboard -> language -> settings -> url modification -> switching between subdomain option, vs custom domains -> entering the same domains.

2. Oembed
2.1. Added a oembed provider in functions.php wp_oembed_add_provider( 'https://subdomain.domain.com/*', 'https://domain.com/oembed/', false );
2.2.
![image](https://user-images.githubusercontent.com/37236334/103434290-ea0af200-4c07-11eb-910e-5091ca3ce2fc.png)
2.3. The endpoint at which the oembed is requested from the new post frontend is https://rutest.mainampasauli.news/wp-json/oembed/1.0/proxy?url=https://rutest.mainampasauli.news/hukuygiuygiuyg/&lang=ru&_locale=user  So I tried a couple of urlencoded and regular permutations with this request. Unsuccessful. 
* embeding from domain.com works fine as expected. 

Thank you

**Comment by snotrman** [comment]
Are these two issues only on my end?

Is this a bug, or a lack of a feature? 

What is your outlook on how should I proceed with fixing these two issues?

**Comment by snotrman** [comment]
- Am I suppose to be able to paste sub.domain.com/article1 while writing a post and the regular WordPress link oembed preview opens? Or is that not a feature?

- Should it be possible to preview an unpublished post draft with the sub.domain.com/p=2345?

**Comment by snotrman** [comment]
So what's the truth? Does anybody know?

**Comment by Chouby** [comment]
This issue rather looks as a support request.

**Comment by snotrman** [comment]
Support or not. The question is about polylang's code. Is there such a feature? And if yes -- why doesn't polylang's subdomain work for wp_oembed_add_provider()?

**Comment by originaliko** [comment]
I have the same issue. I use 2 different domains for 2 different languages and previewing a post (or page or custom post) only works on the primary language.
