### ISSUE TITLE
Conflict with Elementor - When Polylang is Active Custom Taxonomies Cannot be Found in Posts Widget's Query

### ISSUE THREAD

**Issue by black-eye** [polylang/polylang#708]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a custom taxonomy (named Produkty) linked to the Posts. When I activate Polylang, I cannot find the terms of this taxonomy in the Posts widget's query anymore. When I deactivate Polylang, the terms are back:

![obrazek](https://user-images.githubusercontent.com/5634870/103837857-e3f39600-508b-11eb-89c7-043cb8bfdb59.png)

## Steps to reproduce

1. Create a custom taxonomy
2. Link the taxonomy to Posts
3. Create some terms for the custom taxonomy and link them to random posts
4. Create Elementor page and insert a Posts widget to this page
5. Try to query posts by selecting your taxonomy term (it should work)
6. Activate Polylang
7. Repeat step 5 (it won't work)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Additional info
There's no difference wheather the custom taxonomy is marked for the translation or not.

For some very strange reason the terms are found, when I deactivate the native taxonomies using this code:

```
function bleye_remove_post_category_from_pll( $taxonomies, $is_settings ) {
    unset( $taxonomies['category'] );
    unset( $taxonomies['post_tag'] );
    return $taxonomies;
}
add_filter( 'pll_get_taxonomies', 'bleye_remove_post_category_from_pll', 10, 2 );

```

Strangely enough, when I try to deactivate just the translation of Posts using this code it doesn't work:

```
function bleye_remove_post_translation_from_pll( $post_types, $is_settings ) {
	unset( $post_types['post'] );
	return $post_types;
}
add_filter( 'pll_get_post_types', 'bleye_remove_post_translation_from_pll', 10, 2 );

```

**Comment by black-eye** [comment]
This Issue is most likely caused by Elementor itself, so I've started the same issue there - https://github.com/elementor/elementor/issues/13517

But you might have better insight into what's happening there and you could guide them to a quick solution. Thanks

**Comment by Chrystll** [comment]
You said that you have enabled the translation of your custom taxonomy in Languages > Settings > Custom post types and taxonomies. But you should make sure that you have well assigned it a language and that you translated in your other languages.

**Comment by black-eye** [comment]
@Chrystll 
> You said that you have enabled the translation of your custom taxonomy in Languages > Settings > Custom post types and taxonomies. But you should make sure that you have well assigned it a language and that you translated in your other languages.

Oh, you are right! The term hadn't a language assigned, I had to do it manually. Now it works. Thanks!
