### ISSUE TITLE
Error when previewing another theme with Twenty Seventeen activated

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#71]
I get the following error when I have Twenty Seventeen activated and I preview another theme like Twenty Sixteen in the customizer.

> Fatal error: Uncaught Error: Call to undefined function twentyseventeen_panel_count() in plugins/polylang/modules/plugins/plugins-compat.php:623

**Comment by Chouby** [comment]
Indeed. I am testing get_template() before the customizer filters it :/
