### ISSUE TITLE
Cant add key to POLYLANG Modul Dashboard

### ISSUE THREAD

**Issue by DavidSchmidt1** [polylang/polylang#712]
Hi,
i bought an Polylang-Key for our Website. Nevertheless its not possible to add an key to the Polylang-Modul. The modul seems to be deactiveted. It looks like that:

![grafik](https://user-images.githubusercontent.com/45099474/104222303-655b7780-5442-11eb-9fa6-e3a4b759853f.png)

I tried to reinstall Polylang which didnt helped. Is there anyway to fix it without resetting the database?

**Comment by sebastienserre** [comment]
Hello @DavidSchmidt1 

To install Polylang Pro you need to download our Pro version thanks to the link inside the e-mail you received after your purchase.
As a Polylang Pro customer, you have access to our premium help desk, and you should ask support through our dedicated channel: https://polylang.pro/support/

Regards
