### ISSUE TITLE
Including pages in Jetpack Infinite Scroll ajax query

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#74]
My site has different languages for the languages. I have setup Jetpack Infinite Scroll setup.

The initial query only loads posts but when loading further posts by Jetpack infinite scroll pages are included in the query. The reason for this is that `query_args[post_type]` is not defined. It should be `query_args[post_type]:posts`.

Running
Jetpack: 4.4.2
Polylang(Pro): 2.0.10
WordPress: 4.6.1

**Comment by Chouby** [comment]
I don't succeed to reproduce the issue. However I indeed notice that `query_args[post_type]` is not defined for the default language when the language code is hidden in the url (it is defined to posts in other cases). However I notice that `query_args[post_type]` is also not defined when Polylang is deactivated. So I gues that Jetpack is able to query only posts when the post type is not defined.

**Comment by grappler** [comment]
The issue only occurs when you are using multiple domains.

Make sure you only have two or three posts and have a few pages. You can see the issue here. http://grapplerulrich.tk/

**Comment by Chouby** [comment]
I could reproduce on my local install with multiple domains. I will investigate.

**Comment by grappler** [comment]
Merci Beaucoup!
