### ISSUE TITLE
Woocommerce related products mixing languages

### ISSUE THREAD

**Issue by yotamdahan** [polylang/polylang#740]
Hello, I’m using Woocommerce with Polylang, and I’m having trouble with related products in single-product.php page.

My website contain 2 languages (Hebrew, English). Assuming I have set English as the site language, and I’m viewing product that defined for English, the related products will also show results for Hebrew products.

I have used woocommerce default page for now, so there shouldn’t be any conflicts with related product syntax.

Here is what I have tried so far to fix that but got stuck with the logic here (Not sure it’s the right approach)

```
add_filter( 'woocommerce_product_related_posts', 'custom_related_products' );
function custom_related_products($product){
    global $woocommerce;
    // Meta query
    $meta_query = array();
    $meta_query[] = $woocommerce->query->visibility_meta_query();
    $meta_query[] = $woocommerce->query->stock_status_meta_query();
    $meta_query   = array_filter( $meta_query );
    // Get the posts
    $related_posts = get_posts( array(
            'orderby'        => 'rand',
            'posts_per_page' => '4',
            'post_type'      => 'product',
            'fields'         => 'ids',
            'meta_query'     => $meta_query
        ) );

        if ( $related_posts->have_posts() ) {
          while ( $related_posts->have_posts() ) : $related_posts->the_post();
            if(pll_get_post_language(get_the_ID())){
               //Not sure its the right approach for this..
            }
          endwhile;
        }
    $related_posts = array_diff( $related_posts, array( $product->id ), $product->get_upsells() );
    return $related_posts;
}
```

How can I solve that?

Relevant link: https://nouvellemaison.co.il/product/%d7%93%d7%95%d7%92%d7%9e%d7%90-%d7%9c%d7%9e%d7%95%d7%a6%d7%a8/

**Comment by raaaahman** [comment]
We provide a specific add-on for WooCommerce: https://polylang.pro/products/
Here is its documentation: https://polylang.pro/doc-category/polylang-for-woocommerce/
If you have any issue with this add-on, please contact us through our support desk (don't forget to copy your license key): https://polylang.pro/support/

**Comment by dirad** [comment]
@yotamdahan  did you manage to find a solution?
I am dealing with the same issue

**Comment by yotamdahan** [comment]
> @yotamdahan did you manage to find a solution?
> I am dealing with the same issue


```
add_filter( 'woocommerce_related_products', 'custom_related_products', 9999, 3 ); 
function custom_related_products($product){
//Define default language
$lang = 'he';

//Check if language is equal to non-default
if (get_locale() == 'en_US') {
	$lang = 'en';
}

//Change related products meta data arguments
$related_posts = get_posts( array(
    'orderby'        => 'rand',
    'posts_per_page' => '4',
    'post_type'      => 'product',
    'meta_query'     => $meta_query,
    'lang'           => $lang,
	'suppress_filters' => false
) );

return $related_posts;
}
```

**Comment by dirad** [comment]
Nice!
Toda Raba :vulcan_salute:
