### ISSUE TITLE
Deprecated jQuery functions

### ISSUE THREAD

**Issue by mrleemon** [polylang/polylang#741]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

According to the jQuery Migrate Helper your plugin (most recent version) throws some warnings:

```
/wp-content/plugins/polylang/js/classic-editor.min.js: jQuery.fn.change() event shorthand is deprecated
/wp-content/plugins/polylang/js/classic-editor.min.js: jQuery.unique is deprecated; use jQuery.uniqueSort
/wp-content/plugins/polylang/js/classic-editor.min.js: jQuery.isArray is deprecated; use Array.isArray
/wp-content/plugins/polylang/js/classic-editor.min.js: jQuery.isFunction() is deprecated

```

**Comment by Chouby** [comment]
We forgot the first one in our jQuery migration project in 2.9. The 3 others ar not coming directly from our code but from WodPress.

**Comment by mrleemon** [comment]
Thanks!

**Comment by mrleemon** [comment]
There's still a deprecated `click()` shorthand function in there:

https://github.com/polylang/polylang/blob/1a4dea94613a7daaf171ef79eb7b3421fc6a6f67/js/classic-editor.js#L49

And a deprecated `bind('click')` in `nav-menu.js`:

https://github.com/polylang/polylang/blob/81fcebcc5dc12f9133c419ebb2da31f548a7d944/js/nav-menu.js#L9

**Comment by mrleemon** [comment]
Also, as of jQuery 3.0, the syntax `jQuery( document ).ready( handler )` is deprecated and the `jQuery( handler )` syntax is the only recommended one: [https://api.jquery.com/ready/](https://api.jquery.com/ready/)

There are two instances in:

https://github.com/polylang/polylang/blob/81fcebcc5dc12f9133c419ebb2da31f548a7d944/js/user.js#L7

and:

https://github.com/polylang/polylang/blob/81fcebcc5dc12f9133c419ebb2da31f548a7d944/js/nav-menu.js#L7

They should be changed to:

`jQuery( function ( $ ) { .... } );`

**Comment by manooweb** [comment]
Thanks @mrleemon 
We're looking at them
