### ISSUE TITLE
PHP Warning: Attempt to read property "home_url" on bool

### ISSUE THREAD

**Issue by EldarAgalarov** [polylang/polylang#745]
PHP Warning: Attempt to read property "home_url" on bool in /wp-content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/links.php on line 37\n

Polylang 2.9.2 Pro
PHP 8.0.1

**Comment by Chrystll** [comment]
For support questions on Polylang Pro, please use our helpdesk https://polylang.pro/support/ rather than GitHub. You'll get faster answers. Please don't forget to describe which action triggers your issue in your support request.
