### ISSUE TITLE
Medias activation should depend on media mime type

### ISSUE THREAD

**Issue by Malaiac** [polylang/polylang#750]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. I use a plugin that generates a XML file (logistics) for each order and saves them as attachment to the order
2. The XML file is language insensitive
3. Other medias (like images) are language sensitive
4. The logistics plugin displays links to the XML files in a metabox (edit order admin page)
5. With "Medias" setting activated on Polylang, the XML attachements query is modified by Polylang and cannot find the XML files

## Expected behavior and actual behavior

I suppose I could force media duplication but that would force the copy of hundreds of XML files that I don't need (they're not translatable)

The XML files are all "text/xml" mime type 

## Possible solution
Allow for mime type selection of medias to translate or not

**Comment by Chouby** [comment]
I understand the need for this request but this is unfortunately impossible to achieve on our side. Indeed, the decision to translate or not a type of content is made at post type level ( The language is a taxonomy registered for this post type). And all medias are in the same post type `attachment`. 

To solve you issue, you may explore the possibility to register a new post type with the same features as `attachment` except that you'll decide to make it untranslatable. To be honest I neved did that, so I don't know how much extra development it requires compared to a simple custom post type.

Also, just to make sure you did not miss the information, the media file is shared across all translations. Only the information stored in the database is duplicate.
