### ISSUE TITLE
problem with /en and /de

### ISSUE THREAD

**Issue by ramonahaha** [polylang/polylang#758]
Hi all,
I use the free version of polylang and I think I came across a bug. 
I couldn't find a similar error here and hope it is okay to post this here. I got error messages from google search console:
1- Submitted URL seems to be a Soft 404 on domain mydomain.com/de and my domain.com/en
2- Either 'name' or 'item.name' should be specified on domain mydomain.com/de and my domain.com/en

/en and /de are not pages on my site. this is just the language code set by polylang.

Error 1 is showing up in google search console when I select the settings in URL modifications: 
- The language is set from the directory name in pretty permalinks
Example: https://mydomain.com/en/my-post/
- Remove /language/ in pretty permalinks
Example: https://mydomain.com/en/
- The front page URL contains the language code instead of the page name or page ID
Example: https://mydomain.com/en/ instead of https://mydomain.com/en/home/

Error 2 is submitted from google when I select the settings in URL modifications: 
Error 1 is showing up in google search console when I select the settings in URL modifications: 
- The language is set from the directory name in pretty permalinks
Example: https://mydomain.com/en/my-post/
- Remove /language/ in pretty permalinks
Example: https://mydomain.com/en/

Error 2 was the first error and I got rid of it by ticking "The front page URL contains the language code instead of the page name or page ID Example: https://mydomain.com/en/ instead of https://mydomain.com/en/home/"

Google validated the fix but showed me a new issue: Error 1

I deactivated all plugins in wordpress and tested it again with the same result.
I added a redirect from theses "pages" to my en or de homepage without success. I think because /en and /de are not real pages.
Whatever setting I use on your setting page I am not able to start validation and get the message: URL is not on Google - 
This page is not in the index, but not because of an error. See the details below to learn why it wasn't indexed. Learn more

That makes sense because /en and /de are not pages. But for whatever reason google sees an error on these non-pages.

I also checked my xml site and these pages (/en and /de) are not included. There are pages like mydomain/en/home or mydomain/de/startseite, which is right.

I cleared cache of my website after each setting change.

Wordpress, theme and plugins are all up to date.

**Comment by Chrystll** [comment]
Please don't use GitHub for support requests. For support requests, please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)

**Comment by EbuEge** [comment]
so.. is there any solution for that? can you share the link of answer or solutions?
