### ISSUE TITLE
Undefined index: terms

### ISSUE THREAD

**Issue by Digikube** [polylang/polylang#76]
I have some troubles, but I don't understand what is causing this problem…
**Notice**:  Undefined index: terms in **/…/plugins/polylang/frontend/frontend-auto-translate.php** on line **221**

**Comment by Digikube** [comment]
I think it comes from conflict between authors and author taxonomy generated by [Co-Authors Plus](https://fr.wordpress.org/plugins/co-authors-plus/) plugin

**Comment by Chouby** [comment]
It looks like the theme (or a 3rd party plugin) is making a [tax query](https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters) without terms. I looked at Co-Authors Plus and this plugin uses the tax query only once (in code related to WP CLI), and [correctly sets the terms index](https://github.com/Automattic/Co-Authors-Plus/blob/c8d7893b35c45aa078dc7b121ecede600b4a4c2d/php/class-wp-cli.php#L461). So I don't believe that this is the faulty plugin.

**Comment by Digikube** [comment]
Oh ok… I have a request to find same downloads from same author like that :
`$args = array(
		'post_type' => 'download',
		'author' => $author_id,
		'post_parent' => 0,
		'post__not_in' => array( get_the_ID() ),
		'tax_query' => array(
			array(
				'taxonomy' => 'download_category',
				'field'    => 'term_id',
				'operator'    => 'EXISTS',
			),
		)
	);`

I pass "download_category" through args to avoid conflict with "author" taxonomy, but I don't want to do anything with it.

**Comment by Chouby** [comment]
You got it! Although, I wrote this function for WP 4.1, I forgot this use case where there are no terms in the query (and also did not thought to it yesterday).

**Comment by Digikube** [comment]
Thanks a lot :)
