### ISSUE TITLE
Homepage permalink is set to wrong address when set the front page url contains the language code instead of the page name or page id to true

### ISSUE THREAD

**Issue by phoenixgao** [polylang/polylang#765]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. My Wordpress instance is running on a kubernetes cluster installed by bitnami Wordpress helm chart. So, my Wordpress service is behind a nginx load balancer (or ingress?)
2. When set `the front page url contains the language code instead of the page name or page id` setting to true

## Expected behavior and actual behavior

I expected that when I visit https://mysite.com/ it shows the English homepage, and when I visit https://mysite.com/fr it shows the french one, however, https://mysite.com redirects me to the wp-admin backend.
So I check the permalink of my frontpage pages, after setting the above option to true,
My English homepage's permalink has been changed to https://internal-ip:8443/ and my french homepage's was changed to https://internal-ip:8443/fr

Maybe it's related to how polylang detects the site's URL?

**Comment by Chrystll** [comment]
Please don't use GitHub for support requests. For support requests, please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should use the [helpdesk](https://polylang.pro/support/))

**Comment by phoenixgao** [comment]
How come it is a support request?
