### ISSUE TITLE
PHP errors when uploading PDF's WP 4.7

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#77]
I get the following error when running Polylang 2.0.11 in WP 4.7

I have enabled automatically duplicate media in all languages when uploading a new file.

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'copy_tax' not found or invalid function name in wp-includes/class-wp-hook.php on line 298

Warning: array_unique() expects parameter 1 to be array, null given in plugins/polylang-pro/modules/sync/admin-sync.php on line 104

Warning: array_intersect(): Argument #2 is not an array in polylang-pro/modules/sync/admin-sync.php on line 119

Warning: Invalid argument supplied for foreach() in polylang-pro/modules/sync/admin-sync.php on line 126
```

**Comment by Chouby** [comment]
I did not reproduce the issue.  However, the second warning makes me think that the issue would rather be related to the usage of the filter [pll_copy_taxonomies](https://github.com/polylang/polylang/blob/2.0.11/modules/sync/admin-sync.php#L104).

**Comment by grappler** [comment]
Sorry, my mistake.
