### ISSUE TITLE
Hreflang tags too low in the page HTML

### ISSUE THREAD

**Issue by arcticguesthouse** [polylang/polylang#771]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open your website and view the page source
2. Enter Google Search Console
3. Check from Legacy Tools and International targeting, whether Google is detecting your hreflang tags

## Expected behavior and actual behavior

Hello. I have been using Polylang free version for more than a year and I recently noticed that on Google Search Console, I am getting an error that my site is not using hreflang tags. I checked this with page source and noticed that the hreflang tags are correctly created by Polylang but the thing is that these codes are placed fairly low in the pages' HTML. 

Google nowadays recommends that these codes are placed high up in the pages' HTML code and at least before any tracking codes that are usually also placed in the <head> part of the HTML. I decided to test this and manually created new hreflang tags for my side and placed them in the beginning of the <head> section and in just two days Google was able to crawl these codes that it couldn't find for more than a year when they were lower down in the page resource. 

I do not know how to create dynamic hreflang tags for my website and don't know either how I can manually move the codes that Polylang is creating, higher up in the page HTML, which means that probably my only option is to change to another plugin such as WPML (who have already acknowledged and fixed this issue in their plugin). 

So I am giving the Polylang developers a free tip: you should really change where the hreflang codes are placed (give them a higher priority by default or something) as many people are having this very same issue when using your plugin. Other solution for me would be a guide on how I can manually fix this issue and move the codes higher up myself. 

Thank you in advance. My website can be seen from [this link](https://arcticguesthouseandigloos.com).

**Comment by Chouby** [comment]
Hello,

>Google nowadays recommends that these codes are placed high up in the pages' HTML code and at least before any tracking codes that are usually also placed in the part of the HTML.
Could you please provide your source (Google documentation) about this recommendation?

**Comment by arcticguesthouse** [comment]
Hello Chouby:

> Put your <link> tags near the top of the <head> element. At minimum, the <link> tags must be inside a well-formed <head> section, or before any items that might cause the <head> to be closed prematurely, such as <p> or a tracking pixel. If in doubt, paste code from your rendered page into an HTML validator to ensure that the links are inside the <head> element.

https://developers.google.com/search/docs/advanced/crawling/localized-versions
