### ISSUE TITLE
Polylang multi-domains draft posts leads to 404.

### ISSUE THREAD

**Issue by danlapteacru** [polylang/polylang#772]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install WordPress
2. Install Polylang and add multidomain support per language
3. Create a draft page and try to preview it.

## Expected behavior and actual behavior

Hello!

Setup:
– nginx two server blocks, for all domains, with HTTPS forced redirect pointing to the same root folder of WordPress installation, with permalinks configured.
– Polylang pointing with a domain for the secondary language (example: domain.com - for English language, domain.dk - for Danish language)

Issue:
– When drafting a post, post preview is opened in the language domain (for example domain.dk) or on the main domain, and so the https://domain.dk/p=1342 leads to a 404.

Question:
Exists a way to fix the issue?

Thanks,

Dan

**Comment by Chouby** [comment]
Drafts are visible ony to connected users. You need to connect to the secondary domain to fix the issue. Polylang Pro does it automatically for you.  https://polylang.pro/doc/single-sign-on-across-multiple-domains/
