### ISSUE TITLE
Plugin breaks support for HTML5 stylesheet link tags

### ISSUE THREAD

**Issue by dboulet** [polylang/polylang#775]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate a theme which uses `add_theme_support( 'html5', array( 'style') );`.
2. Activate Polylang plugin

## Expected behavior and actual behavior

When I follow those steps, I see that stylesheet link tags contain a `type='text/css'` attribute. That attribute is usually removed when themes add support for HTML5 stylesheet link tags.

I believe that this issue is caused by this line:
https://github.com/polylang/polylang/blob/59cac800f4993357d96f5ec75a1a41463e97aade/frontend/choose-lang.php#L100

The call to `wp_styles()` initializes the styles before the theme has a chance to call `add_theme_support()`.

**Comment by Chouby** [comment]
I confirm the bug. Thank you for the report.
