### ISSUE TITLE
Incompatibility with Preferred Languages plugin

### ISSUE THREAD

**Issue by markhowellsmead** [polylang/polylang#776]
When I use `date_i18n` or `get_the_date` when Polylang (Pro) and the [Preferred Languages plugin](https://wordpress.org/plugins/preferred-languages/) are in use, and the user-preferred languages are set to _Deutsch (Schweiz)_ and fallback _Deutsch (Sie)_, the date is always returned in the default site language. e.g. `17. Februar 2021` instead of `17. février 2021` for a Post translated to French.

## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install the plugins detailed above and configure the site with German and French as Polylang languages.
2. Set the WordPress languages as _Deutsch (Schweiz)_ and fallback _Deutsch (Sie)_ using the Preferred Languages plugin.
3. Load a French Post and review the `date_i18n` output.

## Expected behavior and actual behavior

When I follow those steps, I see the date in German.
I was expecting the date in French.

**Comment by markhowellsmead** [comment]
See also https://github.com/swissspidy/preferred-languages/issues/353

**Comment by swissspidy** [comment]
As mentioned at https://github.com/swissspidy/preferred-languages/issues/353 I was not able to reproduce this with the free version.

**Comment by Chouby** [comment]
@markhowellsmead You mentionned Polylang Pro. Did you contact the support about this issue? Looks like Polylang Pro should offer more or less the same feature (which could explain the conflict).

**Comment by markhowellsmead** [comment]
I can also not reproduce this problem with the free version of the Polylang plugin. I will progress this at Polylang Pro support.
