### ISSUE TITLE
Metabox values change affects all languages

### ISSUE THREAD

**Issue by pooria-m** [polylang/polylang#78]
Hello,

Initially I'd better say that I'm using Metabox.io plugin to create my metaboxes. But when I edit a meta value and save it, the value in the other language also changes to that !

**Comment by grappler** [comment]
This would happen if you have enabled to sync custom fields across the translations https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/synchronization-of-meta-content/

**Comment by pooria-m** [comment]
@grappler Oh well. It works now. I used to think that this feature happens only once when the post in the other language is just created. Thanks
