### ISSUE TITLE
Wp Seo compatibility layer crashing site with old WPSEO Pro version

### ISSUE THREAD

**Issue by nicoladj77** [polylang/polylang#781]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

The issue is realted to this commit https://github.com/polylang/polylang/commit/e3973987e60d48667926a1bc3d98fdd9047f6e4e where the method is called without first checking if it exists. I have a client on a really old version of YOAST Pro (7.0.4) and this crashes the site as that version doesn't have that method
I can make a PR for this.

**Comment by Chouby** [comment]
I will merge your PR. But please update. We do **not** maintain our Yoast SEO compatibility with old versions. The same for any other plugin integrations.
