### ISSUE TITLE
Problem with custom flags

### ISSUE THREAD

**Issue by rascayus** [polylang/polylang#790]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Upload custom flag in the /wp-content/polylang/ directory (create the directory if it does not exist).
2. Go in Languages > Settings > URL modifications module then click on save changes.

## Expected behavior and actual behavior

Since version 3.0  it only shows custom flag once, when you refresh the page it shows the predefined flag. In 2.9.2 version it works fine.

Thanks

**Comment by Chouby** [comment]
Did you really test the `master` branch as you wrote?

**Comment by rascayus** [comment]
I've tested master branch, 3.0 and 3.0.1 version. Them all fail. With 2.9.2 version it works fine

**Comment by Chouby** [comment]
And with 3.0.2 ?

**Comment by rascayus** [comment]
Solved!!! Thanks a lot. 3.0.2 works fine

**Comment by Chouby** [comment]
Good to know. Probably your test with the `master` branch was not correct, it was already fixed in this branch when I asked you about it. See #787
