### ISSUE TITLE
Problem with pll_ajax_backend and JSON body

### ISSUE THREAD

**Issue by RayanD-W** [polylang/polylang#798]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

I'm using Thrive, and adding a new Lead Form,
So i'm guessing : 

1. Send an ajax request that will call your javascript from admin_print_footer_scripts function.

## Expected behavior and actual behavior

When I follow those steps, I see that the lead form isn't creating cause of : 

- when one of their POST request is sent as a JSON Polylang add &pll_ajax_backend=1 at the end of the body
- So we have something like {.....}&pll_ajax_backend=1

I was expecting PolyLang to not add data on JSON or not like this.

In the file /admin/admin-base.php, the function admin_print_footer_scripts(), at line (around) 293 I updated the code, now it works perfectly : 

```php
if ('undefined' === typeof options.data || 'string' === typeof options.data) {
    try {
        const parsedData = {...JSON.parse(options.data), ...<?php echo $arr; // phpcs:ignore WordPress.Security.EscapeOutput ?>};
        options.data = JSON.stringify(parsedData);
    } catch (e) {
        addStringParameters();
    }
} else {
    // Otherwise options.data is probably an object.
    options.data = Object.assign( options.data, <?php echo $arr; // phpcs:ignore WordPress.Security.EscapeOutput ?> );
}
```

Thanks for your time I hope it's usefull.

**Comment by manooweb** [comment]
Hello @RayanD-W,

Thanks for your report.

I don't known Thrive: is it a theme, a plugin ?
Is it there a way to get its code to understand what is on conflict. Espacially to see how it send the ajax request, it process it server side.

Regards

**Comment by RayanD-W** [comment]
Hello @manooweb ,

It's a plugin, I tried to get into their minified javascript but.. what an hard time.
https://thrivethemes.com/leads/

I've sent the issue to their team, I hope they'll answer here to give more information, if not i'll try again to get their ajax call

**Comment by manooweb** [comment]
Ok. Thanks @RayanD-W 
We recently changed this code after issues reported after jQuery update to 3.5.1 in WordPress. However it seems it miss us some cases.
To correct a more general way, it's good to have some code example as the Thrive/leads one to understand what's wrong.

By waiting, you can patch our code as you propose. Just be careful about Polylang updates which will override this patch.

**Comment by mariolamacchia** [comment]
It seems that this also affects the [HubSpot plugin](https://wordpress.org/plugins/leadin/). Users can't set up the plugin as it relies on a POST request and `&pll_ajax_backend=1` is added at the end of the JSON payload. All the conflicts started happening since v3 of Polylang was released.

If it can help, this is the code of the HubSpot plugin that fires the POST request https://plugins.trac.wordpress.org/browser/leadin/trunk/js/src/api/wordpressAjaxClient.js#L6. I haven't dug too much into this, but I'd say [this line](https://github.com/polylang/polylang/commit/7a0f0639a3d1f2739a67c1bbc2c646e943462ee7#diff-fea8f8858e51a84a9135a2f86cc01241e2d074a15936ef852e1d518858224308R293) is responsible, as `options.data` is going to be a string even if the payload is JSON.

**Comment by manooweb** [comment]
Hello @mariolamacchia,

Yes! It helps to have a case to test and fix. Thank you so much 😉
You're right this regression has been introduced since Polylang 3.0 because wa rewrote this part of code.

Regards
