### ISSUE TITLE
Missing argument 3 for icl_t()

### ISSUE THREAD

**Issue by gilvancn** [polylang/polylang#8]
Plugin Polylang giving conflict with theme file "Goliath".
`Warning: Missing argument 3 for icl_t(), called in /home/pubsi387/public_html/mysite/wp-content/themes/goliath/theme/theme-functions.php on line 1403 and defined in /home/pubsi387/public_html/mysite/wp-content/plugins/polylang/modules/wpml/wpml-compat.php on line 256`

Stopped giving the error after deleting the "IF" on line 256 of the file in Polylang.

Has anyone seen this error or incompatibility with other themes?
I'm using the latest version = 1.9.1.

**Comment by Chouby** [comment]
I confirm that in WPML, the argument 3 of icl_t is optional. But in Polylang, it's currently the only one needed (due to the fact that WPML and Polylang handle strings translations in a very different way).

I will investigate if a workaround is possible.

**Comment by gilvancn** [comment]
Okay, thank you Chouby the return.
I'm waiting for an alternative.

**Comment by Chouby** [comment]
If you want to benefit the fix before the next release, just download https://github.com/polylang/polylang/archive/1.9.x.zip

**Comment by gilvancn** [comment]
Cool. Thank you for your support and this wonderful plugin.
I downloaded here and tested and confirmed that this problem is gone. :)
