### ISSUE TITLE
Styling issue with Gutenberg

### ISSUE THREAD

**Issue by marcbelletre** [polylang/polylang#812]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate Polylang Pro
2. Add multiple languages
3. Open a post or a page using the Gutenberg editor
4. Open the translations sidebar

## Expected behavior and actual behavior

The CSS is not right in the translations panel when using the Gutenberg editor. As you can see in the screenshot below the three icons are not aligned correctly.  
This is not a big deal obviously but it is quite disturbing :)

I can't make a PR for this as the issue exists only in the Pro version.

<img width="292" alt="Capture d’écran 2021-03-25 à 16 41 12" src="https://user-images.githubusercontent.com/6853334/112509664-f75ff480-8d90-11eb-8a92-beb9eb0e82e8.png">

**Comment by manooweb** [comment]
Hello @marcbelletre, 

Could you please contact our support https://polylang.pro/support/
and then precise which:
- WordPress version
- Polylang Pro version

and also paste the WordPress site health please.

Thank you

**Comment by marcbelletre** [comment]
Hi @manooweb,

Thank you for your answer.  
After further research I found out it was actually because of some custom CSS I had in my editor. I didn't even think about this... Sorry for the waste of time 😕

**Comment by manooweb** [comment]
Thanks for the feedback 😉
