### ISSUE TITLE
Multiple hreflang errors

### ISSUE THREAD

**Issue by TheTravelBunny** [polylang/polylang#814]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Right click on a page of a website using polylang
2. OR run ahrefs/semrush site audit (free version) on a site with polyang
3. OR use Website Auditor (free) on a site with polylang

## Expected behavior and actual behavior

When I follow those steps, I see...

Missing reciprocal hreflang (no return-tag)
Self-reference hreflang annotation missing
Hreflang to non-canonical
X-default hreflang annotation missing

I was expecting...

None of these errors.

## Permalink settings

Common Settings: `https://www.the-travel-bunny.com/sample-post/`

Optional:
– Product category base `product-category`
– Product tag base `product-tag`

Product permalinks: Custom base `/product/`

_I am using a static front page._

## Polylang settings

URL modifications
– The language is set from the directory name in pretty permalinks
– Hide URL language information for default language
– Remove /language/ in pretty permalinks
– The front page url contains the language code instead of the page name or page id

Detect browser language deactivated
Media activated

Custom post types and Taxonomies
– Custom post types: Products
– Custom taxonomies: Brands, Product categories, Product tags, Product shipping classes

Synchronization: Published date
WPML compatibility activated by default (no option to select otherwise)

## More details
Links crawled and errors signaled by ahrefs site audit.
Also found by semrush website audit, but on a lower number of pages, because their free version only crawls 100 URLs.
Also identified by Website auditor v4.49.7
(Links to screenshots at the end of this message)

## Screenshots

- Ahrefs: https://prnt.sc/10sytv8
- Semrush: https://prnt.sc/10syu4c
- Website Auditor: https://prnt.sc/10syvw5

**Comment by TheTravelBunny** [comment]
Hi, can anybody help? I feel like the plugin developers are ignoring this issue signaled here and on the support forum... And it's not a small detail, these are important errors.

**Comment by Chouby** [comment]
We are not ignoring bugs when they are well documented (when the reporter provides us enough steps so that we can reproduce the bug consistently on our test install). This issue doesn't look like a bug report but as a support request for **your site**. And it's true that, if we offer Polylang for free, we can't support it for free.

I this issue, I don't know how to reproduce this:
>Missing reciprocal hreflang (no return-tag)
Self-reference hreflang annotation missing
Hreflang to non-canonical

For the "X-default hreflang annotation missing", you can refer to #826 that I just answered to.
