### ISSUE TITLE
Can't unregister widget 'PLL_Widget_Calendar'

### ISSUE THREAD

**Issue by gansrigler** [polylang/polylang#823]
I use a custom Wordpress theme and I want to unregister the Calendar widget. I've read [here](https://github.com/polylang/polylang/issues/316) that Polylang already unregistered the standard Calendar widget, then registers its own 'PLL_Widget_Calendar'. But it seems that I can't disable or unregister this one. Any help? Thank you!

**Comment by Chouby** [comment]
You can unregister **any** widget, including the widgets registered by Polylang, the same way we do to unregister the native calendar wiidget. See https://github.com/polylang/polylang/blob/3.0.3/include/base.php#L103.

Please don't use GitHub for support requests. For support requests, please use the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/).
