### ISSUE TITLE
Setup wizard > Media: English string missing word

### ISSUE THREAD

**Issue by paulschreiber** [polylang/polylang#832]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install Pollang
2. Add one or more languages
3. Click continue

## Expected behavior and actual behavior

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/86784/117058559-c6a69f80-acec-11eb-9bfa-2ff250ebf9b7.png)

"Allow Polylang translate media"

I was expecting...
a grammatical sentence (Allow Polylang to translate media)

**Comment by manooweb** [comment]
Thanks @paulschreiber. It will be fixed in a future Polylang release. See #833

**Comment by Chouby** [comment]
Punting to 3.1, not to break translations in 3.0.x
