### ISSUE TITLE
Set session coookie

### ISSUE THREAD

**Issue by aaadipop** [polylang/polylang#834]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

Not necessary an issue

## Expected behavior and actual behavior

Be able to set a sesison cookie

I was expecting...

To be able to set a session cookie :) 

Hey, it will be great if we can pass a `-1` arg or smtg like this to `add_filter( 'pll_cookie_expiration', function() { return -1; } );` and be able to set a session cookie 

then, in `includes/cookies.php` i suppose it will be smtg like:

```
$expiration = apply_filters( 'pll_cookie_expiration', YEAR_IN_SECONDS );

$defaults = array(
        'expires'  => ($expiration > 0) ? time() + $expiration : '',
        'path'     => COOKIEPATH,

```

and ... that's all

currently, we update this file in place, at every update :) 

thanks

**Comment by Chouby** [comment]
This is an excellent suggestion. Thanks.
