### ISSUE TITLE
Polylang + Yoast SEO + WP Super Cache - cache cleared with every reload

### ISSUE THREAD

**Issue by mklusak** [polylang/polylang#847]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Have (latest) Polylang, Yoast SEO and WP Super Cache plugins active.
2. Set up WP Super Cache caching and browse frontend with incognito mode - wp-content/cache/supercache/ folder is filled with static cache files / folders
3. Reload/click any WP admin page, without anything saving etd, just simple reload 
4. /cache/ folder is empty

## The problem (?)

I debug_trace()'d WP Super Cache function `prune_super_cache()` and found out it is called from Yoast SEO function `clear_cache` (wordpress-seo-premium\inc\options\class-wpseo-options.php), which is called by `clear_cache` function in polylang\integrations\wpseo\wpseo.php ... and there it is in function `wpseo_translate_options` that is hooked to `wp_loaded` action.

So Polylang is efectively hooking clear cache function to every page load ... even admin-ajax.php hearbeat etc..

**Comment by Chouby** [comment]
I don't follow you: `WPSEO_options::clear_cache()` just empties an internal Yoast SEO variable storing Yoast options. See
https://github.com/Yoast/wordpress-seo/blob/16.3/inc/options/class-wpseo-options.php#L287-L289 
Moreover this function is called by Yoast SEO itself several times per page load (for each post type or taxonomy registered). See https://github.com/Yoast/wordpress-seo/blob/16.3/inc/options/class-wpseo-options.php#L71-L74.
So I don't understand the link with WP Super Cache.

For your information this variable is storing Yoast SEO options to avoid caling `get_option()`. Thus, this prevents the filters `option_wpseo_titles` and `option_wpseo_social` to operate. That's why we need to clear this cache to force Yoast SEO to call `get_option()`.

**Comment by mklusak** [comment]
Oh, I am sorry, it's Yoast SEO PREMIUM plugin, and it's not updated on our website anymore.Iits `WPSEO_options::clear_cache()` is this:

```
public static function clear_cache() {
	_deprecated_function( __METHOD__, 'WPSEO 1.5.6.1', 'WPSEO_Utils::clear_cache()' );
	WPSEO_Utils::clear_cache();
}
```

This is logged debug_trace():

```
Array
(
    [0] => Array
        (
            [file] => ...\wp-content\plugins\wp-super-cache\wp-cache-phase2.php
            [line] => 2776
            [function] => prune_super_cache
            [args] => Array
                (
                    [0] => ...\wp-content/cache/supercache/
                    [1] => 1
                )

        )

    [1] => Array
        (
            [file] => ...\wp-content\plugins\wordpress-seo-premium\inc\class-wpseo-utils.php
            [line] => 508
            [function] => wp_cache_clear_cache
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => ...\wp-content\plugins\wordpress-seo-premium\inc\options\class-wpseo-options.php
            [line] => 449
            [function] => clear_cache
            [class] => WPSEO_Utils
            [type] => ::
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => ...\wp-content\plugins\polylang\integrations\wpseo\wpseo.php
            [line] => 62
            [function] => clear_cache
            [class] => WPSEO_Options
            [type] => ::
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => ...\wp-includes\class-wp-hook.php
            [line] => 292
            [function] => wpseo_translate_options
            [class] => PLL_WPSEO
            [object] => PLL_WPSEO Object
                (
                )

            [type] => ->
            [args] => Array
                (
                    [0] => 
                )

        )
...
```

So, it's probably sorted out in later versions of Yoast SEO.
