### ISSUE TITLE
hreflang code

### ISSUE THREAD

**Issue by thetoine** [polylang/polylang#85]
Hi,

I received an alert from Google Webmaster about an _"Incorrect hreflang implementation"_.

_pll_rel_hreflang_attributes_ seems to return the language code without the country suffix.

For Canada English, it should return "en-ca". Or Canada French, "fr-ca".

https://github.com/polylang/polylang/blob/0d3f6eb8608c7749a788dd122132c32b211b0990/frontend/frontend-filters-links.php#L238

Best regards,

**Comment by grappler** [comment]
Here is the documentation from Google on href https://support.google.com/webmasters/answer/189077?hl=en

According to the documentation `en` is sufficient. @thetoine Is your site geared towards Canadien English speakers only? You could always change it for your own site using the flter `pll_rel_hreflang_attributes`

**Comment by Chouby** [comment]
Yes. Using 'en' or 'fr' is correct to target all English and French speakers instead of only Canadian people.
What is the exact error message?

**Comment by strarsis** [comment]
@Chouby: So I encountered the same issue and I noticed the reason for this message in Google Search Console is that Polylang adds `<link>` elements with hreflang for all the site languages –
even when there is no translation for that page, hence Google Bot won't be able to find the translated page (404).

**Comment by Chouby** [comment]
You *must* translate your home page in all languages.

**Comment by strarsis** [comment]
@Chouby: But when the home page hadn't been translated yet, the `<link` shouldn't be inserted by Polylang because it would point to a non-existing page and cause issues/confusion, like in the Googlebot.

**Comment by Chouby** [comment]
You *must* translate your home page in all languages. Polylang doesn't work correctly if you don't translate your home pages an all languages. There is an error message displayed if you attempt to assign a front page which is not translated in all languages. It's of possible to trick Polylang (for example by temporarily deactivating the plugin to assign the front page), but that's at your own risk. I did my best for this not to happen.

**Comment by alexsoluweb** [comment]
When having fr_CA and en_CA set up in polylang and both home page present. Why hreflang dont include the region code? According to this doc, it should... I tested up into à clean install.  

https://polylang.pro/hreflang-tag-attributes-and-polylang-everything-you-need-to-know/
