### ISSUE TITLE
Home page's permalink is not correct after enable polylang and use multiple domain with the site 

### ISSUE THREAD

**Issue by milk531** [polylang/polylang#865]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue
1. make different domain resolve to one site, for example, both www.mysite.com and mysite.com
2. in the editor, when you use different domain to edit the same page, other pages'  permalinks will change with the domain you use to access the editor, but the front page's permalink remain the same. 

## Expected behavior and actual behavior

1. When access localized home page , say de language, If the permalink is https://mysite.com/de, then link https://mysite.com/de can be opening correctly , but https://www.mysite.com/de will redirect to https://www.mysite.com/wp-admin.
2. Other pages's localized version except home page can be accessing correctly with both www and no-www domain

**Comment by Chouby** [comment]
I tested various settings and could not reproduce.  Could you post a copy of your site health info for me to test with the exact same settings.

**Comment by milk531** [comment]
> I tested various settings and could not reproduce. Could you post a copy of your site health info for me to test with the exact same settings?

Here is the site health info, I use bitnami to install and configure wordpress on the host, the site has three domain and they all suffer the same issue when access the front page with localized page.


### wp-core ###

version: 5.7.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 6
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /opt/bitnami/apps/wordpress/htdocs
wordpress_size: loading...
uploads_path: /opt/bitnami/apps/wordpress/htdocs/wp-content/uploads
uploads_size: loading...
themes_path: /opt/bitnami/apps/wordpress/htdocs/wp-content/themes
themes_size: loading...
plugins_path: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Saasland (saasland)
version: 3.3.4 (latest version: 3.3.5)
author: DroitThemes
author_website: https://themeforest.net/user/droitthemes
parent_theme: none
theme_features: core-block-patterns, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, automatic-feed-links, woocommerce, title-tag, post-thumbnails, post-formats, menus, html5, align-wide, editor-styles, editor-style, responsive-embeds, widgets
theme_path: /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/saasland
auto_update: Disabled

### wp-themes-inactive (1) ###

Bizberg: version: 4.2.9.15, author: Bizberg Themes (latest version: 4.2.9.25), Auto-updates disabled

### wp-mu-plugins (1) ###

Elementor Safe Mode: version: 1.0.0, author: Elementor.com

### wp-plugins-active (17) ###

Ads.txt Manager: version: 1.3.0, author: 10up, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.9.5, author: Elliot Condon (latest version: 5.9.6), Auto-updates disabled
Akismet Anti-Spam: version: 4.1.9, author: Automattic, Auto-updates disabled
Contact Form 7: version: 5.4.1, author: Takayuki Miyoshi, Auto-updates disabled
DT Redux Framework: version: 3.6.15, author: Team Redux, Auto-updates disabled
Elementor: version: 3.2.3, author: Elementor.com (latest version: 3.2.4), Auto-updates disabled
Enable Media Replace: version: 3.5.0, author: ShortPixel, Auto-updates disabled
Polylang: version: 3.0.5, author: WP SYNTEX, Auto-updates disabled
Polylang Connect for Elementor: version: 1.0.6, author: David Decker - DECKERWEB, Auto-updates disabled
Rank Math SEO: version: 1.0.63, author: Rank Math (latest version: 1.0.65), Auto-updates disabled
Saasland Core: version: 3.3.3, author: DroitThemes, Auto-updates disabled
Smush: version: 3.8.4, author: WPMU DEV (latest version: 3.8.5), Auto-updates disabled
Ultimate Category Excluder: version: 1.5, author: Marios Alexandrou, Auto-updates disabled
WPForms Lite: version: 1.6.6, author: WPForms (latest version: 1.6.7), Auto-updates disabled
WP Mail SMTP: version: 2.7.0, author: WPForms (latest version: 2.8.0), Auto-updates disabled
WP Post Page Clone: version: 1.1, author: Gaurang Sondagar, Auto-updates disabled
WP Super Cache: version: 1.7.3, author: Automattic, Auto-updates disabled

### wp-plugins-inactive (4) ###

AMP: version: 2.1.1, author: AMP Project Contributors (latest version: 2.1.2), Auto-updates disabled
GDPR Cookie Consent: version: 2.0.1, author: WebToffee (latest version: 2.0.3), Auto-updates disabled
One Click Demo Import: version: 3.0.2, author: OCDI, Auto-updates disabled
Support Board: version: 3.0.8, author: Schiocco, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1688
imagemagick_version: ImageMagick 6.9.8-3 Q16 x86_64 2020-12-01 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 40M
upload_max_filesize: 40M
max_effective_size: 40 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 2 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 49152
	imagick::RESOURCETYPE_MAP: 2 GB
	imagick::RESOURCETYPE_MEMORY: 988 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.05

### wp-server ###

server_architecture: Linux 4.19.0-16-cloud-amd64 x86_64
httpd_software: Apache
php_version: 7.4.13 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 300
upload_max_filesize: 40M
php_post_max_size: 40M
curl_version: 7.73.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 8.0.22
client_version: mysqlnd 7.4.13

### wp-constants ###

WP_HOME: https://www.ahasave.com/
WP_SITEURL: https://www.ahasave.com/
WP_CONTENT_DIR: /opt/bitnami/apps/wordpress/htdocs/wp-content
WP_PLUGIN_DIR: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wpforms ###

version: 1.6.6
lite: Mar 15, 2021 @ 9:17am
upload_dir: Writable
db_tables: wp_wpforms_tasks_meta
total_forms: 1
total_submissions: 1

### wp_mail_smtp ###

version: 2.7.0
license_key_type: lite
debug: No debug notices found.
db_tables: wp_wpmailsmtp_tasks_meta
lite_install_date: Mar 15, 2021 @ 9:11am

### pll_options ###

browser: 0
rewrite: 1
hide_default: 1
force_lang: 1
redirect_lang: 1
media_support: true
sync: 0
post_types: post, page, wp_block, attachment, elementor_library
taxonomies: 0
domains: 0
version: 3.0.5
default_lang: en
main_menu: en => 74 | id => 524
overlay_menu: en => 74 | id => 524
previous_version: 3.0.4

### pll_language_en ###

term_id: 244
name: English
slug: en
term_group: 0
term_taxonomy_id: 244
count: 422
tl_term_id: 245
tl_term_taxonomy_id: 245
tl_count: 78
locale: en_US
is_rtl: 0
w3c: en-US
facebook: en_US
home_url: https://www.ahasave.com/
search_url: https://www.ahasave.com/
mo_id: 9297
page_on_front: 4917
page_for_posts: 6714
flag_code: us
flag_url: /wp-content/plugins/polylang/flags/us.png
custom_flag_url: 0

### pll_language_pt ###

term_id: 550
name: Português
slug: pt
term_group: 0
term_taxonomy_id: 550
count: 0
tl_term_id: 551
tl_term_taxonomy_id: 551
tl_count: 1
locale: pt_BR
is_rtl: 0
w3c: pt-BR
facebook: pt_BR
home_url: https://www.ahasave.com/pt/
search_url: https://www.ahasave.com/pt/
mo_id: 11599
page_on_front: 0
page_for_posts: 0
flag_code: br
flag_url: /wp-content/plugins/polylang/flags/br.png
custom_flag_url: 0

### pll_language_id ###

term_id: 496
name: Bahasa Indonesia
slug: id
term_group: 1
term_taxonomy_id: 496
count: 28
tl_term_id: 497
tl_term_taxonomy_id: 497
tl_count: 1
locale: id_ID
is_rtl: 0
w3c: id-ID
facebook: id_ID
home_url: https://www.ahasave.com/id/
search_url: https://www.ahasave.com/id/
mo_id: 10572
page_on_front: 10576
page_for_posts: 11134
flag_code: id
flag_url: /wp-content/plugins/polylang/flags/id.png
custom_flag_url: 0

**Comment by Chouby** [comment]
I checked your site and notice an unepexted behavior. On your site a no-www url is *not* redirected to the corresponding www url as it should (WordPress makes this redirect to avoid duplicate content). See https://github.com/WordPress/WordPress/blob/5.8/wp-includes/canonical.php. That's probably the reason why I could not (and still cannot) reproduce the issue on my test site which keeps the default WP behavior for this.

Due to this unexpected behavior, it's likely that the canonical redirect mechanism of Polylang is messed although I cannot know exactly where.

NB: the redirect to `/wp-admin/` is due to Polylang using the safe redirect mechanism of WP: WP checks the redirect. It it is not valid, it redirects to `/wp-admin/` instead. See https://github.com/WordPress/WordPress/blob/5.8/wp-includes/pluggable.php#L1446. In you case, it probably validates only redirects to the www.

NB2: In #879 we decided not to do any redirect is WP doesn't validate the redirect instead of letting it redirect to `/wp-admin/`. This may partially fix your issue.

**Comment by milk531** [comment]
yes, we do not redirect no-www to www, both domain are binding to the same site and can be accessed. I've try the newest version and it works fine, thank you so much

**Comment by selimimre** [comment]
I think I have the same problem. @Chouby any chance you can take a look?

Our website is http://soulof.yoga/. Before, when we type this URL, it was going to http://soulof.yoga/de-de/home. But now it is not going there. Some other version on home is loading with missing data. When I use “www” then it works. I mean if I type http://www.soulof.yoga, then it goes to https://soulof.yoga/de-de/home/.

Wordpress and Polylang have updated to the most recent version.

Best,

Selim

**Comment by selimimre** [comment]
This issue resolved itself! I haven't done any changes or plugin updates but 1 day later redirection started to work again.
