### ISSUE TITLE
PHP notice when adding a CPT archive link in a menu

### ISSUE THREAD

**Issue by davidwebca** [polylang/polylang#868]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add Polylang with a theme or plugin that adds a Custom Post Type (with archive activated)
2. Set WP_DEBUG to true
3. Go to Appearance -> Menus
4. Try to add a Custom Post Type archive Link from the left hand bar

### When I follow those steps, I see...
Ajax fails because of a hard crash 500 error.

### I was expecting...
The menu element should be added to the nav

## Explanation
The problem comes simply from polylang/include/nav-menu.php:70. The url attribute is not defined on WP_Post_Type items, which are the items passed by WordsPress when adding a post type archive link. This results on a crash because the url attribute is undefined. A simple "isset" check on the $item->url before this condition should do the trick.

It seems to only ever be happening on that screen and with Ajax. People can still add post type archive menu items from the customizer since it uses a different method and different checks.

## Temporary fix
For anyone struggling with this issue, you can add a filter with a higher priority in your theme like so. It simply adds an empty url attribute to the object to make sure the check doesn't crash later on inside Polylang's code.

```php
add_filter('wp_setup_nav_menu_item', function($menu_item) {
    // seems to only be happening on ajax
    if(wp_doing_ajax()) {
        if(!isset($menu_item->url)) {
            $menu_item->url = '';
        }
    }
    return $menu_item;
});
```

**Comment by Chouby** [comment]
Thank you for the bug report.

I don't reprodue an error 500. But I reproduce a PHP notice: `Undefined property: WP_Post_Type::$url in polylang/include/nav-menu.php on line 70`.
