### ISSUE TITLE
WooCommerce language bug since #831 has been merge

### ISSUE THREAD

**Issue by thomascharbit** [polylang/polylang#874]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

- WordPress 5.7.2
- WooCommerce 3.4.1
- Polylang Pro 3.0.5, 2 languages enabled (assuming English as default language, French as second language)
- Polylang for WooCommerce 1.5.5
- WP Rocket 5.8.8

1. Add a French product to the cart
2. Go to cart page
2. Switch to English language
3. Switch back to french language

## Expected behavior and actual behavior

The cart page is expected to be displayed in the chosen language, including menus, i18n strings, products in cart

Now i have a mixed up page. French cart page displays english menu, english product, but i18n french translations.
It then happens on any page as soon as you have some products in the cart.

## Why?

In `WC_Product_Variation_Data_Store_CPT` class, WooCommerce may trigger some `clean_post_cache()`
calls when reading product data from DB.

I suspect since #831 has been merged this sets `PLL()->curlang` to the wrong language while rendering the page.

Thanks

**Comment by Chrystll** [comment]
I don't reproduce your issue with the following versions:

- WordPress 5.7.2
- WooCommerce **5**.4.1
- Polylang Pro 3.0.5
- Polylang for WooCommerce 1.5.5
- WP Rocket **3**.8.8

Do you use WooCommerce 5.4.1 (latest version) or 3.4.1?

As you get a Polylang Business Pack license key could you please contact us on [our helpdesk](https://polylang.pro/support/) to investigate your issue?

**Comment by thomascharbit** [comment]
Sorry yes WC 5.4.1 + WP Rocket 3.8.8.

I think it only happens if WooCommerce triggers a product update when reading the product from DB, which is not always the case.

https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L96-L111

Looks like you can reproduce it if you change a product attribute name or value.

I will open a support ticket.

**Comment by Chouby** [comment]
Hello,

I reproduce. The issue is that we trigger this product update. So I'll try to fix this on the Polylang for WooCommerce side.
