### ISSUE TITLE
wpseo schema wrong url

### ISSUE THREAD

**Issue by webgrafia** [polylang/polylang#882]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1.Install polylang pro and wpseo last version and yoast test plugin
2.setup multilanguages with different domain (but maybe happen also with subdir conf)
3. monitor schema url

## Expected behavior and actual behavior

When I follow those steps, "sometimes" schema url of domain are wrong. It happen ONLY for item that are stored in indexable tables of yoast (recently intrduced), if I reset indexable tables (using yoast test plugin) they fix, but randomly they still appear wrong (maybe because putted in indexable tables from some async process) 

I was expecting the right schema url based on post languages

**Comment by Chrystll** [comment]
To try to reproduce your issue could you please show me what you mean by "3. monitor schema url"?
