### ISSUE TITLE
Double strings in Strings translations

### ISSUE THREAD

**Issue by wpexplorer** [polylang/polylang#89]
I am using a couple functions to register Customizer settings "theme_mods" for translation. Like this:

```php
add_filter( 'wpex_register_theme_mod_strings', function() {
	return array(
		'wpex_logo'                    => '',
		'wpex_logo_retina'             => '',
		'wpex_logo_retina_height'      => '',
		'wpex_home_slider_custom_code' => '',
		'wpex_footer_copyright'        => '<a href="http://www.wordpress.org" title="WordPress" target="_blank">WordPress</a> Theme Designed &amp; Developed by <a href="http://www.wpexplorer.com/" target="_blank" title="WPExplorer">WPExplorer</a>',
	);
} );
```

```php
function wpex_register_theme_mod_strings() {
	return apply_filters( 'wpex_register_theme_mod_strings', array() );
}

```
```php
function wpex_wpml_register_strings( $key, $default = null ) {

	// Get strings
	$strings = wpex_register_theme_mod_strings();

	// Register strings for WPMl
	if ( function_exists( 'icl_register_string' ) ) {
		foreach( $strings as $string => $default ) {
			icl_register_string( 'Theme Mod', $string, get_theme_mod( $string, $default ) );
		}
	}

	// Register strings for Polylang
	if ( function_exists( 'pll_register_string' ) ) {
		foreach( $strings as $string => $default ) {
			pll_register_string( $string, get_theme_mod( $string, $default ), 'Theme Mod', true );
		}
	}

}
add_action( 'admin_init', 'wpex_wpml_register_strings' );
```

The problem is the registered strings display twice in the strings translation panel. It doesn't cause any real issues because when you save 1 it saves the other, but it's a bit confusing for the end user and if there are a lot of strings on a particular theme then it bloats things up a lot.

Screenshot:

![screen shot 2017-01-28 at 9 57 17 am](https://cloud.githubusercontent.com/assets/1128841/22398583/3e1a54f4-e540-11e6-977d-875d3f843077.png)

We try and provide Polylang support to all our products and hopefully prevent customers from bothering you guys so any help with this would be very appreciated, thank you!

**Comment by Chouby** [comment]
Hi,

Polylang supports both `icl_register_string()` as part of the WPML compatibility mode and `pll_register_sring()` (native Polylang way). So you are indeed registering the string two times.

So to use only the Polylang native way, you can change your code to:

```php
function wpex_wpml_register_strings( $key, $default = null ) {

	// Get strings
	$strings = wpex_register_theme_mod_strings();

	// Register strings for Polylang
	if ( function_exists( 'pll_register_string' ) ) {
		foreach( $strings as $string => $default ) {
			pll_register_string( $string, get_theme_mod( $string, $default ), 'Theme Mod', true );
		}
	}

	// Register strings for WPML
	elseif ( function_exists( 'icl_register_string' ) ) {
		foreach( $strings as $string => $default ) {
			icl_register_string( 'Theme Mod', $string, get_theme_mod( $string, $default ) );
		}
	}

}
```
Thus you would first check for Polylang and if Polylang is not activated, check for WPML.

**Comment by wpexplorer** [comment]
@Chouby I actually thought of that, however, even when I completely comment out the code for WPML it still shows the strings twice. I was thinking that maybe there is a function in Polylang that auto pulls options from the WP Customizer?

Either-way, shouldn't there be a check when a string is registered to make sure there isn't already a string with the same name to prevent duplicates in any circumstance?

**Comment by Chouby** [comment]
`icl_register_string()` persistently registers strings (as WPML does). So even if you remove the code (or deactivate the theme), they are kept in the table until you delete them with the bulk action.

On the other hand, strings registered with `pll_register_string()` are not persistent. If you remove the code, they won't appear. These strings don't have a checkbox for the bulk delete as it's useless.

**Comment by wpexplorer** [comment]
@Chouby - Thank you so much. I was not aware of that and I apologize as I should have thought about it. Perfect !
