### ISSUE TITLE
get_page_by_path does not work with Polylang URLs

### ISSUE THREAD

**Issue by acki** [polylang/polylang#891]
If you use get_page_by_path with language URL's, it returns NULL.

For example:

Base language is EN and original site is /detailpage

get_page_by_path( '/detailpage' )
returns page id 1234

get_page_by_path( '/de/detailseite' )
returns page id NULL (expecting 4321)

get_page_by_path ( '/detailseite' )
returns page id 4321

Can you take a look and fix this?

Tested with:

WordPress 5.7.2
Polylang Pro 3.0.6

**Comment by Chouby** [comment]
This is a known issue since the beginning of Polylang. Unfortunately there is no filter in this function to modify its behavior. If you need such feature you'll need to write you own function.
