### ISSUE TITLE
Feed multilanguage

### ISSUE THREAD

**Issue by Mte90** [polylang/polylang#899]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

I am just looking on a way to get a feed that aggregates the posts for both the languages, like for `domain.tld/feed`.

I don't see any option for that.

**Comment by Chouby** [comment]
You can use `https://yoursite.com/feed/?lang=`. Providing an empty `lang` parameter deactivates the language filter.

**Comment by Mte90** [comment]
Doesn't work.
On my website the `https://yoursite.com/feed/` return a 404 also without parameters.
I have the feed under the lang folder like `https://yoursite.com/en/feed/`.
I see that with `https://yoursite.com/en/feed/?lang=` works but doesn't seem a right behaviour.

**Comment by Mte90** [comment]
Anyway i fixed in this way:

```
add_filter( 'feed_link', 'add_lang_for_italian' );

function add_lang_for_italian($url) {
    if ( pll_current_language() == 'it' ) {
        return $url . '?lang=';
    }
    return $url;
}
```
