### ISSUE TITLE
Polylang does not work with Jetpack CPT

### ISSUE THREAD

**Issue by bitcolorine** [polylang/polylang#9]
Hi,
I'm building a site with three languages and using Jetpack's portfolio feature. It seems that Polylang doesn't work with Jetpack custom post types (portfolio). It seems strange since it's such a widely used plugin. I'm not sure if this is an issue or regular support. Jetpack's team seems to think it is an issue with Polylang.

**Comment by Chouby** [comment]
Hi!

Could you please be more specific? What do you expect and what are you obtaining instead?

**Comment by bitcolorine** [comment]
Hi, I was expecting the Langes widget on the window [like this](https://goo.gl/photos/ZH1ZrdaJHg9mdS7f8). It doesn't appear in the portfolio projects.

**Comment by Chouby** [comment]
Could you go in Settings->Languages->Settings then in Custom post types and Taxonomies module, check the "Projects" checbox?

**Comment by bitcolorine** [comment]
Oh my goodness, I feel so silly. I have been using polylang for quite a while but never with CPT up until now. 
I will close my ticket on the WP forum and add the response. Merci beaucoup!

**Comment by Chouby** [comment]
Good :)
