### ISSUE TITLE
Allow HTML in Author bio

### ISSUE THREAD

**Issue by illycz** [polylang/polylang#933]
I'm trying to use HTML within User Biographical Info.

Recommendation is use filters like below:
```
remove_filter( 'pre_user_description', 'wp_filter_kses' );
add_filter( 'pre_user_description', 'wp_filter_post_kses');
```

But it looks, that Polylang strip HTML tags too.
Is it possible disable this for Polylang too?

Thanks

**Comment by Chouby** [comment]
Does it work better for you with the changes applied in #934?

**Comment by illycz** [comment]
Great, working!
