### ISSUE TITLE
Avoid PHP notices for invalid search requests

### ISSUE THREAD

**Issue by ocean90** [polylang/polylang#937]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a language and assign it as a default for all existing posts
2. Use "The language is set from the directory name in pretty permalinks" setting and uncheck "Hide URL language information for default language"
3. Now open `example.com/de/randomstring/?s=` where `de` is the slug of the language

## Expected behavior and actual behavior

When I follow those steps, I see several PHP notices. See the following screenshots from Query Monitor:
<img width="1360" alt="php-notices" src="https://user-images.githubusercontent.com/617637/142927365-a11fe436-06cc-465f-be7c-ace67aa77756.png">

This is because the wrong template is loaded:
<img width="742" alt="template" src="https://user-images.githubusercontent.com/617637/142927412-58d6873c-48e2-4083-8337-eb0b51ff18f6.png">

I was expecting no PHP notices and the 404 template to be loaded.

This seems to be caused by this code: https://github.com/polylang/polylang/blob/6ce5b2844d52e57d764764e6441fcd839dafc7c5/frontend/choose-lang.php#L310-L318

**Comment by Chouby** [comment]
Hi @ocean90,

Thank you for the bug report. The issue is indeed due to the code you are pointing to. the `$query->query['s']` part was added to mimic the WP behavior which has changed since I introduced it. See https://core.trac.wordpress.org/ticket/11330

So instead of your PR, I propose to remove this part of the code.
I added 2 tests, one when querying only the empty search (as I initially worked only on this case), on to test the issue described here. See #940. What do you think?

**Comment by ocean90** [comment]
@Chouby Even better! I did a quick test with #940 and it works as expected.
