### ISSUE TITLE
Bug Strings translations time format not update

### ISSUE THREAD

**Issue by robertoentringer** [polylang/polylang#94]
Time format not update in the admin page : Strings translations

See the video below for the error :

http://recordit.co/LDs3RTNSE6

![lds3rtnse6](https://cloud.githubusercontent.com/assets/1759811/22701772/edb766a6-ed5e-11e6-9343-3ca54ac14de5.gif)

Version Wp : 7.7.2
Version plugin : 2.1
Version Apache : 2.2.31
Version de PHP : 5.6.22
Version de MySQL : 5.6.35

Thanks for helping me out!

Best regards,
Roberto.

**Comment by Chouby** [comment]
Thanks! I will fix that soon.

**Comment by robertoentringer** [comment]
Thanks for your prompt response to this matter !
