### ISSUE TITLE
URL modifications with country and language in path

### ISSUE THREAD

**Issue by dejwsz** [polylang/polylang#951]
By using the option "The language is set from the directory name in pretty permalinks" it is possible to add language context path fragment like "/en/...". 
It would be good to have also similar option which adds a combination of language and country what can be useful in some cases like "/en_GB/...".
Or there is any other way to do this now ?

**Comment by dejwsz** [comment]
The case is when you have different content not only for given language but also the country and it would be good the URL reflects this.

**Comment by Chouby** [comment]
You can't use uppercases for the slug, but you can use something like: `/en_gb/`. Accepted characters are lowercase characters,`-` and `_`. See https://polylang.pro/doc/configure-the-languages/#language-code.
