### ISSUE TITLE
PHP Warning:  Attempt to read property "slug" on null in /integrations/wpseo/wpseo.php on line 305

### ISSUE THREAD

**Issue by alfredo49** [polylang/polylang#954]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

I just update to php 8.0 and in my php error logs all the time returns:

23-Dec-2021 10:27:14 UTC] PHP Warning:  Attempt to read property "slug" on null in /xxx/wp-content/plugins/polylang/integrations/wpseo/wpseo.php on line 305

Thxs

**Comment by alfredo49** [comment]
Hi:
I dont know how to reproduce this, It does not happen when I enter a specific page, I’ve observed that actually it’s totally random.
This morning when I look at the error log of my server I found this error repeated many times.

These would help for an idea;
1- https://core.trac.wordpress.org/ticket/29660#comment:44
2- https://core.trac.wordpress.org/ticket/52510

Some developers modify your plugins code to solve that

**Comment by Chouby** [comment]
Could you share your site health? I am especially interested in the plugins list with their version and the Polylang sections.

**Comment by alfredo49** [comment]
Hi @Chouby 

Sorry for the delay, i have to roll back to php 7.4 to see site health, this is the reason you will see php 7.4 in the site health, but the issue is with php8

`
### wp-core ###

version: 5.8.3
site_language: es_ES
user_language: es_ES
timezone: Europe/Madrid
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /usr/home/mvpql.es/web
wordpress_size: 26,29 GB (28224971949 bytes)
uploads_path: /usr/home/mvpql.es/web/wp-content/uploads
uploads_size: 1,08 GB (1157358494 bytes)
themes_path: /usr/home/mvpql.es/web/wp-content/themes
themes_size: 2,40 MB (2511384 bytes)
plugins_path: /usr/home/mvpql.es/web/wp-content/plugins
plugins_size: 145,48 MB (152547136 bytes)
database_size: 66,95 MB (70205440 bytes)
total_size: 27,57 GB (29607594403 bytes)

### wp-active-theme ###

name: html5blank-child (html5blank-child)
version: undefined
author: Anónimo
author_website: (undefined)
parent_theme: HTML5 Blank (html5blank)
theme_features: core-block-patterns, menus, post-thumbnails, automatic-feed-links, widgets, widgets-block-editor, editor-style
theme_path: /usr/home/mvpql.es/web/wp-content/themes/html5blank-child
auto_update: Desactivado

### wp-parent-theme ###

name: HTML5 Blank (html5blank)
version: 1.4.3
author: Todd Motto (@toddmotto)
author_website: http://toddmotto.com
theme_path: /usr/home/mvpql.es/web/wp-content/themes/html5blank
auto_update: Desactivado

### wp-plugins-active (13) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors, Actualizaciones automáticas desactivadas
Composium - WP Bakery Page Builder Extensions Addon: version: 5.6.1, author: Tekanewa Scripts by Kraut Coding, Actualizaciones automáticas desactivadas
Disable Embeds: version: 1.5.0, author: Pascal Birchler, Actualizaciones automáticas desactivadas
GDPR Cookie Compliance: version: 4.7.2, author: Moove Agency, Actualizaciones automáticas desactivadas
Pods - Custom Content Types and Fields: version: 2.8.8.1, author: Pods Framework Team, Actualizaciones automáticas desactivadas
Polylang: version: 3.1.3, author: WP SYNTEX, Actualizaciones automáticas desactivadas
Really Simple SSL: version: 5.2.1, author: Really Simple Plugins, Actualizaciones automáticas desactivadas
Redirection: version: 5.1.3, author: John Godley, Actualizaciones automáticas desactivadas
Server IP & Memory Usage Display: version: 2.1.0, author: Apasionados, Apasionados del Marketing, Actualizaciones automáticas desactivadas
Wordfence Security: version: 7.5.7, author: Wordfence, Actualizaciones automáticas desactivadas
WPBakery Page Builder: version: 6.8.0, author: Michael M - WPBakery.com, Actualizaciones automáticas desactivadas
WPS Hide Login: version: 1.9.2, author: WPServeur, NicolasKulka, wpformation, Actualizaciones automáticas desactivadas
Yoast SEO: version: 17.8, author: Team Yoast, Actualizaciones automáticas desactivadas

### wp-plugins-inactive (4) ###

All-in-One WP Migration: version: 7.52, author: ServMask, Actualizaciones automáticas desactivadas
All-in-One WP Migration Unlimited Extension: version: 2.16, author: ServMask, Actualizaciones automáticas desactivadas
All In One WP Security: version: 4.4.9, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy, Actualizaciones automáticas desactivadas
UpdraftPlus - Backup/Restore: version: 1.16.69, author: UpdraftPlus.Com, DavidAnderson, Actualizaciones automáticas desactivadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 35M
upload_max_filesize: 35M
max_effective_size: 35 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.9.0-16-amd64 x86_64
httpd_software: Apache
php_version: 7.4.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 1000
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 35M
php_post_max_size: 35M
curl_version: 7.52.1 OpenSSL/1.0.2u
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.2.41-MariaDB-10.2.41+maria~stretch-log
client_version: mysqlnd 7.4.26

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /usr/home/mvpql.es/web/wp-content
WP_PLUGIN_DIR: /usr/home/mvpql.es/web/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:91.0) Gecko/20100101 Firefox/91.0
pods-session-save-path: /home/mvpql.es/tmp
pods-session-save-path-exists: Sí
pods-session-save-path-writable: Sí
pods-session-max-lifetime: 7200
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Sí
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 35,204M
pods-memory-current-usage-real: 12,000M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Sí
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Sí
pods-api-cache: Sí
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Desactivar sesiones
pods-can-use-sessions: Sí

### pll_options ###

browser: 0
rewrite: 1
hide_default: 1
force_lang: 0
redirect_lang: 0
media_support: 1
sync: 0
post_types: post, page, wp_block, attachment, boletin, guia, meme, noticia, ramo
taxonomies: 0
domains: 0
version: 3.1.3
default_lang: es
previous_version: 3.1.2

### pll_language_es ###

term_id: 2
name: Español
slug: es
term_group: 1
term_taxonomy_id: 2
count: 2666
tl_term_id: 3
tl_term_taxonomy_id: 3
tl_count: 85
locale: es_ES
is_rtl: 0
w3c: es-ES
facebook: es_ES
home_url: https://mvpql.es/
search_url: https://mvpql.es/
mo_id: 2894
page_on_front: 0
page_for_posts: 0
flag_code: es
flag_url: https://mvpql.es/wp-content/plugins/polylang/flags/es.png
custom_flag_url: 0

### pll_language_ca ###

term_id: 9
name: Català
slug: ca
term_group: 2
term_taxonomy_id: 9
count: 2222
tl_term_id: 10
tl_term_taxonomy_id: 10
tl_count: 83
locale: ca
is_rtl: 0
w3c: ca
facebook: ca_ES
home_url: https://mvpql.es/ca/
search_url: https://mvpql.es/ca/
mo_id: 2896
page_on_front: 0
page_for_posts: 0
flag_code: catalonia
flag_url: https://mvpql.es/wp-content/plugins/polylang/flags/catalonia.png
custom_flag_url: 0

### pll_language_eu ###

term_id: 72
name: Euskara
slug: eu
term_group: 3
term_taxonomy_id: 72
count: 2206
tl_term_id: 73
tl_term_taxonomy_id: 73
tl_count: 88
locale: eu
is_rtl: 0
w3c: eu
facebook: eu_ES
home_url: https://mvpql.es/eu/
search_url: https://mvpql.es/eu/
mo_id: 4251
page_on_front: 0
page_for_posts: 0
flag_code: basque
flag_url: https://mvpql.es/wp-content/plugins/polylang/flags/basque.png
custom_flag_url: 0

### pll_language_gl ###

term_id: 76
name: Galego
slug: gl
term_group: 4
term_taxonomy_id: 76
count: 2204
tl_term_id: 77
tl_term_taxonomy_id: 77
tl_count: 85
locale: gl_ES
is_rtl: 0
w3c: gl-ES
facebook: gl_ES
home_url: https://mvpql.es/gl/
search_url: https://mvpql.es/gl/
mo_id: 4252
page_on_front: 0
page_for_posts: 0
flag_code: galicia
flag_url: https://mvpql.es/wp-content/plugins/polylang/flags/galicia.png
custom_flag_url: 0

### pll_language_en ###

term_id: 13
name: English
slug: en
term_group: 5
term_taxonomy_id: 13
count: 2207
tl_term_id: 14
tl_term_taxonomy_id: 14
tl_count: 98
locale: en_GB
is_rtl: 0
w3c: en-GB
facebook: en_GB
home_url: https://mvpql.es/en/
search_url: https://mvpql.es/en/
mo_id: 2897
page_on_front: 0
page_for_posts: 0
flag_code: gb
flag_url: https://mvpql.es/wp-content/plugins/polylang/flags/gb.png
custom_flag_url: 0

### pll_warnings ###

post-no-lang: attachment => 3604 , 3596 , 3589 , 3583 , 3582 | ramo => 3423 , 3416 , 3410 , 3404

`
