### ISSUE TITLE
Add class to <img> in language switcher

### ISSUE THREAD

**Issue by draconus** [polylang/polylang#97]
Please add CSS class to <img> tag for language switcher so that flag icons can be manipulated via CSS.

In include/language.php there is a line:
`<img src="%s" title="%s" alt="%s" />`

If I replace it with
`<img src="%s" title="%s" alt="%s" class="pllimgclass" />`

I will have proper CSS class to work with. Please make this option stock

**Comment by chesio** [comment]
Hi,

You can target image elements with selectors like: `.lang-item img` or `a[lang] > img`. Not sure if extra class is needed...

Cheers,
Česlav

**Comment by draconus** [comment]
That actually works. Don't know why but it works. Thanks!

**Comment by chesio** [comment]
If you don't know why it works, you might be interested in learning about various [CSS Selectors](https://www.w3schools.com/cssref/css_selectors.asp).

**Comment by draconus** [comment]
@chesio great stuff, thanks!
