### ISSUE TITLE
Translate widgets in WP 5.9+

### ISSUE THREAD

**Issue by thomas-SGB** [polylang/polylang#974]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Update to Wordpress 5.9
2. Go to the widget area
3. There is no option to restrict / enable the widget to certain languages.

## Expected behavior and actual behavior

In Wordpress <5.9 you could select that a widget is only shown in one language. On multilingual pages this feature is essential if you are using widgets. But after upgrading to Wordpress 5.9 this Polylang feature is missing.

**Comment by Chouby** [comment]
Legacy widgets and Block widgets work in a completely different way.
In Polylang 3.1, we have adapted our compatibility with legacy widgets to make sure that they continue to work in WordPress 5.9 with the legacy widget block.
Other developments to add a language filter for the new widget blocks have been added in Polylang Pro. 
See also: https://polylang.pro/polylang-3-1-is-on-its-way/ and https://polylang.pro/doc/widgets/#legacy-widget.
