### ISSUE TITLE
Custom Hreflangs added on all pages

### ISSUE THREAD

**Issue by carloscastromx** [polylang/polylang#976]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Use the pll_rel_hreflang_attributes filter to customize hreflangs

## Expected behavior and actual behavior
Only customized hreflangs for the specified URLs should be changed.

When I follow those steps, I see...

The custom hreflangs being present in all the site's pages.

I was expecting...

The hreflang tags to be present only in the homepage

## Context
My website's hreflang tags were currently like this on the homepage:
```
<link rel="alternate" href="https://xxx.com/en/" hreflang="en-US" />
<link rel="alternate" href="https://xxx.com/" hreflang="es" />
<link rel="alternate" href="https://xxx.com/en-ca/" hreflang="en-CA" />
```
So, I changed them with the ```pll_rel_hreflang_attributes``` filter to this:
```
<link rel="alternate" href="https://xxx.com/en/" hreflang="en" />
<link rel="alternate" href="https://xxx.com/" hreflang="es-MX" />
<link rel="alternate" href="https://xxx.com/en-ca/" hreflang="en-CA" />
```
However, these tags are also appearing on other translated pages like https://xxx.com/en/privacy-policy/ when the proper hreflang tags with the translated versions of that URL should appear.

Am I trying to change the hreflang values for my languages incorrectly? How should I customize the hreflang tags per page to avoid this from happening?

Thanks!

**Comment by Chouby** [comment]
This **is** a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
