### ISSUE TITLE
Endless loop loading language file (.mo)

### ISSUE THREAD

**Issue by dhosting** [polylang/polylang#977]
https://github.com/polylang/polylang/blob/f1fdc4823bc7a47878f200ac41a91d188307e487/frontend/frontend-filters.php#L48

I have encountered a problem where an infinite loop occurs and the process runs out of memory.

In each case with the current version:
Wordpress -> as multisite
Theme: Divi
Polylang with two languages de_DE + en_GB
User language/locale not default, e.g. de_DE

In this constellation it comes to an endless loop if you want to save a page with the DIVI frontend builder and also with the wordpress heartbeat. (all AJAX requests)

It is seemingly endlessly trying to load the language file ./wp-content/themes/Divi/lang/de_DE.mo, depending on the set page language.

I have already checked the hooks and routines of DIVI, but everything indicates that the problem is caused by the above line.

If this line is commented out, the AJAX request works again without any problems.
As an interim solution it helps to set the user locale to empty.

An excerpt from the hook debugging that causes the error.

`Array
(
    [10] => Array
        (
            [0000000073b2f3e1000000004d70dd0aload_textdomain_mofile] => Array
                (
                    [function] => Array
                        (
                            [0] => PLL_Frontend_Filters Object
                                (
                                    [options] => Array
                                        (
                                            [browser] => 0
                                            [rewrite] => 1
                                            [hide_default] => 1
                                            [force_lang] => 1
                                            [redirect_lang] => 0
                                            [media_support] => 1
                                            [uninstall] => 0
                                            [sync] => Array
                                                (
                                                )

                                            [post_types] => Array
                                                (
                                                )

                                            [taxonomies] => Array
                                                (
                                                )

                                            [domains] => Array
                                                (
                                                )

                                            [version] => 3.1.4
                                            [first_activation] => 1643895473
                                            [default_lang] => de
                                            [nav_menus] => Array
                                                (
                                                    [Divi] => Array
                                                        (
                                                            [primary-menu] => Array
                                                                (
                                                                    [de] => 2
                                                                    [en] => 0
                                                                )

                                                            [secondary-menu] => Array
                                                                (
                                                                    [de] => 0
                                                                    [en] => 0
                                                                )

                                                            [footer-menu] => Array
                                                                (
                                                                    [de] => 6
                                                                    [en] => 0
                                                                )

                                                        )

                                                )

                                        )

                                    [model] => PLL_Model Object
                                        (
                                            [cache] => PLL_Cache Object
                                                (`

**Comment by Chouby** [comment]
I don't understand how to reproduce the issue. Could you please provide steps starting from a fresh install with Polylang and Divi?
