### ISSUE TITLE
ACF Media not translated

### ISSUE THREAD

**Issue by arthurmuchir** [polylang/polylang#98]
When I request a translation in a WP_Query with this args :
```
$id = pll_get_post($id, $lang);

$args = array(
    'p' => $id ? $id : '',
    'post_type' => 'page'
);
```

I get the translated content as wanted, but linked ACF media images are them not translated (flexible content in ACF), I get the original language version.
Custom Fields is unchecked in Polylang Sync Settings.

Is there anythings I miss ?
I am using Polylang 2.1.1 / ACF PRO 5.5.

Thanks !

**Comment by Chouby** [comment]
What are you doing next after to get the ACF media?

**Comment by arthurmuchir** [comment]
I am using `get_fields(postID)` with `postID` being the translated content ID (the one recovered from `pll_get_post`).

**Comment by Chouby** [comment]
Are you sure that pll_get_post correctly translated your post id? Would you share a gist with the complete code?

**Comment by arthurmuchir** [comment]
Yes, I got the correct translated post id. I will do a gist

**Comment by arthurmuchir** [comment]
OK, reproducing the case on a separate site I found that there was an issue with JSON API Plugin.

Thanks & Sorry.
