### ISSUE TITLE
Needs compatibility with block menus for WordPress 5.9's Gutenberg-based "full site editing" theming/layout system

### ISSUE THREAD

**Issue by nekohayo** [polylang/polylang#982]
## Prerequisites

- [x] This is not a usage question
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Try to build a multilingual menu with WordPress [5.9](https://wordpress.org/news/2022/01/josephine/)'s new default theme, TwentyTwentyTwo. You can't, the block widget is unilingual in practice.

## Expected behavior and actual behavior

With the new "full site editing" feature that [defines the core of WordPress 5.9 and its new official default theme](https://make.wordpress.org/core/2022/01/04/block-themes-a-new-way-to-build-themes-in-wordpress-5-9/), users can now edit pages and the site's layout templates/design with a Gutenberg-based editor instead of the Customizer or traditional menus configuration area.

The problem is that Polylang does not provide a way to edit those block-based widget menus in a multilingual way from within the Gutenberg-based editor, which in turns makes hurts the usability of Polylang's baseline offering, which in turns makes it look bad (especially in terms of first impressions for new users trying it out, i.e. "proof that it works"), as this is arguably an essential feature for the present and future of Wordpress themes.

**Comment by mthld** [comment]
I just took a few minutes to try out Polylang with the base theme, Twenty twenty, under WordPress 5.9 and indeed it isn't working. 🥲

**Comment by manooweb** [comment]
Sorry but our compatibility with the full site editing WordPress 5.9 feature, especailly about our language switcher in navigation block, is only implemented in our premium version.
See https://polylang.pro/its-official-polylang-3-2-is-available/
The stable release will come soon.

However a plugin was developed to be able to use classic menu as a legacy menu block.
https://wordpress.org/plugins/classic-menu-block/
It may be able to meet your expectations.

**Comment by dguruwu** [comment]
That classic menu block plugin looks sketchy but I am trying it out anyways as a first time Polylang user.  I am not familiar with these manipulating blocks as opposed to menus and widgets of past.

https://wordpress.org/support/topic/missing-source/

Do you expect full site editing to be available with free version in the future or will it only be available with premium?
